/**
 * @file Spi_Cfg.h
 * @brief Spi Configuration configuration header
 * @version 1.0.0
 * @date 2026-08-10
 * @note AUTO-GENERATED by yuleASR Configurator
 */

#ifndef SPI_CFG_H
#define SPI_CFG_H

#include "Std_Types.h"   /* 非宏段依赖 Std_Types 基础类型 (uint32/uint8/uint16/boolean 等)，生成宏段不含此 include */

#include "Std_Types.h"

/*==================================================================================================
*                                    PRE-COMPILE CONFIGURATION
*================================================================================================*/

/*==================================================================================================
*                                    General Configuration
*================================================================================================*/
#define SPI_DEV_ERROR_DETECT    STD_ON
#define SPI_VERSION_INFO_API    STD_ON
#define SPI_MAX_EXTERNAL_DEV    (16U)
#define SPI_SERVICE_ID_GETVERSIONINFO    (9U)

/*==================================================================================================
*                                    Module Configuration Counts
*================================================================================================*/
#define SPI_CHANNEL_COUNT    (4U)

/*==================================================================================================
*                                    Processing Modes
*================================================================================================*/
#define SPI_INTERRUPT_SUPPORT    STD_ON

/*==================================================================================================
*                                    Hardware Object Handles
*================================================================================================*/
#define SPI_DMA_TX_CHANNEL_BASE    (8U)
#define SPI_DMA_RX_CHANNEL_BASE    (12U)
#define SPI_TX_FIFO_THRESHOLD    (32U)
#define SPI_RX_FIFO_THRESHOLD    (32U)

/*==================================================================================================
*                                    Timing Configuration
*================================================================================================*/
#define SPI_TRANSFER_TIMEOUT_MS    (1000U)

/*==================================================================================================
*                                    Other Configuration
*================================================================================================*/
#define SPI_VENDOR_ID_CFG    (1U)
#define SPI_MODULE_ID_CFG    (122U)
#define SPI_SW_MAJOR_VERSION_CFG    (1U)
#define SPI_SW_MINOR_VERSION_CFG    (0U)
#define SPI_SW_PATCH_VERSION_CFG    (0U)
#define SPI_DMA_SUPPORT    STD_ON
#define SPI_MULTI_SLAVE_SUPPORT    STD_ON
#define SPI_FIFO_SUPPORT    STD_ON
#define SPI_MAX_JOB    (16U)
#define SPI_MAX_SEQUENCE    (8U)
#define SPI_REF_CLOCK_HZ    (80000000U)
#define SPI_DMA_FIFO_THRESHOLD    (4U)
#define SPI_IRQ_PRIORITY    (4U)
#define SPI_FIFO_DEPTH    (64U)
#define SPI_SERVICE_ID_INIT    (0U)
#define SPI_SERVICE_ID_DEINIT    (1U)
#define SPI_SERVICE_ID_WRITEB_IB    (2U)
#define SPI_SERVICE_ID_ASYNC_TRANSMIT    (3U)
#define SPI_SERVICE_ID_READ_IB    (4U)
#define SPI_SERVICE_ID_SETUP_EB    (5U)
#define SPI_SERVICE_ID_GETSTATUS    (6U)
#define SPI_SERVICE_ID_GETJOBRESULT    (7U)
#define SPI_SERVICE_ID_GETSEQUENCERESULT    (8U)
#define SPI_SERVICE_ID_SYNCTRANSMIT    (10U)
#define SPI_SERVICE_ID_GETHWUNITSTATUS    (11U)
#define SPI_SERVICE_ID_CANCEL    (12U)
#define SPI_SERVICE_ID_SET_CLOCK    (13U)


/*==================================================================================================
*  NON-MACRO SEGMENT (preserved from handwritten header, merged by codegen splice)
*  typedef(2) + struct(0) + extern config tables(0) — 依赖宏段计数宏, 故置于宏段之后
*================================================================================================*/
typedef uint8 Spi_ChannelType;

/** @brief SPI 序列标识类型 */
typedef uint8 Spi_SequenceType;
#endif /* SPI_CFG_H */

/*==================[end of file]===========================================*/
