/**
 * @file EcuC_Cfg.h
 * @brief EcuC Configuration configuration header
 * @version 1.0.0
 * @date 2026-08-10
 * @note AUTO-GENERATED by yuleASR Configurator
 */

#ifndef ECUC_CFG_H
#define ECUC_CFG_H

/*==================================================================================================
*                                    PRE-COMPILE CONFIGURATION
*================================================================================================*/

/*==================================================================================================
*                                    General Configuration
*================================================================================================*/
#define ECUC_DEV_ERROR_DETECT    STD_ON
#define ECUC_VERSION_INFO_API    STD_ON

/*==================================================================================================
*                                    Timing Configuration
*================================================================================================*/
#define ECUC_MAIN_FUNCTION_PERIOD_MS    (10U)

/*==================================================================================================
*                                    Other Configuration
*================================================================================================*/
#define ECUC_MAX_PDUS    (32U)
#define ECUC_MAX_SIGNALS    (128U)
#define ECUC_MAX_ROUTING_PATHS    (16U)
#define ECUC_MAX_PDU_LENGTH    (256U)
#define ECUC_MAX_SIGNAL_SIZE    (64U)
#define ECUC_GATEWAY_DIRECT    STD_ON
#define ECUC_GATEWAY_INDIRECT    STD_OFF
#define ECUC_SIGNAL_ADAPTATION_ENABLED    STD_ON
#ifndef ECUC_E_NO_ERROR
#define ECUC_E_NO_ERROR    (0U)
#endif
#ifndef ECUC_E_PARAM_POINTER
#define ECUC_E_PARAM_POINTER    (1U)
#endif
#define ECUC_VENDOR_ID_VALUE    (1U)
#define ECUC_MODULE_ID_VALUE    (150U)
#define ECUC_SW_MAJOR_VERSION_VALUE    (1U)
#define ECUC_SW_MINOR_VERSION_VALUE    (0U)
#define ECUC_SW_PATCH_VERSION_VALUE    (0U)

#endif /* ECUC_CFG_H */

/*==================[end of file]===========================================*/
