/**
 * @file LinM_Cfg.h
 * @brief LinM Configuration configuration header
 * @version 1.0.0
 * @date 2026-08-10
 * @note AUTO-GENERATED by yuleASR Configurator
 */

#ifndef LINM_CFG_H
#define LINM_CFG_H

/*==================================================================================================
*                                    PRE-COMPILE CONFIGURATION
*================================================================================================*/

/*==================================================================================================
*                                    General Configuration
*================================================================================================*/
#define LINM_DEV_ERROR_DETECT    STD_ON
#define LINM_VERSION_INFO_API    STD_ON

/*==================================================================================================
*                                    Timing Configuration
*================================================================================================*/
#define LINM_WAKEUP_TIMEOUT_MS    (50U)
#define LINM_SLEEP_TIMEOUT_MS    (100U)
#define LINM_SLAVE_RESPONSE_TIMEOUT_MS    (20U)
#define LINM_MAIN_FUNCTION_PERIOD_MS    (5U)

/*==================================================================================================
*                                    Other Configuration
*================================================================================================*/
#define LINM_WAKEUP_SUPPORT    STD_ON
#define LINM_SLEEP_SUPPORT    STD_ON
#define LINM_MASTER_NODE_SUPPORT    STD_ON
#define LINM_NUMBER_OF_CHANNELS    (1U)
#define LINM_NUMBER_OF_SCHEDULES    (4U)
#define LINM_NUMBER_OF_ENTRIES    (16U)
#define LINM_CHANNEL_0    (0U)
#define LINM_SCHEDULE_NULL    (0U)
#define LINM_SCHEDULE_MASTER    (1U)
#define LINM_SCHEDULE_DIAGNOSTIC    (2U)
#define LINM_SCHEDULE_TABLE_0    (3U)
#define LINM_ENTRY_TYPE_UNCONDITIONAL    (0U)
#define LINM_ENTRY_TYPE_EVENT_TRIGGERED    (1U)
#define LINM_ENTRY_TYPE_SPORADIC    (2U)
#define LINM_ENTRY_TYPE_DIAGNOSTIC    (3U)
#define LINM_ENTRY_TYPE_SLAVE_TO_SLAVE    (4U)
#define LINM_ENTRY_TYPE_EMPTY    (255U)
#define LINM_FRAME_TYPE_PUBLISHER    (0U)
#define LINM_FRAME_TYPE_SUBSCRIBER    (1U)
#define LINM_FRAME_TYPE_SUBSCRIBER_AUTO    (2U)
#define LINM_SCHEDULE_BASE_TIME_MS    (10U)
#define LINM_MASTER_REQUEST_DELAY_MS    (5U)
#define LINM_ENTRY_DELAY_MASK    (255U)
#define LINM_ENTRY_FRAME_MASK    (65280U)
#define LINM_ENTRY_TYPE_MASK    (16711680U)
#define LINM_ENTRY_DELAY_SHIFT    (0U)
#define LINM_ENTRY_FRAME_SHIFT    (8U)
#define LINM_ENTRY_TYPE_SHIFT    (16U)
#define LINM_SCHEDULE_PRIORITY_HIGH    (0U)
#define LINM_SCHEDULE_PRIORITY_NORMAL    (1U)
#define LINM_SCHEDULE_PRIORITY_LOW    (2U)
#define LINM_NULL_ENTRY    (4294967295U)

#endif /* LINM_CFG_H */

/*==================[end of file]===========================================*/
