/**
 * @file Ea_Cfg.h
 * @brief Ea Configuration configuration header
 * @version 1.0.0
 * @date 2026-08-10
 * @note AUTO-GENERATED by yuleASR Configurator
 */

#ifndef EA_CFG_H
#define EA_CFG_H

/*==================================================================================================
*                                    PRE-COMPILE CONFIGURATION
*================================================================================================*/

/*==================================================================================================
*                                    General Configuration
*================================================================================================*/
#define EA_DEV_ERROR_DETECT    STD_ON
#define EA_VERSION_INFO_API    STD_ON
#define EA_DEVICE_INDEX    (0U)

/*==================================================================================================
*                                    Module Configuration Counts
*================================================================================================*/
#define EA_NUM_BLOCKS    (32U)

/*==================================================================================================
*                                    Processing Modes
*================================================================================================*/
#define EA_POLL_MODE    STD_ON

/*==================================================================================================
*                                    Timing Configuration
*================================================================================================*/
#define EA_MAIN_FUNCTION_PERIOD_MS    (10U)

/*==================================================================================================
*                                    Other Configuration
*================================================================================================*/
#define EA_SET_MODE_SUPPORTED    STD_ON
#define EA_MAX_BLOCK_SIZE    (256U)
#define EA_BLOCK_ID_CONFIG    (1U)
#define EA_BLOCK_ID_CALIBRATION    (2U)
#define EA_BLOCK_ID_FAULT_MEMORY    (3U)
#define EA_BLOCK_ID_VIN    (4U)
#define EA_BLOCK_ID_ODOMETER    (5U)
#define EA_BLOCK_ID_USER_DATA_1    (6U)
#define EA_BLOCK_ID_USER_DATA_2    (7U)
#define EA_BLOCK_ID_RESERVED    (0U)
#define EA_BLOCK_SIZE_CONFIG    (64U)
#define EA_BLOCK_SIZE_CALIBRATION    (128U)
#define EA_BLOCK_SIZE_FAULT_MEMORY    (256U)
#define EA_BLOCK_SIZE_VIN    (17U)
#define EA_BLOCK_SIZE_ODOMETER    (8U)
#define EA_BLOCK_SIZE_USER_DATA    (64U)
#define EA_SECTOR_SIZE    (4096U)
#define EA_NUMBER_OF_SECTORS    (8U)
#define EA_INDEX_SIZE    (16U)
#define EA_NVM_JOB_END_NOTIFICATION    STD_ON
#define EA_NVM_JOB_ERROR_NOTIFICATION    STD_ON
#define EA_BLOCK_CRC_ENABLED    STD_ON

#endif /* EA_CFG_H */

/*==================[end of file]===========================================*/
