/**
 * @file DoIP_Cfg.h
 * @brief DoIP_Ecual Configuration configuration header
 * @version 1.0.0
 * @date 2026-08-10
 * @note AUTO-GENERATED by yuleASR Configurator
 */

#ifndef DOIP_CFG_H
#define DOIP_CFG_H

#include "Std_Types.h"   /* 非宏段依赖 Std_Types 基础类型 (uint32/uint8/uint16/boolean 等)，生成宏段不含此 include */

/*==================================================================================================
*                                    PRE-COMPILE CONFIGURATION
*================================================================================================*/

/*==================================================================================================
*                                    General Configuration
*================================================================================================*/
#ifndef DOIP_DEV_ERROR_DETECT
#define DOIP_DEV_ERROR_DETECT    STD_ON
#endif
#ifndef DOIP_VERSION_INFO_API
#define DOIP_VERSION_INFO_API    STD_ON
#endif

/*==================================================================================================
*                                    Hardware Object Handles
*================================================================================================*/
#define DOIP_UDP_SOAD_RX_PDU_ID    (0U)
#define DOIP_UDP_SOAD_TX_PDU_ID    (1U)
#define DOIP_TCP_SOAD_RX_PDU_ID_BASE    (2U)
#define DOIP_TCP_SOAD_TX_PDU_ID_BASE    (6U)
#define DOIP_PDUR_RX_PDU_ID_BASE    (0U)
#define DOIP_PDUR_TX_PDU_ID_BASE    (10U)

/*==================================================================================================
*                                    Timing Configuration
*================================================================================================*/
#define DOIP_GENERAL_INACTIVITY_TIMEOUT    (300000U)
#define DOIP_ALIVE_CHECK_RESPONSE_TIMEOUT    (500U)

/*==================================================================================================
*                                    Other Configuration
*================================================================================================*/
#ifndef DOIP_ROUTING_ACTIVATION_AUTHENTICATION
#define DOIP_ROUTING_ACTIVATION_AUTHENTICATION    STD_ON
#endif
#ifndef DOIP_ROUTING_ACTIVATION_CONFIRMATION
#define DOIP_ROUTING_ACTIVATION_CONFIRMATION    STD_ON
#endif
#ifndef DOIP_ALIVE_CHECK_SUPPORT
#define DOIP_ALIVE_CHECK_SUPPORT    STD_ON
#endif
#ifndef DOIP_NODE_TYPE
#define DOIP_NODE_TYPE    DOIP_NODE_TYPE_GATEWAY
#endif
#ifndef DOIP_VEHICLE_ANNOUNCEMENT
#define DOIP_VEHICLE_ANNOUNCEMENT    STD_ON
#endif
#ifndef DOIP_USE_EID_AS_VIN
#define DOIP_USE_EID_AS_VIN    STD_OFF
#endif
#ifndef DOIP_OBD_SUPPORT
#define DOIP_OBD_SUPPORT    STD_ON
#endif
#define DOIP_PROTOCOL_VERSION    (3U)
#define DOIP_PROTOCOL_VERSION_INVERTED    (252U)
#define DOIP_UDP_DISCOVERY_PORT    (13400U)
#define DOIP_TCP_DATA_PORT    (13400U)
#define DOIP_UDP_TEST_EQUIPMENT_PORT    (49152U)
#define DOIP_VEHICLE_ANNOUNCEMENT_INTERVAL    (500U)
#define DOIP_VEHICLE_ANNOUNCEMENT_NUM    (3U)
#define DOIP_INITIAL_INACTIVITY_TIME    (500U)
#define DOIP_ALIVE_CHECK_INTERVAL    (15000U)
#define DOIP_BUFFER_SIZE    (4096U)
#define DOIP_MAX_TESTER_CONNECTIONS    (4U)
#define DOIP_MAX_SIMULTANEOUS_REQUESTS    (2U)
#define DOIP_VIN_LENGTH    (17U)
#define DOIP_EID_LENGTH    (6U)
#define DOIP_GID_LENGTH    (6U)
#define DOIP_MAX_DIAG_MESSAGE_SIZE    (4095U)
#define DOIP_ROUTING_ACTIVATION_RESERVED    (0U)
#define DOIP_ROUTING_ACTIVATION_OEM    (4294967295U)
#define DOIP_FURTHER_ACTION_NONE    (0U)
#define DOIP_FURTHER_ACTION_CENTRAL_SEC    (16U)
#define DOIP_SYNC_STATUS_COMPLETE    (0U)
#define DOIP_SYNC_STATUS_INCOMPLETE    (16U)
#define DOIP_LOCAL_LOGICAL_ADDRESS    (1U)
#define DOIP_FUNCTIONAL_REQUEST_ADDR    (58368U)
#define DOIP_DEFAULT_TESTER_ADDRESS    (3584U)
#define DOIP_WWH_OBD_TESTER_ADDRESS    (3585U)
#define DOIP_CDS_TESTER_ADDRESS    (3586U)
#define DOIP_PAYLOAD_TYPE_GENERIC_NACK    (0U)
#define DOIP_PAYLOAD_TYPE_VID_REQUEST    (1U)
#define DOIP_PAYLOAD_TYPE_VID_RESPONSE    (4U)
#define DOIP_PAYLOAD_TYPE_ROUTING_ACTIVATION_REQUEST    (5U)
#define DOIP_PAYLOAD_TYPE_ROUTING_ACTIVATION_RESPONSE    (6U)
#define DOIP_PAYLOAD_TYPE_ALIVE_CHECK_REQUEST    (7U)
#define DOIP_PAYLOAD_TYPE_ALIVE_CHECK_RESPONSE    (8U)
#define DOIP_PAYLOAD_TYPE_DIAGNOSTIC_MESSAGE    (32769U)
#define DOIP_PAYLOAD_TYPE_DIAGNOSTIC_MESSAGE_ACK    (32770U)
#define DOIP_PAYLOAD_TYPE_DIAGNOSTIC_MESSAGE_NACK    (32771U)
#define DOIP_PAYLOAD_TYPE_ENTITY_STATUS_REQUEST    (16385U)
#define DOIP_PAYLOAD_TYPE_ENTITY_STATUS_RESPONSE    (16386U)
#define DOIP_PAYLOAD_TYPE_POWER_MODE_INFO_REQUEST    (16387U)
#define DOIP_PAYLOAD_TYPE_POWER_MODE_INFO_RESPONSE    (16388U)
#define DOIP_PAYLOAD_TYPE_DIAGNOSTIC_POWER_MODE_REQUEST    (16387U)
#define DOIP_PAYLOAD_TYPE_DIAGNOSTIC_POWER_MODE_RESPONSE    (16388U)
#define DOIP_NACK_CODE_INCORRECT_PATTERN_FORMAT    (0U)
#define DOIP_NACK_CODE_UNKNOWN_PAYLOAD_TYPE    (1U)
#define DOIP_NACK_CODE_MESSAGE_TOO_LARGE    (2U)
#define DOIP_NACK_CODE_OUT_OF_MEMORY    (3U)
#define DOIP_NACK_CODE_INVALID_PAYLOAD_LENGTH    (4U)
#define DOIP_ROUTING_ACTIVATION_DEFAULT    (0U)
#define DOIP_ROUTING_ACTIVATION_WWH_OBD    (1U)
#define DOIP_ROUTING_ACTIVATION_CDS    (2U)
#define DOIP_ROUTING_ACTIVATION_CENTRAL_SECURITY    (3U)


/*==================================================================================================
*  NON-MACRO SEGMENT (preserved from handwritten header, merged by codegen splice)
*  typedef(1) + struct(5) + extern config tables(1) — 依赖宏段计数宏, 故置于宏段之后
*================================================================================================*/
struct DoIP_ConfigType;

/* Node type enumeration */
typedef enum
{
    DOIP_NODE_TYPE_GATEWAY = 0,
    DOIP_NODE_TYPE_NODE    = 1
} DoIP_NodeType;

/* Routing activation configuration */
typedef struct
{
    uint8                   routingActivationType;
    uint16                  testerLogicalAddress;
    boolean                 authenticationRequired;
    boolean                 confirmationRequired;
    boolean                 oemDataRequired;
    uint8                   priority;
    uint32                  timeout;
} DoIP_RoutingActivationConfigType;

/* Socket connection configuration */
typedef struct
{
    uint16                  socketId;
    boolean                 isTcp;
    uint16                  localPort;
    uint8                   localAddr[4];
    uint16                  remotePort;
    uint8                   remoteAddr[4];
    uint16                  rxPduId;
    uint16                  txPduId;
} DoIP_SocketConfigType;

/* Tester connection configuration */
typedef struct
{
    uint16                  testerLogicalAddress;
    uint8                   testerHwAddress[6];
    uint16                  routingActivationRef;
    boolean                 tlsRequired;
} DoIP_TesterConfigType;

/* Vehicle announcement configuration */
typedef struct
{
    uint8                   vin[17];
    uint8                   eid[6];
    uint8                   gid[6];
    uint16                  logicalAddress;
    uint8                   furtherActionReq;
    uint8                   syncStatus;
    uint16                  announcementInterval;
    uint8                   announcementCount;
    boolean                 useEidAsVin;
} DoIP_VehicleAnnouncementConfigType;

/* Main configuration structure */
typedef struct DoIP_ConfigType
{
    const DoIP_RoutingActivationConfigType* routingActivations;
    uint8                                   numRoutingActivations;
    const DoIP_SocketConfigType*            sockets;
    uint8                                   numSockets;
    const DoIP_TesterConfigType*            testers;
    uint8                                   numTesters;
    const DoIP_VehicleAnnouncementConfigType* vehicleAnnouncement;
} DoIP_ConfigType;

/*================================================================================
**  EXTERNAL CONFIGURATION REFERENCES
================================================================================*/

extern const DoIP_ConfigType DoIP_Config;
#endif /* DOIP_CFG_H */

/*==================[end of file]===========================================*/
