/**
 * @file Mcu_Cfg.h
 * @brief MCU Driver Configuration Template - AutoSAR MCAL
 * @version 1.0.0
 * @date 2026-04-22
 * @author ConfigGenerator
 *
 * @note This file is generated by the ConfigGenerator tool.
 *       Manual changes may be overwritten.
 */

#ifndef MCU_CFG_H
#define MCU_CFG_H

#include "Std_Types.h"

/*==================================================================================================
*                                    PRE-COMPILE CONFIGURATION
==================================================================================================*/
#define MCU_DEV_ERROR_DETECT            (STD_ON)
#define MCU_VERSION_INFO_API            (STD_ON)
#define MCU_NO_PLL                      (STD_OFF)
#define MCU_INIT_CLOCK                  (STD_ON)
#define MCU_GET_RAM_STATE_API           (STD_OFF)

/*==================================================================================================
*                                    CLOCK CONFIGURATION
==================================================================================================*/
#define MCU_CLOCK_SETTING_DEFAULT       (0U)
#define MCU_NUM_CLOCK_CONFIGS           (1U)

/*==================================================================================================
*                                    RAM SECTOR CONFIGURATION
==================================================================================================*/
#define MCU_NUM_RAM_SECTORS             (1U)

/*==================================================================================================
*                                    MODE CONFIGURATION
==================================================================================================*/
#define MCU_NUM_MODES                   (3U)

#define MCU_MODE_RUN                    (0U)
#define MCU_MODE_SLEEP                  (1U)
#define MCU_MODE_DEEP_SLEEP             (2U)

/*==================================================================================================
*                                    RESET CONFIGURATION
==================================================================================================*/
#define MCU_NUM_RESET_REASONS           (8U)

#define MCU_RESET_UNDEFINED             (0U)
#define MCU_RESET_POWER_ON              (1U)
#define MCU_RESET_WATCHDOG              (2U)
#define MCU_RESET_SW                    (3U)
#define MCU_RESET_PIN                   (4U)
#define MCU_RESET_BROWN_OUT             (5U)
#define MCU_RESET_LOCKUP                (6U)
#define MCU_RESET_EXTERNAL              (7U)

/*==================================================================================================
*                                    CLOCK FREQUENCY (Hz)
==================================================================================================*/
#define MCU_XTAL_FREQUENCY              (24000000U)   /* 24 MHz */
#define MCU_SYSTEM_CLOCK_FREQUENCY      (800000000U)  /* 800 MHz */
#define MCU_BUS_CLOCK_FREQUENCY         (200000000U)  /* 200 MHz */
#define MCU_FLASH_CLOCK_FREQUENCY       (40000000U)   /* 40 MHz */

#endif /* MCU_CFG_H */
