/**
 * @file Spi_Cfg.h
 * @brief SPI Driver Configuration Template - AutoSAR MCAL
 * @version 1.0.0
 * @date 2026-04-22
 * @author ConfigGenerator
 *
 * @note This file is generated by the ConfigGenerator tool.
 *       Manual changes may be overwritten.
 */

#ifndef SPI_CFG_H
#define SPI_CFG_H

#include "Std_Types.h"

/*==================================================================================================
*                                    PRE-COMPILE CONFIGURATION
==================================================================================================*/
#define SPI_DEV_ERROR_DETECT            (STD_ON)
#define SPI_VERSION_INFO_API            (STD_ON)
#define SPI_INTERRUPTIBLE_SEQ_ALLOWED   (STD_OFF)
#define SPI_HW_STATUS_API               (STD_ON)
#define SPI_CANCEL_API                  (STD_OFF)
#define SPI_LEVEL_DELIVERED             (2U)

/*==================================================================================================
*                                    CHANNEL CONFIGURATION
==================================================================================================*/
#define SPI_NUM_CHANNELS                (4U)
#define SPI_NUM_JOBS                    (8U)
#define SPI_NUM_SEQUENCES               (4U)
#define SPI_NUM_HW_UNITS                (3U)

/*==================================================================================================
*                                    SPI CHANNEL IDs
==================================================================================================*/
#define SPI_CHANNEL_0                   (0U)
#define SPI_CHANNEL_1                   (1U)
#define SPI_CHANNEL_2                   (2U)
#define SPI_CHANNEL_3                   (3U)

/*==================================================================================================
*                                    SPI JOB IDs
==================================================================================================*/
#define SPI_JOB_0                       (0U)
#define SPI_JOB_1                       (1U)
#define SPI_JOB_2                       (2U)
#define SPI_JOB_3                       (3U)

/*==================================================================================================
*                                    SPI SEQUENCE IDs
==================================================================================================*/
#define SPI_SEQUENCE_0                  (0U)
#define SPI_SEQUENCE_1                  (1U)
#define SPI_SEQUENCE_2                  (2U)
#define SPI_SEQUENCE_3                  (3U)

/*==================================================================================================
*                                    SPI DATA WIDTH
==================================================================================================*/
#define SPI_DATA_WIDTH_8BIT             (8U)
#define SPI_DATA_WIDTH_16BIT            (16U)
#define SPI_DATA_WIDTH_32BIT            (32U)

/*==================================================================================================
*                                    SPI CLOCK POLARITY/PHASE
==================================================================================================*/
#define SPI_CPOL_LOW                    (0U)
#define SPI_CPOL_HIGH                   (1U)
#define SPI_CPHA_LEADING                (0U)
#define SPI_CPHA_TRAILING               (1U)

/*==================================================================================================
*                                    SPI TRANSFER START
==================================================================================================*/
#define SPI_TRANSFER_START_LSB          (0U)
#define SPI_TRANSFER_START_MSB          (1U)

/*==================================================================================================
*                                    SPI BAUDRATE PRESCALER
==================================================================================================*/
#define SPI_BAUDRATE_PRESCALER_2        (0U)
#define SPI_BAUDRATE_PRESCALER_4        (1U)
#define SPI_BAUDRATE_PRESCALER_8        (2U)
#define SPI_BAUDRATE_PRESCALER_16       (3U)
#define SPI_BAUDRATE_PRESCALER_32       (4U)
#define SPI_BAUDRATE_PRESCALER_64       (5U)
#define SPI_BAUDRATE_PRESCALER_128      (6U)
#define SPI_BAUDRATE_PRESCALER_256      (7U)

#endif /* SPI_CFG_H */
