/**
 * @file FiM_Cfg.h
 * @brief FiM Configuration configuration header
 * @version 1.0.0
 * @date 2026-08-10
 * @note AUTO-GENERATED by yuleASR Configurator
 */

#ifndef FIM_CFG_H
#define FIM_CFG_H

/*==================================================================================================
*                                    PRE-COMPILE CONFIGURATION
*================================================================================================*/

/*==================================================================================================
*                                    General Configuration
*================================================================================================*/
#define FIM_DEV_ERROR_DETECT    STD_ON
#define FIM_VERSION_INFO_API    STD_ON

/*==================================================================================================
*                                    Module Configuration Counts
*================================================================================================*/
#define FIM_NUM_FUNCTIONS    (32U)
#define FIM_NUM_EVENTS_PER_FUNCTION    (8U)
#define FIM_NUM_SUMMARY_EVENTS    (16U)

/*==================================================================================================
*                                    Timing Configuration
*================================================================================================*/
#define FIM_MAIN_FUNCTION_PERIOD_MS    (10U)

/*==================================================================================================
*                                    Other Configuration
*================================================================================================*/
#define FIM_INHIBITION_CONFIGURATION_SUPPORTED    STD_ON
#ifndef FIM_MAX_FUNCTIONS
#define FIM_MAX_FUNCTIONS    (32U)
#endif
#define FIM_FID_MIN    (1U)
#define FIM_FID_MAX    (31U)
#define FIM_FID_INVALID    (0U)
#define FIM_SUMMARY_EVENT_ID_MIN    (1U)
#define FIM_SUMMARY_EVENT_ID_MAX    (15U)
#define FIM_SUMMARY_EVENT_ID_INVALID    (0U)
#define FIM_INHIBIT_NONE    (0U)
#define FIM_INHIBIT_IF_TEST_FAILED    DEM_UDS_STATUS_TF
#define FIM_INHIBIT_IF_TEST_FAILED_TOC    DEM_UDS_STATUS_TFTOC
#define FIM_INHIBIT_IF_PENDING    DEM_UDS_STATUS_PDTC
#define FIM_INHIBIT_IF_CONFIRMED    DEM_UDS_STATUS_CDTC
#define FIM_INHIBIT_IF_TEST_NOT_COMPLETED_TOC    DEM_UDS_STATUS_TNCTOC
#define FIM_INHIBIT_IF_TEST_NOT_COMPLETED_SLC    DEM_UDS_STATUS_TNCSLC
#define FIM_INHIBIT_IF_TEST_FAILED_SLC    DEM_UDS_STATUS_TFSLC
#define FIM_INHIBIT_IF_WARNING_INDICATOR    DEM_UDS_STATUS_WIR
#define FIM_DEFAULT_PERMISSION    FIM_PERMISSION_ALLOWED
#define FIM_DEFAULT_AVAILABILITY    STD_ON

#endif /* FIM_CFG_H */

/*==================[end of file]===========================================*/
