/**
 * @file LinTrcv_Cfg.h
 * @brief LinTrcv Configuration configuration header
 * @version 1.0.0
 * @date 2026-08-10
 * @note AUTO-GENERATED by yuleASR Configurator
 */

#ifndef LINTRCV_CFG_H
#define LINTRCV_CFG_H

#include "Std_Types.h"   /* 非宏段依赖 Std_Types 基础类型 (uint32/uint8/uint16/boolean 等)，生成宏段不含此 include */

#include "Std_Types.h"
#include "MemMap.h"
#include "MemMap.h"
#include "MemMap.h"
#include "MemMap.h"
#include "MemMap.h"
#include "MemMap.h"
#include "MemMap.h"
#include "MemMap.h"

/*==================================================================================================
*                                    PRE-COMPILE CONFIGURATION
*================================================================================================*/

/*==================================================================================================
*                                    General Configuration
*================================================================================================*/
#ifndef LINTRCV_DEV_ERROR_DETECT
#define LINTRCV_DEV_ERROR_DETECT    STD_ON
#endif
#ifndef LINTRCV_VERSION_INFO_API
#define LINTRCV_VERSION_INFO_API    STD_ON
#endif
#define LINTRCV_SPI_DEVICE_ID    (0U)

/*==================================================================================================
*                                    Module Configuration Counts
*================================================================================================*/
#ifndef LINTRCV_NUM_CHANNELS
#define LINTRCV_NUM_CHANNELS    (2U)
#endif

/*==================================================================================================
*                                    Hardware Object Handles
*================================================================================================*/
#ifndef DIO_CHANNEL_TJA1021_0_TXD
#define DIO_CHANNEL_TJA1021_0_TXD    (3U)
#endif
#ifndef DIO_CHANNEL_TJA1021_0_RXD
#define DIO_CHANNEL_TJA1021_0_RXD    (4U)
#endif

/*==================================================================================================
*                                    Other Configuration
*================================================================================================*/
#ifndef LINTRCV_WAKEUP_SUPPORTED
#define LINTRCV_WAKEUP_SUPPORTED    STD_ON
#endif
#ifndef LINTRCV_WAKEUP_BY_BUS_USED
#define LINTRCV_WAKEUP_BY_BUS_USED    STD_ON
#endif
#ifndef LINTRCV_WAKEUP_BY_PIN_USED
#define LINTRCV_WAKEUP_BY_PIN_USED    STD_ON
#endif
#ifndef LINTRCV_SPI_SUPPORT
#define LINTRCV_SPI_SUPPORT    STD_OFF
#endif
#ifndef LINTRCV_I2C_SUPPORT
#define LINTRCV_I2C_SUPPORT    STD_OFF
#endif
#ifndef LINTRCV_TJA1021_SUPPORT
#define LINTRCV_TJA1021_SUPPORT    STD_ON
#endif
#ifndef LINTRCV_TJA1022_SUPPORT
#define LINTRCV_TJA1022_SUPPORT    STD_ON
#endif
#define LINTRCV_MAX_CHANNELS    (4U)
#define LINTRCV_CHANNEL_0    (0U)
#define LINTRCV_CHANNEL_1    (1U)
#define LINTRCV_CHANNEL_2    (2U)
#define LINTRCV_CHANNEL_3    (3U)
#ifndef DIO_CHANNEL_TJA1021_0_EN
#define DIO_CHANNEL_TJA1021_0_EN    (0U)
#endif
#ifndef DIO_CHANNEL_TJA1021_0_NWAKE
#define DIO_CHANNEL_TJA1021_0_NWAKE    (1U)
#endif
#ifndef DIO_CHANNEL_TJA1021_0_NERR
#define DIO_CHANNEL_TJA1021_0_NERR    (2U)
#endif
#ifndef DIO_CHANNEL_TJA1021_1_EN
#define DIO_CHANNEL_TJA1021_1_EN    (10U)
#endif
#ifndef DIO_CHANNEL_TJA1021_1_NWAKE
#define DIO_CHANNEL_TJA1021_1_NWAKE    (11U)
#endif
#ifndef DIO_CHANNEL_TJA1021_1_NERR
#define DIO_CHANNEL_TJA1021_1_NERR    (12U)
#endif
#ifndef LINTRCV_WAKEUP_SOURCE_0
#define LINTRCV_WAKEUP_SOURCE_0    (16U)
#endif
#ifndef LINTRCV_WAKEUP_SOURCE_1
#define LINTRCV_WAKEUP_SOURCE_1    (32U)
#endif
#ifndef LINTRCV_WAKEUP_SOURCE_2
#define LINTRCV_WAKEUP_SOURCE_2    (64U)
#endif
#ifndef LINTRCV_WAKEUP_SOURCE_3
#define LINTRCV_WAKEUP_SOURCE_3    (128U)
#endif
#define LINTRCV_TJA1021_SLEEP_TO_NORMAL_US    (1000U)
#define LINTRCV_TJA1021_STANDBY_TO_NORMAL_US    (100U)
#define LINTRCV_TJA1021_NORMAL_TO_STANDBY_US    (50U)
#define LINTRCV_TJA1021_NORMAL_TO_SLEEP_US    (50U)
#define LINTRCV_WAKEUP_DEBOUNCE_US    (50U)
#define LINTRCV_TJA1021_EN_HIGH    STD_ON
#define LINTRCV_TJA1021_EN_LOW    STD_OFF
#define LINTRCV_TJA1021_NWAKE_ACTIVE    STD_OFF
#define LINTRCV_TJA1021_NWAKE_INACTIVE    STD_ON
#define LINTRCV_TJA1021_NERR_ERROR    STD_OFF
#define LINTRCV_TJA1021_NERR_NO_ERROR    STD_ON
#define LINTRCV_DEFAULT_INITIAL_MODE    LINTRCV_OPMODE_NORMAL
#define LINTRCV_DEFAULT_WAKEUP_BY_BUS    STD_ON
#define LINTRCV_DEFAULT_WAKEUP_BY_PIN    STD_ON
#define LINTRCV_SPI_CHANNEL    (0U)
#define LINTRCV_DIO_NOTIFICATION_API    STD_ON


/*==================================================================================================
*  NON-MACRO SEGMENT (preserved from handwritten header, merged by codegen splice)
*  typedef(0) + struct(0) + extern config tables(1) — 依赖宏段计数宏, 故置于宏段之后
*================================================================================================*/
extern void EcuM_SetWakeupEvent(uint32 wakeupSource);
#endif /* LINTRCV_CFG_H */

/*==================[end of file]===========================================*/
