/*
 * DDS Configuration Tool - Command Line Interface
 *
 * Copyright (c) 2024 DDS Config Tool Authors
 * SPDX-License-Identifier: MIT
 */

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <getopt.h>
#include <errno.h>
#include <unistd.h>

#include "dds_config_types.h"
#include "dds_config_parser.h"
#include "dds_config_validator.h"

#define PROGRAM_NAME "dds-config"
#define PROGRAM_VERSION "1.0.0"

/* Command types */
typedef enum {
    CMD_NONE = 0,
    CMD_INIT,
    CMD_VALIDATE,
    CMD_GENERATE,
    CMD_APPLY,
    CMD_EXPORT,
    CMD_LIST,
    CMD_INTERACTIVE,
    CMD_HELP,
    CMD_VERSION
} command_t;

/* Command options */
typedef struct {
    command_t command;
    char *input_file;
    char *output_file;
    char *output_dir;
    dds_config_format_t format;
    dds_validation_options_t validation_opts;
    int domain_id;
    bool list_topics;
    bool list_qos;
    bool list_domains;
    bool list_participants;
    bool verbose;
    bool quiet;
} cli_options_t;

/* Function prototypes */
static void print_usage(const char *program);
static void print_version(void);
static void print_help(void);
static int parse_args(int argc, char *argv[], cli_options_t *opts);
static int cmd_init(const cli_options_t *opts);
static int cmd_validate(const cli_options_t *opts);
static int cmd_generate(const cli_options_t *opts);
static int cmd_list(const cli_options_t *opts);
static int cmd_export(const cli_options_t *opts);
static dds_configuration_t* create_default_config(void);
static int write_config_file(const dds_configuration_t *config,
                              const char *filename,
                              dds_config_format_t format);

/* Default configuration template */
static const char *default_yaml_config =
    "# DDS Configuration File\n"
    "# Generated by dds-config init\n"
    "\n"
    "version: \"1.0.0\"\n"
    "\n"
    "system:\n"
    "  name: \"MyDDSSystem\"\n"
    "  description: \"DDS System Configuration\"\n"
    "  version: \"1.0.0\"\n"
    "\n"
    "# Domain Configuration\n"
    "domains:\n"
    "  - id: 0\n"
    "    name: \"DefaultDomain\"\n"
    "    description: \"Default domain for system communication\"\n"
    "    discovery:\n"
    "      enabled: true\n"
    "      protocol: UDPv4\n"
    "      lease_duration: \"30s\"\n"
    "    transport:\n"
    "      multicast: false\n"
    "    security:\n"
    "      enabled: false\n"
    "\n"
    "# QoS Profiles\n"
    "qos_profiles:\n"
    "  - name: \"default_qos\"\n"
    "    description: \"Default QoS profile\"\n"
    "    reliability:\n"
    "      kind: BEST_EFFORT\n"
    "    durability:\n"
    "      kind: VOLATILE\n"
    "    history:\n"
    "      kind: KEEP_LAST\n"
    "      depth: 1\n"
    "\n"
    "  - name: \"reliable_qos\"\n"
    "    description: \"Reliable communication QoS\"\n"
    "    reliability:\n"
    "      kind: RELIABLE\n"
    "      max_blocking_time: \"100ms\"\n"
    "    durability:\n"
    "      kind: TRANSIENT_LOCAL\n"
    "    history:\n"
    "      kind: KEEP_LAST\n"
    "      depth: 10\n"
    "\n"
    "# Topic Definitions\n"
    "topics:\n"
    "  - name: \"HelloWorldTopic\"\n"
    "    type: \"HelloWorld\"\n"
    "    domain_id: 0\n"
    "    qos_profile: \"default_qos\"\n"
    "\n"
    "# Participant Definitions\n"
    "participants:\n"
    "  - name: \"DefaultParticipant\"\n"
    "    domain_id: 0\n"
    "    qos_profile: \"default_qos\"\n"
    "\n"
    "# Logging Configuration\n"
    "logging:\n"
    "  enabled: true\n"
    "  level: INFO\n"
    "  output: stdout\n"
    "\n"
    "# Monitoring Configuration\n"
    "monitoring:\n"
    "  enabled: false\n"
    "  statistics_enabled: false\n";

int main(int argc, char *argv[]) {
    cli_options_t opts;
    int ret = 0;

    memset(&opts, 0, sizeof(opts));
    opts.format = DDS_CONFIG_FORMAT_AUTO;
    opts.domain_id = -1;
    opts.validation_opts = DDS_VALIDATION_DEFAULT_OPTIONS;

    if (parse_args(argc, argv, &opts) != 0) {
        return 1;
    }

    switch (opts.command) {
        case CMD_INIT:
            ret = cmd_init(&opts);
            break;
        case CMD_VALIDATE:
            ret = cmd_validate(&opts);
            break;
        case CMD_GENERATE:
            fprintf(stderr, "Generate command not yet implemented\n");
            ret = 1;
            break;
        case CMD_APPLY:
            fprintf(stderr, "Apply command not yet implemented\n");
            ret = 1;
            break;
        case CMD_EXPORT:
            ret = cmd_export(&opts);
            break;
        case CMD_LIST:
            ret = cmd_list(&opts);
            break;
        case CMD_INTERACTIVE:
            fprintf(stderr, "Interactive mode not yet implemented\n");
            ret = 1;
            break;
        case CMD_HELP:
            print_help();
            break;
        case CMD_VERSION:
            print_version();
            break;
        default:
            print_usage(argv[0]);
            ret = 1;
            break;
    }

    /* Cleanup */
    free(opts.input_file);
    free(opts.output_file);
    free(opts.output_dir);

    return ret;
}

static void print_usage(const char *program) {
    fprintf(stderr, "Usage: %s <command> [options]\n\n", program);
    fprintf(stderr, "Commands:\n");
    fprintf(stderr, "  init [file]          Initialize a new configuration file\n");
    fprintf(stderr, "  validate <file>      Validate a configuration file\n");
    fprintf(stderr, "  generate <file>      Generate C code from configuration\n");
    fprintf(stderr, "  apply <file>         Apply configuration to DDS system\n");
    fprintf(stderr, "  export <file>        Export configuration to different format\n");
    fprintf(stderr, "  list <file>          List configuration entities\n");
    fprintf(stderr, "  interactive          Start interactive configuration mode\n");
    fprintf(stderr, "  help                 Show detailed help\n");
    fprintf(stderr, "  version              Show version information\n");
    fprintf(stderr, "\n");
}

static void print_version(void) {
    printf("%s version %s\n", PROGRAM_NAME, PROGRAM_VERSION);
    printf("DDS Configuration Tool\n");
    printf("Copyright (c) 2024 DDS Config Tool Authors\n");
}

static void print_help(void) {
    print_version();
    printf("\n");
    print_usage(PROGRAM_NAME);
    printf("Options:\n");
    printf("  -f, --format <fmt>   Set output format (yaml, json, xml)\n");
    printf("  -o, --output <file>  Set output file\n");
    printf("  -d, --dir <dir>      Set output directory\n");
    printf("  --domain <id>        Specify domain ID\n");
    printf("  --strict             Enable strict validation mode\n");
    printf("  -v, --verbose        Enable verbose output\n");
    printf("  -q, --quiet          Suppress non-error output\n");
    printf("  -h, --help           Show this help message\n");
    printf("\nExamples:\n");
    printf("  dds-config init config.yaml\n");
    printf("  dds-config validate config.yaml\n");
    printf("  dds-config list config.yaml --topics\n");
    printf("  dds-config export config.yaml --format json -o output.json\n");
}

static int parse_args(int argc, char *argv[], cli_options_t *opts) {
    static struct option long_options[] = {
        {"format", required_argument, 0, 'f'},
        {"output", required_argument, 0, 'o'},
        {"dir", required_argument, 0, 'd'},
        {"domain", required_argument, 0, 1},
        {"strict", no_argument, 0, 2},
        {"topics", no_argument, 0, 3},
        {"qos-profiles", no_argument, 0, 4},
        {"domains", no_argument, 0, 5},
        {"participants", no_argument, 0, 6},
        {"verbose", no_argument, 0, 'v'},
        {"quiet", no_argument, 0, 'q'},
        {"help", no_argument, 0, 'h'},
        {"version", no_argument, 0, 'V'},
        {0, 0, 0, 0}
    };

    if (argc < 2) {
        print_usage(argv[0]);
        return 1;
    }

    /* Parse command */
    const char *cmd = argv[1];
    if (strcmp(cmd, "init") == 0) {
        opts->command = CMD_INIT;
    } else if (strcmp(cmd, "validate") == 0) {
        opts->command = CMD_VALIDATE;
    } else if (strcmp(cmd, "generate") == 0) {
        opts->command = CMD_GENERATE;
    } else if (strcmp(cmd, "apply") == 0) {
        opts->command = CMD_APPLY;
    } else if (strcmp(cmd, "export") == 0) {
        opts->command = CMD_EXPORT;
    } else if (strcmp(cmd, "list") == 0) {
        opts->command = CMD_LIST;
    } else if (strcmp(cmd, "interactive") == 0) {
        opts->command = CMD_INTERACTIVE;
    } else if (strcmp(cmd, "help") == 0 || strcmp(cmd, "--help") == 0) {
        opts->command = CMD_HELP;
        return 0;
    } else if (strcmp(cmd, "version") == 0 || strcmp(cmd, "--version") == 0 || strcmp(cmd, "-v") == 0) {
        opts->command = CMD_VERSION;
        return 0;
    } else {
        fprintf(stderr, "Unknown command: %s\n", cmd);
        print_usage(argv[0]);
        return 1;
    }

    /* Shift arguments for getopt */
    int cmd_argc = argc - 1;
    char **cmd_argv = argv + 1;

    int c;
    int option_index = 0;
    optind = 1;  /* Reset getopt */

    while ((c = getopt_long(cmd_argc, cmd_argv, "f:o:d:vqhV",
                            long_options, &option_index)) != -1) {
        switch (c) {
            case 'f':
                if (strcmp(optarg, "yaml") == 0) {
                    opts->format = DDS_CONFIG_FORMAT_YAML;
                } else if (strcmp(optarg, "json") == 0) {
                    opts->format = DDS_CONFIG_FORMAT_JSON;
                } else if (strcmp(optarg, "xml") == 0) {
                    opts->format = DDS_CONFIG_FORMAT_XML;
                } else {
                    fprintf(stderr, "Unknown format: %s\n", optarg);
                    return 1;
                }
                break;
            case 'o':
                opts->output_file = strdup(optarg);
                break;
            case 'd':
                opts->output_dir = strdup(optarg);
                break;
            case 1: /* --domain */
                opts->domain_id = atoi(optarg);
                break;
            case 2: /* --strict */
                opts->validation_opts.strict_mode = true;
                break;
            case 3: /* --topics */
                opts->list_topics = true;
                break;
            case 4: /* --qos-profiles */
                opts->list_qos = true;
                break;
            case 5: /* --domains */
                opts->list_domains = true;
                break;
            case 6: /* --participants */
                opts->list_participants = true;
                break;
            case 'v':
                opts->verbose = true;
                break;
            case 'q':
                opts->quiet = true;
                break;
            case 'h':
                opts->command = CMD_HELP;
                return 0;
            case 'V':
                opts->command = CMD_VERSION;
                return 0;
            default:
                return 1;
        }
    }

    /* Get input file if provided */
    if (optind < cmd_argc) {
        opts->input_file = strdup(cmd_argv[optind]);
    }

    return 0;
}

static int cmd_init(const cli_options_t *opts) {
    const char *filename = opts->input_file ? opts->input_file : "dds_config.yaml";
    dds_config_format_t format = opts->format;

    if (format == DDS_CONFIG_FORMAT_AUTO) {
        format = dds_config_detect_format(filename);
        if (format == DDS_CONFIG_FORMAT_AUTO) {
            format = DDS_CONFIG_FORMAT_YAML;  /* Default */
        }
    }

    /* Check if file exists */
    if (access(filename, F_OK) == 0) {
        fprintf(stderr, "File already exists: %s\n", filename);
        return 1;
    }

    /* Write default configuration */
    FILE *fp = fopen(filename, "w");
    if (!fp) {
        fprintf(stderr, "Failed to create file: %s (%s)\n",
                filename, strerror(errno));
        return 1;
    }

    /* For now, only YAML is supported in the template */
    if (format == DDS_CONFIG_FORMAT_YAML) {
        fprintf(fp, "%s", default_yaml_config);
    } else {
        fprintf(stderr, "Default templates only available for YAML format\n");
        fclose(fp);
        unlink(filename);
        return 1;
    }

    fclose(fp);

    if (!opts->quiet) {
        printf("Created DDS configuration file: %s\n", filename);
    }

    return 0;
}

static int cmd_validate(const cli_options_t *opts) {
    if (!opts->input_file) {
        fprintf(stderr, "Error: No configuration file specified\n");
        return 1;
    }

    if (!opts->quiet) {
        printf("Validating: %s\n", opts->input_file);
    }

    /* Create parser */
    dds_config_parser_t *parser = dds_config_parser_create(NULL, NULL);
    if (!parser) {
        fprintf(stderr, "Failed to create parser\n");
        return 1;
    }

    /* Load configuration */
    dds_configuration_t *config = NULL;
    dds_config_error_t err = dds_config_parser_load_file(
        parser, opts->input_file, opts->format, &config);

    dds_config_parser_destroy(parser);

    if (err != DDS_CONFIG_OK) {
        fprintf(stderr, "Parse error: %s\n", dds_config_error_string(err));
        return 1;
    }

    /* Validate configuration */
    dds_validation_result_t *result = dds_config_validate(
        config, &opts->validation_opts);

    if (!result) {
        fprintf(stderr, "Validation failed: internal error\n");
        dds_config_destroy(config);
        return 1;
    }

    /* Print validation results */
    if (!opts->quiet || !dds_validation_result_is_valid(result)) {
        dds_validation_result_print(result);
    }

    int ret = dds_validation_result_is_valid(result) ? 0 : 1;

    dds_validation_result_destroy(result);
    dds_config_destroy(config);

    return ret;
}

static int cmd_list(const cli_options_t *opts) {
    if (!opts->input_file) {
        fprintf(stderr, "Error: No configuration file specified\n");
        return 1;
    }

    /* Create parser */
    dds_config_parser_t *parser = dds_config_parser_create(NULL, NULL);
    if (!parser) {
        fprintf(stderr, "Failed to create parser\n");
        return 1;
    }

    /* Load configuration */
    dds_configuration_t *config = NULL;
    dds_config_error_t err = dds_config_parser_load_file(
        parser, opts->input_file, opts->format, &config);

    dds_config_parser_destroy(parser);

    if (err != DDS_CONFIG_OK) {
        fprintf(stderr, "Parse error: %s\n", dds_config_error_string(err));
        return 1;
    }

    /* Determine what to list */
    bool list_all = !opts->list_topics && !opts->list_qos &&
                    !opts->list_domains && !opts->list_participants;

    if (list_all || opts->list_domains) {
        printf("\n=== Domains (%zu) ===\n", config->domain_count);
        for (size_t i = 0; i < config->domain_count; i++) {
            dds_domain_config_t *d = &config->domains[i];
            printf("  [%u] %s\n", d->domain_id,
                   d->name[0] ? d->name : "(unnamed)");
            if (d->description[0]) {
                printf("       Description: %s\n", d->description);
            }
        }
    }

    if (list_all || opts->list_topics) {
        printf("\n=== Topics (%zu) ===\n", config->topic_count);
        for (size_t i = 0; i < config->topic_count; i++) {
            dds_topic_config_t *t = &config->topics[i];
            printf("  %s\n", t->name);
            printf("       Type: %s\n", t->type_name);
            printf("       Domain: %u\n", t->domain_id);
            if (t->qos_profile[0]) {
                printf("       QoS Profile: %s\n", t->qos_profile);
            }
        }
    }

    if (list_all || opts->list_qos) {
        printf("\n=== QoS Profiles (%zu) ===\n", config->qos_profile_count);
        for (size_t i = 0; i < config->qos_profile_count; i++) {
            dds_qos_profile_t *q = &config->qos_profiles[i];
            printf("  %s\n", q->name);
            if (q->description[0]) {
                printf("       Description: %s\n", q->description);
            }
            if (q->has_reliability) {
                printf("       Reliability: %s\n",
                       dds_qos_reliability_to_string(q->reliability.kind));
            }
            if (q->has_durability) {
                printf("       Durability: %s\n",
                       dds_qos_durability_to_string(q->durability.kind));
            }
        }
    }

    if (list_all || opts->list_participants) {
        printf("\n=== Participants (%zu) ===\n", config->participant_count);
        for (size_t i = 0; i < config->participant_count; i++) {
            dds_participant_config_t *p = &config->participants[i];
            printf("  %s\n", p->name);
            printf("       Domain: %u\n", p->domain_id);
            if (p->qos_profile[0]) {
                printf("       QoS Profile: %s\n", p->qos_profile);
            }
        }
    }

    printf("\n");
    dds_config_destroy(config);
    return 0;
}

static int cmd_export(const cli_options_t *opts) {
    if (!opts->input_file) {
        fprintf(stderr, "Error: No input file specified\n");
        return 1;
    }

    if (!opts->output_file) {
        fprintf(stderr, "Error: No output file specified (use -o)\n");
        return 1;
    }

    dds_config_format_t output_format = opts->format;
    if (output_format == DDS_CONFIG_FORMAT_AUTO) {
        output_format = dds_config_detect_format(opts->output_file);
        if (output_format == DDS_CONFIG_FORMAT_AUTO) {
            fprintf(stderr, "Error: Cannot detect output format from filename\n");
            return 1;
        }
    }

    /* Create parser */
    dds_config_parser_t *parser = dds_config_parser_create(NULL, NULL);
    if (!parser) {
        fprintf(stderr, "Failed to create parser\n");
        return 1;
    }

    /* Load configuration */
    dds_configuration_t *config = NULL;
    dds_config_error_t err = dds_config_parser_load_file(
        parser, opts->input_file, DDS_CONFIG_FORMAT_AUTO, &config);

    dds_config_parser_destroy(parser);

    if (err != DDS_CONFIG_OK) {
        fprintf(stderr, "Parse error: %s\n", dds_config_error_string(err));
        return 1;
    }

    /* Write to output file */
    err = write_config_file(config, opts->output_file, output_format);
    dds_config_destroy(config);

    if (err != DDS_CONFIG_OK) {
        fprintf(stderr, "Export error: %s\n", dds_config_error_string(err));
        return 1;
    }

    if (!opts->quiet) {
        printf("Exported configuration to: %s\n", opts->output_file);
    }

    return 0;
}

static dds_configuration_t* create_default_config(void) {
    dds_configuration_t *config = dds_config_create();
    if (!config) {
        return NULL;
    }

    /* Set version */
    strncpy(config->version, "1.0.0", sizeof(config->version) - 1);

    /* Set system info */
    strncpy(config->system.name, "MyDDSSystem",
            sizeof(config->system.name) - 1);
    strncpy(config->system.description, "DDS System Configuration",
            sizeof(config->system.description) - 1);
    strncpy(config->system.version, "1.0.0",
            sizeof(config->system.version) - 1);

    /* Add default domain */
    config->domains = calloc(1, sizeof(dds_domain_config_t));
    if (config->domains) {
        config->domain_count = 1;
        config->domains[0].domain_id = 0;
        strncpy(config->domains[0].name, "DefaultDomain",
                sizeof(config->domains[0].name) - 1);
        config->domains[0].discovery.enabled = true;
        config->domains[0].discovery.protocol = DDS_TRANSPORT_UDPv4;
    }

    /* Add default QoS profile */
    config->qos_profiles = calloc(1, sizeof(dds_qos_profile_t));
    if (config->qos_profiles) {
        config->qos_profile_count = 1;
        strncpy(config->qos_profiles[0].name, "default_qos",
                sizeof(config->qos_profiles[0].name) - 1);
        config->qos_profiles[0].reliability.kind = DDS_RELIABILITY_BEST_EFFORT;
        config->qos_profiles[0].has_reliability = true;
        config->qos_profiles[0].durability.kind = DDS_DURABILITY_VOLATILE;
        config->qos_profiles[0].has_durability = true;
        config->qos_profiles[0].history.kind = DDS_HISTORY_KEEP_LAST;
        config->qos_profiles[0].history.depth = 1;
        config->qos_profiles[0].has_history = true;
    }

    return config;
}

static int write_config_file(const dds_configuration_t *config,
                              const char *filename,
                              dds_config_format_t format) {
    (void)config;  /* Unused for now */

    FILE *fp = fopen(filename, "w");
    if (!fp) {
        return DDS_CONFIG_ERR_FILE_IO;
    }

    /* For now, only simple YAML export is implemented */
    if (format == DDS_CONFIG_FORMAT_YAML) {
        fprintf(fp, "# DDS Configuration\n");
        fprintf(fp, "version: \"%s\"\n\n", config->version);

        fprintf(fp, "system:\n");
        fprintf(fp, "  name: \"%s\"\n", config->system.name);
        fprintf(fp, "  description: \"%s\"\n", config->system.description);
        fprintf(fp, "  version: \"%s\"\n\n", config->system.version);

        fprintf(fp, "domains:\n");
        for (size_t i = 0; i < config->domain_count; i++) {
            fprintf(fp, "  - id: %u\n", config->domains[i].domain_id);
            fprintf(fp, "    name: \"%s\"\n", config->domains[i].name);
        }

        fprintf(fp, "\ntopics:\n");
        for (size_t i = 0; i < config->topic_count; i++) {
            fprintf(fp, "  - name: \"%s\"\n", config->topics[i].name);
            fprintf(fp, "    type: \"%s\"\n", config->topics[i].type_name);
            fprintf(fp, "    domain_id: %u\n", config->topics[i].domain_id);
        }
    } else {
        fprintf(stderr, "Export to %s not yet implemented\n",
                dds_config_format_extension(format));
        fclose(fp);
        return DDS_CONFIG_ERR_INVALID_FORMAT;
    }

    fclose(fp);
    return DDS_CONFIG_OK;
}
