/**
 * @file SomeIpTp_Cfg.h
 * @brief SomeIpTp Configuration configuration header
 * @version 1.0.0
 * @date 2026-08-10
 * @note AUTO-GENERATED by yuleASR Configurator
 */

#ifndef SOMEIPTP_CFG_H
#define SOMEIPTP_CFG_H

/*==================================================================================================
*                                    PRE-COMPILE CONFIGURATION
*================================================================================================*/

/*==================================================================================================
*                                    General Configuration
*================================================================================================*/
#define SOMEIPTP_DEV_ERROR_DETECT    STD_ON
#define SOMEIPTP_VERSION_INFO_API    STD_ON

/*==================================================================================================
*                                    Hardware Object Handles
*================================================================================================*/
#define SOMEIPTP_RX_BUFFER_SIZE    (65536U)
#define SOMEIPTP_TX_BUFFER_SIZE    (65536U)
#define SOMEIPTP_TX_TIMEOUT_MS    (1000U)
#define SOMEIPTP_RX_TIMEOUT_MS    (1000U)
#define SOMEIPTP_PDU_ID_CHANNEL_0_TX    (0U)
#define SOMEIPTP_PDU_ID_CHANNEL_0_RX    (1U)
#define SOMEIPTP_PDU_ID_CHANNEL_1_TX    (2U)
#define SOMEIPTP_PDU_ID_CHANNEL_1_RX    (3U)

/*==================================================================================================
*                                    Timing Configuration
*================================================================================================*/
#define SOMEIPTP_RETRANSMIT_TIMEOUT_MS    (500U)
#define SOMEIPTP_MAIN_FUNCTION_PERIOD_MS    (10U)

/*==================================================================================================
*                                    Other Configuration
*================================================================================================*/
#define SOMEIPTP_NUMBER_OF_CHANNELS    (4U)
#define SOMEIPTP_MAX_PDU_LENGTH    (65536U)
#define SOMEIPTP_MAX_SEGMENT_SIZE    (1392U)
#define SOMEIPTP_MAX_RETRIES    (3U)
#define SOMEIPTP_CHANNEL_ID_0    (0U)
#define SOMEIPTP_CHANNEL_ID_1    (1U)
#define SOMEIPTP_CHANNEL_ID_2    (2U)
#define SOMEIPTP_CHANNEL_ID_3    (3U)

#endif /* SOMEIPTP_CFG_H */

/*==================[end of file]===========================================*/
