/**
 * @file IoHwAb_Cfg.h
 * @brief IoHwAb Configuration configuration header
 * @version 1.0.0
 * @date 2026-08-10
 * @note AUTO-GENERATED by yuleASR Configurator
 */

#ifndef IOHWAB_CFG_H
#define IOHWAB_CFG_H

/*==================================================================================================
*                                    PRE-COMPILE CONFIGURATION
*================================================================================================*/

/*==================================================================================================
*                                    General Configuration
*================================================================================================*/
#define IOHWAB_DEV_ERROR_DETECT    STD_ON
#define IOHWAB_VERSION_INFO_API    STD_ON
#define IOHWAB_NUM_SPI_DEVICES    (4U)
#define IOHWAB_SPI_DEVICE_0    (0U)
#define IOHWAB_SPI_DEVICE_1    (1U)
#define IOHWAB_SPI_DEVICE_2    (2U)
#define IOHWAB_SPI_DEVICE_3    (3U)

/*==================================================================================================
*                                    Module Configuration Counts
*================================================================================================*/
#define IOHWAB_NUM_ANALOG_CHANNELS    (16U)
#define IOHWAB_NUM_DIGITAL_CHANNELS    (32U)
#define IOHWAB_NUM_PWM_CHANNELS    (8U)

/*==================================================================================================
*                                    Timing Configuration
*================================================================================================*/
#define IOHWAB_MAIN_FUNCTION_PERIOD_MS    (10U)

/*==================================================================================================
*                                    Other Configuration
*================================================================================================*/
#define IOHWAB_ANALOG_CHANNEL_0    (0U)
#define IOHWAB_ANALOG_CHANNEL_1    (1U)
#define IOHWAB_ANALOG_CHANNEL_2    (2U)
#define IOHWAB_ANALOG_CHANNEL_3    (3U)
#define IOHWAB_ANALOG_CHANNEL_4    (4U)
#define IOHWAB_ANALOG_CHANNEL_5    (5U)
#define IOHWAB_ANALOG_CHANNEL_6    (6U)
#define IOHWAB_ANALOG_CHANNEL_7    (7U)
#define IOHWAB_ANALOG_CHANNEL_8    (8U)
#define IOHWAB_ANALOG_CHANNEL_9    (9U)
#define IOHWAB_ANALOG_CHANNEL_10    (10U)
#define IOHWAB_ANALOG_CHANNEL_11    (11U)
#define IOHWAB_ANALOG_CHANNEL_12    (12U)
#define IOHWAB_ANALOG_CHANNEL_13    (13U)
#define IOHWAB_ANALOG_CHANNEL_14    (14U)
#define IOHWAB_ANALOG_CHANNEL_15    (15U)
#define IOHWAB_DIGITAL_CHANNEL_0    (0U)
#define IOHWAB_DIGITAL_CHANNEL_1    (1U)
#define IOHWAB_DIGITAL_CHANNEL_2    (2U)
#define IOHWAB_DIGITAL_CHANNEL_3    (3U)
#define IOHWAB_DIGITAL_CHANNEL_4    (4U)
#define IOHWAB_DIGITAL_CHANNEL_5    (5U)
#define IOHWAB_DIGITAL_CHANNEL_6    (6U)
#define IOHWAB_DIGITAL_CHANNEL_7    (7U)
#define IOHWAB_DIGITAL_CHANNEL_8    (8U)
#define IOHWAB_DIGITAL_CHANNEL_9    (9U)
#define IOHWAB_DIGITAL_CHANNEL_10    (10U)
#define IOHWAB_DIGITAL_CHANNEL_11    (11U)
#define IOHWAB_DIGITAL_CHANNEL_12    (12U)
#define IOHWAB_DIGITAL_CHANNEL_13    (13U)
#define IOHWAB_DIGITAL_CHANNEL_14    (14U)
#define IOHWAB_DIGITAL_CHANNEL_15    (15U)
#define IOHWAB_PWM_CHANNEL_0    (0U)
#define IOHWAB_PWM_CHANNEL_1    (1U)
#define IOHWAB_PWM_CHANNEL_2    (2U)
#define IOHWAB_PWM_CHANNEL_3    (3U)
#define IOHWAB_PWM_CHANNEL_4    (4U)
#define IOHWAB_PWM_CHANNEL_5    (5U)
#define IOHWAB_PWM_CHANNEL_6    (6U)
#define IOHWAB_PWM_CHANNEL_7    (7U)
#define IOHWAB_ADC_RESOLUTION    (4095U)
#define IOHWAB_PWM_DUTY_SCALE    (10000U)

#endif /* IOHWAB_CFG_H */

/*==================[end of file]===========================================*/
