/**
 * @file Xcp_Cfg.h
 * @brief Xcp_Ecual Configuration configuration header
 * @version 1.0.0
 * @date 2026-08-10
 * @note AUTO-GENERATED by yuleASR Configurator
 */

#ifndef XCP_CFG_H
#define XCP_CFG_H

#include "Std_Types.h"   /* 非宏段依赖 Std_Types 基础类型 (uint32/uint8/uint16/boolean 等)，生成宏段不含此 include */

#include "Std_Types.h"

/*==================================================================================================
*                                    PRE-COMPILE CONFIGURATION
*================================================================================================*/

/*==================================================================================================
*                                    General Configuration
*================================================================================================*/
#define XCP_DEV_ERROR_DETECT    STD_ON

/*==================================================================================================
*                                    Timing Configuration
*================================================================================================*/
#define XCP_SESSION_TIMEOUT    (30000U)
#define XCP_RESPONSE_TIMEOUT    (1000U)

/*==================================================================================================
*                                    Other Configuration
*================================================================================================*/
#define XCP_PROTOCOL_LAYER_VERSION_MAJOR    (1U)
#define XCP_PROTOCOL_LAYER_VERSION_MINOR    (0U)
#define XCP_ON_CAN_ENABLED    STD_ON
#define XCP_ON_ETH_ENABLED    STD_OFF
#define XCP_ON_USB_ENABLED    STD_OFF
#define XCP_ON_FLEXRAY_ENABLED    STD_OFF
#define XCP_CALIBRATION_ENABLED    STD_ON
#define XCP_PAGE_SWITCHING_ENABLED    STD_ON
#define XCP_DAQ_ENABLED    STD_ON
#define XCP_STIM_ENABLED    STD_OFF
#define XCP_CHECKSUM_ENABLED    STD_ON
#define XCP_BLOCK_MODE_ENABLED    STD_ON
#define XCP_INTERLEAVED_MODE_ENABLED    STD_OFF
#define XCP_MASTER_BLOCK_MODE_ENABLED    STD_OFF
#define XCP_RESOURCE_CAL_PAG    (1U)
#define XCP_RESOURCE_DAQ    (4U)
#define XCP_RESOURCE_STIM    (8U)
#define XCP_RESOURCE_PGM    (16U)
#define XCP_CTO_SIZE    (8U)
#define XCP_DTO_SIZE    (8U)
#define XCP_MAX_DAQ_LISTS    (16U)
#define XCP_MAX_DAQ    (16U)
#define XCP_MAX_CTO    (8U)
#define XCP_MAX_DTO    (8U)
#define XCP_MAX_SEED_SIZE    (8U)
#define XCP_MAX_KEY_SIZE    (8U)
#define XCP_MAX_STIM    (4U)
#define XCP_MAX_ODT    (8U)
#define XCP_MAX_ODT_ENTRIES    (7U)
#define XCP_MAX_EVENT_CHANNELS    (8U)
#define XCP_MAX_SEGMENTS    (4U)
#define XCP_MAX_PAGES    (2U)
#define XCP_PAGE_SIZE    (4096U)
#define XCP_MAX_BS    (255U)
#define XCP_MIN_ST    (0U)
#define XCP_MAX_UPLOAD_SIZE    (255U)
#define XCP_MAX_DOWNLOAD_SIZE    (255U)
#define XCP_ADDR_EXT_RAM    (0U)
#define XCP_ADDR_EXT_FLASH    (1U)
#define XCP_ADDR_EXT_EEPROM    (2U)
#define XCP_ADDR_EXT_EXT_MEM    (255U)
#define XCP_DAQ_MIN_PRESCALER    (1U)
#define XCP_DAQ_MAX_PRESCALER    (255U)
#define XCP_TIMESTAMP_ENABLED    STD_ON
#define XCP_TIMESTAMP_SIZE    (2U)
#define XCP_TIMESTAMP_UNIT    (1U)
#define XCP_TIMESTAMP_TICKS_PER_UNIT    (1U)
#define XCP_CHECKSUM_XOR8    (1U)
#define XCP_CHECKSUM_CRC16    (2U)
#define XCP_CHECKSUM_CRC32    (3U)
#define XCP_CHECKSUM_CRC16_CCITT    (4U)
#define XCP_CHECKSUM_TYPE    (2U)
#define XCP_SLAVE_NAME    "YuleTech_XCP"
#define XCP_SLAVE_NAME_LEN    (12U)
#define XCP_SLAVE_VERSION_MAJOR    (1U)
#define XCP_SLAVE_VERSION_MINOR    (0U)
#define XCP_RESOURCE_DEFAULT_LOCK    (0U)
#define XCP_SEED_KEY_ENABLED    STD_OFF
#define XCP_SEED_LENGTH    (4U)
#define XCP_KEY_LENGTH    (4U)
#define XCP_USER_COPY_CAL_PAGE_CALLBACK    STD_OFF
#define XCP_USER_CHECKSUM_CALLBACK    STD_OFF
#define XCP_USER_TIMESTAMP_CALLBACK    STD_ON
#define XCP_ECU_CONFIGURATION_ID    (1U)
#define XCP_E_PARAM_POINTER    (1U)
#define XCP_E_PARAM_LENGTH    (2U)
#define XCP_E_PARAM_ADDRESS    (3U)
#define XCP_E_UNINIT    (4U)
#define XCP_E_ALREADY_INITIALIZED    (5U)
#define XCP_E_INVALID_STATE    (6U)
#define XCP_E_INVALID_DAQ_LIST    (7U)
#define XCP_E_INVALID_ODT    (8U)
#define XCP_E_INVALID_ODT_ENTRY    (9U)


/*==================================================================================================
*  NON-MACRO SEGMENT (preserved from handwritten header, merged by codegen splice)
*  typedef(1) + struct(4) + extern config tables(4) — 依赖宏段计数宏, 故置于宏段之后
*================================================================================================*/
typedef enum {
    XCP_CONFIG_VARIANT_PRE_COMPILE = 0,
    XCP_CONFIG_VARIANT_LINK_TIME,
    XCP_CONFIG_VARIANT_POST_BUILD
} Xcp_ConfigVariantType;

/*============================================================================
 *                          CONFIGURATION STRUCTURES
 *===========================================================================*/

/* Event channel configuration */
typedef struct {
    uint8  eventChannelNumber;
    uint8  eventChannelName[32];
    uint8  eventChannelCycleTime;  /* in ms */
    uint8  eventChannelPriority;
    uint16 eventChannelMaxDaqList;
} Xcp_EventChannelConfigType;

/* Segment configuration */
typedef struct {
    uint8  segmentNumber;
    uint32 segmentStart;
    uint32 segmentSize;
    uint8  numberOfPages;
    uint8  addressExtension;
    uint8  compressionMethod;
    uint8  encryptionMethod;
} Xcp_SegmentConfigType;

/* DAQ list configuration */
typedef struct {
    uint8  daqListNumber;
    uint16 maxOdt;
    uint16 maxOdtEntries;
    boolean fixedEventChannel;
    uint8  eventChannelNumber;
} Xcp_DaqListConfigType;

/* General configuration */
typedef struct {
    uint8  maxCto;
    uint8  maxDto;
    uint8  protocolLayerVersion;
    uint8  transportLayerVersion;
    uint8  byteOrder;           /* 0 = Intel, 1 = Motorola */
    uint8  addressGranularity;  /* 1, 2, or 4 bytes */
    uint8  slaveBlockMode;
} Xcp_GeneralConfigType;

/*============================================================================
 *                          CONFIGURATION EXTERNS
 *===========================================================================*/
extern const Xcp_GeneralConfigType Xcp_GeneralConfig;
extern const Xcp_SegmentConfigType Xcp_SegmentConfig[XCP_MAX_SEGMENTS];
extern const Xcp_EventChannelConfigType Xcp_EventChannelConfig[XCP_MAX_EVENT_CHANNELS];
extern const Xcp_DaqListConfigType Xcp_DaqListConfig[XCP_MAX_DAQ_LISTS];
#endif /* XCP_CFG_H */

/*==================[end of file]===========================================*/
