/**
 * @file Port_Cfg.h
 * @brief Port Configuration configuration header
 * @version 1.0.0
 * @date 2026-08-10
 * @note AUTO-GENERATED by yuleASR Configurator
 */

#ifndef PORT_CFG_H
#define PORT_CFG_H

/*==================================================================================================
*                                    PRE-COMPILE CONFIGURATION
*================================================================================================*/

/*==================================================================================================
*                                    General Configuration
*================================================================================================*/
#define PORT_DEV_ERROR_DETECT    STD_ON
#define PORT_VERSION_INFO_API    STD_ON

/*==================================================================================================
*                                    Module Configuration Counts
*================================================================================================*/
#define PORT_NUM_PORTS    (8U)
#define PORT_NUM_PINS_PER_PORT    (32U)
#define PORT_TOTAL_NUM_PINS    (256U)

/*==================================================================================================
*                                    Other Configuration
*================================================================================================*/
#define PORT_SET_PIN_DIRECTION_API    STD_ON
#define PORT_SET_PIN_MODE_API    STD_ON
#define PORT_DE_INIT_API    STD_ON
#define PORT_A    (0U)
#define PORT_B    (1U)
#define PORT_C    (2U)
#define PORT_D    (3U)
#define PORT_E    (4U)
#define PORT_F    (5U)
#define PORT_G    (6U)
#define PORT_H    (7U)
#define PORT_PIN_MODE_GPIO    (0U)
#define PORT_PIN_MODE_CAN    (1U)
#define PORT_PIN_MODE_SPI    (2U)
#define PORT_PIN_MODE_UART    (3U)
#define PORT_PIN_MODE_I2C    (4U)
#define PORT_PIN_MODE_PWM    (5U)
#define PORT_PIN_MODE_ADC    (6U)
#define PORT_PIN_MODE_ETH    (7U)
#define PORT_PIN_MODE_USB    (8U)
#define PORT_PIN_MODE_FLEXIO    (9U)
#define PORT_PIN_MODE_DISABLED    (15U)
#define PORT_A_PIN_0    (0U)
#define PORT_A_PIN_1    (1U)
#define PORT_A_PIN_2    (2U)
#define PORT_A_PIN_3    (3U)
#define PORT_A_PIN_4    (4U)
#define PORT_A_PIN_5    (5U)
#define PORT_A_PIN_6    (6U)
#define PORT_A_PIN_7    (7U)
#define PORT_B_PIN_0    (256U)
#define PORT_B_PIN_1    (257U)
#define PORT_B_PIN_2    (258U)
#define PORT_B_PIN_3    (259U)
#define PORT_B_PIN_4    (260U)
#define PORT_B_PIN_5    (261U)
#define PORT_B_PIN_6    (262U)
#define PORT_B_PIN_7    (263U)
#define PORT_C_PIN_0    (512U)
#define PORT_C_PIN_1    (513U)
#define PORT_C_PIN_2    (514U)
#define PORT_C_PIN_3    (515U)
#define PORT_C_PIN_4    (516U)
#define PORT_C_PIN_5    (517U)
#define PORT_C_PIN_6    (518U)
#define PORT_C_PIN_7    (519U)
#define PORT_D_PIN_0    (768U)
#define PORT_D_PIN_1    (769U)
#define PORT_D_PIN_2    (770U)
#define PORT_D_PIN_3    (771U)
#define PORT_D_PIN_4    (772U)
#define PORT_D_PIN_5    (773U)
#define PORT_D_PIN_6    (774U)
#define PORT_D_PIN_7    (775U)
/*==================================================================================================
*                                    FUNCTION-LIKE MACROS (VERBATIM)
*================================================================================================*/
#define PORT_CONFIGSET_NAME             (Port_ConfigSet)


#endif /* PORT_CFG_H */

/*==================[end of file]===========================================*/
