/**
 * @file Mem_Cfg.h
 * @brief Mem Configuration configuration header
 * @version 1.0.0
 * @date 2026-08-10
 * @note AUTO-GENERATED by yuleASR Configurator
 */

#ifndef MEM_CFG_H
#define MEM_CFG_H

/*==================================================================================================
*                                    PRE-COMPILE CONFIGURATION
*================================================================================================*/

/*==================================================================================================
*                                    General Configuration
*================================================================================================*/
#define MEM_DEV_ERROR_DETECT    STD_ON
#define MEM_VERSION_INFO_API    STD_ON

/*==================================================================================================
*                                    Module Configuration Counts
*================================================================================================*/
#define MEM_NUM_POOLS    (3U)

/*==================================================================================================
*                                    Timing Configuration
*================================================================================================*/
#define MEM_MAIN_FUNCTION_PERIOD_MS    (10U)

/*==================================================================================================
*                                    Other Configuration
*================================================================================================*/
#define MEM_CFG_AR_RELEASE_MAJOR_VERSION    (4U)
#define MEM_CFG_AR_RELEASE_MINOR_VERSION    (7U)
#define MEM_CFG_AR_RELEASE_REVISION_VERSION    (0U)
#define MEM_CFG_SW_MAJOR_VERSION    (1U)
#define MEM_CFG_SW_MINOR_VERSION    (0U)
#define MEM_CFG_SW_PATCH_VERSION    (0U)
#define MEM_DEFAULT_POOL_INDEX    (0U)
#define MEM_FAST_POOL_SIZE    (4096U)
#define MEM_STANDARD_POOL_SIZE    (16384U)
#define MEM_LARGE_POOL_SIZE    (65536U)
#define MEM_MIN_BLOCK_SIZE    (16U)
#define MEM_FAST_POOL_MAX_BLOCK    (256U)
#define MEM_STANDARD_POOL_MAX_BLOCK    (2048U)
#define MEM_LARGE_POOL_MAX_BLOCK    (65536U)
#define MEM_DEFAULT_ALIGNMENT    (4U)
#define MEM_ENABLE_CHECKSUM    STD_ON
#define MEM_ENABLE_MONITORING    STD_ON
#define MEM_DEFRAG_THRESHOLD    (30U)
#define MEM_MAX_ALLOCATIONS    (256U)
#define MEM_MAGIC_NUMBER_CFG    (1296387361U)

#endif /* MEM_CFG_H */

/*==================[end of file]===========================================*/
