#!/usr/bin/env python3
"""
Network Simulator for Multi-ECU Testing
Integrates with Mininet for network topology simulation
Includes fault injection capabilities using tc/netem
"""

import subprocess
import time
import json
import sys
from dataclasses import dataclass
from typing import List, Dict, Optional

@dataclass
class NetworkLink:
    """Network link configuration"""
    src: str
    dst: str
    bandwidth: int  # Mbps
    delay: str      # e.g., "10ms"
    loss: float     # percentage
    jitter: str     # e.g., "5ms"

@dataclass
class ECUNode:
    """ECU node configuration"""
    name: str
    ip: str
    mac: str
    group: str

class NetworkTopology:
    """Defines the automotive network topology"""
    
    def __init__(self):
        self.nodes: List[ECUNode] = []
        self.links: List[NetworkLink] = []
        self.switch = None
        
    def add_ecu(self, name: str, ip: str, mac: str, group: str):
        """Add an ECU node to topology"""
        self.nodes.append(ECUNode(name, ip, mac, group))
        
    def add_link(self, src: str, dst: str, bandwidth: int = 1000, 
                 delay: str = "1ms", loss: float = 0.0, jitter: str = "0ms"):
        """Add a network link"""
        self.links.append(NetworkLink(src, dst, bandwidth, delay, loss, jitter))
        
    def to_mininet(self) -> str:
        """Generate Mininet topology Python script"""
        script = '''#!/usr/bin/env python3
"""
Mininet topology for Automotive Ethernet testing
Generated by network simulator
"""

from mininet.topo import Topo
from mininet.net import Mininet
from mininet.node import OVSSwitch, Controller
from mininet.link import TCLink
from mininet.cli import CLI
from mininet.log import setLogLevel, info

class AutomotiveTopo(Topo):
    def build(self):
        # Add switch
        s1 = self.addSwitch('s1')
        
'''
        
        # Add hosts
        for node in self.nodes:
            script += f'''        # {node.name}
        {node.name} = self.addHost('{node.name}', ip='{node.ip}', mac='{node.mac}')
        self.addLink({node.name}, s1, bw=1000, delay='1ms')
        
'''
        
        script += '''
def run():
    """Create and run the network"""
    topo = AutomotiveTopo()
    net = Mininet(topo=topo, switch=OVSSwitch, link=TCLink, controller=Controller)
    
    net.start()
    
    info("Network started\\n")
    info("Nodes: ")
    for node in net.hosts:
        info(f"{node.name} ")
    info("\\n")
    
    # Run CLI
    CLI(net)
    
    net.stop()

if __name__ == '__main__':
    setLogLevel('info')
    run()
'''
        return script


class FaultInjector:
    """Network fault injection using tc/netem"""
    
    def __init__(self, interface: str):
        self.interface = interface
        
    def reset(self):
        """Reset tc rules"""
        subprocess.run(
            ["tc", "qdisc", "del", "dev", self.interface, "root"],
            capture_output=True
        )
        
    def add_delay(self, delay: str, jitter: str = "0ms"):
        """Add network delay"""
        self.reset()
        subprocess.run([
            "tc", "qdisc", "add", "dev", self.interface, "root",
            "netem", "delay", delay, jitter
        ], check=True)
        
    def add_loss(self, loss_percent: float):
        """Add packet loss"""
        self.reset()
        subprocess.run([
            "tc", "qdisc", "add", "dev", self.interface, "root",
            "netem", "loss", f"{loss_percent}%"
        ], check=True)
        
    def add_corruption(self, corruption_percent: float):
        """Add packet corruption"""
        self.reset()
        subprocess.run([
            "tc", "qdisc", "add", "dev", self.interface, "root",
            "netem", "corrupt", f"{corruption_percent}%"
        ], check=True)
        
    def add_duplication(self, duplicate_percent: float):
        """Add packet duplication"""
        self.reset()
        subprocess.run([
            "tc", "qdisc", "add", "dev", self.interface, "root",
            "netem", "duplicate", f"{duplicate_percent}%"
        ], check=True)
        
    def add_reordering(self, reorder_percent: float):
        """Add packet reordering"""
        self.reset()
        subprocess.run([
            "tc", "qdisc", "add", "dev", self.interface, "root",
            "netem", "reorder", f"{reorder_percent}%"
        ], check=True)
        
    def add_bandwidth_limit(self, rate: str, burst: str = "32kbit", latency: str = "400ms"):
        """Add bandwidth limit"""
        self.reset()
        subprocess.run([
            "tc", "qdisc", "add", "dev", self.interface, "root",
            "tbf", "rate", rate, "burst", burst, "latency", latency
        ], check=True)


class NetworkTestScenarios:
    """Predefined network test scenarios"""
    
    SCENARIOS = {
        "normal": {
            "description": "Normal operation - no faults",
            "delay": "1ms",
            "loss": 0.0,
            "bandwidth": "1000mbit"
        },
        "congestion": {
            "description": "Network congestion - limited bandwidth",
            "delay": "10ms",
            "loss": 0.5,
            "bandwidth": "100mbit"
        },
        "packet_loss": {
            "description": "High packet loss",
            "delay": "5ms",
            "loss": 5.0,
            "bandwidth": "1000mbit"
        },
        "high_latency": {
            "description": "High latency network",
            "delay": "100ms",
            "jitter": "20ms",
            "loss": 0.0,
            "bandwidth": "1000mbit"
        },
        "packet_corruption": {
            "description": "Packet corruption",
            "delay": "2ms",
            "corruption": 1.0,
            "bandwidth": "1000mbit"
        },
        "reordering": {
            "description": "Packet reordering",
            "delay": "10ms",
            "reordering": 5.0,
            "bandwidth": "1000mbit"
        },
        "automotive_worst_case": {
            "description": "Automotive worst-case scenario",
            "delay": "50ms",
            "jitter": "10ms",
            "loss": 2.0,
            "corruption": 0.1,
            "bandwidth": "100mbit"
        }
    }
    
    @classmethod
    def get_scenario(cls, name: str) -> Dict:
        """Get scenario configuration"""
        return cls.SCENARIOS.get(name, cls.SCENARIOS["normal"])
    
    @classmethod
    def list_scenarios(cls):
        """List all available scenarios"""
        print("\nAvailable Network Test Scenarios:")
        print("-" * 50)
        for name, config in cls.SCENARIOS.items():
            print(f"  {name}: {config['description']}")
        print()


class NetworkMonitor:
    """Monitor network conditions"""
    
    def __init__(self, interface: str):
        self.interface = interface
        
    def get_stats(self) -> Dict:
        """Get interface statistics"""
        try:
            result = subprocess.run(
                ["tc", "-s", "qdisc", "show", "dev", self.interface],
                capture_output=True, text=True
            )
            return {
                "interface": self.interface,
                "tc_output": result.stdout,
                "timestamp": time.time()
            }
        except Exception as e:
            return {"error": str(e)}
            
    def ping_test(self, target: str, count: int = 10) -> Dict:
        """Run ping test"""
        try:
            result = subprocess.run(
                ["ping", "-c", str(count), target],
                capture_output=True, text=True
            )
            
            # Parse ping output
            lines = result.stdout.split('\n')
            stats = {"target": target, "raw_output": result.stdout}
            
            for line in lines:
                if "packets transmitted" in line:
                    parts = line.split(',')
                    for part in parts:
                        if "received" in part:
                            stats["received"] = int(part.split()[0])
                        if "packet loss" in part:
                            stats["loss_percent"] = float(part.split('%')[0])
                if "avg" in line and "ms" in line:
                    # Extract average latency
                    avg_part = line.split('/')
                    if len(avg_part) >= 5:
                        stats["avg_latency_ms"] = float(avg_part[4])
                        
            return stats
            
        except Exception as e:
            return {"error": str(e)}


def main():
    """Main entry point"""
    import argparse
    
    parser = argparse.ArgumentParser(description="Network Simulator for Multi-ECU Testing")
    parser.add_argument("--scenario", choices=list(NetworkTestScenarios.SCENARIOS.keys()),
                       default="normal", help="Network test scenario")
    parser.add_argument("--interface", default="eth0", help="Network interface")
    parser.add_argument("--list-scenarios", action="store_true", help="List available scenarios")
    parser.add_argument("--ping-test", help="Run ping test to target")
    parser.add_argument("--monitor", action="store_true", help="Monitor network stats")
    
    args = parser.parse_args()
    
    if args.list_scenarios:
        NetworkTestScenarios.list_scenarios()
        return
        
    # Apply scenario
    scenario = NetworkTestScenarios.get_scenario(args.scenario)
    print(f"\nApplying scenario: {args.scenario}")
    print(f"Description: {scenario['description']}")
    
    injector = FaultInjector(args.interface)
    injector.reset()
    
    if "delay" in scenario:
        jitter = scenario.get("jitter", "0ms")
        injector.add_delay(scenario["delay"], jitter)
        
    if "loss" in scenario and scenario["loss"] > 0:
        injector.add_loss(scenario["loss"])
        
    if "corruption" in scenario and scenario["corruption"] > 0:
        injector.add_corruption(scenario["corruption"])
        
    if "reordering" in scenario and scenario["reordering"] > 0:
        injector.add_reordering(scenario["reordering"])
        
    print(f"Scenario applied to interface: {args.interface}")
    
    # Run ping test if requested
    if args.ping_test:
        monitor = NetworkMonitor(args.interface)
        print(f"\nRunning ping test to {args.ping_test}...")
        stats = monitor.ping_test(args.ping_test)
        print(json.dumps(stats, indent=2))
        
    # Monitor if requested
    if args.monitor:
        monitor = NetworkMonitor(args.interface)
        print("\nMonitoring network stats (Ctrl+C to stop)...")
        try:
            while True:
                stats = monitor.get_stats()
                print(f"[{time.strftime('%H:%M:%S')}] {stats}")
                time.sleep(5)
        except KeyboardInterrupt:
            print("\nMonitoring stopped")


if __name__ == '__main__':
    main()
