/**
 * @file Eep_Cfg.h
 * @brief Eep Configuration configuration header
 * @version 1.0.0
 * @date 2026-08-10
 * @note AUTO-GENERATED by yuleASR Configurator
 */

#ifndef EEP_CFG_H
#define EEP_CFG_H

#include "Std_Types.h"

/*==================================================================================================
*                                    PRE-COMPILE CONFIGURATION
*================================================================================================*/

/*==================================================================================================
*                                    General Configuration
*================================================================================================*/
#define EEP_DEV_ERROR_DETECT    STD_ON
#define EEP_VERSION_INFO_API    STD_ON

/*==================================================================================================
*                                    Processing Modes
*================================================================================================*/
#define EEP_POLLING_MODE    STD_ON

/*==================================================================================================
*                                    Other Configuration
*================================================================================================*/
#define EEP_CANCEL_API    STD_ON
#define EEP_BASE_ADDRESS    (134742016U)
#define EEP_SIZE    (65536U)
#define EEP_PAGE_SIZE    (8U)
#define EEP_WRITE_CYCLE_TIME    (10U)
#define EEP_ERASE_CYCLE_TIME    (20U)
#define EEP_JOB_CALL_CYCLE    (10U)

#endif /* EEP_CFG_H */

/*==================[end of file]===========================================*/
