/**
 * @file Adc_Cfg.h
 * @brief Adc Configuration configuration header
 * @version 1.0.0
 * @date 2026-08-10
 * @note AUTO-GENERATED by yuleASR Configurator
 */

#ifndef ADC_CFG_H
#define ADC_CFG_H

/*==================================================================================================
*                                    PRE-COMPILE CONFIGURATION
*================================================================================================*/

/*==================================================================================================
*                                    General Configuration
*================================================================================================*/
#define ADC_DEV_ERROR_DETECT    STD_ON
#define ADC_VERSION_INFO_API    STD_ON

/*==================================================================================================
*                                    Module Configuration Counts
*================================================================================================*/
#define ADC_NUM_HW_UNITS    (2U)
#define ADC_NUM_GROUPS    (8U)
#define ADC_NUM_CHANNELS    (16U)
#define ADC_STREAM_NUM_SAMPLES    (1U)

/*==================================================================================================
*                                    Timing Configuration
*================================================================================================*/
#define ADC_MAIN_FUNCTION_PERIOD_MS    (10U)

/*==================================================================================================
*                                    Other Configuration
*================================================================================================*/
#define ADC_DE_INIT_API    STD_ON
#define ADC_ENABLE_START_STOP_GROUP_API    STD_ON
#define ADC_HW_TRIGGER_API    STD_ON
#define ADC_READ_GROUP_API    STD_ON
#define ADC_GET_STREAM_LAST_POINTER_API    STD_ON
#define ADC_ENABLE_QUEUING    STD_ON
#define ADC_GRP_NOTIF_CAPABILITY    STD_ON
#define ADC_POWER_STATE_SUPPORTED    STD_OFF
#define ADC_HWUNIT_0    (0U)
#define ADC_HWUNIT_1    (1U)
#define ADC_GROUP_0    (0U)
#define ADC_GROUP_1    (1U)
#define ADC_GROUP_2    (2U)
#define ADC_GROUP_3    (3U)
#define ADC_GROUP_4    (4U)
#define ADC_GROUP_5    (5U)
#define ADC_GROUP_6    (6U)
#define ADC_GROUP_7    (7U)
#define ADC_CHANNEL_0    (0U)
#define ADC_CHANNEL_1    (1U)
#define ADC_CHANNEL_2    (2U)
#define ADC_CHANNEL_3    (3U)
#define ADC_CHANNEL_4    (4U)
#define ADC_CHANNEL_5    (5U)
#define ADC_CHANNEL_6    (6U)
#define ADC_CHANNEL_7    (7U)
#define ADC_CHANNEL_8    (8U)
#define ADC_CHANNEL_9    (9U)
#define ADC_CHANNEL_10    (10U)
#define ADC_CHANNEL_11    (11U)
#define ADC_CHANNEL_12    (12U)
#define ADC_CHANNEL_13    (13U)
#define ADC_CHANNEL_14    (14U)
#define ADC_CHANNEL_15    (15U)
#define ADC_DEFAULT_RESOLUTION    ADC_RESOLUTION_12BIT
#define ADC_DEFAULT_SAMPLING_TIME    ADC_SAMPLING_TIME_15CYCLES
#define ADC_CLOCK_FREQUENCY_HZ    (24000000U)

#endif /* ADC_CFG_H */

/*==================[end of file]===========================================*/
