/**
 * @file Swc_Cfg.h
 * @brief Swc Configuration configuration header
 * @version 1.0.0
 * @date 2026-08-10
 * @note AUTO-GENERATED by yuleASR Configurator
 */

#ifndef SWC_CFG_H
#define SWC_CFG_H

#include "Std_Types.h"   /* 非宏段依赖 Std_Types 基础类型 (uint32/uint8/uint16/boolean 等)，生成宏段不含此 include */

#include "Std_Types.h"

/*==================================================================================================
*                                    PRE-COMPILE CONFIGURATION
*================================================================================================*/

/*==================================================================================================
*                                    General Configuration
*================================================================================================*/
#define SWC_DEV_ERROR_DETECT    STD_ON
#define SWC_VERSION_INFO_API    STD_ON

/*==================================================================================================
*                                    Module Configuration Counts
*================================================================================================*/
#define SWC_INSTANCE_COUNT_ENABLED    STD_ON

/*==================================================================================================
*                                    Timing Configuration
*================================================================================================*/
#define SWC_DEFAULT_SCHEDULING_PERIOD_MS    (10U)

/*==================================================================================================
*                                    Other Configuration
*================================================================================================*/
#define SWC_CFG_VENDOR_ID    (1U)
#define SWC_CFG_MODULE_ID    (80U)
#define SWC_CFG_AR_MAJOR_VERSION    (4U)
#define SWC_CFG_AR_MINOR_VERSION    (4U)
#define SWC_CFG_AR_PATCH_VERSION    (0U)
#define SWC_CFG_SW_MAJOR_VERSION    (1U)
#define SWC_CFG_SW_MINOR_VERSION    (0U)
#define SWC_CFG_SW_PATCH_VERSION    (0U)
#define SWC_MAX_COMPONENT_INSTANCES    (16U)
#define SWC_MAX_RUNNABLES_PER_COMPONENT    (8U)
#define SWC_MAX_PORTS_PER_COMPONENT    (16U)
#define SWC_MAX_RTE_EVENTS    (32U)
#define SWC_EVENT_QUEUE_SIZE    (64U)
#define SWC_MAX_NAME_LENGTH    (32U)
#define SWC_CYCLIC_SCHEDULING_ENABLED    STD_ON
#define SWC_RTE_CALLBACK_ENABLED    STD_ON
#define SWC_PORT_BUFFERING_ENABLED    STD_ON
#define SWC_PORT_BUFFER_SIZE    (256U)
#ifndef SWC_RTE_NOTIFICATION_CALLBACK
#define SWC_RTE_NOTIFICATION_CALLBACK    (NULL_PTR)
#endif
#ifndef SWC_ERROR_HOOK
#define SWC_ERROR_HOOK    (NULL_PTR)
#endif


/*==================================================================================================
*  NON-MACRO SEGMENT (preserved from handwritten header, merged by codegen splice)
*  typedef(0) + struct(5) + extern config tables(2) — 依赖宏段计数宏, 故置于宏段之后
*================================================================================================*/
struct Swc_ComponentConfigType;
struct Swc_RunnableConfigType;
struct Swc_PortConfigType;

/* Port configuration structure */
typedef struct Swc_PortConfigType
{
    uint16 portId;
    uint16 interfaceId;
    uint8 direction;              /* 0=Provided, 1=Required, 2=PR */
    uint16 dataElementSize;
    uint8 portType;               /* SenderReceiver, ClientServer, etc. */
    boolean isQueued;
    uint16 queueLength;
    const char portName[SWC_MAX_NAME_LENGTH];
} Swc_PortConfigType;

/* Runnable configuration structure */
typedef struct Swc_RunnableConfigType
{
    uint16 runnableId;
    void (*runnableFunc)(void);
    boolean canBeInvokedConcurrently;
    uint16 minStartIntervalMs;
    uint16 priority;
    const char runnableName[SWC_MAX_NAME_LENGTH];
} Swc_RunnableConfigType;

/* RTE event configuration structure */
typedef struct Swc_EventConfigType
{
    uint16 eventId;
    uint8 eventType;              /* INIT, CYCLIC, DATA_RECEIVED, etc. */
    uint16 periodMs;              /* For cyclic events */
    uint16 targetRunnableId;
    uint8 eventMask;
    boolean autoEnable;
} Swc_EventConfigType;

/* Component configuration structure */
typedef struct Swc_ComponentConfigType
{
    uint16 componentId;
    const char componentName[SWC_MAX_NAME_LENGTH];
    uint8 componentType;          /* Application, SensorActuator, ComplexDevice, Service */
    uint8 numPorts;
    const Swc_PortConfigType* portConfigs;
    uint8 numRunnables;
    const Swc_RunnableConfigType* runnableConfigs;
    uint8 numEvents;
    const Swc_EventConfigType* eventConfigs;
    uint16 instanceDataSize;
    void (*initFunc)(void);
    void (*shutdownFunc)(void);
} Swc_ComponentConfigType;

/* Global configuration structure */
typedef struct
{
    uint8 numComponents;
    const Swc_ComponentConfigType* componentConfigs;
    uint16 schedulingPeriodMs;
    boolean enableTracing;
    void (*traceCallback)(uint8 level, const char* msg);
} Swc_ConfigType;

/*==================================================================================================
*                                    CONFIGURATION VARIANTS
==================================================================================================*/

/* Pre-compile configuration pointer (defined in Swc_Lcfg.c) */
extern const Swc_ConfigType Swc_Config;

/* Post-build configuration variant (optional) */
#if (SWC_PB_CONFIG == STD_ON)
extern const Swc_ConfigType* Swc_ConfigPtr;
#endif
#endif /* SWC_CFG_H */

/*==================[end of file]===========================================*/
