/**
 * @file Cdd_Fvm_Cfg.h
 * @brief Cdd_Fvm Configuration configuration header
 * @version 1.0.0
 * @date 2026-08-10
 * @note AUTO-GENERATED by yuleASR Configurator
 */

#ifndef CDD_FVM_CFG_H
#define CDD_FVM_CFG_H

/*==================================================================================================
*                                    PRE-COMPILE CONFIGURATION
*================================================================================================*/

/*==================================================================================================
*                                    General Configuration
*================================================================================================*/
#define CDD_FVM_DEV_ERROR_DETECT    STD_ON
#define CDD_FVM_VERSION_INFO_API    STD_ON

/*==================================================================================================
*                                    Module Configuration Counts
*================================================================================================*/
#define CDD_FVM_NUM_CONFIGURED_BANKS    (2U)

/*==================================================================================================
*                                    Timing Configuration
*================================================================================================*/
#define CDD_FVM_PERIODIC_CHECK_ENABLED    STD_ON
#define CDD_FVM_MAIN_FUNCTION_PERIOD    (10U)

/*==================================================================================================
*                                    Other Configuration
*================================================================================================*/
#define CDD_FVM_BACKEND_RAM    (0U)
#define CDD_FVM_BACKEND_FLS    (1U)
#ifndef CDD_FVM_BACKEND
#define CDD_FVM_BACKEND    (0U)
#endif
#define CDD_FVM_MAX_BANKS    (4U)
#define CDD_FVM_BANK_0_START_ADDR    (4194304U)
#define CDD_FVM_BANK_0_SIZE    (262144U)
#define CDD_FVM_BANK_1_START_ADDR    (4456448U)
#define CDD_FVM_BANK_1_SIZE    (262144U)
#define CDD_FVM_BANK_2_START_ADDR    (4718592U)
#define CDD_FVM_BANK_2_SIZE    (262144U)
#define CDD_FVM_BANK_3_START_ADDR    (4980736U)
#define CDD_FVM_BANK_3_SIZE    (262144U)
#define CDD_FVM_ERASE_GRANULARITY    (4096U)
#define CDD_FVM_BANK_MAGIC    (2784084190U)
#define CDD_FVM_SIGNATURE_SIZE    (4U)
#define CDD_FVM_RAM_BASE_ADDR    (4194304U)
#define CDD_FVM_RAM_POOL_SIZE    (524288U)
#define CDD_FVM_E_PARAM_POINTER    (1U)
#define CDD_FVM_E_PARAM_BANK    (2U)
#define CDD_FVM_E_PARAM_RANGE    (3U)
#define CDD_FVM_E_UNINIT    (4U)
#define CDD_FVM_E_BUSY    (5U)
#define CDD_FVM_E_WRITE_PROTECTED    (6U)
#define CDD_FVM_E_CORRUPT    (7U)
#define CDD_FVM_E_NO_VALID_BANK    (8U)
#define CDD_FVM_E_COPY_VERIFY    (9U)
#define CDD_FVM_E_HW    (10U)

#endif /* CDD_FVM_CFG_H */

/*==================[end of file]===========================================*/
