/**
 * @file Pwm_Cfg.h
 * @brief Pwm Configuration configuration header
 * @version 1.0.0
 * @date 2026-08-10
 * @note AUTO-GENERATED by yuleASR Configurator
 */

#ifndef PWM_CFG_H
#define PWM_CFG_H

/*==================================================================================================
*                                    PRE-COMPILE CONFIGURATION
*================================================================================================*/

/*==================================================================================================
*                                    General Configuration
*================================================================================================*/
#define PWM_DEV_ERROR_DETECT    STD_ON
#define PWM_VERSION_INFO_API    STD_ON

/*==================================================================================================
*                                    Module Configuration Counts
*================================================================================================*/
#define PWM_NUM_CHANNELS    (8U)

/*==================================================================================================
*                                    Timing Configuration
*================================================================================================*/
#define PWM_SET_PERIOD_AND_DUTY_API    STD_ON
#define PWM_DEFAULT_PERIOD    (1000U)

/*==================================================================================================
*                                    Other Configuration
*================================================================================================*/
#define PWM_DE_INIT_API    STD_ON
#define PWM_SET_DUTY_CYCLE_API    STD_ON
#define PWM_SET_OUTPUT_TO_IDLE_API    STD_ON
#define PWM_GET_OUTPUT_STATE_API    STD_ON
#define PWM_NOTIFICATION_SUPPORTED    STD_ON
#define PWM_POWER_STATE_SUPPORTED    STD_OFF
#define PWM_CHANNEL_0    (0U)
#define PWM_CHANNEL_1    (1U)
#define PWM_CHANNEL_2    (2U)
#define PWM_CHANNEL_3    (3U)
#define PWM_CHANNEL_4    (4U)
#define PWM_CHANNEL_5    (5U)
#define PWM_CHANNEL_6    (6U)
#define PWM_CHANNEL_7    (7U)
#define PWM_DEFAULT_DUTY_CYCLE    (16384U)
#define PWM_DUTY_CYCLE_RESOLUTION    (32768U)
#define PWM_CLOCK_FREQUENCY_HZ    (24000000U)

#endif /* PWM_CFG_H */

/*==================[end of file]===========================================*/
