/**
 * @file MemMap.h
 * @brief Memory mapping header for compiler abstraction and memory section handling
 * @version 1.0.0
 * @date 2026-04-14
 * @author Shanghai Yule Electronics Technology Co., Ltd.
 * @copyright Copyright (c) 2026 Shanghai Yule Electronics Technology Co., Ltd.
 *
 * AutoSAR Standard: Memory Mapping
 * This file provides memory section pragmas for different compilers
 */

#ifndef MEMMAP_H
#define MEMMAP_H

/*==================================================================================================
*                                          INCLUDE FILES
==================================================================================================*/
#include "Compiler.h"

/*==================================================================================================
*                                    VERSION INFORMATION
==================================================================================================*/
#define MEMMAP_VENDOR_ID                (0x01U) /* YuleTech Vendor ID */
#define MEMMAP_MODULE_ID                (0x00U) /* Memory Mapping Module ID */
#define MEMMAP_AR_RELEASE_MAJOR_VERSION (0x04U)
#define MEMMAP_AR_RELEASE_MINOR_VERSION (0x04U)
#define MEMMAP_AR_RELEASE_REVISION_VERSION (0x00U)
#define MEMMAP_SW_MAJOR_VERSION         (0x01U)
#define MEMMAP_SW_MINOR_VERSION         (0x00U)
#define MEMMAP_SW_PATCH_VERSION         (0x00U)

/*==================================================================================================
*                                    MEMORY SECTION START/STOP MACROS
*                                    Compiler: GCC
==================================================================================================*/
#if defined(__GNUC__)

/* Code Sections */
#define MCU_START_SEC_CODE
#define MCU_STOP_SEC_CODE

#define PORT_START_SEC_CODE
#define PORT_STOP_SEC_CODE

#define DIO_START_SEC_CODE
#define DIO_STOP_SEC_CODE

#define CAN_START_SEC_CODE
#define CAN_STOP_SEC_CODE

#define SPI_START_SEC_CODE
#define SPI_STOP_SEC_CODE

#define GPT_START_SEC_CODE
#define GPT_STOP_SEC_CODE

#define PWM_START_SEC_CODE
#define PWM_STOP_SEC_CODE

#define ADC_START_SEC_CODE
#define ADC_STOP_SEC_CODE

#define WDG_START_SEC_CODE
#define WDG_STOP_SEC_CODE

#define COM_START_SEC_CODE
#define COM_STOP_SEC_CODE

#define PDUR_START_SEC_CODE
#define PDUR_STOP_SEC_CODE

/* Const Sections */
#define MCU_START_SEC_CONST_UNSPECIFIED
#define MCU_STOP_SEC_CONST_UNSPECIFIED

#define PORT_START_SEC_CONST_UNSPECIFIED
#define PORT_STOP_SEC_CONST_UNSPECIFIED

#define DIO_START_SEC_CONST_UNSPECIFIED
#define DIO_STOP_SEC_CONST_UNSPECIFIED

#define CAN_START_SEC_CONST_UNSPECIFIED
#define CAN_STOP_SEC_CONST_UNSPECIFIED

#define SPI_START_SEC_CONST_UNSPECIFIED
#define SPI_STOP_SEC_CONST_UNSPECIFIED

#define GPT_START_SEC_CONST_UNSPECIFIED
#define GPT_STOP_SEC_CONST_UNSPECIFIED

#define PWM_START_SEC_CONST_UNSPECIFIED
#define PWM_STOP_SEC_CONST_UNSPECIFIED

#define ADC_START_SEC_CONST_UNSPECIFIED
#define ADC_STOP_SEC_CONST_UNSPECIFIED

#define WDG_START_SEC_CONST_UNSPECIFIED
#define WDG_STOP_SEC_CONST_UNSPECIFIED

#define COM_START_SEC_CONST_UNSPECIFIED
#define COM_STOP_SEC_CONST_UNSPECIFIED

#define PDUR_START_SEC_CONST_UNSPECIFIED
#define PDUR_STOP_SEC_CONST_UNSPECIFIED

/* Config Data Sections */
#define MCU_START_SEC_CONFIG_DATA_UNSPECIFIED
#define MCU_STOP_SEC_CONFIG_DATA_UNSPECIFIED

#define PORT_START_SEC_CONFIG_DATA_UNSPECIFIED
#define PORT_STOP_SEC_CONFIG_DATA_UNSPECIFIED

#define DIO_START_SEC_CONFIG_DATA_UNSPECIFIED
#define DIO_STOP_SEC_CONFIG_DATA_UNSPECIFIED

#define CAN_START_SEC_CONFIG_DATA_UNSPECIFIED
#define CAN_STOP_SEC_CONFIG_DATA_UNSPECIFIED

#define SPI_START_SEC_CONFIG_DATA_UNSPECIFIED
#define SPI_STOP_SEC_CONFIG_DATA_UNSPECIFIED

#define GPT_START_SEC_CONFIG_DATA_UNSPECIFIED
#define GPT_STOP_SEC_CONFIG_DATA_UNSPECIFIED

#define PWM_START_SEC_CONFIG_DATA_UNSPECIFIED
#define PWM_STOP_SEC_CONFIG_DATA_UNSPECIFIED

#define ADC_START_SEC_CONFIG_DATA_UNSPECIFIED
#define ADC_STOP_SEC_CONFIG_DATA_UNSPECIFIED

#define WDG_START_SEC_CONFIG_DATA_UNSPECIFIED
#define WDG_STOP_SEC_CONFIG_DATA_UNSPECIFIED

#define COM_START_SEC_CONFIG_DATA_UNSPECIFIED
#define COM_STOP_SEC_CONFIG_DATA_UNSPECIFIED

#define PDUR_START_SEC_CONFIG_DATA_UNSPECIFIED
#define PDUR_STOP_SEC_CONFIG_DATA_UNSPECIFIED

/* VAR Sections */
#define MCU_START_SEC_VAR_CLEARED_UNSPECIFIED
#define MCU_STOP_SEC_VAR_CLEARED_UNSPECIFIED

#define PORT_START_SEC_VAR_CLEARED_UNSPECIFIED
#define PORT_STOP_SEC_VAR_CLEARED_UNSPECIFIED

#define DIO_START_SEC_VAR_CLEARED_UNSPECIFIED
#define DIO_STOP_SEC_VAR_CLEARED_UNSPECIFIED

#define CAN_START_SEC_VAR_CLEARED_UNSPECIFIED
#define CAN_STOP_SEC_VAR_CLEARED_UNSPECIFIED

#define SPI_START_SEC_VAR_CLEARED_UNSPECIFIED
#define SPI_STOP_SEC_VAR_CLEARED_UNSPECIFIED

#define GPT_START_SEC_VAR_CLEARED_UNSPECIFIED
#define GPT_STOP_SEC_VAR_CLEARED_UNSPECIFIED

#define PWM_START_SEC_VAR_CLEARED_UNSPECIFIED
#define PWM_STOP_SEC_VAR_CLEARED_UNSPECIFIED

#define ADC_START_SEC_VAR_CLEARED_UNSPECIFIED
#define ADC_STOP_SEC_VAR_CLEARED_UNSPECIFIED

#define WDG_START_SEC_VAR_CLEARED_UNSPECIFIED
#define WDG_STOP_SEC_VAR_CLEARED_UNSPECIFIED

#define COM_START_SEC_VAR_CLEARED_UNSPECIFIED
#define COM_STOP_SEC_VAR_CLEARED_UNSPECIFIED

#define PDUR_START_SEC_VAR_CLEARED_UNSPECIFIED
#define PDUR_STOP_SEC_VAR_CLEARED_UNSPECIFIED

#define DOIP_START_SEC_CODE
#define DOIP_STOP_SEC_CODE

#define DOIP_START_SEC_CONST_UNSPECIFIED
#define DOIP_STOP_SEC_CONST_UNSPECIFIED

#define DOIP_START_SEC_CONFIG_DATA_UNSPECIFIED
#define DOIP_STOP_SEC_CONFIG_DATA_UNSPECIFIED

#define DOIP_START_SEC_VAR_CLEARED_UNSPECIFIED
#define DOIP_STOP_SEC_VAR_CLEARED_UNSPECIFIED

#define DOCAN_START_SEC_CODE
#define DOCAN_STOP_SEC_CODE

#define DOCAN_START_SEC_CONST_UNSPECIFIED
#define DOCAN_STOP_SEC_CONST_UNSPECIFIED

#define DOCAN_START_SEC_CONFIG_DATA_UNSPECIFIED
#define DOCAN_STOP_SEC_CONFIG_DATA_UNSPECIFIED

#define DOCAN_START_SEC_VAR_CLEARED_UNSPECIFIED
#define DOCAN_STOP_SEC_VAR_CLEARED_UNSPECIFIED

/*==================================================================================================
*                                    MEMORY SECTION START/STOP MACROS
*                                    Compiler: ARM Compiler (ARMCC)
==================================================================================================*/
#elif defined(__CC_ARM) || defined(__ARMCC_VERSION)

/* Code Sections */
#define MCU_START_SEC_CODE
#define MCU_STOP_SEC_CODE

#define PORT_START_SEC_CODE
#define PORT_STOP_SEC_CODE

#define DIO_START_SEC_CODE
#define DIO_STOP_SEC_CODE

#define CAN_START_SEC_CODE
#define CAN_STOP_SEC_CODE

#define SPI_START_SEC_CODE
#define SPI_STOP_SEC_CODE

#define GPT_START_SEC_CODE
#define GPT_STOP_SEC_CODE

#define PWM_START_SEC_CODE
#define PWM_STOP_SEC_CODE

#define ADC_START_SEC_CODE
#define ADC_STOP_SEC_CODE

#define WDG_START_SEC_CODE
#define WDG_STOP_SEC_CODE

#define COM_START_SEC_CODE
#define COM_STOP_SEC_CODE

#define PDUR_START_SEC_CODE
#define PDUR_STOP_SEC_CODE

/* Const Sections */
#define MCU_START_SEC_CONST_UNSPECIFIED
#define MCU_STOP_SEC_CONST_UNSPECIFIED

#define PORT_START_SEC_CONST_UNSPECIFIED
#define PORT_STOP_SEC_CONST_UNSPECIFIED

#define DIO_START_SEC_CONST_UNSPECIFIED
#define DIO_STOP_SEC_CONST_UNSPECIFIED

#define CAN_START_SEC_CONST_UNSPECIFIED
#define CAN_STOP_SEC_CONST_UNSPECIFIED

#define SPI_START_SEC_CONST_UNSPECIFIED
#define SPI_STOP_SEC_CONST_UNSPECIFIED

#define GPT_START_SEC_CONST_UNSPECIFIED
#define GPT_STOP_SEC_CONST_UNSPECIFIED

#define PWM_START_SEC_CONST_UNSPECIFIED
#define PWM_STOP_SEC_CONST_UNSPECIFIED

#define ADC_START_SEC_CONST_UNSPECIFIED
#define ADC_STOP_SEC_CONST_UNSPECIFIED

#define WDG_START_SEC_CONST_UNSPECIFIED
#define WDG_STOP_SEC_CONST_UNSPECIFIED

#define COM_START_SEC_CONST_UNSPECIFIED
#define COM_STOP_SEC_CONST_UNSPECIFIED

#define PDUR_START_SEC_CONST_UNSPECIFIED
#define PDUR_STOP_SEC_CONST_UNSPECIFIED

/* Config Data Sections */
#define MCU_START_SEC_CONFIG_DATA_UNSPECIFIED
#define MCU_STOP_SEC_CONFIG_DATA_UNSPECIFIED

#define PORT_START_SEC_CONFIG_DATA_UNSPECIFIED
#define PORT_STOP_SEC_CONFIG_DATA_UNSPECIFIED

#define DIO_START_SEC_CONFIG_DATA_UNSPECIFIED
#define DIO_STOP_SEC_CONFIG_DATA_UNSPECIFIED

#define CAN_START_SEC_CONFIG_DATA_UNSPECIFIED
#define CAN_STOP_SEC_CONFIG_DATA_UNSPECIFIED

#define SPI_START_SEC_CONFIG_DATA_UNSPECIFIED
#define SPI_STOP_SEC_CONFIG_DATA_UNSPECIFIED

#define GPT_START_SEC_CONFIG_DATA_UNSPECIFIED
#define GPT_STOP_SEC_CONFIG_DATA_UNSPECIFIED

#define PWM_START_SEC_CONFIG_DATA_UNSPECIFIED
#define PWM_STOP_SEC_CONFIG_DATA_UNSPECIFIED

#define ADC_START_SEC_CONFIG_DATA_UNSPECIFIED
#define ADC_STOP_SEC_CONFIG_DATA_UNSPECIFIED

#define WDG_START_SEC_CONFIG_DATA_UNSPECIFIED
#define WDG_STOP_SEC_CONFIG_DATA_UNSPECIFIED

#define COM_START_SEC_CONFIG_DATA_UNSPECIFIED
#define COM_STOP_SEC_CONFIG_DATA_UNSPECIFIED

#define PDUR_START_SEC_CONFIG_DATA_UNSPECIFIED
#define PDUR_STOP_SEC_CONFIG_DATA_UNSPECIFIED

/* VAR Sections */
#define MCU_START_SEC_VAR_CLEARED_UNSPECIFIED
#define MCU_STOP_SEC_VAR_CLEARED_UNSPECIFIED

#define PORT_START_SEC_VAR_CLEARED_UNSPECIFIED
#define PORT_STOP_SEC_VAR_CLEARED_UNSPECIFIED

#define DIO_START_SEC_VAR_CLEARED_UNSPECIFIED
#define DIO_STOP_SEC_VAR_CLEARED_UNSPECIFIED

#define CAN_START_SEC_VAR_CLEARED_UNSPECIFIED
#define CAN_STOP_SEC_VAR_CLEARED_UNSPECIFIED

#define SPI_START_SEC_VAR_CLEARED_UNSPECIFIED
#define SPI_STOP_SEC_VAR_CLEARED_UNSPECIFIED

#define GPT_START_SEC_VAR_CLEARED_UNSPECIFIED
#define GPT_STOP_SEC_VAR_CLEARED_UNSPECIFIED

#define PWM_START_SEC_VAR_CLEARED_UNSPECIFIED
#define PWM_STOP_SEC_VAR_CLEARED_UNSPECIFIED

#define ADC_START_SEC_VAR_CLEARED_UNSPECIFIED
#define ADC_STOP_SEC_VAR_CLEARED_UNSPECIFIED

#define WDG_START_SEC_VAR_CLEARED_UNSPECIFIED
#define WDG_STOP_SEC_VAR_CLEARED_UNSPECIFIED

#define COM_START_SEC_VAR_CLEARED_UNSPECIFIED
#define COM_STOP_SEC_VAR_CLEARED_UNSPECIFIED

#define PDUR_START_SEC_VAR_CLEARED_UNSPECIFIED
#define PDUR_STOP_SEC_VAR_CLEARED_UNSPECIFIED

#define DOIP_START_SEC_CODE
#define DOIP_STOP_SEC_CODE

#define DOIP_START_SEC_CONST_UNSPECIFIED
#define DOIP_STOP_SEC_CONST_UNSPECIFIED

#define DOIP_START_SEC_CONFIG_DATA_UNSPECIFIED
#define DOIP_STOP_SEC_CONFIG_DATA_UNSPECIFIED

#define DOIP_START_SEC_VAR_CLEARED_UNSPECIFIED
#define DOIP_STOP_SEC_VAR_CLEARED_UNSPECIFIED

#define DOCAN_START_SEC_CODE
#define DOCAN_STOP_SEC_CODE

#define DOCAN_START_SEC_CONST_UNSPECIFIED
#define DOCAN_STOP_SEC_CONST_UNSPECIFIED

#define DOCAN_START_SEC_CONFIG_DATA_UNSPECIFIED
#define DOCAN_STOP_SEC_CONFIG_DATA_UNSPECIFIED

#define DOCAN_START_SEC_VAR_CLEARED_UNSPECIFIED
#define DOCAN_STOP_SEC_VAR_CLEARED_UNSPECIFIED

/*==================================================================================================
*                                    MEMORY SECTION START/STOP MACROS
*                                    Compiler: IAR
==================================================================================================*/
#elif defined(__ICCARM__)

/* Code Sections */
#define MCU_START_SEC_CODE
#define MCU_STOP_SEC_CODE

#define PORT_START_SEC_CODE
#define PORT_STOP_SEC_CODE

#define DIO_START_SEC_CODE
#define DIO_STOP_SEC_CODE

#define CAN_START_SEC_CODE
#define CAN_STOP_SEC_CODE

#define SPI_START_SEC_CODE
#define SPI_STOP_SEC_CODE

#define GPT_START_SEC_CODE
#define GPT_STOP_SEC_CODE

#define PWM_START_SEC_CODE
#define PWM_STOP_SEC_CODE

#define ADC_START_SEC_CODE
#define ADC_STOP_SEC_CODE

#define WDG_START_SEC_CODE
#define WDG_STOP_SEC_CODE

#define COM_START_SEC_CODE
#define COM_STOP_SEC_CODE

#define PDUR_START_SEC_CODE
#define PDUR_STOP_SEC_CODE

/* Const Sections */
#define MCU_START_SEC_CONST_UNSPECIFIED
#define MCU_STOP_SEC_CONST_UNSPECIFIED

#define PORT_START_SEC_CONST_UNSPECIFIED
#define PORT_STOP_SEC_CONST_UNSPECIFIED

#define DIO_START_SEC_CONST_UNSPECIFIED
#define DIO_STOP_SEC_CONST_UNSPECIFIED

#define CAN_START_SEC_CONST_UNSPECIFIED
#define CAN_STOP_SEC_CONST_UNSPECIFIED

#define SPI_START_SEC_CONST_UNSPECIFIED
#define SPI_STOP_SEC_CONST_UNSPECIFIED

#define GPT_START_SEC_CONST_UNSPECIFIED
#define GPT_STOP_SEC_CONST_UNSPECIFIED

#define PWM_START_SEC_CONST_UNSPECIFIED
#define PWM_STOP_SEC_CONST_UNSPECIFIED

#define ADC_START_SEC_CONST_UNSPECIFIED
#define ADC_STOP_SEC_CONST_UNSPECIFIED

#define WDG_START_SEC_CONST_UNSPECIFIED
#define WDG_STOP_SEC_CONST_UNSPECIFIED

#define COM_START_SEC_CONST_UNSPECIFIED
#define COM_STOP_SEC_CONST_UNSPECIFIED

#define PDUR_START_SEC_CONST_UNSPECIFIED
#define PDUR_STOP_SEC_CONST_UNSPECIFIED

/* Config Data Sections */
#define MCU_START_SEC_CONFIG_DATA_UNSPECIFIED
#define MCU_STOP_SEC_CONFIG_DATA_UNSPECIFIED

#define PORT_START_SEC_CONFIG_DATA_UNSPECIFIED
#define PORT_STOP_SEC_CONFIG_DATA_UNSPECIFIED

#define DIO_START_SEC_CONFIG_DATA_UNSPECIFIED
#define DIO_STOP_SEC_CONFIG_DATA_UNSPECIFIED

#define CAN_START_SEC_CONFIG_DATA_UNSPECIFIED
#define CAN_STOP_SEC_CONFIG_DATA_UNSPECIFIED

#define SPI_START_SEC_CONFIG_DATA_UNSPECIFIED
#define SPI_STOP_SEC_CONFIG_DATA_UNSPECIFIED

#define GPT_START_SEC_CONFIG_DATA_UNSPECIFIED
#define GPT_STOP_SEC_CONFIG_DATA_UNSPECIFIED

#define PWM_START_SEC_CONFIG_DATA_UNSPECIFIED
#define PWM_STOP_SEC_CONFIG_DATA_UNSPECIFIED

#define ADC_START_SEC_CONFIG_DATA_UNSPECIFIED
#define ADC_STOP_SEC_CONFIG_DATA_UNSPECIFIED

#define WDG_START_SEC_CONFIG_DATA_UNSPECIFIED
#define WDG_STOP_SEC_CONFIG_DATA_UNSPECIFIED

#define COM_START_SEC_CONFIG_DATA_UNSPECIFIED
#define COM_STOP_SEC_CONFIG_DATA_UNSPECIFIED

#define PDUR_START_SEC_CONFIG_DATA_UNSPECIFIED
#define PDUR_STOP_SEC_CONFIG_DATA_UNSPECIFIED

/* VAR Sections */
#define MCU_START_SEC_VAR_CLEARED_UNSPECIFIED
#define MCU_STOP_SEC_VAR_CLEARED_UNSPECIFIED

#define PORT_START_SEC_VAR_CLEARED_UNSPECIFIED
#define PORT_STOP_SEC_VAR_CLEARED_UNSPECIFIED

#define DIO_START_SEC_VAR_CLEARED_UNSPECIFIED
#define DIO_STOP_SEC_VAR_CLEARED_UNSPECIFIED

#define CAN_START_SEC_VAR_CLEARED_UNSPECIFIED
#define CAN_STOP_SEC_VAR_CLEARED_UNSPECIFIED

#define SPI_START_SEC_VAR_CLEARED_UNSPECIFIED
#define SPI_STOP_SEC_VAR_CLEARED_UNSPECIFIED

#define GPT_START_SEC_VAR_CLEARED_UNSPECIFIED
#define GPT_STOP_SEC_VAR_CLEARED_UNSPECIFIED

#define PWM_START_SEC_VAR_CLEARED_UNSPECIFIED
#define PWM_STOP_SEC_VAR_CLEARED_UNSPECIFIED

#define ADC_START_SEC_VAR_CLEARED_UNSPECIFIED
#define ADC_STOP_SEC_VAR_CLEARED_UNSPECIFIED

#define WDG_START_SEC_VAR_CLEARED_UNSPECIFIED
#define WDG_STOP_SEC_VAR_CLEARED_UNSPECIFIED

#define COM_START_SEC_VAR_CLEARED_UNSPECIFIED
#define COM_STOP_SEC_VAR_CLEARED_UNSPECIFIED

#define PDUR_START_SEC_VAR_CLEARED_UNSPECIFIED
#define PDUR_STOP_SEC_VAR_CLEARED_UNSPECIFIED

#define DOIP_START_SEC_CODE
#define DOIP_STOP_SEC_CODE

#define DOIP_START_SEC_CONST_UNSPECIFIED
#define DOIP_STOP_SEC_CONST_UNSPECIFIED

#define DOIP_START_SEC_CONFIG_DATA_UNSPECIFIED
#define DOIP_STOP_SEC_CONFIG_DATA_UNSPECIFIED

#define DOIP_START_SEC_VAR_CLEARED_UNSPECIFIED
#define DOIP_STOP_SEC_VAR_CLEARED_UNSPECIFIED

#define DOCAN_START_SEC_CODE
#define DOCAN_STOP_SEC_CODE

#define DOCAN_START_SEC_CONST_UNSPECIFIED
#define DOCAN_STOP_SEC_CONST_UNSPECIFIED

#define DOCAN_START_SEC_CONFIG_DATA_UNSPECIFIED
#define DOCAN_STOP_SEC_CONFIG_DATA_UNSPECIFIED

#define DOCAN_START_SEC_VAR_CLEARED_UNSPECIFIED
#define DOCAN_STOP_SEC_VAR_CLEARED_UNSPECIFIED

/*==================================================================================================
*                                    MEMORY SECTION START/STOP MACROS
*                                    Compiler: Default/Fallback
==================================================================================================*/
#else

/* Code Sections - Default empty macros */
#define MCU_START_SEC_CODE
#define MCU_STOP_SEC_CODE

#define PORT_START_SEC_CODE
#define PORT_STOP_SEC_CODE

#define DIO_START_SEC_CODE
#define DIO_STOP_SEC_CODE

#define CAN_START_SEC_CODE
#define CAN_STOP_SEC_CODE

#define SPI_START_SEC_CODE
#define SPI_STOP_SEC_CODE

#define GPT_START_SEC_CODE
#define GPT_STOP_SEC_CODE

#define PWM_START_SEC_CODE
#define PWM_STOP_SEC_CODE

#define ADC_START_SEC_CODE
#define ADC_STOP_SEC_CODE

#define WDG_START_SEC_CODE
#define WDG_STOP_SEC_CODE

#define COM_START_SEC_CODE
#define COM_STOP_SEC_CODE

#define PDUR_START_SEC_CODE
#define PDUR_STOP_SEC_CODE

/* Const Sections */
#define MCU_START_SEC_CONST_UNSPECIFIED
#define MCU_STOP_SEC_CONST_UNSPECIFIED

#define PORT_START_SEC_CONST_UNSPECIFIED
#define PORT_STOP_SEC_CONST_UNSPECIFIED

#define DIO_START_SEC_CONST_UNSPECIFIED
#define DIO_STOP_SEC_CONST_UNSPECIFIED

#define CAN_START_SEC_CONST_UNSPECIFIED
#define CAN_STOP_SEC_CONST_UNSPECIFIED

#define SPI_START_SEC_CONST_UNSPECIFIED
#define SPI_STOP_SEC_CONST_UNSPECIFIED

#define GPT_START_SEC_CONST_UNSPECIFIED
#define GPT_STOP_SEC_CONST_UNSPECIFIED

#define PWM_START_SEC_CONST_UNSPECIFIED
#define PWM_STOP_SEC_CONST_UNSPECIFIED

#define ADC_START_SEC_CONST_UNSPECIFIED
#define ADC_STOP_SEC_CONST_UNSPECIFIED

#define WDG_START_SEC_CONST_UNSPECIFIED
#define WDG_STOP_SEC_CONST_UNSPECIFIED

#define COM_START_SEC_CONST_UNSPECIFIED
#define COM_STOP_SEC_CONST_UNSPECIFIED

#define PDUR_START_SEC_CONST_UNSPECIFIED
#define PDUR_STOP_SEC_CONST_UNSPECIFIED

/* Config Data Sections */
#define MCU_START_SEC_CONFIG_DATA_UNSPECIFIED
#define MCU_STOP_SEC_CONFIG_DATA_UNSPECIFIED

#define PORT_START_SEC_CONFIG_DATA_UNSPECIFIED
#define PORT_STOP_SEC_CONFIG_DATA_UNSPECIFIED

#define DIO_START_SEC_CONFIG_DATA_UNSPECIFIED
#define DIO_STOP_SEC_CONFIG_DATA_UNSPECIFIED

#define CAN_START_SEC_CONFIG_DATA_UNSPECIFIED
#define CAN_STOP_SEC_CONFIG_DATA_UNSPECIFIED

#define SPI_START_SEC_CONFIG_DATA_UNSPECIFIED
#define SPI_STOP_SEC_CONFIG_DATA_UNSPECIFIED

#define GPT_START_SEC_CONFIG_DATA_UNSPECIFIED
#define GPT_STOP_SEC_CONFIG_DATA_UNSPECIFIED

#define PWM_START_SEC_CONFIG_DATA_UNSPECIFIED
#define PWM_STOP_SEC_CONFIG_DATA_UNSPECIFIED

#define ADC_START_SEC_CONFIG_DATA_UNSPECIFIED
#define ADC_STOP_SEC_CONFIG_DATA_UNSPECIFIED

#define WDG_START_SEC_CONFIG_DATA_UNSPECIFIED
#define WDG_STOP_SEC_CONFIG_DATA_UNSPECIFIED

#define COM_START_SEC_CONFIG_DATA_UNSPECIFIED
#define COM_STOP_SEC_CONFIG_DATA_UNSPECIFIED

#define PDUR_START_SEC_CONFIG_DATA_UNSPECIFIED
#define PDUR_STOP_SEC_CONFIG_DATA_UNSPECIFIED

/* VAR Sections */
#define MCU_START_SEC_VAR_CLEARED_UNSPECIFIED
#define MCU_STOP_SEC_VAR_CLEARED_UNSPECIFIED

#define PORT_START_SEC_VAR_CLEARED_UNSPECIFIED
#define PORT_STOP_SEC_VAR_CLEARED_UNSPECIFIED

#define DIO_START_SEC_VAR_CLEARED_UNSPECIFIED
#define DIO_STOP_SEC_VAR_CLEARED_UNSPECIFIED

#define CAN_START_SEC_VAR_CLEARED_UNSPECIFIED
#define CAN_STOP_SEC_VAR_CLEARED_UNSPECIFIED

#define SPI_START_SEC_VAR_CLEARED_UNSPECIFIED
#define SPI_STOP_SEC_VAR_CLEARED_UNSPECIFIED

#define GPT_START_SEC_VAR_CLEARED_UNSPECIFIED
#define GPT_STOP_SEC_VAR_CLEARED_UNSPECIFIED

#define PWM_START_SEC_VAR_CLEARED_UNSPECIFIED
#define PWM_STOP_SEC_VAR_CLEARED_UNSPECIFIED

#define ADC_START_SEC_VAR_CLEARED_UNSPECIFIED
#define ADC_STOP_SEC_VAR_CLEARED_UNSPECIFIED

#define WDG_START_SEC_VAR_CLEARED_UNSPECIFIED
#define WDG_STOP_SEC_VAR_CLEARED_UNSPECIFIED

#define COM_START_SEC_VAR_CLEARED_UNSPECIFIED
#define COM_STOP_SEC_VAR_CLEARED_UNSPECIFIED

#define PDUR_START_SEC_VAR_CLEARED_UNSPECIFIED
#define PDUR_STOP_SEC_VAR_CLEARED_UNSPECIFIED

#define DOIP_START_SEC_CODE
#define DOIP_STOP_SEC_CODE

#define DOIP_START_SEC_CONST_UNSPECIFIED
#define DOIP_STOP_SEC_CONST_UNSPECIFIED

#define DOIP_START_SEC_CONFIG_DATA_UNSPECIFIED
#define DOIP_STOP_SEC_CONFIG_DATA_UNSPECIFIED

#define DOIP_START_SEC_VAR_CLEARED_UNSPECIFIED
#define DOIP_STOP_SEC_VAR_CLEARED_UNSPECIFIED

#define DOCAN_START_SEC_CODE
#define DOCAN_STOP_SEC_CODE

#define DOCAN_START_SEC_CONST_UNSPECIFIED
#define DOCAN_STOP_SEC_CONST_UNSPECIFIED

#define DOCAN_START_SEC_CONFIG_DATA_UNSPECIFIED
#define DOCAN_STOP_SEC_CONFIG_DATA_UNSPECIFIED

#define DOCAN_START_SEC_VAR_CLEARED_UNSPECIFIED
#define DOCAN_STOP_SEC_VAR_CLEARED_UNSPECIFIED

#endif /* Compiler selection */

#endif /* MEMMAP_H */
