/**
 * @file NvM_EccHandler_Cfg.h
 * @brief NvM_EccHandler Configuration configuration header
 * @version 1.0.0
 * @date 2026-08-10
 * @note AUTO-GENERATED by yuleASR Configurator
 */

#ifndef NVM_ECCHANDLER_CFG_H
#define NVM_ECCHANDLER_CFG_H

#include "NvM_EccHandler.h"

/*==================================================================================================
*                                    PRE-COMPILE CONFIGURATION
*================================================================================================*/

/*==================================================================================================
*                                    Module Configuration Counts
*================================================================================================*/
#define NVM_ECCHANDLER_CFG_DEFAULT_RETRY_COUNT    (3U)
#define NVM_ECCHANDLER_CFG_NUM_BLOCKS    (5U)

/*==================================================================================================
*                                    Hardware Object Handles
*================================================================================================*/
#define NVM_ECCHANDLER_CFG_VENDOR_ID    (43U)
#define NVM_ECCHANDLER_CFG_AR_RELEASE_MAJOR_VERSION    (4U)
#define NVM_ECCHANDLER_CFG_AR_RELEASE_MINOR_VERSION    (7U)
#define NVM_ECCHANDLER_CFG_AR_RELEASE_REVISION_VERSION    (0U)
#define NVM_ECCHANDLER_CFG_SW_MAJOR_VERSION    (1U)
#define NVM_ECCHANDLER_CFG_SW_MINOR_VERSION    (0U)
#define NVM_ECCHANDLER_CFG_SW_PATCH_VERSION    (0U)
#define NVM_ECCHANDLER_CFG_ENABLED    STD_ON
#define NVM_ECCHANDLER_CFG_WRITE_VERIFICATION    STD_ON

/*==================================================================================================
*                                    Other Configuration
*================================================================================================*/
#define NVM_BLOCK_ID_DEM_ADMIN    (1U)
#define NVM_BLOCK_ID_DEM_STATUS    (2U)
#define NVM_BLOCK_ID_ECUM_CONFIG    (3U)
#define NVM_BLOCK_ID_BSWM_CONFIG    (4U)
#define NVM_BLOCK_ID_APP_DATA    (5U)

#endif /* NVM_ECCHANDLER_CFG_H */

/*==================[end of file]===========================================*/
