/*
 * Platform_MemMap.h - Memory mapping for platform safety features
 */
#ifndef PLATFORM_MEMMAP_H
#define PLATFORM_MEMMAP_H

#ifndef PLATFORM_START_SEC_CODE
#define PLATFORM_START_SEC_CODE
#endif
#ifndef PLATFORM_STOP_SEC_CODE
#define PLATFORM_STOP_SEC_CODE
#endif
#ifndef PLATFORM_START_SEC_CONST_UNSPECIFIED
#define PLATFORM_START_SEC_CONST_UNSPECIFIED
#endif
#ifndef PLATFORM_STOP_SEC_CONST_UNSPECIFIED
#define PLATFORM_STOP_SEC_CONST_UNSPECIFIED
#endif
#ifndef PLATFORM_START_SEC_VAR_CLEARED
#define PLATFORM_START_SEC_VAR_CLEARED
#endif
#ifndef PLATFORM_STOP_SEC_VAR_CLEARED
#define PLATFORM_STOP_SEC_VAR_CLEARED
#endif

#endif /* PLATFORM_MEMMAP_H */
