/**
 * @file Com_Cfg.h
 * @brief Com Configuration configuration header
 * @version 1.0.0
 * @date 2026-08-10
 * @note AUTO-GENERATED by yuleASR Configurator
 */

#ifndef COM_CFG_H
#define COM_CFG_H

/*==================================================================================================
*                                    PRE-COMPILE CONFIGURATION
*================================================================================================*/

/*==================================================================================================
*                                    General Configuration
*================================================================================================*/
#define COM_DEV_ERROR_DETECT    STD_ON
#define COM_VERSION_INFO_API    STD_ON

/*==================================================================================================
*                                    Module Configuration Counts
*================================================================================================*/
#define COM_NUM_OF_IPDUS    (64U)
#define COM_NUM_OF_SIGNALS    (256U)
#define COM_NUM_OF_IPDU_GROUPS    (16U)
#define COM_NUM_IPDU_GROUPS    COM_NUM_OF_IPDU_GROUPS
#define COM_NUM_OF_SIGNAL_GROUPS    (16U)

/*==================================================================================================
*                                    Hardware Object Handles
*================================================================================================*/
#define COM_TX_MODE_DIRECT    (0U)
#define COM_TX_MODE_PERIODIC    (1U)
#define COM_TX_MODE_MIXED    (2U)

/*==================================================================================================
*                                    Other Configuration
*================================================================================================*/
#define COM_MAX_SIGNALS    (256U)
#define COM_MAX_IPDUS    (64U)
#define COM_MAX_GROUPS    (16U)
#define COM_MAX_SIGNAL_LENGTH    (64U)
#define COM_LITTLE_ENDIAN    (0U)
#define COM_BIG_ENDIAN    (1U)
#define COM_MAX_IPDU_BUFFER_SIZE    (128U)
#define COM_MAX_IPDU_LENGTH    (64U)

#endif /* COM_CFG_H */

/*==================[end of file]===========================================*/
