/**
 * @file Flash_Cfg.h
 * @brief Flash Configuration configuration header
 * @version 1.0.0
 * @date 2026-08-10
 * @note AUTO-GENERATED by yuleASR Configurator
 */

#ifndef FLASH_CFG_H
#define FLASH_CFG_H

#include "Std_Types.h"   /* 非宏段依赖 Std_Types 基础类型 (uint32/uint8/uint16/boolean 等)，生成宏段不含此 include */
#include "S32K312.h"

/*==================================================================================================
*                                    PRE-COMPILE CONFIGURATION
*================================================================================================*/

/*==================================================================================================
*                                    General Configuration
*================================================================================================*/
#define FLS_DEV_ERROR_DETECT    STD_ON
#define FLS_VERSION_INFO_API    STD_ON
#define FLASH_DEV_ERROR_DETECT    STD_ON
#define FLASH_RUNTIME_ERROR_DETECT    STD_OFF
#define FLASH_VERSION_INFO_API    STD_ON
#define FLASH_SID_GETVERSIONINFO    (3U)

/*==================================================================================================
*                                    Module Configuration Counts
*================================================================================================*/
#define FLS_NUM_OF_CONFIGURED_SECTORS    (8U)
#define FLS_NUM_OF_FLASH_BANKS    (2U)
#define FLASH_NUM_OF_SECTORS    (8U)

/*==================================================================================================
*                                    Processing Modes
*================================================================================================*/
#define FLS_USE_INTERRUPTS    STD_OFF

/*==================================================================================================
*                                    Timing Configuration
*================================================================================================*/
#define FLS_TIMEOUT_SUPERVISION_ENABLED    STD_ON
#define FLS_MAX_ERASE_TIMEOUT_US    (10000000U)
#define FLS_MAX_PROGRAM_TIMEOUT_US    (100000U)
#define FLASH_TIMEOUT_MS    (1000U)

/*==================================================================================================
*                                    Other Configuration
*================================================================================================*/
#define FLS_CFG_VENDOR_ID    (1U)
#define FLS_CFG_MODULE_ID    (92U)
#define FLS_CFG_SW_MAJOR_VERSION    (1U)
#define FLS_CFG_SW_MINOR_VERSION    (0U)
#define FLS_CFG_SW_PATCH_VERSION    (0U)
#define FLS_CFG_AR_MAJOR_VERSION    (4U)
#define FLS_CFG_AR_MINOR_VERSION    (4U)
#define FLS_CFG_AR_PATCH_VERSION    (0U)
#define FLS_CANCEL_API    STD_ON
#define FLS_SET_MODE_API    STD_ON
#define FLS_COMPARE_API    STD_ON
#define FLS_BLANK_CHECK_API    STD_ON
#define FLS_RUNTIME_CONFIG_API    STD_OFF
#define FLS_BANK1_BASE_ADDRESS    (134217728U)
#define FLS_BANK2_BASE_ADDRESS    (135266304U)
#define FLS_TOTAL_SIZE    (2097152U)
#define FLS_BANK_SIZE    (1048576U)
#define FLS_SECTOR_SIZE_4KB_VALUE    (4096U)
#define FLS_SECTOR_SIZE_32KB_VALUE    (32768U)
#define FLS_SECTOR_SIZE_64KB_VALUE    (65536U)
#define FLS_SECTOR_SIZE_128KB_VALUE    (131072U)
#define FLS_ERASE_4KB_TIME_TYPICAL    (125000U)
#define FLS_ERASE_4KB_TIME_MAX    (400000U)
#define FLS_ERASE_32KB_TIME_TYPICAL    (500000U)
#define FLS_ERASE_32KB_TIME_MAX    (1600000U)
#define FLS_ERASE_64KB_TIME_TYPICAL    (1000000U)
#define FLS_ERASE_64KB_TIME_MAX    (3200000U)
#define FLS_ERASE_128KB_TIME_TYPICAL    (2000000U)
#define FLS_ERASE_128KB_TIME_MAX    (6400000U)
#define FLS_PROGRAM_BYTE_TIME_TYPICAL    (16U)
#define FLS_PROGRAM_BYTE_TIME_MAX    (100U)
#define FLS_PROGRAM_WORD_TIME_TYPICAL    (32U)
#define FLS_PROGRAM_WORD_TIME_MAX    (200U)
#define FLS_MAX_WAIT_STATES    (15U)
#define FLS_ACR_LATENCY_POS    (0U)
#define FLS_ACR_LATENCY_MASK    (15U)
#define FLS_ACR_PRFTEN    (256U)
#define FLS_ACR_ICEN    (512U)
#define FLS_ACR_DCEN    (1024U)
#define FLS_ACR_RUN_PD    (2048U)
#define FLS_ACR_SLEEP_PD    (4096U)
#define FLS_KEY1    (1164378403U)
#define FLS_KEY2    (3455027627U)
#define FLS_OPT_KEY1    (135866939U)
#define FLS_OPT_KEY2    (1281191551U)
#define FLS_SR_EOP    (1U)
#define FLS_SR_OPERR    (2U)
#define FLS_SR_PROGERR    (8U)
#define FLS_SR_WRPERR    (16U)
#define FLS_SR_PGAERR    (32U)
#define FLS_SR_SIZERR    (64U)
#define FLS_SR_PGSERR    (128U)
#define FLS_SR_MISERR    (256U)
#define FLS_SR_FASTERR    (512U)
#define FLS_SR_RDERR    (16384U)
#define FLS_SR_OPTVERR    (32768U)
#define FLS_SR_BSY    (65536U)
#define FLS_CR_PG    (1U)
#define FLS_CR_SER    (2U)
#define FLS_CR_MER    (4U)
#define FLS_CR_SNB_POS    (3U)
#define FLS_CR_SNB_MASK    (120U)
#define FLS_CR_PSIZE_POS    (8U)
#define FLS_CR_PSIZE_MASK    (768U)
#define FLS_CR_MER1    (32768U)
#define FLS_CR_STRT    (65536U)
#define FLS_CR_OPTSTRT    (131072U)
#define FLS_CR_FSTPG    (262144U)
#define FLS_CR_EOPIE    (16777216U)
#define FLS_CR_ERRIE    (33554432U)
#define FLS_CR_RDERRIE    (67108864U)
#define FLS_CR_OBL_LAUNCH    (134217728U)
#define FLS_CR_OPTLOCK    (1073741824U)
#define FLS_CR_LOCK    (2147483648U)
#define FLS_PSIZE_BYTE    (0U)
#define FLS_PSIZE_HALFWORD    (256U)
#define FLS_PSIZE_WORD    (512U)
#define FLS_PSIZE_DOUBLEWORD    (768U)
#define FLS_RDP_LEVEL_NONE    (170U)
#define FLS_RDP_LEVEL_1    (0U)
#define FLS_RDP_LEVEL_2    (204U)
#define FLS_WRP_SECTOR_0    (1U)
#define FLS_WRP_SECTOR_1    (2U)
#define FLS_WRP_SECTOR_2    (4U)
#define FLS_WRP_SECTOR_3    (8U)
#define FLS_WRP_SECTOR_4    (16U)
#define FLS_WRP_SECTOR_5    (32U)
#define FLS_WRP_SECTOR_6    (64U)
#define FLS_WRP_SECTOR_7    (128U)
#define FLS_WRP_ALL_SECTORS    (255U)
#define FLS_PCROP_ENABLED    STD_OFF
#define FLS_PCROP_RDP_ERASE    STD_OFF
#define FLASH_VENDOR_ID    (1U)
#define FLASH_MODULE_ID    (40U)
#define FLASH_INSTANCE_ID    (0U)
#define FLASH_SW_MAJOR_VERSION    (1U)
#define FLASH_SW_MINOR_VERSION    (0U)
#define FLASH_SW_PATCH_VERSION    (0U)
#define FLASH_SET_MODE_API    STD_ON
#define FLASH_SUSPEND_RESUME_API    STD_OFF
#define FLASH_CANCEL_API    STD_OFF
#define FLASH_COMPARE_API    STD_OFF
#define FLASH_BLANK_CHECK_API    STD_OFF
#define FLASH_JOB_END_NOTIFICATION    STD_OFF
#define FLASH_JOB_ERROR_NOTIFICATION    STD_OFF
#define FLASH_USE_ACCESS_CODE    STD_OFF
#define FLASH_TOTAL_SIZE    (1048576U)
#define FLASH_BASE_ADDRESS    (134217728U)
#define FLASH_END_ADDRESS    (135266304U)
#define FLASH_PROGRAM_UNIT    (8U)
#define FLASH_ERASE_UNIT    (8192U)
#define FLASH_MAX_READ_NORMAL_MODE    (100U)
#define FLASH_MAX_READ_FAST_MODE    (50U)
#define FLASH_MAX_WRITE_NORMAL_MODE    (500U)
#define FLASH_MAX_WRITE_FAST_MODE    (200U)
#define FLASH_MAX_COMPARE_MODE    (200U)
#define FLASH_BANK_0    (0U)
#define FLASH_BANK_1    (1U)
#define FLASH_SECTOR_0_START_ADDR    (134217728U)
#define FLASH_SECTOR_0_SIZE    (131072U)
#define FLASH_SECTOR_0_PAGE_SIZE    (8192U)
#define FLASH_SECTOR_1_START_ADDR    (134348800U)
#define FLASH_SECTOR_1_SIZE    (131072U)
#define FLASH_SECTOR_1_PAGE_SIZE    (8192U)
#define FLASH_SECTOR_2_START_ADDR    (134479872U)
#define FLASH_SECTOR_2_SIZE    (131072U)
#define FLASH_SECTOR_2_PAGE_SIZE    (8192U)
#define FLASH_SECTOR_3_START_ADDR    (134610944U)
#define FLASH_SECTOR_3_SIZE    (131072U)
#define FLASH_SECTOR_3_PAGE_SIZE    (8192U)
#define FLASH_SECTOR_4_START_ADDR    (134742016U)
#define FLASH_SECTOR_4_SIZE    (131072U)
#define FLASH_SECTOR_4_PAGE_SIZE    (8192U)
#define FLASH_SECTOR_5_START_ADDR    (134873088U)
#define FLASH_SECTOR_5_SIZE    (131072U)
#define FLASH_SECTOR_5_PAGE_SIZE    (8192U)
#define FLASH_SECTOR_6_START_ADDR    (135004160U)
#define FLASH_SECTOR_6_SIZE    (131072U)
#define FLASH_SECTOR_6_PAGE_SIZE    (8192U)
#define FLASH_SECTOR_7_START_ADDR    (135135232U)
#define FLASH_SECTOR_7_SIZE    (131072U)
#define FLASH_SECTOR_7_PAGE_SIZE    (8192U)
#define FLASH_CR    (*((volatile uint32*)0x40023C14U))
#define FLASH_CR_PG    (1U)
#define FLASH_CR_SER    (2U)
#define FLASH_CR_MER    (4U)
#define FLASH_CR_SNB_P    (8U)
#define FLASH_CR_SNB_Pos    (3U)
#define FLASH_CR_STRT    (65536U)
#define FLASH_CR_LOCK    (2147483648U)
#define FLASH_SR    (*((volatile uint32*)0x40023C0CU))
#define FLASH_SR_BSY    (1U)
#define FLASH_SR_PGERR    (4U)
#define FLASH_SR_WRPERR    (16U)
#define FLASH_SR_PGAERR    (32U)
#define FLASH_SR_PGPERR    (64U)
#define FLASH_SR_PGSERR    (128U)
#define FLASH_SR_OPERR    (512U)
#define FLASH_KEYR    (*((volatile uint32*)0x40023C04U))
#define FLASH_KEY_1    (1164378403U)
#define FLASH_KEY_2    (3455027627U)
#define FLASH_SID_INIT    (1U)
#define FLASH_SID_DEINIT    (2U)
#define FLASH_SID_ERASE    (4U)
#define FLASH_SID_WRITE    (5U)
#define FLASH_SID_READ    (6U)
#define FLASH_SID_CANCEL    (7U)
#define FLASH_SID_GETJOBRESULT    (8U)
#define FLASH_SID_SETMODE    (9U)
#define FLASH_SID_COMPARE    (10U)
#define FLASH_SID_BLANKCHECK    (11U)
#define FLASH_SID_SUSPEND    (12U)
#define FLASH_SID_RESUME    (13U)
#define FLASH_E_UNINIT    (1U)
#define FLASH_E_BUSY    (2U)
#define FLASH_E_ALREADY_INITIALIZED    (3U)
#define FLASH_E_PARAM_POINTER    (4U)
#define FLASH_E_PARAM_CONFIG    (5U)
#define FLASH_E_PARAM_ADDRESS    (6U)
#define FLASH_E_PARAM_LENGTH    (7U)
#define FLASH_E_WRITE_FAILED    (8U)
#define FLASH_E_ERASE_FAILED    (9U)
#define FLASH_E_COMPARE_FAILED    (10U)
#define FLASH_E_BLANK_CHECK_FAILED    (11U)
#define FLASH_UNINIT    (0U)
#define FLASH_IDLE    (1U)
#define FLASH_BUSY    (2U)
#define FLASH_BUSY_ERASING    (3U)
#define FLASH_BUSY_WRITING    (4U)
#define FLASH_BUSY_READING    (5U)


/*==================================================================================================
*  NON-MACRO SEGMENT (preserved from handwritten header, merged by codegen splice)
*  typedef(10) + struct(6) + extern config tables(4) — 依赖宏段计数宏, 故置于宏段之后
*  剔除重复 #define: FLS_SECTORSIZETYPE_DEFINED, FLASH_VENDOR_ID, FLASH_MODULE_ID, FLASH_INSTANCE_ID, FLASH_SW_MAJOR_VERSION, FLASH_SW_MINOR_VERSION, FLASH_SW_PATCH_VERSION, FLASH_DEV_ERROR_DETECT, FLASH_RUNTIME_ERROR_DETECT, FLASH_VERSION_INFO_API, FLASH_SET_MODE_API, FLASH_SUSPEND_RESUME_API, FLASH_CANCEL_API, FLASH_COMPARE_API, FLASH_BLANK_CHECK_API, FLASH_JOB_END_NOTIFICATION, FLASH_JOB_ERROR_NOTIFICATION, FLASH_USE_ACCESS_CODE, FLASH_NUM_OF_SECTORS, FLASH_TOTAL_SIZE, FLASH_BASE_ADDRESS, FLASH_END_ADDRESS, FLASH_PROGRAM_UNIT, FLASH_ERASE_UNIT, FLASH_TIMEOUT_MS, FLASH_MAX_READ_NORMAL_MODE, FLASH_MAX_READ_FAST_MODE, FLASH_MAX_WRITE_NORMAL_MODE, FLASH_MAX_WRITE_FAST_MODE, FLASH_MAX_COMPARE_MODE, FLASH_BANK_0, FLASH_BANK_1, FLASH_SECTOR_0_START_ADDR, FLASH_SECTOR_0_SIZE, FLASH_SECTOR_0_PAGE_SIZE, FLASH_SECTOR_1_START_ADDR, FLASH_SECTOR_1_SIZE, FLASH_SECTOR_1_PAGE_SIZE, FLASH_SECTOR_2_START_ADDR, FLASH_SECTOR_2_SIZE, FLASH_SECTOR_2_PAGE_SIZE, FLASH_SECTOR_3_START_ADDR, FLASH_SECTOR_3_SIZE, FLASH_SECTOR_3_PAGE_SIZE, FLASH_SECTOR_4_START_ADDR, FLASH_SECTOR_4_SIZE, FLASH_SECTOR_4_PAGE_SIZE, FLASH_SECTOR_5_START_ADDR, FLASH_SECTOR_5_SIZE, FLASH_SECTOR_5_PAGE_SIZE, FLASH_SECTOR_6_START_ADDR, FLASH_SECTOR_6_SIZE, FLASH_SECTOR_6_PAGE_SIZE, FLASH_SECTOR_7_START_ADDR, FLASH_SECTOR_7_SIZE, FLASH_SECTOR_7_PAGE_SIZE, FLASH_CR, FLASH_CR_PG, FLASH_CR_SER, FLASH_CR_MER, FLASH_CR_SNB_P, FLASH_CR_SNB_Pos, FLASH_CR_STRT, FLASH_CR_LOCK, FLASH_SR, FLASH_SR_BSY, FLASH_SR_PGERR, FLASH_SR_WRPERR, FLASH_SR_PGAERR, FLASH_SR_PGPERR, FLASH_SR_PGSERR, FLASH_SR_OPERR, FLASH_KEYR, FLASH_KEY_1, FLASH_KEY_2（生成宏段提供同名宏）
*================================================================================================*/
typedef uint32 Fls_AddressType;

/* Length Type */
typedef uint32 Fls_LengthType;

/* Sector Index Type */
typedef uint8 Fls_SectorIndexType;

/* Error Flags Type */
typedef uint32 Fls_ErrorFlagsType;

/************************************************************************************
 *                          Configuration Structures
 ************************************************************************************/

/* Sector size type */
#ifndef FLS_SECTORSIZETYPE_DEFINED
typedef enum {
    FLS_SECTOR_SIZE_4KB = 0,
    FLS_SECTOR_SIZE_32KB,
    FLS_SECTOR_SIZE_64KB,
    FLS_SECTOR_SIZE_128KB
} Fls_SectorSizeType;
#endif

/* Flash Sector Configuration */
typedef struct
{
    Fls_AddressType       StartAddress;
    Fls_LengthType        Size;
    Fls_SectorSizeType    SizeType;
    boolean               WriteProtected;
    boolean               ReadProtected;
    uint8                 Bank;
    uint8                 SectorNumber;
} Fls_SectorConfigType;

/* Flash Timing Configuration */
typedef struct
{
    uint32 EraseTime4KB;
    uint32 EraseTime32KB;
    uint32 EraseTime64KB;
    uint32 EraseTime128KB;
    uint32 ProgramByteTime;
    uint32 ProgramWordTime;
    uint32 MaxEraseTimeout;
    uint32 MaxProgramTimeout;
    uint8  WaitStates;
} Fls_TimingConfigType;

/* Flash Protection Configuration */
typedef struct
{
    uint8 ReadProtectionLevel;
    uint32 WriteProtectionMask;
    boolean PcropEnabled;
    uint32 PcropStartAddress;
    uint32 PcropEndAddress;
} Fls_ProtectionConfigType;

/* General Configuration */
typedef struct
{
    boolean UseInterrupts;
    boolean PrefetchEnable;
    boolean InstructionCacheEnable;
    boolean DataCacheEnable;
    uint8   FlashLatency;
} Fls_GeneralConfigType;

/************************************************************************************
 *                          Extern Configuration
 ************************************************************************************/
extern const Fls_SectorConfigType Fls_SectorConfig[FLS_NUM_OF_CONFIGURED_SECTORS];
extern const Fls_TimingConfigType Fls_TimingConfig;
extern const Fls_ProtectionConfigType Fls_ProtectionConfig;
extern const Fls_GeneralConfigType Fls_GeneralConfig;



/*==================================================================================================
 *                          LEGACY FLASH DRIVER CONFIGURATION
 *  Types and configuration used by the Flash.c driver implementation
 *  (distinct from the Fls_* AUTOSAR API also declared in this header).
 *================================================================================================*/

/* Legacy driver types */
typedef uint32 Flash_AddressType;
typedef uint32 Flash_LengthType;

typedef enum {
    FLASH_MODE_NORMAL = 0,
    FLASH_MODE_FAST
} Flash_OpModeType;

typedef enum {
    FLASH_JOB_OK = 0,
    FLASH_JOB_PENDING,
    FLASH_JOB_FAILED,
    FLASH_JOB_CANCELLED,
    FLASH_JOB_SUSPENDED
} Flash_JobResultType;

typedef struct {
    uint32  sectorStartAddr;
    uint32  sectorSize;
    uint32  pageSize;
    uint8   sectorIndex;
    uint8   bank;
    boolean isProtected;
    boolean isErased;
    boolean isBlankCheckDone;
} Flash_SectorInfoType;

typedef struct {
    const Flash_SectorInfoType* sectorConfig;
    uint32  numOfSectors;
    Flash_OpModeType defaultMode;
    uint32  baseAddress;
    uint32  endAddress;
    uint32  maxReadNormalMode;
    uint32  maxReadFastMode;
    uint32  maxWriteNormalMode;
    uint32  maxWriteFastMode;
    uint32  programUnit;
    uint32  eraseUnit;
    void (*jobEndNotification)(void);
    void (*jobErrorNotification)(void);
} Flash_ConfigType;

/* Version / module info */

/* Feature switches */

/* Geometry */

/* Banks */

/* Sector map (default geometry for a 1 MB flash) */

/* Register definitions (lvalue register access; STM32F4-style default) */

/* Driver status type */
typedef enum {
    FLASH_STATUS_UNINIT = 0,
    FLASH_STATUS_IDLE,
    FLASH_STATUS_BUSY,
    FLASH_STATUS_BUSY_ERASING,
    FLASH_STATUS_BUSY_WRITING,
    FLASH_STATUS_BUSY_READING
} Flash_StatusType;
#endif /* FLASH_CFG_H */

/*==================[end of file]===========================================*/
