/**
 * @file LinTp_Cfg.h
 * @brief LinTp Configuration configuration header
 * @version 1.0.0
 * @date 2026-08-10
 * @note AUTO-GENERATED by yuleASR Configurator
 */

#ifndef LINTP_CFG_H
#define LINTP_CFG_H

/*==================================================================================================
*                                    PRE-COMPILE CONFIGURATION
*================================================================================================*/

/*==================================================================================================
*                                    General Configuration
*================================================================================================*/
#define LINTP_DEV_ERROR_DETECT    STD_ON
#define LINTP_VERSION_INFO_API    STD_ON

/*==================================================================================================
*                                    Module Configuration Counts
*================================================================================================*/
#define LINTP_N_AS_TIMEOUT_COUNT    (LINTP_DEFAULT_N_AS_MS / 5U)
#define LINTP_N_CR_TIMEOUT_COUNT    (LINTP_DEFAULT_N_CR_MS / 5U)

/*==================================================================================================
*                                    Hardware Object Handles
*================================================================================================*/
#define LINTP_PDU_TX_DIAGNOSTIC    (0U)
#define LINTP_PDU_RX_DIAGNOSTIC    (1U)
#define LINTP_PDU_TX_FUNCTIONAL    (2U)
#define LINTP_PDU_RX_FUNCTIONAL    (3U)

/*==================================================================================================
*                                    Timing Configuration
*================================================================================================*/
#define LINTP_MAIN_FUNCTION_PERIOD_MS    (5U)

/*==================================================================================================
*                                    Other Configuration
*================================================================================================*/
#define LINTP_CHANGE_PARAMETER_API    STD_ON
#define LINTP_CANCEL_TRANSMIT_API    STD_ON
#define LINTP_CANCEL_RECEIVE_API    STD_ON
#define LINTP_TC    STD_ON
#define LINTP_NUMBER_OF_CHANNELS    (1U)
#define LINTP_NUMBER_OF_CONNECTIONS    (2U)
#define LINTP_NUMBER_OF_PDUS    (4U)
#define LINTP_CHANNEL_0    (0U)
#define LINTP_CONNECTION_0    (0U)
#define LINTP_CONNECTION_1    (1U)
#define LINTP_NAD_BROADCAST    (127U)
#define LINTP_NAD_DIAGNOSTIC    (1U)
#define LINTP_NAD_FUNCTIONAL    (126U)
#define LINTP_NAD_DEFAULT    (0U)
#define LINTP_DEFAULT_N_AS_MS    (100U)
#define LINTP_DEFAULT_N_CR_MS    (100U)
#define LINTP_DEFAULT_STMIN_MS    (10U)
#define LINTP_MAX_MESSAGE_LENGTH    (4095U)
#define LINTP_SF_MAX_DATA_LENGTH    (6U)
#define LINTP_FF_DATA_LENGTH    (5U)
#define LINTP_CF_DATA_LENGTH    (6U)
#define LINTP_FRAME_SIZE    (8U)
#define LINTP_PCI_SIZE    (1U)
#define LINTP_PCI_MASK    (240U)
#define LINTP_PCI_SF    (0U)
#define LINTP_PCI_FF    (16U)
#define LINTP_PCI_CF    (32U)
#define LINTP_PCI_TYPE_MASK    (240U)
#define LINTP_PCI_DL_MASK    (15U)
#define LINTP_PCI_SN_MASK    (15U)
#define LINTP_SN_MAX    (15U)
#define LINTP_SN_FIRST_CF    (1U)

#endif /* LINTP_CFG_H */

/*==================[end of file]===========================================*/
