/**
 * @file Gpt_Cfg.h
 * @brief GPT Driver Configuration Template - AutoSAR MCAL
 * @version 1.0.0
 * @date 2026-04-22
 * @author ConfigGenerator
 *
 * @note This file is generated by the ConfigGenerator tool.
 *       Manual changes may be overwritten.
 */

#ifndef GPT_CFG_H
#define GPT_CFG_H

#include "Std_Types.h"

/*==================================================================================================
*                                    PRE-COMPILE CONFIGURATION
==================================================================================================*/
#define GPT_DEV_ERROR_DETECT            (STD_ON)
#define GPT_VERSION_INFO_API            (STD_ON)
#define GPT_WAKEUP_FUNCTIONALITY_API    (STD_OFF)
#define GPT_DEINIT_API                  (STD_ON)
#define GPT_TIME_ELAPSED_API            (STD_ON)
#define GPT_TIME_REMAINING_API          (STD_ON)
#define GPT_ENABLE_DISABLE_NOTIFICATION_API (STD_ON)
#define GPT_PREDEF_TIMER_100US_32BIT    (STD_OFF)
#define GPT_PREDEF_TIMER_1US_16BIT      (STD_OFF)
#define GPT_PREDEF_TIMER_1US_24BIT      (STD_OFF)
#define GPT_PREDEF_TIMER_1US_32BIT      (STD_OFF)

/*==================================================================================================
*                                    CHANNEL CONFIGURATION
==================================================================================================*/
#define GPT_NUM_CHANNELS                (4U)

/*==================================================================================================
*                                    CHANNEL IDs
==================================================================================================*/
#define GPT_CHANNEL_0                   (0U)
#define GPT_CHANNEL_1                   (1U)
#define GPT_CHANNEL_2                   (2U)
#define GPT_CHANNEL_3                   (3U)

/*==================================================================================================
*                                    TIMER MODE
==================================================================================================*/
#define GPT_MODE_CONTINUOUS             (0U)
#define GPT_MODE_ONESHOT                (1U)

/*==================================================================================================
*                                    CLOCK PRESCALER
==================================================================================================*/
#define GPT_CLOCK_PRESCALER_1           (0U)
#define GPT_CLOCK_PRESCALER_2           (1U)
#define GPT_CLOCK_PRESCALER_4           (2U)
#define GPT_CLOCK_PRESCALER_8           (3U)
#define GPT_CLOCK_PRESCALER_16          (4U)
#define GPT_CLOCK_PRESCALER_32          (5U)
#define GPT_CLOCK_PRESCALER_64          (6U)
#define GPT_CLOCK_PRESCALER_128         (7U)

/*==================================================================================================
*                                    TICK FREQUENCY (Hz)
==================================================================================================*/
#define GPT_CHANNEL_0_TICK_FREQ         (1000U)   /* 1ms tick */
#define GPT_CHANNEL_1_TICK_FREQ         (10000U)  /* 100us tick */
#define GPT_CHANNEL_2_TICK_FREQ         (100000U) /* 10us tick */
#define GPT_CHANNEL_3_TICK_FREQ         (1000000U)/* 1us tick */

/*==================================================================================================
*                                    MAX TICK VALUE
==================================================================================================*/
#define GPT_CHANNEL_MAX_TICK_VALUE      (0xFFFFFFFFU)

#endif /* GPT_CFG_H */
