/**
 * @file IoHwAb_Cfg.h
 * @brief IO Hardware Abstraction Configuration Template - AutoSAR BSW
 * @version 1.0.0
 * @date 2026-04-22
 * @author ConfigGenerator
 *
 * @note This file is generated by the ConfigGenerator tool.
 *       Manual changes may be overwritten.
 */

#ifndef IOHWAB_CFG_H
#define IOHWAB_CFG_H

#include "Std_Types.h"

/*==================================================================================================
*                                    PRE-COMPILE CONFIGURATION
==================================================================================================*/
#define IOHWAB_DEV_ERROR_DETECT         (STD_ON)
#define IOHWAB_VERSION_INFO_API         (STD_ON)

/*==================================================================================================
*                                    NUMBER OF CHANNELS
==================================================================================================*/
#define IOHWAB_NUM_ANALOG_INPUTS        (16U)
#define IOHWAB_NUM_ANALOG_OUTPUTS       (8U)
#define IOHWAB_NUM_DIGITAL_INPUTS       (32U)
#define IOHWAB_NUM_DIGITAL_OUTPUTS      (32U)
#define IOHWAB_NUM_PWM_OUTPUTS          (8U)
#define IOHWAB_NUM_ICU_INPUTS           (4U)
#define IOHWAB_NUM_OPAMP_CHANNELS       (2U)

/*==================================================================================================
*                                    ANALOG INPUT IDs
==================================================================================================*/
#define IOHWAB_AI_BATTERY_VOLTAGE       (0U)
#define IOHWAB_AI_ENGINE_TEMP           (1U)
#define IOHWAB_AI_COOLANT_TEMP          (2U)
#define IOHWAB_AI_OIL_PRESSURE          (3U)
#define IOHWAB_AI_THROTTLE_POSITION     (4U)
#define IOHWAB_AI_ACCELERATOR_PEDAL     (5U)
#define IOHWAB_AI_AMBIENT_TEMP          (6U)
#define IOHWAB_AI_FUEL_LEVEL            (7U)

/*==================================================================================================
*                                    ANALOG OUTPUT IDs
==================================================================================================*/
#define IOHWAB_AO_IDLE_SPEED_CTRL       (0U)
#define IOHWAB_AO_EGR_CONTROL           (1U)
#define IOHWAB_AO_VVT_CONTROL           (2U)

/*==================================================================================================
*                                    DIGITAL INPUT IDs
==================================================================================================*/
#define IOHWAB_DI_ENGINE_RUNNING        (0U)
#define IOHWAB_DI_CRANKshaft_POS        (1U)
#define IOHWAB_DI_CAMshaft_POS          (2U)
#define IOHWAB_DI_VEHICLE_SPEED_PULSE   (3U)
#define IOHWAB_DI_BRAKE_PEDAL           (4U)
#define IOHWAB_DI_CLUTCH_PEDAL          (5U)
#define IOHWAB_DI_DOOR_OPEN_FRONT_LEFT  (6U)
#define IOHWAB_DI_DOOR_OPEN_FRONT_RIGHT (7U)

/*==================================================================================================
*                                    DIGITAL OUTPUT IDs
==================================================================================================*/
#define IOHWAB_DO_FUEL_PUMP_RELAY       (0U)
#define IOHWAB_DO_MAIN_RELAY            (1U)
#define IOHWAB_DO_FAN_CONTROL           (2U)
#define IOHWAB_DO_MIL_LAMP              (3U)
#define IOHWAB_DO_STARTER_MOTOR         (4U)

/*==================================================================================================
*                                    PWM OUTPUT IDs
==================================================================================================*/
#define IOHWAB_PO_FUEL_INJECTOR_1       (0U)
#define IOHWAB_PO_FUEL_INJECTOR_2       (1U)
#define IOHWAB_PO_FUEL_INJECTOR_3       (2U)
#define IOHWAB_PO_FUEL_INJECTOR_4       (3U)
#define IOHWAB_PO_IDLE_AIR_CONTROL      (4U)

/*==================================================================================================
*                                    ICU INPUT IDs
==================================================================================================*/
#define IOHWAB_ICU_ENGINE_SPEED         (0U)
#define IOHWAB_ICU_VEHICLE_SPEED        (1U)
#define IOHWAB_ICU_CRANKshaft_SIGNAL    (2U)
#define IOHWAB_ICU_CAMshaft_SIGNAL      (3U)

/*==================================================================================================
*                                    ADC RESOLUTION
==================================================================================================*/
#define IOHWAB_ADC_RESOLUTION_8BIT      (8U)
#define IOHWAB_ADC_RESOLUTION_10BIT     (10U)
#define IOHWAB_ADC_RESOLUTION_12BIT     (12U)
#define IOHWAB_ADC_RESOLUTION_16BIT     (16U)

#define IOHWAB_ADC_RESOLUTION           (IOHWAB_ADC_RESOLUTION_12BIT)
#define IOHWAB_ADC_MAX_VALUE            (4095U)

/*==================================================================================================
*                                    VOLTAGE REFERENCE
==================================================================================================*/
#define IOHWAB_ADC_VREF_MV              (3300U)   /* 3.3V */

/*==================================================================================================
*                                    PWM FREQUENCY RANGE
==================================================================================================*/
#define IOHWAB_PWM_MIN_FREQ_HZ          (1U)
#define IOHWAB_PWM_MAX_FREQ_HZ          (20000U)
#define IOHWAB_PWM_DEFAULT_FREQ_HZ      (1000U)

#endif /* IOHWAB_CFG_H */
