/**
 * @file I2c_Cfg.h
 * @brief I2c Configuration configuration header
 * @version 1.0.0
 * @date 2026-08-10
 * @note AUTO-GENERATED by yuleASR Configurator
 */

#ifndef I2C_CFG_H
#define I2C_CFG_H

#include "Std_Types.h"

/*==================================================================================================
*                                    PRE-COMPILE CONFIGURATION
*================================================================================================*/

/*==================================================================================================
*                                    General Configuration
*================================================================================================*/
#define I2C_DEV_ERROR_DETECT    STD_ON
#define I2C_VERSION_INFO_API    STD_ON

/*==================================================================================================
*                                    Module Configuration Counts
*================================================================================================*/
#define I2C_NUM_CHANNELS    (8U)
#define I2C_NUM_HW_UNITS    (4U)
#define I2C_NUM_DMA_CHANNELS    (8U)

/*==================================================================================================
*                                    Processing Modes
*================================================================================================*/
#define I2C_INTERRUPT_SUPPORTED    STD_ON
#define I2C_INTERRUPT_PRIORITY    (5U)
#define I2C_ERROR_INTERRUPT_PRIORITY    (4U)
#define I2C_DMA_TX_INTERRUPT_PRIORITY    (6U)
#define I2C_DMA_RX_INTERRUPT_PRIORITY    (6U)

/*==================================================================================================
*                                    Timing Configuration
*================================================================================================*/
#define I2C_BUS_BUSY_TIMEOUT_MS    (100U)
#define I2C_TRANSFER_TIMEOUT_MS    (1000U)
#define I2C_CLOCK_STRETCH_TIMEOUT_MS    (50U)
#define I2C_SMBUS_TIMEOUT_MS    (35U)
#define I2C_MAIN_FUNCTION_PERIOD_MS    (10U)

/*==================================================================================================
*                                    Other Configuration
*================================================================================================*/
#define I2C_DMA_SUPPORTED    STD_ON
#define I2C_10BIT_ADDRESS_SUPPORTED    STD_ON
#define I2C_16BIT_ADDRESS_SUPPORTED    STD_OFF
#define I2C_SMBUS_SUPPORTED    STD_ON
#define I2C_MULTI_MASTER_SUPPORTED    STD_ON
#define I2C_CLOCK_STRETCHING_SUPPORTED    STD_ON
#define I2C_SLAVE_MODE_SUPPORTED    STD_ON
#define I2C_GENERAL_CALL_SUPPORTED    STD_ON
#define I2C_SW_RESET_API    STD_ON
#define I2C_CHANNEL_0    (0U)
#define I2C_CHANNEL_1    (1U)
#define I2C_CHANNEL_2    (2U)
#define I2C_CHANNEL_3    (3U)
#define I2C_CHANNEL_4    (4U)
#define I2C_CHANNEL_5    (5U)
#define I2C_CHANNEL_6    (6U)
#define I2C_CHANNEL_7    (7U)
#define I2C_HW_UNIT_0    (0U)
#define I2C_HW_UNIT_1    (1U)
#define I2C_HW_UNIT_2    (2U)
#define I2C_HW_UNIT_3    (3U)
#define I2C_PERIPHERAL_CLOCK_FREQ    (24000000U)
#define I2C_STANDARD_MODE_FREQ    (100000U)
#define I2C_FAST_MODE_FREQ    (400000U)
#define I2C_FAST_MODE_PLUS_FREQ    (1000000U)
#define I2C_HIGH_SPEED_MODE_FREQ    (3400000U)
#define I2C_MAX_BUFFER_SIZE    (256U)
#define I2C_MAX_SLAVE_ADDRESSES    (4U)
#define I2C_SMBUS_PEC_SUPPORTED    STD_ON
#define I2C_SMBUS_ALERT_SUPPORTED    STD_ON
#define I2C_DEFAULT_ADDRESS_MODE    I2C_ADDR_MODE_7BIT
#define I2C_DEFAULT_TRANSFER_MODE    I2C_MODE_INTERRUPT

#endif /* I2C_CFG_H */

/*==================[end of file]===========================================*/
