/**
 * @file EthSwt_Cfg.h
 * @brief EthSwt Configuration configuration header
 * @version 1.0.0
 * @date 2026-08-10
 * @note AUTO-GENERATED by yuleASR Configurator
 */

#ifndef ETHSWT_CFG_H
#define ETHSWT_CFG_H

/*==================================================================================================
*                                    PRE-COMPILE CONFIGURATION
*================================================================================================*/

/*==================================================================================================
*                                    General Configuration
*================================================================================================*/
#define ETHSWT_DEV_ERROR_DETECT    STD_ON
#define ETHSWT_VERSION_INFO_API    STD_ON

/*==================================================================================================
*                                    Processing Modes
*================================================================================================*/
#define ETHSWT_LINK_POLL_INTERVAL_MS    (100U)

/*==================================================================================================
*                                    Hardware Object Handles
*================================================================================================*/
#define ETHSWT_TX_QUEUE_DEPTH    (64U)
#define ETHSWT_RX_QUEUE_DEPTH    (64U)

/*==================================================================================================
*                                    Timing Configuration
*================================================================================================*/
#define ETHSWT_MAIN_FUNCTION_PERIOD_MS    (10U)

/*==================================================================================================
*                                    Other Configuration
*================================================================================================*/
#define ETHSWT_MAX_PORTS    (8U)
#define ETHSWT_MAX_VLANS    (16U)
#define ETHSWT_MAX_MAC_FILTERS    (32U)
#define ETHSWT_ALL_PORTS    (255U)
#define ETHSWT_FRAME_BUFFER_SIZE    (1600U)
#define ETHSWT_ENABLE_VLAN    STD_ON
#define ETHSWT_ENABLE_MAC_FILTERING    STD_ON
#define ETHSWT_ENABLE_PORT_STATS    STD_ON
#define ETHSWT_ENABLE_AUTO_NEGOTIATION    STD_ON
#define ETHSWT_ENABLE_FLOW_CONTROL    STD_ON
#define ETHSWT_ENABLE_MIRRORING    STD_ON
#define ETHSWT_DEFAULT_HIGH_WATERMARK    (32U)
#define ETHSWT_DEFAULT_LOW_WATERMARK    (8U)
#define ETHSWT_DEFAULT_PAUSE_TIME    (512U)
#define ETHSWT_DEFAULT_SPEED    ETHSWT_SPEED_AUTO
#define ETHSWT_DEFAULT_DUPLEX    ETHSWT_DUPLEX_FULL
#define ETHSWT_DEFAULT_MTU    (1500U)

#endif /* ETHSWT_CFG_H */

/*==================[end of file]===========================================*/
