/**
 * @file MemIf_Cfg.h
 * @brief MemIf Configuration configuration header
 * @version 1.0.0
 * @date 2026-08-10
 * @note AUTO-GENERATED by yuleASR Configurator
 */

#ifndef MEMIF_CFG_H
#define MEMIF_CFG_H

#include "Std_Types.h"

/*==================================================================================================
*                                    PRE-COMPILE CONFIGURATION
*================================================================================================*/

/*==================================================================================================
*                                    General Configuration
*================================================================================================*/
#ifndef MEMIF_DEV_ERROR_DETECT
#define MEMIF_DEV_ERROR_DETECT    STD_ON
#endif
#ifndef MEMIF_VERSION_INFO_API
#define MEMIF_VERSION_INFO_API    STD_ON
#endif
#define MEMIF_NUMBER_OF_DEVICES    (2U)
#define MEMIF_NUMBER_OF_FEE_DEVICES    (1U)
#define MEMIF_NUMBER_OF_EA_DEVICES    (1U)
#define MEMIF_FEE_DEVICE_INDEX    (0U)
#define MEMIF_EA_DEVICE_INDEX    (1U)
#ifndef MEMIF_TOTAL_NUM_DEVICES
#define MEMIF_TOTAL_NUM_DEVICES    (1U)
#endif

/*==================================================================================================
*                                    Processing Modes
*================================================================================================*/
#define MEMIF_POLLING_MODE    STD_ON
#define MEMIF_INTERRUPT_MODE    STD_OFF

/*==================================================================================================
*                                    Timing Configuration
*================================================================================================*/
#define MEMIF_READ_TIMEOUT_MS    (100U)
#define MEMIF_WRITE_TIMEOUT_MS    (1000U)
#define MEMIF_ERASE_TIMEOUT_MS    (5000U)

/*==================================================================================================
*                                    Other Configuration
*================================================================================================*/
#define MEMIF_MAX_BLOCK_NUMBER    (256U)
#define MEMIF_MAX_BLOCK_SIZE    (4096U)
#define MEMIF_FEE_USED    STD_ON
#define MEMIF_EA_USED    STD_ON
#define MEMIF_USE_RTE    STD_OFF
#define MEMIF_CANCEL_API    STD_ON
#define MEMIF_SETMODE_API    STD_ON
#define MEMIF_GETSTATUS_API    STD_ON
#define MEMIF_GETJOBRESULT_API    STD_ON
#define MEMIF_INVALIDATEBLOCK_API    STD_ON
#define MEMIF_ERASEIMMEDIATEBLOCK_API    STD_ON
#define MEMIF_MULTI_CORE_SUPPORT    STD_OFF
#define MEMIF_FEE_CORE_ID    (0U)
#define MEMIF_EA_CORE_ID    (0U)
#ifndef MEMIF_INSTANCE_ID
#define MEMIF_INSTANCE_ID    (0U)
#endif
#ifndef MEMIF_SID_INIT
#define MEMIF_SID_INIT    (1U)
#endif
#ifndef MEMIF_PATH_FEE
#define MEMIF_PATH_FEE    (0U)
#endif
#ifndef MEMIF_PATH_EA
#define MEMIF_PATH_EA    (1U)
#endif
#ifndef MEMIF_BUSY_INTERNAL
#define MEMIF_BUSY_INTERNAL    (2U)
#endif
#ifndef MEMIF_UNINIT
#define MEMIF_UNINIT    (0U)
#endif
/*==================================================================================================
*                                    CONDITIONAL INCLUDES
*================================================================================================*/
#if (MEMIF_FEE_USED == STD_ON)
    #include "Fee.h"
#endif
#if (MEMIF_EA_USED == STD_ON)
    #include "Ea.h"
#endif

/*==================================================================================================
*                                    FUNCTION-LIKE MACROS (VERBATIM)
*================================================================================================*/
#if (MEMIF_FEE_USED == STD_ON)
    #ifndef Fee_Read
        #define Fee_Read(BlockNumber, BlockOffset, DataBufferPtr, Length) \
            Fee_Read(BlockNumber, BlockOffset, DataBufferPtr, Length)
    #endif
    
    #ifndef Fee_Write
        #define Fee_Write(BlockNumber, DataBufferPtr) \
            Fee_Write(BlockNumber, DataBufferPtr)
    #endif
    
    #ifndef Fee_Cancel
        #define Fee_Cancel() Fee_Cancel()
    #endif
    
    #ifndef Fee_GetStatus
        #define Fee_GetStatus() Fee_GetStatus()
    #endif
    
    #ifndef Fee_GetJobResult
        #define Fee_GetJobResult() Fee_GetJobResult()
    #endif
#endif
#if (MEMIF_EA_USED == STD_ON)
    #ifndef Ea_Read
        #define Ea_Read(BlockNumber, DataBufferPtr) \
            Ea_Read(BlockNumber, DataBufferPtr)
    #endif
    
    #ifndef Ea_Write
        #define Ea_Write(BlockNumber, DataBufferPtr) \
            Ea_Write(BlockNumber, DataBufferPtr)
    #endif
    
    #ifndef Ea_Cancel
        #define Ea_Cancel() Ea_Cancel()
    #endif
    
    #ifndef Ea_GetStatus
        #define Ea_GetStatus() Ea_GetStatus()
    #endif
    
    #ifndef Ea_GetJobResult
        #define Ea_GetJobResult() Ea_GetJobResult()
    #endif
#endif


#endif /* MEMIF_CFG_H */

/*==================[end of file]===========================================*/
