/**
 * @file CryIf_Cfg.h
 * @brief CryIf Configuration configuration header
 * @version 1.0.0
 * @date 2026-08-10
 * @note AUTO-GENERATED by yuleASR Configurator
 */

#ifndef CRYIF_CFG_H
#define CRYIF_CFG_H

#include "CryIf_Types.h"

#include "CryIf_Types.h"

/*==================================================================================================
*                                    PRE-COMPILE CONFIGURATION
*================================================================================================*/

/*==================================================================================================
*                                    General Configuration
*================================================================================================*/
#ifndef CRYIF_DEV_ERROR_DETECT
#define CRYIF_DEV_ERROR_DETECT    STD_ON
#endif
#ifndef CRYIF_VERSION_INFO_API
#define CRYIF_VERSION_INFO_API    STD_ON
#endif

/*==================================================================================================
*                                    Module Configuration Counts
*================================================================================================*/
#define CRYIF_CFG_MAX_CHANNEL_COUNT    (4U)
#define CRYIF_CFG_MAX_KEY_COUNT    (8U)
#define CRYIF_CFG_MAX_JOB_COUNT    (16U)
#define CRYIF_CFG_NUM_CHANNELS    (2U)
#define CRYIF_CFG_NUM_KEYS    (4U)

/*==================================================================================================
*                                    Timing Configuration
*================================================================================================*/
#define CRYIF_CFG_MAIN_FUNCTION_PERIOD_MS    (10U)

/*==================================================================================================
*                                    Other Configuration
*================================================================================================*/
#define CRYIF_CFG_AR_RELEASE_MAJOR_VERSION    (4U)
#define CRYIF_CFG_AR_RELEASE_MINOR_VERSION    (4U)
#define CRYIF_CFG_AR_RELEASE_REVISION_VERSION    (0U)
#define CRYIF_CFG_SW_MAJOR_VERSION    (1U)
#define CRYIF_CFG_SW_MINOR_VERSION    (0U)
#define CRYIF_CFG_SW_PATCH_VERSION    (0U)
#ifndef CRYIF_KEY_ELEMENT_COPY_API
#define CRYIF_KEY_ELEMENT_COPY_API    STD_ON
#endif
#ifndef CRYIF_KEY_VALID_CHECK_API
#define CRYIF_KEY_VALID_CHECK_API    STD_ON
#endif
#define CRYIF_CFG_MAX_BUFFER_SIZE    (1024U)
#define CRYIF_CFG_MAX_KEY_ELEMENT_SIZE    (256U)
#define CRYIF_CFG_CHANNEL_0_ID    (0U)
#define CRYIF_CFG_CHANNEL_0_DRIVER_INDEX    (0U)
#define CRYIF_CFG_CHANNEL_0_DRIVER_OBJ    (0U)
#define CRYIF_CFG_CHANNEL_0_MAX_KEY_SIZE    (256U)
#define CRYIF_CFG_CHANNEL_0_MAX_JOB_SIZE    (1024U)
#define CRYIF_CFG_CHANNEL_1_ID    (1U)
#define CRYIF_CFG_CHANNEL_1_DRIVER_INDEX    (0U)
#define CRYIF_CFG_CHANNEL_1_DRIVER_OBJ    (1U)
#define CRYIF_CFG_CHANNEL_1_MAX_KEY_SIZE    (256U)
#define CRYIF_CFG_CHANNEL_1_MAX_JOB_SIZE    (1024U)
#define CRYIF_CFG_KEY_0_ID    (0U)
#define CRYIF_CFG_KEY_0_CRYPTO_KEY_ID    (0U)
#define CRYIF_CFG_KEY_0_DRIVER_INDEX    (0U)
#define CRYIF_CFG_KEY_0_SECURITY_LEVEL    CRYIF_SEC_LEVEL_3
#define CRYIF_CFG_KEY_1_ID    (1U)
#define CRYIF_CFG_KEY_1_CRYPTO_KEY_ID    (1U)
#define CRYIF_CFG_KEY_1_DRIVER_INDEX    (0U)
#define CRYIF_CFG_KEY_1_SECURITY_LEVEL    CRYIF_SEC_LEVEL_2
#define CRYIF_CFG_KEY_2_ID    (2U)
#define CRYIF_CFG_KEY_2_CRYPTO_KEY_ID    (2U)
#define CRYIF_CFG_KEY_2_DRIVER_INDEX    (0U)
#define CRYIF_CFG_KEY_2_SECURITY_LEVEL    CRYIF_SEC_LEVEL_1
#define CRYIF_CFG_KEY_3_ID    (3U)
#define CRYIF_CFG_KEY_3_CRYPTO_KEY_ID    (3U)
#define CRYIF_CFG_KEY_3_DRIVER_INDEX    (0U)
#define CRYIF_CFG_KEY_3_SECURITY_LEVEL    CRYIF_SEC_LEVEL_NONE
#define CRYIF_KEY_ELEMENT_ID_IV    (1U)
#define CRYIF_KEY_ELEMENT_ID_KEY    (2U)
#define CRYIF_KEY_ELEMENT_ID_SALT    (3U)
#define CRYIF_KEY_ELEMENT_ID_ITERATIONS    (4U)
#define CRYIF_KEY_ELEMENT_ID_ALGORITHM    (5U)
#define CRYIF_KEY_ELEMENT_ID_SEED_STATE    (6U)
#define CRYIF_KEY_ELEMENT_ID_DRBG_STATE    (7U)
#define CRYIF_KEY_ELEMENT_ID_MAC    (8U)
#define CRYIF_KEY_ELEMENT_ID_SIGNATURE    (9U)
#define CRYIF_KEY_ELEMENT_ID_PUBKEY    (10U)
#define CRYIF_KEY_ELEMENT_ID_PRIVKEY    (11U)
#define CRYIF_KEY_ELEMENT_ID_CERTIFICATE    (12U)
#define CRYIF_KEY_ELEMENT_ID_CERTIFICATE_DATA    (13U)
#define CRYIF_KEY_ELEMENT_ID_CERTIFICATE_SIGN    (14U)
#define CRYIF_KEY_ELEMENT_ID_CERTIFICATE_ID    (15U)
#define CRYIF_CFG_NOTIFICATION_ENABLED    STD_ON
#define CRYIF_CFG_JOB_CALLBACK    CryIf_JobNotificationCallback
#define CRYIF_CFG_KEY_CALLBACK    CryIf_KeyNotificationCallback
#ifndef CRYIF_DEBUG_ENABLED
#define CRYIF_DEBUG_ENABLED    STD_OFF
#endif
/*==================================================================================================
*                                    FUNCTION-LIKE MACROS (VERBATIM)
*================================================================================================*/
#define CRYIF_CFG_SEC_LEVEL_TO_CSM(level)       ((level) * 0x10U)
#define CRYIF_CFG_IS_VALID_SEC_LEVEL(level)     \
(((level) >= CRYIF_SEC_LEVEL_NONE) && ((level) <= CRYIF_SEC_LEVEL_7))
#if (CRYIF_DEBUG_ENABLED == STD_ON)
    #include <stdio.h>
    #define CRYIF_DBG_PRINT(fmt, ...)           printf("[CRYIF] " fmt "\n", ##__VA_ARGS__)
#else
    #define CRYIF_DBG_PRINT(fmt, ...)           ((void)0)
#endif



/*==================================================================================================
*  NON-MACRO SEGMENT (preserved from handwritten header, merged by codegen splice)
*  typedef(0) + struct(0) + extern config tables(1) — 依赖宏段计数宏, 故置于宏段之后
*================================================================================================*/
extern const CryIf_ConfigType CryIf_Config;
#endif /* CRYIF_CFG_H */

/*==================[end of file]===========================================*/
