/**
 * @file DoIP_Cfg.h
 * @brief DoIP Configuration configuration header
 * @version 1.0.0
 * @date 2026-08-10
 * @note AUTO-GENERATED by yuleASR Configurator
 */

#ifndef DOIP_CFG_H
#define DOIP_CFG_H

#include "Std_Types.h"   /* 非宏段依赖 Std_Types 基础类型 (uint32/uint8/uint16/boolean 等)，生成宏段不含此 include */

/*==================================================================================================
*                                    PRE-COMPILE CONFIGURATION
*================================================================================================*/

/*==================================================================================================
*                                    General Configuration
*================================================================================================*/
#define DOIP_DEV_ERROR_DETECT    STD_ON
#define DOIP_VERSION_INFO_API    STD_ON

/*==================================================================================================
*                                    Module Configuration Counts
*================================================================================================*/
#define DOIP_VEHICLE_ANNOUNCEMENT_COUNT    (3U)

/*==================================================================================================
*                                    Hardware Object Handles
*================================================================================================*/
#define DOIP_DCM_TX_DIAG_REQUEST    (0U)
#define DOIP_DCM_RX_DIAG_RESPONSE    (1U)
#define DOIP_SOAD_TX_PDU_ID    (0U)
#define DOIP_SOAD_RX_PDU_ID    (1U)

/*==================================================================================================
*                                    Timing Configuration
*================================================================================================*/
#define DOIP_MAIN_FUNCTION_PERIOD_MS    (10U)
#define DOIP_GENERAL_INACTIVITY_TIMEOUT_MS    (180000U)
#define DOIP_INITIAL_INACTIVITY_TIMEOUT_MS    (2000U)
#define DOIP_ALIVE_CHECK_TIMEOUT_MS    (500U)
#define DOIP_ALIVE_CHECK_RESPONSE_TIMEOUT_MS    (5000U)

/*==================================================================================================
*                                    Other Configuration
*================================================================================================*/
#define DOIP_DCM_SUPPORT    STD_ON
#define DOIP_SOAD_SUPPORT    STD_ON
#define DOIP_PROTOCOL_VERSION    (2U)
#define DOIP_PROTOCOL_VERSION_INVERT    (253U)
#define DOIP_HEADER_LENGTH    (8U)
#define DOIP_DIAG_MSG_HEADER_LENGTH    (4U)
#define DOIP_ROUTING_ACTIVATION_REQ_LEN    (7U)
#define DOIP_ROUTING_ACTIVATION_RES_LEN    (13U)
#ifndef DOIP_MAX_CONNECTIONS
#define DOIP_MAX_CONNECTIONS    (4U)
#endif
#define DOIP_MAX_ROUTING_ACTIVATIONS    (8U)
#define DOIP_MAX_TESTERS    (4U)
#define DOIP_MAX_ENTITY    (1U)
#define DOIP_MAX_DIAG_REQUEST_LENGTH    (4096U)
#define DOIP_MAX_DIAG_RESPONSE_LENGTH    (4096U)
#define DOIP_MAX_VEHICLE_ID_LENGTH    (32U)
#define DOIP_MAX_ALIVE_CHECK_LENGTH    (8U)
#define DOIP_VEH_ANNOUNCEMENT_INTERVAL_MS    (500U)
#define DOIP_VEH_ANNOUNCEMENT_INITIAL_DELAY_MS    (500U)
#define DOIP_VEHICLE_ANNOUNCEMENT_INTERVAL    (50U)
#define DOIP_VEHICLE_ANNOUNCEMENT_INITIAL_DELAY    (50U)
#define DOIP_CONNECTION_0    (0U)
#define DOIP_CONNECTION_1    (1U)
#define DOIP_CONNECTION_2    (2U)
#define DOIP_CONNECTION_3    (3U)
#define DOIP_SOCON_TCP_DATA_0    (0U)
#define DOIP_SOCON_TCP_DATA_1    (1U)
#define DOIP_SOCON_TCP_DATA_2    (2U)
#define DOIP_SOCON_TCP_DATA_3    (3U)
#define DOIP_SOCON_UDP_DISCOVERY    (4U)
#define DOIP_SOCON_UDP_TEST_EQUIP    (5U)
#define DOIP_SOCON_TCP_DATA    (0U)
#define DOIP_SOCON_TCP_ROUTING    (6U)
#define DOIP_LOGICAL_ADDRESS_ECU    (1U)
#define DOIP_LOGICAL_ADDRESS_TESTER_1    (3584U)
#define DOIP_LOGICAL_ADDRESS_TESTER_2    (3585U)
#define DOIP_LOGICAL_ADDRESS_TESTER_3    (3586U)
#define DOIP_LOGICAL_ADDRESS_TESTER_4    (3587U)
#define DOIP_LOGICAL_ADDRESS_BROADCAST    (65535U)
#define DOIP_ROUTING_ACTIVATION_0    (0U)
#define DOIP_ROUTING_ACTIVATION_1    (1U)
#define DOIP_ROUTING_ACTIVATION_2    (2U)
#define DOIP_ROUTING_ACTIVATION_3    (3U)
#define DOIP_ROUTING_ACTIVATION_DEFAULT    (0U)
#define DOIP_ROUTING_ACTIVATION_WWH_OBD    (1U)
#define DOIP_ROUTING_ACTIVATION_CENTRAL_SECURITY    (224U)
#define DOIP_ROUTING_ACTIVATION_ADSB    (225U)
#define DOIP_PORT_TCP_DATA    (13400U)
#define DOIP_PORT_UDP_DISCOVERY    (13400U)
#define DOIP_PORT_UDP_TEST_EQUIP    (13401U)
#define DOIP_FURTHER_ACTION_NO_FURTHER    (0U)
#define DOIP_FURTHER_ACTION_CENTRAL_SEC    (16U)
#define DOIP_VIN_GID_STATUS_VIN_INVALID    (0U)
#define DOIP_VIN_GID_STATUS_VIN_VALID    (1U)
#define DOIP_VIN_GID_STATUS_GID_SYNCHRONIZED    (2U)
#define DOIP_VIN_GID_STATUS_GID_NOT_SYNC    (4U)
#define DOIP_VEHICLE_DISCOVERY_ENABLED    STD_ON
#define DOIP_ROUTING_ACTIVATION_ENABLED    STD_ON
#define DOIP_DIAGNOSTIC_MESSAGE_ENABLED    STD_ON
#define DOIP_ALIVE_CHECK_ENABLED    STD_ON
#define DOIP_ENTITY_STATUS_ENABLED    STD_ON
#define DOIP_DIAGNOSTIC_POWER_MODE_ENABLED    STD_ON
#define DOIP_AUTHENTICATION_REQUIRED    STD_OFF
#define DOIP_CONFIRMATION_REQUIRED    STD_OFF
#define DOIP_USE_SECURE_CONNECTIONS    STD_OFF
#define DOIP_USER_VEHICLE_ID_RESPONSE_FNC    (NULL_PTR)
#define DOIP_USER_ROUTING_ACTIVATION_RESPONSE_FNC    (NULL_PTR)
#define DOIP_USER_ALIVE_CHECK_RESPONSE_FNC    (NULL_PTR)
#ifndef DOIP_CFG_GENERAL_INACTIVITY
#define DOIP_CFG_GENERAL_INACTIVITY    (300000U)
#endif
#ifndef DOIP_DEFAULT_ACTIVATION_TYPE
#define DOIP_DEFAULT_ACTIVATION_TYPE    (1U)
#endif
#ifndef DOIP_WWH_OBD_ACTIVATION_TYPE
#define DOIP_WWH_OBD_ACTIVATION_TYPE    (2U)
#endif
#ifndef DOIP_CENTRAL_SECURITY_TYPE
#define DOIP_CENTRAL_SECURITY_TYPE    (4U)
#endif
#ifndef DOIP_VIN_LENGTH
#define DOIP_VIN_LENGTH    (17U)
#endif
#ifndef DOIP_EID_LENGTH
#define DOIP_EID_LENGTH    (6U)
#endif
#ifndef DOIP_GID_LENGTH
#define DOIP_GID_LENGTH    (6U)
#endif
#ifndef DOIP_LOGICAL_ADDRESS
#define DOIP_LOGICAL_ADDRESS    (3584U)
#endif
#ifndef DOIP_FURTHER_ACTION
#define DOIP_FURTHER_ACTION    (0U)
#endif
#ifndef DOIP_VIN
#define DOIP_VIN    "YULETECHASR000001"
#endif
#ifndef DOIP_EID
#define DOIP_EID    ""
#endif
#ifndef DOIP_GID
#define DOIP_GID    ""
#endif


/*==================================================================================================
*  NON-MACRO SEGMENT (preserved from handwritten header, merged by codegen splice)
*  typedef(0) + struct(4) + extern config tables(0) — 依赖宏段计数宏, 故置于宏段之后
*================================================================================================*/
typedef struct {
    uint16 TesterAddress;
    boolean AuthenticationRequired;
    boolean ConfirmationRequired;
    uint8 AllowedActivationTypes;
} DoIP_TesterConfigType;

typedef struct {
    uint16 TargetAddress;
    uint8 ProtocolType;
    uint16 LowerLayerPduId;
} DoIP_TargetConfigType;

typedef struct {
    uint16 LogicalAddress;
    const uint8* Vin;
    const uint8* Eid;
    const uint8* Gid;
    uint8 FurtherAction;
    uint8 MaxConnections;
    uint32 GeneralInactivityTime;
} DoIP_GeneralConfigType;

typedef struct {
    uint16 SoConId;
    boolean IsTcp;
    boolean IsUdp;
    uint16 LocalPort;
    const uint8* LocalIpAddress;
    uint16 RemotePort;
    const uint8* RemoteIpAddress;
} DoIP_SoConConfigType;
#endif /* DOIP_CFG_H */

/*==================[end of file]===========================================*/
