/**
 * @file Wdg_Cfg.h
 * @brief Wdg Configuration configuration header
 * @version 1.0.0
 * @date 2026-08-10
 * @note AUTO-GENERATED by yuleASR Configurator
 */

#ifndef WDG_CFG_H
#define WDG_CFG_H

/*==================================================================================================
*                                    PRE-COMPILE CONFIGURATION
*================================================================================================*/

/*==================================================================================================
*                                    General Configuration
*================================================================================================*/
#define WDG_DEV_ERROR_DETECT    STD_ON
#define WDG_VERSION_INFO_API    STD_ON

/*==================================================================================================
*                                    Processing Modes
*================================================================================================*/
#define WDG_FAST_MODE_INTERRUPT    STD_ON
#define WDG_SLOW_MODE_INTERRUPT    STD_ON

/*==================================================================================================
*                                    Timing Configuration
*================================================================================================*/
#define WDG_DEFAULT_TIMEOUT    (100U)
#define WDG_FAST_MODE_TIMEOUT    (50U)
#define WDG_FAST_MODE_TIMEOUT_PRE_US    (500U)
#define WDG_SLOW_MODE_TIMEOUT    (500U)
#define WDG_SLOW_MODE_TIMEOUT_PRE_US    (1000U)
#define WDG_MAX_TIMEOUT    (1000U)
#define WDG_MIN_TIMEOUT    (1U)
#define WDG_TIMEOUT_PRE_WARNING    STD_ON

/*==================================================================================================
*                                    Other Configuration
*================================================================================================*/
#define WDG_DISABLE_ALLOWED    STD_OFF
#define WDG_INITIAL_MODE    WDGIF_FAST_MODE
#define WDG_FAST_MODE_PRESCALER    WDG_PRESCALER_64
#define WDG_FAST_MODE_WINDOW_ENABLED    STD_ON
#define WDG_FAST_MODE_WINDOW_START    (10U)
#define WDG_FAST_MODE_WINDOW_END    (40U)
#define WDG_SLOW_MODE_PRESCALER    WDG_PRESCALER_128
#define WDG_SLOW_MODE_WINDOW_ENABLED    STD_ON
#define WDG_SLOW_MODE_WINDOW_START    (100U)
#define WDG_SLOW_MODE_WINDOW_END    (400U)
#define WDG_BASE_ADDRESS    (807927808U)
#define WDG_CLOCK_FREQUENCY_HZ    (32000U)
#define WDG_VALIDATE_WINDOW_MODE    STD_ON
#define WDG_WINDOW_ERROR_ACTION    WDG_WINDOW_ERROR_RESET
#define WDG_PRE_WARNING_CALLBACK    STD_ON

#endif /* WDG_CFG_H */

/*==================[end of file]===========================================*/
