/**
 * @file FiM_Cfg.h
 * @brief FiM_Ecual Configuration configuration header
 * @version 1.0.0
 * @date 2026-08-10
 * @note AUTO-GENERATED by yuleASR Configurator
 */

#ifndef FIM_CFG_H
#define FIM_CFG_H

#include "Std_Types.h"   /* 非宏段依赖 Std_Types 基础类型 (uint32/uint8/uint16/boolean 等)，生成宏段不含此 include */

#include "Std_Types.h"

/*==================================================================================================
*                                    PRE-COMPILE CONFIGURATION
*================================================================================================*/

/*==================================================================================================
*                                    General Configuration
*================================================================================================*/
#define FIM_VERSION_INFO_API    STD_ON
#define FIM_DEV_ERROR_DETECT    STD_ON

/*==================================================================================================
*                                    Other Configuration
*================================================================================================*/
#define FIM_CFG_AR_RELEASE_MAJOR_VERSION    (4U)
#define FIM_CFG_AR_RELEASE_MINOR_VERSION    (4U)
#define FIM_EVENT_UPDATE_TRIGGERED_BY_DEM    STD_ON
#define FIM_FUNCTION_INHIBITION_AVAILABLE    STD_ON
#define FIM_EVENT_UPDATE_TRIGGER    STD_ON
#define FIM_MAIN_FUNCTION_CALLOUT_SUPPORTED    STD_OFF
#define FIM_CFG_NUMBER_OF_FIDS    (32U)
#define FIM_CFG_MAX_FID    (FIM_CFG_NUMBER_OF_FIDS - 1u)
#define FIM_CFG_NUMBER_OF_EVENTS    (64U)
#define FIM_CFG_MAX_EVENT    (FIM_CFG_NUMBER_OF_EVENTS - 1u)
#define FIM_CFG_MAX_INHIBITION_CONFIG    (128U)
#define FIM_CFG_MAX_EVENT_FID_MAP    (96U)
#define FIM_INVALID_FID    (65535U)
#define FIM_INVALID_EVENT    (65535U)
#define FIM_LAST_FAILED    (1U)
#define FIM_NOT_TESTED    (2U)
#define FIM_TESTED_FAULTY    (4U)
#define FIM_TESTED_AND_FAILED    (4U)
#define FIM_INHIBIT_IF_FAILED    (5U)
#define FIM_MASK_NONE    (0U)
#define FIM_MASK_ALL_FAILURES    (7U)
#define DEM_UDS_STATUS_TF    (1U)
#define DEM_UDS_STATUS_TFTOC    (2U)
#define DEM_UDS_STATUS_PDTC    (4U)
#define DEM_UDS_STATUS_CDTC    (8U)
#define DEM_UDS_STATUS_TNCSLC    (16U)
#define DEM_UDS_STATUS_TFSLC    (32U)
#define DEM_UDS_STATUS_TNCTOC    (64U)
#define DEM_UDS_STATUS_WIR    (128U)
#define FIM_FID_POWER_LIMIT    (0U)
#define FIM_FID_TORQUE_LIMIT    (1U)
#define FIM_FID_SPEED_LIMIT    (2U)
#define FIM_FID_EMISSION_CONTROL    (3U)
#define FIM_FID_START_STOP_FUNCTION    (4U)
#define FIM_FID_CRUISE_CONTROL    (5U)
#define FIM_FID_ADAS_FEATURES    (6U)
#define FIM_FID_THERMAL_MANAGEMENT    (7U)
#define FIM_FID_BATTERY_CHARGING    (8U)
#define FIM_FID_REGENERATIVE_BRAKING    (9U)
#define FIM_FID_USER_DEFINED_1    (10U)
#define FIM_FID_USER_DEFINED_2    (11U)
#define FIM_EVENT_CATALYST_DAMAGE    (0U)
#define FIM_EVENT_MISFIRE    (1U)
#define FIM_EVENT_FUEL_SYSTEM    (2U)
#define FIM_EVENT_O2_SENSOR    (3U)
#define FIM_EVENT_BOOST_PRESSURE    (4U)
#define FIM_EVENT_COOLANT_TEMP    (5U)
#define FIM_EVENT_THROTTLE_POSITION    (6U)
#define FIM_EVENT_MAF_SENSOR    (7U)
#define FIM_EVENT_ENGINE_KNOCK    (8U)
#define FIM_EVENT_BATTERY_VOLTAGE    (9U)
#define FIM_CFG_CONST    const
#define FIM_CFG_CONST_ROOT    const


/*==================================================================================================
*  NON-MACRO SEGMENT (preserved from handwritten header, merged by codegen splice)
*  typedef(2) + struct(4) + extern config tables(0) — 依赖宏段计数宏, 故置于宏段之后
*================================================================================================*/
typedef uint16 FiM_FunctionIdType;

typedef uint16 FiM_InhibitionMaskConfigurationType;

typedef struct {
    FiM_FunctionIdType      Fid;
    uint16                  EventId;
    uint8                   InhibitionMask;
} FiM_InhibitionConfigType;

typedef struct {
    uint16                  EventId;
    FiM_FunctionIdType      Fid;
    uint8                   InhibitionMask;
} FiM_EventFidMappingType;

typedef struct {
    uint16                  EventId;
    boolean                 isConfigured;
} FiM_EventConfigType;

typedef struct {
    FiM_FunctionIdType      Fid;
    boolean                 isConfigured;
    boolean                 availability;
    boolean                 defaultPermission;
} FiM_FidConfigType;
#endif /* FIM_CFG_H */

/*==================[end of file]===========================================*/
