/**
 * @file Crc_Cfg.h
 * @brief Crc Configuration configuration header
 * @version 1.0.0
 * @date 2026-08-10
 * @note AUTO-GENERATED by yuleASR Configurator
 */

#ifndef CRC_CFG_H
#define CRC_CFG_H

#include "Std_Types.h"   /* 非宏段依赖 Std_Types 基础类型 (uint32/uint8/uint16/boolean 等)，生成宏段不含此 include */

#include "Std_Types.h"

/*==================================================================================================
*                                    PRE-COMPILE CONFIGURATION
*================================================================================================*/

/*==================================================================================================
*                                    General Configuration
*================================================================================================*/
#define CRC_DEV_ERROR_DETECT    STD_OFF
#define CRC_VERSION_INFO_API    STD_ON

/*==================================================================================================
*                                    Other Configuration
*================================================================================================*/
#define CRC_8_MODE    STD_ON
#define CRC_8_POLYNOMIAL    (29U)
#define CRC_8_INITIAL_VALUE    (255U)
#define CRC_8_XOR_OUT    (255U)
#define CRC_8_TABLE_MODE    STD_ON
#define CRC_8_TABLE_SIZE    (256U)
#define CRC_16_MODE    STD_ON
#define CRC_16_POLYNOMIAL    (4129U)
#define CRC_16_INITIAL_VALUE    (65535U)
#define CRC_16_XOR_OUT    (0U)
#define CRC_16_TABLE_MODE    STD_ON
#define CRC_16_TABLE_SIZE    (256U)
#define CRC_32_MODE    STD_ON
#define CRC_32_POLYNOMIAL    (79764919U)
#define CRC_32_INITIAL_VALUE    (4294967295U)
#define CRC_32_XOR_OUT    (4294967295U)
#define CRC_32_TABLE_MODE    STD_ON
#define CRC_32_TABLE_SIZE    (256U)


/*==================================================================================================
*  NON-MACRO SEGMENT (preserved from handwritten header, merged by codegen splice)
*  typedef(0) + struct(1) + extern config tables(1) — 依赖宏段计数宏, 故置于宏段之后
*================================================================================================*/
typedef struct {
    boolean Crc8_Enabled;
    boolean Crc16_Enabled;
    boolean Crc32_Enabled;
    uint8 Crc8_Polynomial;
    uint16 Crc16_Polynomial;
    uint32 Crc32_Polynomial;
    uint8 Crc8_InitValue;
    uint16 Crc16_InitValue;
    uint32 Crc32_InitValue;
} Crc_ConfigType;

/*==================================================================================================
 * EXTERN CONFIGURATION
 ==================================================================================================*/
extern const Crc_ConfigType Crc_Config;
#endif /* CRC_CFG_H */

/*==================[end of file]===========================================*/
