/**
 * @file Icu_Cfg.h
 * @brief Icu Configuration configuration header
 * @version 1.0.0
 * @date 2026-08-10
 * @note AUTO-GENERATED by yuleASR Configurator
 */

#ifndef ICU_CFG_H
#define ICU_CFG_H

/*==================================================================================================
*                                    PRE-COMPILE CONFIGURATION
*================================================================================================*/

/*==================================================================================================
*                                    General Configuration
*================================================================================================*/
#define ICU_DEV_ERROR_DETECT    STD_ON
#define ICU_VERSION_INFO_API    STD_ON

/*==================================================================================================
*                                    Module Configuration Counts
*================================================================================================*/
#define ICU_EDGE_COUNT_API    STD_ON
#define ICU_NUM_CHANNELS    (8U)
#define ICU_MAX_EDGE_COUNT    (65535U)

/*==================================================================================================
*                                    Timing Configuration
*================================================================================================*/
#define ICU_MAIN_FUNCTION_PERIOD_MS    (1U)

/*==================================================================================================
*                                    Other Configuration
*================================================================================================*/
#define ICU_DE_INIT_API    STD_ON
#define ICU_SET_MODE_API    STD_ON
#define ICU_DISABLE_WAKEUP_API    STD_ON
#define ICU_ENABLE_WAKEUP_API    STD_ON
#define ICU_CHECK_WAKEUP_API    STD_ON
#define ICU_TIMESTAMP_API    STD_ON
#define ICU_SIGNAL_MEASUREMENT_API    STD_ON
#define ICU_WAKEUP_FUNCTIONALITY_API    STD_OFF
#define ICU_REPORT_WAKEUP_SOURCE    STD_OFF
#define ICU_CHANNEL_0    (0U)
#define ICU_CHANNEL_1    (1U)
#define ICU_CHANNEL_2    (2U)
#define ICU_CHANNEL_3    (3U)
#define ICU_CHANNEL_4    (4U)
#define ICU_CHANNEL_5    (5U)
#define ICU_CHANNEL_6    (6U)
#define ICU_CHANNEL_7    (7U)
#define ICU_DEFAULT_MODE    ICU_MODE_NORMAL
#define ICU_DEFAULT_ACTIVATION    ICU_RISING_EDGE
#define ICU_CLOCK_FREQUENCY_HZ    (24000000U)
#define ICU_EMIOS_0_BASE_ADDR    (1073922048U)
#define ICU_EMIOS_1_BASE_ADDR    (1073926144U)
#define ICU_TIMESTAMP_BUFFER_SIZE    (256U)
#define ICU_DEFAULT_BUFFER_SIZE    (16U)
#define ICU_TPM1_BASE_ADDR    (1073979392U)
#define ICU_TPM2_BASE_ADDR    (1073983488U)
#define ICU_TPM3_BASE_ADDR    (1073987584U)
#define ICU_TPM4_BASE_ADDR    (1073991680U)
/*==================================================================================================
*                                    CONDITIONAL INCLUDES
*================================================================================================*/
#ifdef S32K312
#include "S32K312.h"
#endif


#endif /* ICU_CFG_H */

/*==================[end of file]===========================================*/
