/**
 * @file Csm_Cfg.h
 * @brief Csm Configuration configuration header
 * @version 1.0.0
 * @date 2026-08-10
 * @note AUTO-GENERATED by yuleASR Configurator
 */

#ifndef CSM_CFG_H
#define CSM_CFG_H

#include "Std_Types.h"   /* 非宏段依赖 Std_Types 基础类型 (uint32/uint8/uint16/boolean 等)，生成宏段不含此 include */
#include "Csm_Types.h"

#include "Std_Types.h"
#include "Csm_Types.h"

/*==================================================================================================
*                                    PRE-COMPILE CONFIGURATION
*================================================================================================*/

/*==================================================================================================
*                                    General Configuration
*================================================================================================*/
#ifndef CSM_CFG_DEV_ERROR_DETECT
#define CSM_CFG_DEV_ERROR_DETECT    STD_ON
#endif
#define CSM_CFG_VERSION_INFO_API    STD_ON

/*==================================================================================================
*                                    Timing Configuration
*================================================================================================*/
#define CSM_CFG_SERVICE_TIMEOUT_MS    (1000U)
#define CSM_CFG_MAIN_FUNCTION_PERIOD_MS    (10U)
#define CSM_DEM_SERVICE_TIMEOUT_EVENT_ID    (3U)

/*==================================================================================================
*                                    Other Configuration
*================================================================================================*/
#define CSM_CFG_VENDOR_ID    (43U)
#define CSM_CFG_AR_RELEASE_MAJOR_VERSION    (4U)
#define CSM_CFG_AR_RELEASE_MINOR_VERSION    (7U)
#define CSM_CFG_AR_RELEASE_REVISION_VERSION    (0U)
#define CSM_CFG_SW_MAJOR_VERSION    (1U)
#define CSM_CFG_SW_MINOR_VERSION    (0U)
#define CSM_CFG_SW_PATCH_VERSION    (0U)
#define CSM_CFG_ASYNC_SUPPORT    STD_ON
#define CSM_CFG_QUEUE_SUPPORT    STD_ON
#define CSM_CFG_KEY_PERSISTENCE_SUPPORT    STD_ON
#define CSM_CFG_RANDOM_GENERATOR_SUPPORT    STD_ON
#define CSM_CFG_DEM_INTEGRATION    STD_ON
#define CSM_KEY_ID_NONE    (4294967295U)
#define CSM_KEY_ID_MASTER    (1U)
#define CSM_KEY_ID_SESSION    (2U)
#define CSM_KEY_ID_STORAGE    (3U)
#define CSM_KEY_ID_DIAGNOSTIC    (4U)
#define CSM_KEY_ID_SECURE_BOOT    (5U)
#define CSM_KEY_ID_COMMUNICATION    (6U)
#define CSM_KEY_ID_DEBUG    (7U)
#define CSM_KEY_ELEMENT_ID_SECRET    (1U)
#define CSM_KEY_ELEMENT_ID_PUBLIC    (2U)
#define CSM_KEY_ELEMENT_ID_PRIVATE    (3U)
#define CSM_KEY_ELEMENT_ID_IV    (4U)
#define CSM_KEY_ELEMENT_ID_SALT    (5U)
#define CSM_KEY_ELEMENT_ID_SEED    (6U)
#define CSM_JOB_ID_NONE    (4294967295U)
#define CSM_JOB_ID_HASH_DEFAULT    (1U)
#define CSM_JOB_ID_ENCRYPT_DEFAULT    (2U)
#define CSM_JOB_ID_DECRYPT_DEFAULT    (3U)
#define CSM_JOB_ID_MAC_GENERATE_DEFAULT    (4U)
#define CSM_JOB_ID_MAC_VERIFY_DEFAULT    (5U)
#define CSM_JOB_ID_SIGN_DEFAULT    (6U)
#define CSM_JOB_ID_VERIFY_DEFAULT    (7U)
#define CSM_JOB_ID_RANDOM_DEFAULT    (8U)
#define CSM_CFG_DEFAULT_HASH_ALGORITHM    CSM_ALGOFAM_SHA2_256
#define CSM_CFG_DEFAULT_CIPHER_ALGORITHM    CSM_ALGOFAM_AES
#define CSM_CFG_DEFAULT_CIPHER_MODE    CSM_ALGOMODE_CBC
#define CSM_CFG_DEFAULT_CIPHER_KEY_LENGTH    (128U)
#define CSM_CFG_DEFAULT_MAC_ALGORITHM    CSM_ALGOFAM_HMAC
#define CSM_CFG_DEFAULT_MAC_HASH_ALGORITHM    CSM_ALGOFAM_SHA2_256
#define CSM_CFG_DEFAULT_SIGNATURE_ALGORITHM    CSM_ALGOFAM_ECDSA
#define CSM_CFG_DEFAULT_SIGNATURE_KEY_LENGTH    (256U)
#define CSM_CFG_QUEUE_SIZE    CSM_MAX_QUEUE_DEPTH
#define CSM_CFG_MAX_CONCURRENT_JOBS    (4U)
#define CSM_DEM_HARDWARE_FAILURE_EVENT_ID    (1U)
#define CSM_DEM_KEY_INVALID_EVENT_ID    (2U)
#define CSM_DEM_ENTROPY_EXHAUSTION_EVENT_ID    (4U)


/*==================================================================================================
*  NON-MACRO SEGMENT (preserved from handwritten header, merged by codegen splice)
*  typedef(0) + struct(0) + extern config tables(6) — 依赖宏段计数宏, 故置于宏段之后
*================================================================================================*/
extern Std_ReturnType Csm_Cfg_KeyWrite(
    uint32 keyId,
    uint32 elementId,
    const uint8* data,
    uint32 length
);

/**
 * @brief 密钥读取函数
 * 
 * 用于从持久化存储读取密钥
 * 
 * @param keyId 密钥ID
 * @param elementId 元素ID
 * @param data 数据缓冲区
 * @param length 长度指针 (输入/输出)
 * @return E_OK: 成功, E_NOT_OK: 失败
 */
extern Std_ReturnType Csm_Cfg_KeyRead(
    uint32 keyId,
    uint32 elementId,
    uint8* data,
    uint32* length
);

/**
 * @brief 硬件加密服务函数
 * 
 * 实际加密操作由硬件完成
 * 
 * @param jobId 作业ID
 * @param serviceType 服务类型
 * @param input 输入数据
 * @param inputLength 输入长度
 * @param output 输出缓冲区
 * @param outputLength 输出长度指针
 * @return E_OK: 成功, E_NOT_OK: 失败, E_BUSY: 忙碌
 */
extern Std_ReturnType Csm_Cfg_HwService(
    uint32 jobId,
    Csm_ServiceType serviceType,
    const uint8* input,
    uint32 inputLength,
    uint8* output,
    uint32* outputLength
);

/**
 * @brief 随机数生成函数
 * 
 * @param data 输出缓冲区
 * @param length 需要的长度
 * @return E_OK: 成功, E_NOT_OK: 失败
 */
extern Std_ReturnType Csm_Cfg_RandomGenerate(
    uint8* data,
    uint32 length
);

/**
 * @brief 获取当前时间戳
 * 
 * @return 时间戳 (ms)
 */
extern uint32 Csm_Cfg_GetTimestamp(void);

#define CSM_STOP_SEC_CODE
#include "Csm_MemMap.h"

/*==================================================================================================
*                                       外部变量声明
==================================================================================================*/
#define CSM_START_SEC_CONFIG_DATA_UNSPECIFIED
#include "Csm_MemMap.h"

/**
 * @brief 默认配置
 */
extern const Csm_ConfigType Csm_Config;

#define CSM_STOP_SEC_CONFIG_DATA_UNSPECIFIED
#include "Csm_MemMap.h"
#endif /* CSM_CFG_H */

/*==================[end of file]===========================================*/
