/**
 * @file Os_Cfg.h
 * @brief Os Configuration configuration header
 * @version 1.0.0
 * @date 2026-08-10
 * @note AUTO-GENERATED by yuleASR Configurator
 */

#ifndef OS_CFG_H
#define OS_CFG_H

#include "Std_Types.h"

/*==================================================================================================
*                                    PRE-COMPILE CONFIGURATION
*================================================================================================*/

/*==================================================================================================
*                                    General Configuration
*================================================================================================*/
#define OS_CFG_DEV_ERROR_DETECT    STD_ON

/*==================================================================================================
*                                    Module Configuration Counts
*================================================================================================*/
#define OS_CFG_NUM_TASKS    (8U)
#ifndef OS_TASK_COUNT
#define OS_TASK_COUNT    (8U)
#endif
#ifndef OS_RESOURCE_COUNT
#define OS_RESOURCE_COUNT    (0U)
#endif
#define OS_CFG_NUM_ALARMS    (6U)
#define OS_CFG_NUM_RESOURCES    (4U)
#define OS_CFG_MAIN_COUNTER_TICKS_PER_MS    (1U)
#define OS_CFG_MAIN_COUNTER_MAX_ALLOWED    (4294967295U)
#define OS_CFG_MAIN_COUNTER_MIN_CYCLE    (1U)

/*==================================================================================================
*                                    Controller Definitions
*================================================================================================*/
#define OsRes_CanController    (0U)

/*==================================================================================================
*                                    Hardware Object Handles
*================================================================================================*/
#define OsTask_ComMainFunctionRx    (5U)
#define OsTask_ComMainFunctionTx    (6U)

/*==================================================================================================
*                                    Timing Configuration
*================================================================================================*/
#define OS_ALARM_PERIOD_10MS    (10U)
#define OS_ALARM_PERIOD_50MS    (50U)
#define OS_ALARM_PERIOD_100MS    (100U)

/*==================================================================================================
*                                    Other Configuration
*================================================================================================*/
#define OS_CFG_USE_GET_SERVICE_ID    STD_ON
#define OS_CFG_USE_PARAMETER_ACCESS    STD_ON
#define OS_CFG_PROTECTION_HOOK    STD_OFF
#define OS_CFG_STACK_MONITORING    STD_ON
#define OS_CFG_STARTUP_HOOK    STD_ON
#define OS_CFG_SHUTDOWN_HOOK    STD_ON
#define OS_CFG_ERROR_HOOK    STD_ON
#define OS_CFG_PRETASK_HOOK    STD_OFF
#define OS_CFG_POSTTASK_HOOK    STD_OFF
#define OsTask_Init    (0U)
#define OsTask_10ms    (1U)
#define OsTask_50ms    (2U)
#define OsTask_100ms    (3U)
#define OsTask_Background    (4U)
#define OsTask_Diagnostic    (7U)
#define OS_TASK_PRIORITY_IDLE    (1U)
#define OS_TASK_PRIORITY_LOW    (2U)
#define OS_TASK_PRIORITY_NORMAL    (3U)
#define OS_TASK_PRIORITY_HIGH    (4U)
#define OS_TASK_PRIORITY_CRITICAL    (5U)
#define OsAlarm_BswM_MainFunction    (0U)
#define OsAlarm_Com_MainFunction    (1U)
#define OsAlarm_CanIf_MainFunction    (2U)
#define OsAlarm_Dcm_MainFunction    (3U)
#define OsAlarm_NvM_MainFunction    (4U)
#define OsAlarm_Dem_MainFunction    (5U)
#define OsRes_NvMBlock    (1U)
#define OsRes_ComBuffer    (2U)
#define OsRes_Diagnostic    (3U)
#define OS_EVENT_INIT_COMPLETE    (1U)
#define OS_EVENT_CAN_MESSAGE_RECEIVED    (2U)
#define OS_EVENT_NVM_WRITE_COMPLETE    (4U)
#define OS_EVENT_DIAGNOSTIC_REQUEST    (8U)
#define OS_EVENT_MODE_SWITCH    (16U)
#define OS_CFG_TASK_STACK_SIZE    (4096U)
#define OS_CFG_ISR_STACK_SIZE    (2048U)

#endif /* OS_CFG_H */

/*==================[end of file]===========================================*/
