/**
 * @file Os_TimingProtection_Cfg.h
 * @brief Os_TimingProtection Configuration configuration header
 * @version 1.0.0
 * @date 2026-08-10
 * @note AUTO-GENERATED by yuleASR Configurator
 */

#ifndef OS_TIMINGPROTECTION_CFG_H
#define OS_TIMINGPROTECTION_CFG_H

#include "Std_Types.h"   /* 非宏段依赖 Std_Types 基础类型 (uint32/uint8/uint16/boolean 等)，生成宏段不含此 include */
#include "Os.h"

#include "Os.h"

/*==================================================================================================
*                                    PRE-COMPILE CONFIGURATION
*================================================================================================*/

/*==================================================================================================
*                                    Module Configuration Counts
*================================================================================================*/
#ifndef OS_TASK_COUNT
#define OS_TASK_COUNT    (8U)
#endif
#ifndef OS_RESOURCE_COUNT
#define OS_RESOURCE_COUNT    (0U)
#endif

/*==================================================================================================
*                                    Processing Modes
*================================================================================================*/
#define OS_INTERRUPT_LOCK_PROTECTION    STD_ON

/*==================================================================================================
*                                    Other Configuration
*================================================================================================*/
#define OS_TIMING_PROTECTION_ENABLED    STD_ON
#define OS_EXECUTION_TIME_PROTECTION    STD_ON
#define OS_MAX_TASK_EXECUTION_TIME_MS    (100U)
#define OS_MAX_ISR_EXECUTION_TIME_MS    (50U)
#define OS_ARRIVAL_TIME_PROTECTION    STD_ON
#define OS_MAX_TASK_ARRIVAL_INTERVAL_MS    (10U)
#define OS_RESOURCE_LOCK_PROTECTION    STD_ON
#define OS_MAX_RESOURCE_LOCK_TIME_MS    (50U)
#define OS_MAX_ALL_INT_LOCK_TIME_MS    (10U)
#define OS_MAX_OS_INT_LOCK_TIME_MS    (50U)


/*==================================================================================================
*  NON-MACRO SEGMENT (preserved from handwritten header, merged by codegen splice)
*  typedef(1) + struct(3) + extern config tables(3) — 依赖宏段计数宏, 故置于宏段之后
*================================================================================================*/
typedef enum
{
    OS_TIMING_ACTION_NONE = 0,
    OS_TIMING_ACTION_TASK_KILL,
    OS_TIMING_ACTION_TASK_RESTART,
    OS_TIMING_ACTION_ERROR_HOOK,
    OS_TIMING_ACTION_PROTECTION_HOOK
} Os_TimingFaultActionType;

/* Timing Budget Configuration */
typedef struct
{
    TaskType                    TaskId;
    uint32                      ExecutionTimeBudget;    /* In microseconds */
    uint32                      ArrivalTimeMin;         /* Min interval in microseconds */
    Os_TimingFaultActionType    FaultAction;
} Os_TaskTimingBudgetType;

typedef struct
{
    ResourceType                ResourceId;
    uint32                      LockTimeBudget;         /* Max lock time in microseconds */
    Os_TimingFaultActionType    FaultAction;
} Os_ResourceTimingBudgetType;

typedef struct
{
    uint32                      AllIntLockBudget;
    uint32                      OsIntLockBudget;
    Os_TimingFaultActionType    FaultAction;
} Os_InterruptTimingBudgetType;

/* External configuration */
extern const Os_TaskTimingBudgetType Os_TaskTimingBudgets[OS_TASK_COUNT];
extern const Os_ResourceTimingBudgetType Os_ResourceTimingBudgets[OS_RESOURCE_COUNT];
extern const Os_InterruptTimingBudgetType Os_InterruptTimingBudget;
#endif /* OS_TIMINGPROTECTION_CFG_H */

/*==================[end of file]===========================================*/
