"""
DDS Code Generator
Generates C++ code for DDS entities
"""
from jinja2 import Template
from dds_models import DDSConfiguration, DDSDomain, DDSTopic

# Jinja2 template for C++ code generation
CPP_TEMPLATE = '''
// Auto-generated DDS Configuration
// Generated by yuleCommunity DDS Config Tool

#ifndef {{ config_name.upper() }}_DDS_CONFIG_HPP
#define {{ config_name.upper() }}_DDS_CONFIG_HPP

#include <dds/dds.hpp>

namespace {{ namespace }} {

{% for domain in domains %}
// Domain {{ domain.name }} (ID: {{ domain.domain_id }})
namespace domain_{{ domain.domain_id }} {
    
    {% for topic in domain.topics %}
    // Topic: {{ topic.name }}
    struct {{ topic.data_type }} {
        {% if topic.keyed %}
        // @key
        {% endif %}
        // Add your data members here
    };
    
    using {{ topic.name }}Topic = dds::topic::Topic<{{ topic.data_type }}>;
    using {{ topic.name }}Writer = dds::pub::DataWriter<{{ topic.data_type }}>;
    using {{ topic.name }}Reader = dds::sub::DataReader<{{ topic.data_type }}>;
    {% endfor %}
    
} // namespace domain_{{ domain.domain_id }}
{% endfor %}

class DDSApplication {
public:
    DDSApplication() = default;
    ~DDSApplication() = default;
    
    void initialize() {
        {% for domain in domains %}
        // Initialize Domain {{ domain.domain_id }}
        domain_{{ domain.domain_id }}_participant_ = 
            dds::domain::DomainParticipant({{ domain.domain_id }});
        
        {% for topic in domain.topics %}
        // Create Topic {{ topic.name }}
        domain_{{ domain.domain_id }}::{{ topic.name }}Topic 
            {{ topic.name.lower() }}_topic_(
                domain_{{ domain.domain_id }}_participant_, 
                "{{ topic.name }}"
            );
        {% endfor %}
        {% endfor %}
    }
    
private:
    {% for domain in domains %}
    dds::domain::DomainParticipant domain_{{ domain.domain_id }}_participant_;
    {% endfor %}
};

} // namespace {{ namespace }}

#endif // {{ config_name.upper() }}_DDS_CONFIG_HPP
'''

CMAKE_TEMPLATE = '''
# Auto-generated CMakeLists.txt
# Generated by yuleCommunity DDS Config Tool

cmake_minimum_required(VERSION 3.10)
project({{ project_name }} VERSION {{ version }})

set(CMAKE_CXX_STANDARD 14)
set(CMAKE_CXX_STANDARD_REQUIRED ON)

# Find DDS packages
find_package(CycloneDDS REQUIRED)

# Include directories
include_directories(${CMAKE_CURRENT_SOURCE_DIR})

# Generate IDL types
{% for domain in domains %}
{% for topic in domain.topics %}
idl_generate_cyclonedds({{ topic.data_type }} "{{ topic.data_type }}.idl")
{% endfor %}
{% endfor %}

# Add library
add_library(${PROJECT_NAME} SHARED
    {{ config_filename }}.hpp
)

target_link_libraries(${PROJECT_NAME}
    CycloneDDS::ddsc
)
'''

class DDSCodeGenerator:
    """Code generator for DDS configurations"""
    
    def __init__(self, config: DDSConfiguration):
        self.config = config
    
    def generate_cpp(self, namespace: str = "yule_dds") -> str:
        """Generate C++ header file"""
        template = Template(CPP_TEMPLATE)
        return template.render(
            config_name=self.config.name,
            namespace=namespace,
            domains=self.config.domains
        )
    
    def generate_cmake(self, project_name: str = None) -> str:
        """Generate CMakeLists.txt"""
        if not project_name:
            project_name = f"{self.config.name}_dds"
        
        template = Template(CMAKE_TEMPLATE)
        return template.render(
            project_name=project_name,
            version=self.config.version,
            domains=self.config.domains,
            config_filename=self.config.name.lower()
        )
    
    def generate_idl(self, topic: DDSTopic) -> str:
        """Generate IDL for a topic"""
        idl = f"""
// IDL definition for {topic.name}
struct {topic.data_type} {{
    {'// @key' if topic.keyed else ''}
    // TODO: Add data members
}};
"""
        return idl
    
    def generate_qos_xml(self) -> str:
        """Generate DDS QoS XML profile"""
        xml = '''<?xml version="1.0" encoding="UTF-8"?>
<dds xmlns="http://www.omg.org/dds/">
  <qos_library name="{{ config_name }}_library">
    {% for domain in domains %}
    {% for topic in domain.topics %}
    <qos_profile name="{{ topic.name }}_profile">
      <topic_qos>
        <reliability>
          <kind>{{ topic.qos.reliability.kind.value }}</kind>
        </reliability>
        <durability>
          <kind>{{ topic.qos.durability.kind.value }}</kind>
        </durability>
        <history>
          <kind>{{ topic.qos.history.kind.value }}</kind>
          <depth>{{ topic.qos.history.depth }}</depth>
        </history>
      </topic_qos>
    </qos_profile>
    {% endfor %}
    {% endfor %}
  </qos_library>
</dds>
'''
        template = Template(xml)
        return template.render(
            config_name=self.config.name,
            domains=self.config.domains
        )
    
    def save_all(self, output_dir: str):
        """Save all generated files"""
        import os
        
        os.makedirs(output_dir, exist_ok=True)
        
        # Save C++ header
        cpp_file = os.path.join(output_dir, f"{self.config.name.lower()}_dds.hpp")
        with open(cpp_file, 'w') as f:
            f.write(self.generate_cpp())
        
        # Save CMakeLists.txt
        cmake_file = os.path.join(output_dir, "CMakeLists.txt")
        with open(cmake_file, 'w') as f:
            f.write(self.generate_cmake())
        
        # Save QoS XML
        qos_file = os.path.join(output_dir, "qos_profiles.xml")
        with open(qos_file, 'w') as f:
            f.write(self.generate_qos_xml())
        
        # Generate IDL files for each topic
        for domain in self.config.domains:
            for topic in domain.topics:
                idl_file = os.path.join(output_dir, f"{topic.data_type}.idl")
                with open(idl_file, 'w') as f:
                    f.write(self.generate_idl(topic))
        
        return output_dir
