/**
 * @file CanIf_Cfg.h
 * @brief CAN Interface Configuration Template - AutoSAR BSW
 * @version 1.0.0
 * @date 2026-04-22
 * @author ConfigGenerator
 *
 * @note This file is generated by the ConfigGenerator tool.
 *       Manual changes may be overwritten.
 */

#ifndef CANIF_CFG_H
#define CANIF_CFG_H

#include "Std_Types.h"

/*==================================================================================================
*                                    PRE-COMPILE CONFIGURATION
==================================================================================================*/
#define CANIF_DEV_ERROR_DETECT          (STD_ON)
#define CANIF_VERSION_INFO_API          (STD_ON)
#define CANIF_DLC_CHECK                 (STD_ON)
#define CANIF_SOFTWARE_FILTER           (STD_ON)
#define CANIF_READRXPDU_DATA_API        (STD_ON)
#define CANIF_READTXPDU_NOTIFY_STATUS_API (STD_OFF)
#define CANIF_READRXPDU_NOTIFY_STATUS_API (STD_OFF)

/*==================================================================================================
*                                    CONTROLLER CONFIGURATION
==================================================================================================*/
#define CANIF_NUM_CONTROLLERS           (2U)
#define CANIF_NUM_HRH                   (4U)
#define CANIF_NUM_HTH                   (4U)
#define CANIF_NUM_TX_PDUS               (16U)
#define CANIF_NUM_RX_PDUS               (16U)

/*==================================================================================================
*                                    CONTROLLER IDs
==================================================================================================*/
#define CANIF_CONTROLLER_0              (0U)
#define CANIF_CONTROLLER_1              (1U)

/*==================================================================================================
*                                    BAUDRATE CONFIGURATION
==================================================================================================*/
#define CANIF_DEFAULT_BAUDRATE          (500000U)
#define CANIF_DEFAULT_BAUDRATE_CONFIG   (0U)

/*==================================================================================================
*                                    CAN ID TYPE
==================================================================================================*/
typedef uint8 CanIf_CanIdTypeType;

#define CANIF_CANID_TYPE_STANDARD       (0U)
#define CANIF_CANID_TYPE_EXTENDED       (1U)
#define CANIF_CANID_TYPE_MIXED          (2U)

/*==================================================================================================
*                                    PDU MODE
==================================================================================================*/
#define CANIF_PDU_MODE_OFFLINE          (0U)
#define CANIF_PDU_MODE_TX_OFFLINE       (1U)
#define CANIF_PDU_MODE_TX_OFFLINE_ACTIVE (2U)
#define CANIF_PDU_MODE_ONLINE           (3U)

/*==================================================================================================
*                                    CONTROLLER MODE
==================================================================================================*/
#define CANIF_CS_UNINIT                 (0U)
#define CANIF_CS_SLEEP                  (1U)
#define CANIF_CS_STARTED                (2U)
#define CANIF_CS_STOPPED                (3U)

/*==================================================================================================
*                                    TRANSCEIVER MODE
==================================================================================================*/
#define CANIF_TRCV_MODE_NORMAL          (0U)
#define CANIF_TRCV_MODE_STANDBY         (1U)
#define CANIF_TRCV_MODE_SLEEP           (2U)

/*==================================================================================================
*                                    WAKEUP REASON
==================================================================================================*/
#define CANIF_TRCV_WU_ERROR             (0U)
#define CANIF_TRCV_WU_BY_BUS            (1U)
#define CANIF_TRCV_WU_BY_PIN            (2U)
#define CANIF_TRCV_WU_INTERNALLY        (3U)
#define CANIF_TRCV_WU_NOT_SUPPORTED     (4U)
#define CANIF_TRCV_WU_POWER_ON          (5U)
#define CANIF_TRCV_WU_RESET             (6U)
#define CANIF_TRCV_WU_BY_SYSERR         (7U)

/*==================================================================================================
*                                    TX PDU IDs
==================================================================================================*/
#define CANIF_TXPDU_ENGINE_STATUS       ((PduIdType)0U)
#define CANIF_TXPDU_VEHICLE_SPEED       ((PduIdType)1U)
#define CANIF_TXPDU_BATTERY_STATUS      ((PduIdType)2U)
#define CANIF_TXPDU_DIAG_RESPONSE       ((PduIdType)3U)

/*==================================================================================================
*                                    RX PDU IDs
==================================================================================================*/
#define CANIF_RXPDU_ENGINE_CMD          ((PduIdType)0U)
#define CANIF_RXPDU_VEHICLE_CMD         ((PduIdType)1U)
#define CANIF_RXPDU_DIAG_REQUEST        ((PduIdType)2U)

#endif /* CANIF_CFG_H */
