/**
 * @file Dlt_Cfg.h
 * @brief Dlt_Ecual Configuration configuration header
 * @version 1.0.0
 * @date 2026-08-10
 * @note AUTO-GENERATED by yuleASR Configurator
 */

#ifndef DLT_CFG_H
#define DLT_CFG_H

#include "Std_Types.h"

/*==================================================================================================
*                                    PRE-COMPILE CONFIGURATION
*================================================================================================*/

/*==================================================================================================
*                                    General Configuration
*================================================================================================*/
#define DLT_VERSION_INFO_API    STD_ON
#define DLT_DEV_ERROR_DETECT    STD_ON
#define DLT_SID_GET_VERSION_INFO    (7U)

/*==================================================================================================
*                                    Module Configuration Counts
*================================================================================================*/
#define DLT_BUFFER_COUNT    (4U)
#define DLT_MAX_MESSAGE_COUNT    (256U)
#define DLT_MAX_CONTEXT_COUNT    (32U)

/*==================================================================================================
*                                    Timing Configuration
*================================================================================================*/
#define DLT_BUFFERING_TIMEOUT    (1000U)
#define DLT_MAIN_FUNCTION_PERIOD    (10U)

/*==================================================================================================
*                                    Other Configuration
*================================================================================================*/
#define DLT_CFG_AR_MAJOR_VERSION    (4U)
#define DLT_CFG_AR_MINOR_VERSION    (4U)
#define DLT_CFG_AR_PATCH_VERSION    (0U)
#define DLT_CFG_VENDOR_ID    (1U)
#define DLT_MODULE_ID    (210U)
#define DLT_USE_COM    STD_ON
#define DLT_USE_VERBOSE_MODE    STD_ON
#define DLT_USE_LOG_LEVEL_FILTER    STD_ON
#define DLT_USE_TRACE_STATUS    STD_ON
#define DLT_USE_BUFFERING    STD_ON
#define DLT_PROTOCOL_VERSION_MAJOR    (1U)
#define DLT_PROTOCOL_VERSION_MINOR    (0U)
#define DLT_MAX_MESSAGE_LENGTH    (4096U)
#define DLT_MAX_CONTEXT_DESCRIPTION    (32U)
#define DLT_MAX_APP_DESCRIPTION    (32U)
#define DLT_BUFFER_SIZE    (2048U)
#define DLT_MAX_CONTEXT_ID_LENGTH    (4U)
#define DLT_MAX_APP_ID_LENGTH    (4U)
#define DLT_DEFAULT_LOG_LEVEL    DLT_LOG_INFO
#define DLT_DEFAULT_TRACE_STATUS    DLT_TRACE_STATUS_ON
#define DLT_ECU_ID    "ECU1"
#define DLT_ECU_ID_LENGTH    (4U)
#define DLT_DEFAULT_SESSION_ID    (1U)
#define DLT_E_NO_ERROR    (0U)
#define DLT_E_NOT_INITIALIZED    (1U)
#define DLT_E_NULL_POINTER    (2U)
#define DLT_E_INVALID_PARAMETER    (3U)
#define DLT_E_CONTEXT_FULL    (4U)
#define DLT_E_CONTEXT_NOT_FOUND    (5U)
#define DLT_E_BUFFER_FULL    (6U)
#define DLT_E_COM_FAILURE    (7U)
#define DLT_SID_INIT    (1U)
#define DLT_SID_DEINIT    (2U)
#define DLT_SID_SEND_LOG_MESSAGE    (3U)
#define DLT_SID_SEND_TRACE_MESSAGE    (4U)
#define DLT_SID_REGISTER_CONTEXT    (5U)
#define DLT_SID_UNREGISTER_CONTEXT    (6U)
#define DLT_SID_SET_LOG_LEVEL    (8U)
#define DLT_SID_GET_LOG_LEVEL    (9U)
#define DLT_SID_SET_TRACE_STATUS    (10U)
#define DLT_SID_GET_TRACE_STATUS    (11U)
#define DLT_SID_MAIN_FUNCTION    (128U)

#endif /* DLT_CFG_H */

/*==================[end of file]===========================================*/
