/**
 * @file CanTSyn_Cfg.h
 * @brief CanTSyn Configuration configuration header
 * @version 1.0.0
 * @date 2026-08-10
 * @note AUTO-GENERATED by yuleASR Configurator
 */

#ifndef CANTSYN_CFG_H
#define CANTSYN_CFG_H

#include "Std_Types.h"

/*==================================================================================================
*                                    PRE-COMPILE CONFIGURATION
*================================================================================================*/

/*==================================================================================================
*                                    General Configuration
*================================================================================================*/
#define CANTSYN_DEV_ERROR_DETECT    STD_ON
#define CANTSYN_VERSION_INFO_API    STD_ON

/*==================================================================================================
*                                    Module Configuration Counts
*================================================================================================*/
#define CANTSYN_DEBOUNCE_COUNTER    STD_ON
#define CANTSYN_MESSAGE_COUNTER_SUPPORT    STD_ON
#define CANTSYN_SEQUENCE_COUNTER_SUPPORT    STD_ON
#define CANTSYN_NUM_TIME_DOMAINS    (2U)
#define CANTSYN_NUM_INSTANCES    (1U)

/*==================================================================================================
*                                    Hardware Object Handles
*================================================================================================*/
#define CANTSYN_CANCEL_TX_CONFIRMATION    STD_OFF
#define CANTSYN_TX_CONFIRMATION    STD_ON
#define CANTSYN_RX_INDICATION    STD_ON

/*==================================================================================================
*                                    Timing Configuration
*================================================================================================*/
#define CANTSYN_SYNC_PERIOD_MS    (10U)
#define CANTSYN_SYNC_TIMEOUT_MS    (100U)
#define CANTSYN_MAIN_FUNCTION_PERIOD_MS    (1U)

/*==================================================================================================
*                                    Other Configuration
*================================================================================================*/
#define CANTSYN_CFG_VENDOR_ID    (1U)
#define CANTSYN_CFG_MODULE_ID    (164U)
#define CANTSYN_CFG_INSTANCE_ID    (0U)
#define CANTSYN_CFG_AR_RELEASE_MAJOR_VERSION    (34U)
#define CANTSYN_CFG_AR_RELEASE_MINOR_VERSION    (17U)
#define CANTSYN_CFG_AR_RELEASE_REVISION_VERSION    (0U)
#define CANTSYN_CFG_SW_MAJOR_VERSION    (4U)
#define CANTSYN_CFG_SW_MINOR_VERSION    (7U)
#define CANTSYN_CFG_SW_PATCH_VERSION    (0U)
#define CANTSYN_TIME_MASTER_SUPPORT    STD_ON
#define CANTSYN_TIME_SLAVE_SUPPORT    STD_ON
#define CANTSYN_IMMEDIATE_TIME_TRANSMISSION    STD_OFF
#define CANTSYN_GLOBAL_TIME_SUPPORT    STD_ON
#define CANTSYN_CRC_SECURED    STD_OFF
#define CANTSYN_TLV_SUPPORT    STD_ON
#define CANTSYN_USER_DATA_SUPPORT    STD_ON
#define CANTSYN_RATE_CORRECTION_SUPPORT    STD_ON
#define CANTSYN_OFFSET_CORRECTION_SUPPORT    STD_ON
#define CANTSYN_MAX_TIME_BASES    (4U)
#define CANTSYN_MAX_TIME_MASTERS    (2U)
#define CANTSYN_MAX_TIME_SLAVES    (2U)
#define CANTSYN_FUP_DELAY_US    (100U)
#define CANTSYN_SYNC_CYCLE_TIME    (10U)
#define CANTSYN_MAX_TIME_JUMP_US    (1000000U)
#define CANTSYN_DEBOUNCE_TIME_MS    (5U)
#define CANTSYN_SYNC_LOST_THRESHOLD    (10U)
#define CANTSYN_SYNC_CAN_ID_BASE    (384U)
#define CANTSYN_FUP_CAN_ID_BASE    (640U)
#define CANTSYN_OCS_CAN_ID_BASE    (896U)
#define CANTSYN_SYNC_DLC    (8U)
#define CANTSYN_FUP_DLC    (8U)
#define CANTSYN_OCS_DLC    (8U)
#define CANTSYN_EXTENDED_CAN_ID    STD_OFF
#define CANTSYN_PROTOCOL_VERSION    (2U)
#define CANTSYN_TIME_REPRESENTATION    (0U)
#define CANTSYN_SGW_SUPPORT    STD_ON
#define CANTSYN_OFS_SUPPORT    STD_ON
#define CANTSYN_TIME_NOTIFICATION    STD_ON
#define CANTSYN_SYNC_LOSS_NOTIFICATION    STD_ON
#define CANTSYN_INSTANCE_ID    (0U)
#define CANTSYN_TICKS_PER_SYNC    (CANTSYN_SYNC_PERIOD_MS / CANTSYN_MAIN_FUNCTION_PERIOD_MS)
#define CANTSYN_TIMEBASE_GLOBAL_ID    (0U)
#define CANTSYN_TIMEBASE_OFFSET_ID    (1U)
#define CANTSYN_TIMEBASE_LOCAL_ID    (2U)
#define CANTSYN_NUMBER_OF_TIME_DOMAINS    (2U)
#define CANTSYN_NUMBER_OF_PDUS    (2U)
#define CANTSYN_NUMBER_OF_TIME_BASES    (4U)
#define CANTSYN_E_INVALID_PDU_SDU_ID    (1U)

#endif /* CANTSYN_CFG_H */

/*==================[end of file]===========================================*/
