/**
 * @file MemIf_Cfg.h
 * @brief MemIf_Ecual Configuration configuration header
 * @version 1.0.0
 * @date 2026-08-10
 * @note AUTO-GENERATED by yuleASR Configurator
 */

#ifndef MEMIF_CFG_H
#define MEMIF_CFG_H

/*==================================================================================================
*                                    PRE-COMPILE CONFIGURATION
*================================================================================================*/

/*==================================================================================================
*                                    General Configuration
*================================================================================================*/
#define MEMIF_DEV_ERROR_DETECT    STD_ON
#define MEMIF_VERSION_INFO_API    STD_ON
#define MEMIF_NUM_DEVICES    (2U)
#define MEMIF_DEVICE_0    (0U)
#define MEMIF_DEVICE_1    (1U)
#define MEMIF_DEVICE_0_DRIVER    (1U)
#define MEMIF_DEVICE_0_UNDERLYING_ID    (0U)
#define MEMIF_DEVICE_0_TOTAL_SIZE    (1048576U)
#define MEMIF_DEVICE_0_BLOCK_SIZE    (256U)
#define MEMIF_DEVICE_1_DRIVER    (0U)
#define MEMIF_DEVICE_1_UNDERLYING_ID    (0U)
#define MEMIF_DEVICE_1_TOTAL_SIZE    (32768U)
#define MEMIF_DEVICE_1_BLOCK_SIZE    (64U)

/*==================================================================================================
*                                    Other Configuration
*================================================================================================*/
#define MEMIF_UNDERLYING_EEP    (0U)
#define MEMIF_UNDERLYING_FEE    (1U)
#define MEMIF_UNDERLYING_EA    (2U)
#define MEMIF_DEFAULT_MODE    MEMIF_MODE_FAST
#define MEMIF_MAX_BLOCK_NUMBER    (256U)
#define MEMIF_MAX_BLOCK_SIZE    (4096U)

#endif /* MEMIF_CFG_H */

/*==================[end of file]===========================================*/
