/**
 * @file E2E_Cfg.h
 * @brief E2E Configuration configuration header
 * @version 1.0.0
 * @date 2026-08-10
 * @note AUTO-GENERATED by yuleASR Configurator
 */

#ifndef E2E_CFG_H
#define E2E_CFG_H

/*==================================================================================================
*                                    PRE-COMPILE CONFIGURATION
*================================================================================================*/

/*==================================================================================================
*                                    General Configuration
*================================================================================================*/
#define E2E_DEV_ERROR_DETECT    STD_ON
#define E2E_VERSION_INFO_API    STD_ON

/*==================================================================================================
*                                    Module Configuration Counts
*================================================================================================*/
#define E2E_SM_MIN_OK_COUNT    (2U)

/*==================================================================================================
*                                    Other Configuration
*================================================================================================*/
#define E2E_PROFILE_01_ENABLED    STD_ON
#define E2E_PROFILE_02_ENABLED    STD_ON
#define E2E_PROFILE_04_ENABLED    STD_ON
#define E2E_PROFILE_05_ENABLED    STD_ON
#define E2E_PROFILE_06_ENABLED    STD_ON
#define E2E_PROFILE_07_ENABLED    STD_ON
#define E2E_USE_CRC_HARDWARE    STD_OFF
#define E2E_USE_CRC_SOFTWARE    STD_ON
#define E2E_CRC_TABLE_OPTIMIZED    STD_ON
#define E2E_MAX_DATA_LENGTH_P01    (30U)
#define E2E_MAX_DATA_LENGTH_P02    (256U)
#define E2E_MAX_DATA_LENGTH_P04    (4096U)
#define E2E_MAX_DATA_LENGTH_P05    (4096U)
#define E2E_MAX_DATA_LENGTH_P06    (4096U)
#define E2E_MAX_DATA_LENGTH_P07    (4096U)
#define E2E_SM_MAX_ERROR_WINDOW    (15U)
#define E2E_SM_MAX_SYNC_STEPS    (2U)

#endif /* E2E_CFG_H */

/*==================[end of file]===========================================*/
