/**
 * @file CanSm_Cfg.h
 * @brief CanSm Configuration configuration header
 * @version 1.0.0
 * @date 2026-08-10
 * @note AUTO-GENERATED by yuleASR Configurator
 */

#ifndef CANSM_CFG_H
#define CANSM_CFG_H

/*==================================================================================================
*                                    PRE-COMPILE CONFIGURATION
*================================================================================================*/

/*==================================================================================================
*                                    General Configuration
*================================================================================================*/
#define CANSM_DEV_ERROR_DETECT    STD_ON
#define CANSM_VERSION_INFO_API    STD_ON

/*==================================================================================================
*                                    Module Configuration Counts
*================================================================================================*/
#define CANSM_NUM_NETWORKS    (2U)

/*==================================================================================================
*                                    Baudrate Configurations
*================================================================================================*/
#define CANSM_SET_BAUDRATE_API    STD_ON
#define CANSM_GET_BAUDRATE_API    STD_ON
#define CANSM_BAUDRATE_125K    (125U)
#define CANSM_BAUDRATE_250K    (250U)
#define CANSM_BAUDRATE_500K    (500U)
#define CANSM_BAUDRATE_1000K    (1000U)
#define CANSM_DEFAULT_BAUDRATE    (500U)

/*==================================================================================================
*                                    Controller Definitions
*================================================================================================*/
#define CANSM_CONTROLLER_CAN0    (0U)
#define CANSM_CONTROLLER_CAN1    (1U)

/*==================================================================================================
*                                    Timing Configuration
*================================================================================================*/
#define CANSM_MODE_CHANGE_REQUEST_TIMEOUT_MS    (100U)
#define CANSM_NETWORK0_MAIN_FUNCTION_PERIOD_MS    (10U)
#define CANSM_NETWORK1_MAIN_FUNCTION_PERIOD_MS    (10U)

/*==================================================================================================
*                                    Other Configuration
*================================================================================================*/
#define CANSM_BUSOFF_CHECK_ENABLED    STD_ON
#define CANSM_TRANSCEIVER_SUPPORT    STD_ON
#define CANSM_WAKEUP_VALIDATION_ENABLED    STD_ON
#define CANSM_BUSOFF_RECOVERY_L1_MS    (100U)
#define CANSM_BUSOFF_RECOVERY_L2_MS    (1000U)
#define CANSM_BUSOFF_THRESHOLD    (10U)
#define CANSM_MAX_NETWORKS    (4U)
#define CANSM_NETWORK_CAN0    (0U)
#define CANSM_NETWORK_CAN1    (1U)
#define CANSM_NETWORK_CAN2    (2U)
#define CANSM_NETWORK_CAN3    (3U)
#define CANSM_TRANSCEIVER_CAN0    (0U)
#define CANSM_TRANSCEIVER_CAN1    (1U)
#define CANSM_NETWORK0_BUSOFF_RECOVERY_TIME_MS    (1000U)
#define CANSM_NETWORK1_BUSOFF_RECOVERY_TIME_MS    (1000U)
#define CANSM_NETWORK0_WAKEUP_SUPPORT    STD_ON
#define CANSM_NETWORK1_WAKEUP_SUPPORT    STD_ON
#define CANSM_NETWORK0_BUSOFF_RECOVERY_ENABLED    STD_ON
#define CANSM_NETWORK1_BUSOFF_RECOVERY_ENABLED    STD_ON
#define CANSM_BUSOFF_NOTIFICATION_ENABLED    STD_ON
#define CANSM_MODE_CHANGE_NOTIFICATION_ENABLED    STD_ON

#endif /* CANSM_CFG_H */

/*==================[end of file]===========================================*/
