/**
 * @file Boot_Cfg.h
 * @brief Boot Configuration configuration header
 * @version 1.0.0
 * @date 2026-08-10
 * @note AUTO-GENERATED by yuleASR Configurator
 */

#ifndef BOOT_CFG_H
#define BOOT_CFG_H

#include "Std_Types.h"

/*==================================================================================================
*                                    PRE-COMPILE CONFIGURATION
*================================================================================================*/

/*==================================================================================================
*                                    Timing Configuration
*================================================================================================*/
#define BOOT_WDG_TIMEOUT_MS    (5000U)
#define BOOT_VERIFY_TIMEOUT_MS    (10000U)

/*==================================================================================================
*                                    Other Configuration
*================================================================================================*/
#define BOOT_FLASH_BASE    (0U)
#define BOOT_PBL_ADDR    (0U)
#define BOOT_PBL_SIZE    (4096U)
#define BOOT_SBL_ADDR    (8192U)
#define BOOT_SBL_SIZE    (65536U)
#define BOOT_APP_SLOT_A_ADDR    (73728U)
#define BOOT_APP_SLOT_A_SIZE    (974848U)
#define BOOT_APP_SLOT_B_ADDR    (1048576U)
#define BOOT_APP_SLOT_B_SIZE    (917504U)
#define BOOT_BIB_ADDR    (1966080U)
#define BOOT_BIB_SIZE    (65536U)
#define BOOT_NVM_ADDR    (2031616U)
#define BOOT_NVM_SIZE    (32768U)
#define BOOT_MAX_RETRIES    (3U)
#define BOOT_MAX_BOOT_ATTEMPTS    (5U)
#define BOOT_HASH_SIZE    (32U)
#define BOOT_SIGNATURE_SIZE    (64U)
#define BOOT_HSM_KEY_SLOT_PBL    (0U)
#define BOOT_HSM_KEY_SLOT_SBL    (1U)
#define BOOT_HSM_KEY_SLOT_APP    (2U)
#ifndef BOOT_DEBUG_ENABLE
#define BOOT_DEBUG_ENABLE    (0U)
#endif
/*==================================================================================================
*                                    FUNCTION-LIKE MACROS (VERBATIM)
*================================================================================================*/
#if BOOT_DEBUG_ENABLE
#include "SchM.h"
#define BOOT_TRACE(fmt, ...)  SchM_Log(0, fmt, ##__VA_ARGS__)
#else
#define BOOT_TRACE(fmt, ...)
#endif


#endif /* BOOT_CFG_H */

/*==================[end of file]===========================================*/
