/**
 * @file Fee_Cfg.h
 * @brief Fee Configuration configuration header
 * @version 1.0.0
 * @date 2026-08-10
 * @note AUTO-GENERATED by yuleASR Configurator
 */

#ifndef FEE_CFG_H
#define FEE_CFG_H

/*==================================================================================================
*                                    PRE-COMPILE CONFIGURATION
*================================================================================================*/

/*==================================================================================================
*                                    General Configuration
*================================================================================================*/
#define FEE_DEV_ERROR_DETECT    STD_ON
#define FEE_VERSION_INFO_API    STD_ON

/*==================================================================================================
*                                    Module Configuration Counts
*================================================================================================*/
#define FEE_NUM_SECTORS    (4U)
#define FEE_NUM_BLOCKS    (16U)

/*==================================================================================================
*                                    Timing Configuration
*================================================================================================*/
#define FEE_ERASE_TIMEOUT_US    (5000000U)
#define FEE_WRITE_TIMEOUT_US    (100000U)
#define FEE_READ_TIMEOUT_US    (10000U)
#define FEE_BLANK_CHECK_TIMEOUT_US    (10000U)

/*==================================================================================================
*                                    Other Configuration
*================================================================================================*/
#define FEE_ERASE_SUSPEND_SUPPORT    STD_ON
#define FEE_WRITE_VERIFY_SUPPORT    STD_ON
#define FEE_COMPARE_SUPPORT    STD_ON
#define FEE_BLANK_CHECK_SUPPORT    STD_ON
#define FEE_CANCEL_SUPPORT    STD_ON
#define FEE_ECC_CHECK_ENABLED    STD_ON
#define FEE_HW_ERROR_RECOVERY    STD_ON
#define FEE_FLASH_BASE_ADDR    (268435456U)
#define FEE_FLASH_TOTAL_SIZE    (8388608U)
#define FEE_FLASH_SECTOR_SIZE    (65536U)
#define FEE_FLASH_PAGE_SIZE    (256U)
#define FEE_FLASH_WORD_SIZE    (4U)
#define FEE_VIRTUAL_PAGE_SIZE    (8U)
#define FEE_MAX_WRITE_CYCLES    (100000U)
#define FEE_MAX_ERASE_CYCLES    (100000U)
#define FEE_GC_THRESHOLD_PERCENT    (80U)
#define FEE_MAX_READ_NORMAL_MODE    (256U)
#define FEE_MAX_READ_FAST_MODE    (1024U)
#define FEE_MAX_WRITE_NORMAL_MODE    (256U)
#define FEE_MAX_WRITE_FAST_MODE    (512U)
#define FEE_SECTOR0_START_ADDR    (FEE_FLASH_BASE_ADDR + 0x00000000U)
#define FEE_SECTOR0_SIZE    (65536U)
#define FEE_SECTOR0_ERASE_CYCLES    (100000U)
#define FEE_SECTOR0_WRITABLE    STD_ON
#define FEE_SECTOR0_ERASABLE    STD_ON
#define FEE_SECTOR1_START_ADDR    (FEE_FLASH_BASE_ADDR + 0x00010000U)
#define FEE_SECTOR1_SIZE    (65536U)
#define FEE_SECTOR1_ERASE_CYCLES    (100000U)
#define FEE_SECTOR1_WRITABLE    STD_ON
#define FEE_SECTOR1_ERASABLE    STD_ON
#define FEE_SECTOR2_START_ADDR    (FEE_FLASH_BASE_ADDR + 0x00020000U)
#define FEE_SECTOR2_SIZE    (65536U)
#define FEE_SECTOR2_ERASE_CYCLES    (100000U)
#define FEE_SECTOR2_WRITABLE    STD_ON
#define FEE_SECTOR2_ERASABLE    STD_ON
#define FEE_SECTOR3_START_ADDR    (FEE_FLASH_BASE_ADDR + 0x00030000U)
#define FEE_SECTOR3_SIZE    (65536U)
#define FEE_SECTOR3_ERASE_CYCLES    (100000U)
#define FEE_SECTOR3_WRITABLE    STD_ON
#define FEE_SECTOR3_ERASABLE    STD_ON
#define FEE_BLOCK_SIZE_8    (8U)
#define FEE_BLOCK_SIZE_16    (16U)
#define FEE_BLOCK_SIZE_32    (32U)
#define FEE_BLOCK_SIZE_64    (64U)
#define FEE_BLOCK_SIZE_128    (128U)
#define FEE_BLOCK_SIZE_256    (256U)
#define FEE_BLOCK_SIZE_512    (512U)
#define FEE_BLOCK_SIZE_1024    (1024U)
#define FEE_DEFAULT_WRITE_CYCLES    (100000U)
#define FEE_DATA_ALIGNMENT    (8U)
#define FEE_NUMBER_OF_BLOCKS    (10U)
#define FEE_NUMBER_OF_PAGES    (2U)
#define FEE_NUMBER_OF_SECTORS    (2U)
#define FEE_PAGE_SIZE    (65536U)
#define FEE_PAGE_0_START_ADDRESS    (FEE_FLASH_BASE_ADDR + 0x00000000U)
#define FEE_PAGE_1_START_ADDRESS    (FEE_FLASH_BASE_ADDR + 0x00010000U)
#define FEE_GC_REPETITIONS    (3U)
#define FEE_USE_ERASE_SUSPEND    STD_ON
#define FEE_BLOCK_NVM_CONFIG_ID    (1U)
#define FEE_BLOCK_NVM_ADMIN_ID    (2U)
#define FEE_BLOCK_ID_1    (16U)
#define FEE_BLOCK_ID_2    (17U)
#define FEE_BLOCK_ID_3    (18U)
#define FEE_BLOCK_ID_4    (19U)
#define FEE_BLOCK_ID_5    (20U)
#define FEE_BLOCK_ID_6    (21U)
#define FEE_BLOCK_ID_7    (22U)
#define FEE_BLOCK_ID_8    (23U)
#define FEE_JOB_END_NOTIFICATION_ENABLED    STD_ON
#define FEE_JOB_ERROR_NOTIFICATION_ENABLED    STD_ON
#define FEE_SECTOR_MAGIC_NUMBER    (1178944853U)
#define FEE_FLASH_EMPTY_VALUE    (4294967295U)
#define FEE_BLOCK_HEADER_SIZE    (8U)
#define FEE_SECTOR_HEADER_SIZE    (16U)
#ifndef FEE_E_INVALID_CANCEL
#define FEE_E_INVALID_CANCEL    (12U)
#endif

#endif /* FEE_CFG_H */

/*==================[end of file]===========================================*/
