/**
 * @file FlStSt_Cfg.h
 * @brief FlStSt Configuration configuration header
 * @version 1.0.0
 * @date 2026-08-10
 * @note AUTO-GENERATED by yuleASR Configurator
 */

#ifndef FLSTST_CFG_H
#define FLSTST_CFG_H

/*==================================================================================================
*                                    PRE-COMPILE CONFIGURATION
*================================================================================================*/

/*==================================================================================================
*                                    General Configuration
*================================================================================================*/
#define FLSTST_DEV_ERROR_DETECT    STD_ON
#define FLSTST_VERSION_INFO_API    STD_ON

/*==================================================================================================
*                                    Timing Configuration
*================================================================================================*/
#define FLSTST_MAIN_FUNCTION_PERIOD_MS    (10U)

/*==================================================================================================
*                                    Other Configuration
*================================================================================================*/
#define FLSTST_MAX_SECTORS    (8U)
#define FLSTST_MARCH_BACKGROUND_PATTERN    (85U)
#define FLSTST_MARCH_BACKGROUND_INVERT    (170U)
#define FLSTST_MARCH_CHECKERBOARD_A    (170U)
#define FLSTST_MARCH_CHECKERBOARD_B    (85U)
#define FLSTST_BYTES_PER_CYCLE    (4U)
#define FLSTST_ERASE_VALUE    (255U)
#define FLSTST_VERIFY_CHUNK_SIZE    (256U)

#endif /* FLSTST_CFG_H */

/*==================[end of file]===========================================*/
