/**
 * @file LinNm_Cfg.h
 * @brief LinNm Configuration configuration header
 * @version 1.0.0
 * @date 2026-08-10
 * @note AUTO-GENERATED by yuleASR Configurator
 */

#ifndef LINNM_CFG_H
#define LINNM_CFG_H

#include "Std_Types.h"

/*==================================================================================================
*                                    PRE-COMPILE CONFIGURATION
*================================================================================================*/

/*==================================================================================================
*                                    General Configuration
*================================================================================================*/
#ifndef LINNM_DEV_ERROR_DETECT
#define LINNM_DEV_ERROR_DETECT    STD_ON
#endif
#ifndef LINNM_VERSION_INFO_API
#define LINNM_VERSION_INFO_API    STD_ON
#endif
#ifndef LINNM_NODE_DETECTION_ENABLED
#define LINNM_NODE_DETECTION_ENABLED    STD_OFF
#endif

/*==================================================================================================
*                                    Hardware Object Handles
*================================================================================================*/
#define LINNM_CH0_NETWORK_HANDLE    (0U)
#define LINNM_CH1_NETWORK_HANDLE    (1U)
#define LINNM_CH0_TX_PDU_ID    (0U)
#define LINNM_CH0_RX_PDU_ID    (0U)
#define LINNM_CH1_TX_PDU_ID    (1U)
#define LINNM_CH1_RX_PDU_ID    (1U)

/*==================================================================================================
*                                    Timing Configuration
*================================================================================================*/
#ifndef LINNM_TIMEOUT_TIME
#define LINNM_TIMEOUT_TIME    (100U)
#endif
#define LINNM_CH0_TIMEOUT_TIME    (100U)
#define LINNM_CH1_TIMEOUT_TIME    (100U)

/*==================================================================================================
*                                    Other Configuration
*================================================================================================*/
#define LINNM_CFG_VENDOR_ID    (1U)
#define LINNM_CFG_MODULE_ID    (69U)
#define LINNM_CFG_AR_RELEASE_MAJOR_VERSION    (4U)
#define LINNM_CFG_AR_RELEASE_MINOR_VERSION    (4U)
#define LINNM_CFG_AR_RELEASE_REVISION_VERSION    (0U)
#define LINNM_CFG_SW_MAJOR_VERSION    (1U)
#define LINNM_CFG_SW_MINOR_VERSION    (0U)
#define LINNM_CFG_SW_PATCH_VERSION    (0U)
#ifndef LINNM_COM_CONTROL_ENABLED
#define LINNM_COM_CONTROL_ENABLED    STD_ON
#endif
#ifndef LINNM_PASSIVE_MODE_ENABLED
#define LINNM_PASSIVE_MODE_ENABLED    STD_OFF
#endif
#ifndef LINNM_STATE_CHANGE_IND_ENABLED
#define LINNM_STATE_CHANGE_IND_ENABLED    STD_ON
#endif
#ifndef LINNM_REMOTE_SLEEP_IND_ENABLED
#define LINNM_REMOTE_SLEEP_IND_ENABLED    STD_ON
#endif
#ifndef LINNM_NODE_ID_ENABLED
#define LINNM_NODE_ID_ENABLED    STD_ON
#endif
#ifndef LINNM_USER_DATA_ENABLED
#define LINNM_USER_DATA_ENABLED    STD_ON
#endif
#ifndef LINNM_COM_CONTROL_SYNCHRONIZED
#define LINNM_COM_CONTROL_SYNCHRONIZED    STD_OFF
#endif
#ifndef LINNM_COORDINATOR_SYNC_SUPPORT
#define LINNM_COORDINATOR_SYNC_SUPPORT    STD_OFF
#endif
#ifndef LINNM_BUS_SYNCHRONIZATION_ENABLED
#define LINNM_BUS_SYNCHRONIZATION_ENABLED    STD_ON
#endif
#ifndef LINNM_BUSLOAD_REDUCTION_ENABLED
#define LINNM_BUSLOAD_REDUCTION_ENABLED    STD_OFF
#endif
#ifndef LINNM_NUMBER_OF_CHANNELS
#define LINNM_NUMBER_OF_CHANNELS    (2U)
#endif
#ifndef LINNM_MAX_NODES_PER_CHANNEL
#define LINNM_MAX_NODES_PER_CHANNEL    (16U)
#endif
#ifndef LINNM_WAIT_BUSSLEEP_TIME
#define LINNM_WAIT_BUSSLEEP_TIME    (50U)
#endif
#ifndef LINNM_REMOTE_SLEEP_IND_TIME
#define LINNM_REMOTE_SLEEP_IND_TIME    (500U)
#endif
#ifndef LINNM_MSG_CYCLE_TIME
#define LINNM_MSG_CYCLE_TIME    (20U)
#endif
#ifndef LINNM_MSG_REDUCED_TIME
#define LINNM_MSG_REDUCED_TIME    (50U)
#endif
#ifndef LINNM_MSG_CYCLE_OFFSET
#define LINNM_MSG_CYCLE_OFFSET    (5U)
#endif
#ifndef LINNM_REPEAT_MESSAGE_TIME
#define LINNM_REPEAT_MESSAGE_TIME    (150U)
#endif
#define LINNM_CHANNEL_0    (0U)
#define LINNM_CH0_LINIF_CHANNEL    (0U)
#define LINNM_CH0_NODE_ID    (1U)
#define LINNM_CH0_NODE_TYPE    LINNM_NODE_TYPE_MASTER
#define LINNM_CH0_PASSIVE_MODE    STD_OFF
#define LINNM_CH0_STATE_REPORT    STD_ON
#define LINNM_CH0_WAIT_BUSSLEEP_TIME    (50U)
#define LINNM_CH0_REMOTE_SLEEP_IND_TIME    (500U)
#define LINNM_CH0_MSG_CYCLE_TIME    (20U)
#define LINNM_CH0_MSG_REDUCED_TIME    (50U)
#define LINNM_CH0_MSG_CYCLE_OFFSET    (5U)
#define LINNM_CH0_USER_DATA_LENGTH    (6U)
#define LINNM_CH0_BUS_SYNC_ENABLED    STD_ON
#define LINNM_CH0_REMOTE_SLEEP_ENABLED    STD_ON
#define LINNM_CH0_COM_CONTROL_ENABLED    STD_ON
#define LINNM_CH0_COORDINATOR_SYNC    STD_OFF
#define LINNM_CHANNEL_1    (1U)
#define LINNM_CH1_LINIF_CHANNEL    (1U)
#define LINNM_CH1_NODE_ID    (2U)
#define LINNM_CH1_NODE_TYPE    LINNM_NODE_TYPE_SLAVE
#define LINNM_CH1_PASSIVE_MODE    STD_OFF
#define LINNM_CH1_STATE_REPORT    STD_ON
#define LINNM_CH1_WAIT_BUSSLEEP_TIME    (50U)
#define LINNM_CH1_REMOTE_SLEEP_IND_TIME    (500U)
#define LINNM_CH1_MSG_CYCLE_TIME    (20U)
#define LINNM_CH1_MSG_REDUCED_TIME    (50U)
#define LINNM_CH1_MSG_CYCLE_OFFSET    (10U)
#define LINNM_CH1_USER_DATA_LENGTH    (6U)
#define LINNM_CH1_BUS_SYNC_ENABLED    STD_ON
#define LINNM_CH1_REMOTE_SLEEP_ENABLED    STD_ON
#define LINNM_CH1_COM_CONTROL_ENABLED    STD_ON
#define LINNM_CH1_COORDINATOR_SYNC    STD_OFF
#define LINNM_PDU_SIZE    (8U)
#define LINNM_PDU_USER_DATA_SIZE    (6U)
#define LINNM_PDU_BYTE_0    (0U)
#define LINNM_PDU_BYTE_1    (1U)
#define LINNM_PDU_BYTE_2    (2U)
#define LINNM_PDU_BYTE_3    (3U)
#define LINNM_PDU_BYTE_4    (4U)
#define LINNM_PDU_BYTE_5    (5U)
#define LINNM_PDU_BYTE_6    (6U)
#define LINNM_PDU_BYTE_7    (7U)
#define LINNM_PDU_CBV_POS    (0U)
#define LINNM_CBV_ACTIVEWAKEUP_MASK    (1U)
#define LINNM_CBV_RESERVED_MASK    (254U)
#define LINNM_PDU_NODEID_POS    (1U)
#define LINNM_PDU_USERDATA_START    (2U)
#ifndef LINNM_STATE_CHANGE_NOTIFICATION
#define LINNM_STATE_CHANGE_NOTIFICATION    STD_ON
#endif
#ifndef LINNM_REMOTE_SLEEP_CALLBACK
#define LINNM_REMOTE_SLEEP_CALLBACK    STD_ON
#endif
#ifndef LINNM_SYNC_POINT_CALLBACK
#define LINNM_SYNC_POINT_CALLBACK    STD_ON
#endif
/*==================================================================================================
*                                    FUNCTION-LIKE MACROS (VERBATIM)
*================================================================================================*/
#if (LINNM_STATE_CHANGE_NOTIFICATION == STD_ON)
#define LINNM_CALL_STATE_CHANGE_NOTIFICATION(networkHandle, prevState, currState) \
    Nm_StateChangeNotification((networkHandle), (prevState), (currState))
#else
#define LINNM_CALL_STATE_CHANGE_NOTIFICATION(networkHandle, prevState, currState)
#endif
#if (LINNM_REMOTE_SLEEP_CALLBACK == STD_ON)
#define LINNM_CALL_REMOTE_SLEEP_INDICATION(networkHandle) \
    Nm_RemoteSleepIndication((networkHandle))
#define LINNM_CALL_REMOTE_SLEEP_CANCELLATION(networkHandle) \
    Nm_RemoteSleepCancellation((networkHandle))
#else
#define LINNM_CALL_REMOTE_SLEEP_INDICATION(networkHandle)
#define LINNM_CALL_REMOTE_SLEEP_CANCELLATION(networkHandle)
#endif
#if (LINNM_SYNC_POINT_CALLBACK == STD_ON)
#define LINNM_CALL_SYNC_POINT(networkHandle) \
    Nm_SynchronizationPoint((networkHandle))
#else
#define LINNM_CALL_SYNC_POINT(networkHandle)
#endif


#endif /* LINNM_CFG_H */

/*==================[end of file]===========================================*/
