/**
 * @file Fls_Cfg.h
 * @brief Fls Configuration configuration header
 * @version 1.0.0
 * @date 2026-08-10
 * @note AUTO-GENERATED by yuleASR Configurator
 */

#ifndef FLS_CFG_H
#define FLS_CFG_H

#include "S32K312.h"

/*==================================================================================================
*                                    PRE-COMPILE CONFIGURATION
*================================================================================================*/

/*==================================================================================================
*                                    General Configuration
*================================================================================================*/
#define FLS_VERSION_INFO_API    STD_ON
#define FLS_DEV_ERROR_DETECT    STD_ON
#define FLS_RUNTIME_ERROR_DETECT    STD_ON

/*==================================================================================================
*                                    Module Configuration Counts
*================================================================================================*/
#define FLS_NUM_OF_SECTORS    (4U)

/*==================================================================================================
*                                    Timing Configuration
*================================================================================================*/
#define FLS_MAIN_FUNCTION_PERIOD    (10U)
#define FLS_TIMEOUT_VALUE    (1000U)

/*==================================================================================================
*                                    Other Configuration
*================================================================================================*/
#define FLS_JOB_END_NOTIFICATION    STD_ON
#define FLS_JOB_ERROR_NOTIFICATION    STD_ON
#define FLS_USE_ISR    STD_OFF
#define FLS_READ_SYNC_API    STD_OFF
#define FLS_COMPARE_API    STD_ON
#define FLS_CANCEL_API    STD_ON
#define FLS_SET_MODE_API    STD_ON
#define FLS_TOTAL_SIZE    (1048576U)
#define FLS_BASE_ADDRESS    (134217728U)
#define FLS_SECTOR_0_START_ADDR    (134217728U)
#define FLS_SECTOR_0_SIZE    (65536U)
#define FLS_SECTOR_0_PAGE_SIZE    (4U)
#define FLS_SECTOR_1_START_ADDR    (134283264U)
#define FLS_SECTOR_1_SIZE    (65536U)
#define FLS_SECTOR_1_PAGE_SIZE    (4U)
#define FLS_SECTOR_2_START_ADDR    (134348800U)
#define FLS_SECTOR_2_SIZE    (131072U)
#define FLS_SECTOR_2_PAGE_SIZE    (4U)
#define FLS_SECTOR_3_START_ADDR    (134479872U)
#define FLS_SECTOR_3_SIZE    (786432U)
#define FLS_SECTOR_3_PAGE_SIZE    (4U)
#define FLS_MAX_READ_NORMAL_MODE    (256U)
#define FLS_MAX_READ_FAST_MODE    (512U)
#define FLS_MAX_WRITE_NORMAL_MODE    (32U)
#define FLS_MAX_WRITE_FAST_MODE    (64U)
#ifndef FLS_HW_E_PARAM_POINTER
#define FLS_HW_E_PARAM_POINTER    (10U)
#endif


/*==================================================================================================
*  NON-MACRO SEGMENT (preserved from handwritten header, merged by codegen splice)
*  typedef(0) + struct(0) + extern config tables(2) — 依赖宏段计数宏, 故置于宏段之后
*================================================================================================*/
#if (FLS_JOB_END_NOTIFICATION == STD_ON)
    extern void Fls_JobEndNotification(void);
#endif

#if (FLS_JOB_ERROR_NOTIFICATION == STD_ON)
    extern void Fls_JobErrorNotification(void);
#endif
#endif /* FLS_CFG_H */

/*==================[end of file]===========================================*/
