/**
 * @file Gpt_Cfg.h
 * @brief Gpt Configuration configuration header
 * @version 1.0.0
 * @date 2026-08-10
 * @note AUTO-GENERATED by yuleASR Configurator
 */

#ifndef GPT_CFG_H
#define GPT_CFG_H

/*==================================================================================================
*                                    PRE-COMPILE CONFIGURATION
*================================================================================================*/

/*==================================================================================================
*                                    General Configuration
*================================================================================================*/
#define GPT_DEV_ERROR_DETECT    STD_ON
#define GPT_VERSION_INFO_API    STD_ON

/*==================================================================================================
*                                    Module Configuration Counts
*================================================================================================*/
#define GPT_NUM_CHANNELS    (8U)

/*==================================================================================================
*                                    Timing Configuration
*================================================================================================*/
#define GPT_MAIN_FUNCTION_PERIOD_MS    (1U)

/*==================================================================================================
*                                    Other Configuration
*================================================================================================*/
#define GPT_DEINIT_API    STD_ON
#define GPT_TIME_ELAPSED_API    STD_ON
#define GPT_TIME_REMAINING_API    STD_ON
#define GPT_ENABLE_DISABLE_NOTIFICATION_API    STD_ON
#define GPT_WAKEUP_FUNCTIONALITY_API    STD_OFF
#define GPT_REPORT_WAKEUP_SOURCE    STD_OFF
#define GPT_PREDEF_TIMER_1US_16BIT_ENABLE    STD_ON
#define GPT_PREDEF_TIMER_1US_24BIT_ENABLE    STD_OFF
#define GPT_PREDEF_TIMER_1US_32BIT_ENABLE    STD_ON
#define GPT_PREDEF_TIMER_100US_32BIT_ENABLE    STD_ON
#define GPT_CHANNEL_0    (0U)
#define GPT_CHANNEL_1    (1U)
#define GPT_CHANNEL_2    (2U)
#define GPT_CHANNEL_3    (3U)
#define GPT_CHANNEL_4    (4U)
#define GPT_CHANNEL_5    (5U)
#define GPT_CHANNEL_6    (6U)
#define GPT_CHANNEL_7    (7U)
#define GPT_DEFAULT_MODE    GPT_MODE_NORMAL
#define GPT_CLOCK_FREQUENCY_HZ    (24000000U)
#define GPT_MAX_TICK_VALUE    (4294967295U)

#endif /* GPT_CFG_H */

/*==================[end of file]===========================================*/
