/**
 * @file SomeIpIf_Cfg.h
 * @brief SomeIpIf Configuration configuration header
 * @version 1.0.0
 * @date 2026-08-10
 * @note AUTO-GENERATED by yuleASR Configurator
 */

#ifndef SOMEIPIF_CFG_H
#define SOMEIPIF_CFG_H

/*==================================================================================================
*                                    PRE-COMPILE CONFIGURATION
*================================================================================================*/

/*==================================================================================================
*                                    General Configuration
*================================================================================================*/
#define SOMEIPIF_DEV_ERROR_DETECT    STD_ON
#define SOMEIPIF_VERSION_INFO_API    STD_ON

/*==================================================================================================
*                                    Other Configuration
*================================================================================================*/
#define SOMEIP_PROTOCOL_VERSION    (1U)
#define SOMEIP_INTERFACE_VERSION    (1U)
#define SOMEIP_HEADER_SIZE    (16U)
#define SOMEIP_MAX_MESSAGE_LENGTH    (4095U)
#define SOMEIPIF_MAX_SERVICES    (32U)
#define SOMEIPIF_MAX_ENDPOINTS    (16U)
#define SOMEIP_CONNECTION_TCP    (0U)
#define SOMEIP_CONNECTION_UDP    (1U)

#endif /* SOMEIPIF_CFG_H */

/*==================[end of file]===========================================*/
