/**
 * @file Sd_Cfg.h
 * @brief Sd Configuration configuration header
 * @version 1.0.0
 * @date 2026-08-10
 * @note AUTO-GENERATED by yuleASR Configurator
 */

#ifndef SD_CFG_H
#define SD_CFG_H

/*==================================================================================================
*                                    PRE-COMPILE CONFIGURATION
*================================================================================================*/

/*==================================================================================================
*                                    General Configuration
*================================================================================================*/
#define SD_DEV_ERROR_DETECT    STD_ON
#define SD_VERSION_INFO_API    STD_ON

/*==================================================================================================
*                                    Timing Configuration
*================================================================================================*/
#define SD_MAIN_FUNCTION_PERIOD_MS    (10U)

/*==================================================================================================
*                                    Other Configuration
*================================================================================================*/
#define SD_MAX_OFFERED_SERVICES    (16U)
#define SD_MAX_FOUND_SERVICES    (32U)
#define SD_MAX_SUBSCRIPTIONS    (16U)
#define SD_MAX_EVENT_GROUPS    (16U)
#define SD_OFFER_CYCLE_TIME_MS    (2000U)
#define SD_FIND_CYCLE_TIME_MS    (3000U)
#define SD_TTL_DEFAULT_SEC    (5U)
#define SD_INITIAL_DELAY_MS    (500U)
#define SD_SOMEIP_SERVICE_ID    (65535U)
#define SD_SOMEIP_METHOD_ID    (33024U)
#define SD_MAX_SD_MSG_LENGTH    (1400U)
#define SD_MULTICAST_IPV4_ADDR    (4026531839U)
#define SD_MULTICAST_PORT    (30490U)
#define SD_UNICAST_PORT    (30491U)

#endif /* SD_CFG_H */

/*==================[end of file]===========================================*/
