/**
 * @file Lin_Cfg.h
 * @brief Lin Configuration configuration header
 * @version 1.0.0
 * @date 2026-08-10
 * @note AUTO-GENERATED by yuleASR Configurator
 */

#ifndef LIN_CFG_H
#define LIN_CFG_H

#include "Lin.h"

/*==================================================================================================
*                                    PRE-COMPILE CONFIGURATION
*================================================================================================*/

/*==================================================================================================
*                                    General Configuration
*================================================================================================*/
#define LIN_DEV_ERROR_DETECT    STD_ON
#define LIN_VERSION_INFO_API    STD_ON

/*==================================================================================================
*                                    Baudrate Configurations
*================================================================================================*/
#define LIN_BAUDRATE_9600    (9600U)
#define LIN_BAUDRATE_19200    (19200U)
#define LIN_CH0_BAUDRATE    (19200U)
#define LIN_CH1_BAUDRATE    (19200U)

/*==================================================================================================
*                                    Timing Configuration
*================================================================================================*/
#define LIN_TIMEOUT    (100U)
#define LIN_WAKEUP_TIMEOUT    (50U)

/*==================================================================================================
*                                    Other Configuration
*================================================================================================*/
#define LIN_WAKEUP_SUPPORT    STD_ON
#define LIN_MAX_CHANNELS    (2U)
#define LIN_CHANNEL_0    (0U)
#define LIN_CHANNEL_1    (1U)
#define LIN_MAX_FRAME_LENGTH    (8U)
#define LIN_MAX_PID    (63U)
#define LIN_CH0_WAKEUP_SUPPORT    STD_ON
#define LIN_CH1_WAKEUP_SUPPORT    STD_ON

#endif /* LIN_CFG_H */

/*==================[end of file]===========================================*/
