/**
 * @file LinMaster_Cfg.h
 * @brief LinMaster Configuration configuration header
 * @version 1.0.0
 * @date 2026-08-10
 * @note AUTO-GENERATED by yuleASR Configurator
 */

#ifndef LINMASTER_CFG_H
#define LINMASTER_CFG_H

/*==================================================================================================
*                                    PRE-COMPILE CONFIGURATION
*================================================================================================*/

/*==================================================================================================
*                                    General Configuration
*================================================================================================*/
#define LINMASTER_DEV_ERROR_DETECT    STD_ON
#define LINMASTER_VERSION_INFO_API    STD_ON

/*==================================================================================================
*                                    Baudrate Configurations
*================================================================================================*/
#define LINMASTER_DEFAULT_BAUDRATE    (9600U)

/*==================================================================================================
*                                    Hardware Object Handles
*================================================================================================*/
#define LINMASTER_RX_RESPONSE_TIMEOUT_MS    (100U)

/*==================================================================================================
*                                    Timing Configuration
*================================================================================================*/
#define LINMASTER_DEFAULT_TIMEOUT_MS    (100U)
#define LINMASTER_BREAK_SEND_TIMEOUT_MS    (5U)
#define LINMASTER_SYNC_SEND_TIMEOUT_MS    (5U)
#define LINMASTER_PID_SEND_TIMEOUT_MS    (5U)
#define LINMASTER_DATA_SEND_TIMEOUT_MS    (50U)
#define LINMASTER_MAINFUNCTION_PERIOD_MS    (1U)

/*==================================================================================================
*                                    Other Configuration
*================================================================================================*/
#define LINMASTER_DEFAULT_BREAK_US    (728U)
#define LINMASTER_DEFAULT_INTERFRAME_MS    (1U)
#define LINMASTER_MAX_FRAME_CONFIG    (20U)

#endif /* LINMASTER_CFG_H */

/*==================[end of file]===========================================*/
