/**
 * @file Mqtt_Cfg.h
 * @brief Mqtt Configuration configuration header
 * @version 1.0.0
 * @date 2026-08-10
 * @note AUTO-GENERATED by yuleASR Configurator
 */

#ifndef MQTT_CFG_H
#define MQTT_CFG_H

#include "Std_Types.h"   /* 非宏段依赖 Std_Types 基础类型 (uint32/uint8/uint16/boolean 等)，生成宏段不含此 include */

#include "ComStack_Types.h"
#include "TcpIp.h"

/*==================================================================================================
*                                    PRE-COMPILE CONFIGURATION
*================================================================================================*/

/*==================================================================================================
*                                    General Configuration
*================================================================================================*/
#define MQTT_DEV_ERROR_DETECT    STD_ON
#define MQTT_VERSION_INFO_API    STD_ON

/*==================================================================================================
*                                    Timing Configuration
*================================================================================================*/
#define MQTT_MAIN_FUNCTION_PERIOD_MS    (10U)
#define MQTT_TLS_HANDSHAKE_TIMEOUT_MS    (10000U)
#define MQTT_DEFAULT_CONNECT_TIMEOUT_MS    (5000U)
#define MQTT_DEFAULT_RECV_TIMEOUT_MS    (1000U)

/*==================================================================================================
*                                    Other Configuration
*================================================================================================*/
#define MQTT_CFG_MAJOR_VERSION    (1U)
#define MQTT_CFG_MINOR_VERSION    (0U)
#define MQTT_CFG_PATCH_VERSION    (0U)
#define MQTT_DEBUG_MODE    STD_OFF
#define MQTT_SUPPORT_V50    STD_ON
#define MQTT_SUPPORT_TLS    STD_ON
#define MQTT_SUPPORT_MTLS    STD_ON
#define MQTT_SUPPORT_SSL_V30    STD_OFF
#define MQTT_DEFAULT_TLS_VERSION    (771U)
#define MQTT_SUPPORT_AUTO_RECONNECT    STD_ON
#define MQTT_SUPPORT_CHANNEL_CALLBACKS    STD_ON
#define MQTT_SUPPORT_WILL_MESSAGE    STD_ON
#define MQTT_SUPPORT_LAST_WILL    STD_ON
#define MQTT_MAX_CONNECTIONS    (4U)
#define MQTT_MAX_SUBSCRIPTIONS_PER_CONN    (8U)
#define MQTT_MAX_TOPIC_LENGTH    (128U)
#define MQTT_MAX_CLIENT_ID_LENGTH    (64U)
#define MQTT_SEND_BUFFER_SIZE    (2048U)
#define MQTT_RECV_BUFFER_SIZE    (2048U)
#define MQTT_MESSAGE_QUEUE_DEPTH    (8U)
#define MQTT_TLS_SEND_BUFFER_SIZE    (4096U)
#define MQTT_TLS_RECV_BUFFER_SIZE    (4096U)
#define MQTT_TLS_SESSION_CACHE_SIZE    (1024U)
#define MQTT_TLS_MAX_CERT_CHAIN_DEPTH    (3U)
#define MQTT_TLS_VERIFY_EXPIRY    STD_ON
#define MQTT_TLS_VERIFY_HOSTNAME    STD_ON
#define MQTT_TLS_SECURE_RENEGOTIATION    STD_ON
#define MQTT_TLS_SESSION_RESUMPTION    STD_ON
#define MQTT_TLS_HW_ACCELERATION    STD_OFF
#define MQTT_DEFAULT_KEEP_ALIVE_S    (60U)
#define MQTT_DEFAULT_RECONNECT_INTERVAL_MS    (5000U)
#define MQTT_MAX_RECONNECT_ATTEMPTS    (5U)
#define MQTT_CONST    const
#ifndef MQTT_TLS_VERSION_1_2
#define MQTT_TLS_VERSION_1_2    (771U)
#endif
#ifndef MQTT_TLS_VERSION_1_3
#define MQTT_TLS_VERSION_1_3    (772U)
#endif
/*==================================================================================================
*                                    CONDITIONAL INCLUDES
*================================================================================================*/
#if (MQTT_DEV_ERROR_DETECT == STD_ON)
#include "Det.h"
#endif



/*==================================================================================================
*  NON-MACRO SEGMENT (preserved from handwritten header, merged by codegen splice)
*  typedef(0) + struct(2) + extern config tables(0) — 依赖宏段计数宏, 故置于宏段之后
*================================================================================================*/
typedef struct {
    void (*connectionStateChanged)(uint8 connectionId, uint8 newState);
    void (*messageReceived)(uint8 connectionId, const char* topic, 
                           const uint8* payload, uint32 length);
    void (*errorOccurred)(uint8 connectionId, uint8 errorCode);
} Mqtt_NotificationCallbacksType;

/**
 * @brief 模块级配置
 */
typedef struct {
    uint8 maxConnections;
    uint16 sendBufferSize;
    uint16 recvBufferSize;
    uint8 messageQueueDepth;
    boolean enableAutoReconnect;
    Mqtt_NotificationCallbacksType callbacks;
} Mqtt_ConfigType;
#endif /* MQTT_CFG_H */

/*==================[end of file]===========================================*/
