/**
 * @file J1939Nm_Cfg.h
 * @brief J1939Nm Configuration configuration header
 * @version 1.0.0
 * @date 2026-08-10
 * @note AUTO-GENERATED by yuleASR Configurator
 */

#ifndef J1939NM_CFG_H
#define J1939NM_CFG_H

/*==================================================================================================
*                                    PRE-COMPILE CONFIGURATION
*================================================================================================*/

/*==================================================================================================
*                                    General Configuration
*================================================================================================*/
#define J1939NM_DEV_ERROR_DETECT    STD_ON
#define J1939NM_VERSION_INFO_API    STD_ON
#define J1939NM_NODE_DETECTION_ENABLED    STD_ON

/*==================================================================================================
*                                    Timing Configuration
*================================================================================================*/
#define J1939NM_AC_TIMEOUT_MS    (250U)
#define J1939NM_MAIN_FUNCTION_PERIOD_MS    (10U)

/*==================================================================================================
*                                    Other Configuration
*================================================================================================*/
#define J1939NM_NODE_MONITORING_ENABLED    STD_ON
#define J1939NM_BUS_OFF_RECOVERY_ENABLED    STD_ON
#define J1939NM_NUMBER_OF_CHANNELS    (1U)
#define J1939NM_NUMBER_OF_NODES    (1U)
#define J1939NM_CHANNEL_0    (0U)
#define J1939NM_NODE_0    (0U)
#define J1939NM_AC_DELAY_MIN_MS    (50U)
#define J1939NM_AC_DELAY_MAX_MS    (150U)
#define J1939NM_BUS_OFF_RECOVERY_TIME_MS    (1000U)
#define J1939NM_AC_REPEAT_TIME_MS    (1000U)
#define J1939NM_NULL_ADDRESS    (254U)
#define J1939NM_GLOBAL_ADDRESS    (255U)
#define J1939NM_MIN_VALID_ADDRESS    (0U)
#define J1939NM_MAX_VALID_ADDRESS    (253U)
#define J1939NM_NAME_IDENTITY_NUMBER_MASK    (2097151U)
#define J1939NM_NAME_MANUFACTURER_CODE_MASK    (34357641216U)
#define J1939NM_NAME_ECU_INSTANCE_MASK    (240518168576U)
#define J1939NM_NAME_FUNCTION_INSTANCE_MASK    (8521215115264U)
#define J1939NM_NAME_FUNCTION_MASK    (2243003720663040U)
#define J1939NM_NAME_RESERVED_MASK    (2251799813685248U)
#define J1939NM_NAME_VEHICLE_SYSTEM_MASK    (571957152676053000U)
#define J1939NM_NAME_VEHICLE_SYSTEM_INSTANCE_MASK    (8646911284551352000U)
#define J1939NM_NAME_INDUSTRY_GROUP_MASK    (9223372036854776000U)
#define J1939NM_NAME_ARBITRARY_ADDRESS_CAPABLE_MASK    (9223372036854776000U)
#define J1939NM_NAME_IDENTITY_NUMBER_SHIFT    (0U)
#define J1939NM_NAME_MANUFACTURER_CODE_SHIFT    (21U)
#define J1939NM_NAME_ECU_INSTANCE_SHIFT    (32U)
#define J1939NM_NAME_FUNCTION_INSTANCE_SHIFT    (35U)
#define J1939NM_NAME_FUNCTION_SHIFT    (40U)
#define J1939NM_NAME_RESERVED_SHIFT    (48U)
#define J1939NM_NAME_VEHICLE_SYSTEM_SHIFT    (49U)
#define J1939NM_NAME_VEHICLE_SYSTEM_INSTANCE_SHIFT    (56U)
#define J1939NM_NAME_INDUSTRY_GROUP_SHIFT    (60U)
#define J1939NM_NAME_ARBITRARY_ADDRESS_CAPABLE_SHIFT    (63U)
#define J1939NM_DEFAULT_IDENTITY_NUMBER    (1U)
#define J1939NM_DEFAULT_MANUFACTURER_CODE    (2001U)
#define J1939NM_DEFAULT_ECU_INSTANCE    (0U)
#define J1939NM_DEFAULT_FUNCTION_INSTANCE    (0U)
#define J1939NM_DEFAULT_FUNCTION    (0U)
#define J1939NM_DEFAULT_VEHICLE_SYSTEM    (0U)
#define J1939NM_DEFAULT_VEHICLE_SYSTEM_INSTANCE    (0U)
#define J1939NM_DEFAULT_INDUSTRY_GROUP    (0U)
#define J1939NM_DEFAULT_ARBITRARY_ADDRESS_CAPABLE    STD_ON
#define J1939NM_DEFAULT_ADDRESS    (128U)
#define J1939NM_DEFAULT_PREFERRED_ADDRESS    (128U)

#endif /* J1939NM_CFG_H */

/*==================[end of file]===========================================*/
