/**
 * @file Xcp_Cfg.h
 * @brief Xcp Configuration configuration header
 * @version 1.0.0
 * @date 2026-08-10
 * @note AUTO-GENERATED by yuleASR Configurator
 */

#ifndef XCP_CFG_H
#define XCP_CFG_H

#include "Std_Types.h"

/*==================================================================================================
*                                    PRE-COMPILE CONFIGURATION
*================================================================================================*/

/*==================================================================================================
*                                    General Configuration
*================================================================================================*/
#define XCP_DEV_ERROR_DETECT    STD_ON
#define XCP_VERSION_INFO_API    STD_ON

/*==================================================================================================
*                                    Baudrate Configurations
*================================================================================================*/
#define XCP_CAN_BAUDRATE    (500U)

/*==================================================================================================
*                                    Other Configuration
*================================================================================================*/
#define XCP_CFG_VENDOR_ID    (1U)
#define XCP_CFG_MODULE_ID    (208U)
#define XCP_CFG_AR_RELEASE_MAJOR_VERSION    (4U)
#define XCP_CFG_AR_RELEASE_MINOR_VERSION    (4U)
#define XCP_CFG_AR_RELEASE_REVISION_VERSION    (0U)
#define XCP_CFG_SW_MAJOR_VERSION    (1U)
#define XCP_CFG_SW_MINOR_VERSION    (0U)
#define XCP_CFG_SW_PATCH_VERSION    (0U)
#define XCP_NUMBER_OF_CHANNELS    (1U)
#define XCP_MAX_DAQ_LISTS    (4U)
#define XCP_MAX_ODTS_PER_DAQ    (8U)
#define XCP_MAX_ODT_ENTRIES_PER_ODT    (16U)
#define XCP_MAX_CTO_SIZE    (8U)
#define XCP_MAX_DTO_SIZE    (8U)
#define XCP_MAX_EVENT_CHANNELS    (4U)
#define XCP_BLOCK_DOWNLOAD_SUPPORTED    STD_ON
#define XCP_BLOCK_UPLOAD_SUPPORTED    STD_ON
#define XCP_INTERLEAVED_MODE_SUPPORTED    STD_OFF
#define XCP_CHECKSUM_TYPE    (7U)
#define XCP_TIMESTAMP_SUPPORTED    STD_ON
#define XCP_TIMESTAMP_UNIT    (6U)
#define XCP_TIMESTAMP_SIZE    (2U)
#define XCP_DAQ_HEADER_TYPE    (2U)
#define XCP_IDENTIFICATION_FIELD_TYPE    (1U)
#define XCP_ADDRESS_GRANULARITY    (0U)
#define XCP_BYTE_ORDER    (1U)
#define XCP_SLAVE_BLOCK_MODE    STD_ON
#define XCP_MASTER_BLOCK_MODE    STD_ON
#define XCP_INTERLEAVED_BLOCK_MODE    STD_OFF
#define XCP_MAX_BS_UPLOAD    (255U)
#define XCP_MAX_BS_DOWNLOAD    (255U)
#define XCP_MIN_ST    (0U)
#define XCP_STIM_QUEUE_SIZE    (8U)
#define XCP_MAX_CONNECTIONS    (1U)
#define XCP_MAX_SEEDS    (4U)
#define XCP_SEED_KEY_SUPPORTED    STD_ON
#define XCP_CAL_PAGE_SWITCHING    STD_ON
#define XCP_NUMBER_OF_CAL_PAGES    (2U)
#define XCP_PROGRAMMING_SUPPORTED    STD_ON
#define XCP_MAX_PROGRAMMING_SECTOR_SIZE    (1024U)
#define XCP_FLASH_PROGRAMMING_SUPPORTED    STD_ON
#define XCP_NVM_PROGRAMMING_SUPPORTED    STD_ON
#define XCP_RESOURCE_CAL_PAG_PROTECTED    STD_OFF
#define XCP_RESOURCE_DAQ_PROTECTED    STD_OFF
#define XCP_RESOURCE_STIM_PROTECTED    STD_OFF
#define XCP_RESOURCE_PGM_PROTECTED    STD_ON
#define XCP_DAQ_DYNAMIC_ALLOCATION    STD_ON
#define XCP_DAQ_PRESCALER_SUPPORTED    STD_ON
#define XCP_DAQ_TIMESTAMP_SUPPORTED    STD_ON
#define XCP_DAQ_PID_OFF_SUPPORTED    STD_ON
#define XCP_DAQ_OVERLOAD_INDICATION    (1U)
#define XCP_EVENT_CHANNEL_TIMING_TYPE    (0U)
#define XCP_EVENT_CHANNEL_CONSISTENCY    (1U)
#define XCP_ON_CAN_ENABLED    STD_ON
#define XCP_ON_ETH_UDP_ENABLED    STD_ON
#define XCP_ON_ETH_TCP_ENABLED    STD_OFF
#define XCP_ON_FLEXRAY_ENABLED    STD_ON
#define XCP_ON_USB_ENABLED    STD_OFF
#define XCP_ON_LIN_ENABLED    STD_OFF
#define XCP_DAQ_SUPPORTED    STD_ON
#define XCP_GRANULARITY_ODT_ENTRY_SIZE_DAQ    (1U)
#define XCP_MAX_ODT_ENTRY_SIZE_DAQ    (8U)
#define XCP_GRANULARITY_ODT_ENTRY_SIZE_STIM    (1U)
#define XCP_MAX_ODT_ENTRY_SIZE_STIM    (8U)
#define XCP_DAQ_KEY_BYTE    (1U)
#define XCP_MAX_CTO_PGM    (8U)
#define XCP_MAX_BS_PGM    (255U)
#define XCP_MIN_ST_PGM    (0U)
#define XCP_QUEUE_SIZE_PGM    (8U)
#define XCP_INSTANCE_ID    (0U)
#define XCP_CAN_FRAME_TYPE    (0U)
#define XCP_CAN_CTO_ID    (291U)
#define XCP_CAN_DTO_ID    (292U)
#define XCP_ETH_PORT    (5555U)
#define XCP_ETH_BUFFER_SIZE    (1500U)
#define XCP_FLEXRAY_SLOT_ID    (1U)
#define XCP_FLEXRAY_CYCLE    (0U)
#define XCP_NUMBER_OF_MEMORY_RANGES    (4U)
#define XCP_MEMORY_ACCESS_READ    (1U)
#define XCP_MEMORY_ACCESS_WRITE    (2U)
#define XCP_MEMORY_ACCESS_EXECUTE    (4U)
#define XCP_MEMORY_ACCESS_ERASE    (8U)
#define XCP_MEMORY_SECTOR_TYPE_RAM    (0U)
#define XCP_MEMORY_SECTOR_TYPE_ROM    (1U)
#define XCP_MEMORY_SECTOR_TYPE_FLASH    (2U)
#define XCP_MEMORY_SECTOR_TYPE_EEPROM    (3U)
#define XCP_FLASH_ERASE_CALLBACK    Xcp_FlashErase
#define XCP_FLASH_PROGRAM_CALLBACK    Xcp_FlashProgram
#define XCP_FLASH_READ_CALLBACK    Xcp_FlashRead
#define XCP_GET_SEED_CALLBACK    Xcp_GetSeed
#define XCP_COMPARE_KEY_CALLBACK    Xcp_CompareKey
#define XCP_GET_TIMESTAMP_CALLBACK    Xcp_GetTimestamp
/*==================================================================================================
*                                    FUNCTION-LIKE MACROS (VERBATIM)
*================================================================================================*/
#define XCP_AG_TO_BYTES(x)                  ((x) << XCP_ADDRESS_GRANULARITY)
#define XCP_BYTES_TO_AG(x)                  ((x) >> XCP_ADDRESS_GRANULARITY)
#define XCP_IS_RESOURCE_PROTECTED(res, prot)    (((prot) & (res)) != 0U)
#define XCP_SET_RESOURCE_PROTECTION(res, prot)  ((prot) |= (res))
#define XCP_CLEAR_RESOURCE_PROTECTION(res, prot) ((prot) &= ~(res))


#endif /* XCP_CFG_H */

/*==================[end of file]===========================================*/
