/**
 * @file DoCan_Cfg.h
 * @brief DoCan Configuration configuration header
 * @version 1.0.0
 * @date 2026-08-10
 * @note AUTO-GENERATED by yuleASR Configurator
 */

#ifndef DOCAN_CFG_H
#define DOCAN_CFG_H

/*==================================================================================================
*                                    PRE-COMPILE CONFIGURATION
*================================================================================================*/

/*==================================================================================================
*                                    General Configuration
*================================================================================================*/
#define DOCAN_DEV_ERROR_DETECT    STD_ON
#define DOCAN_VERSION_INFO_API    STD_ON

/*==================================================================================================
*                                    Hardware Object Handles
*================================================================================================*/
#define DOCAN_DCM_TX_DIAG_PHYSICAL    (0U)
#define DOCAN_DCM_TX_DIAG_FUNCTIONAL    (1U)
#define DOCAN_DCM_RX_DIAG_PHYSICAL    (2U)
#define DOCAN_DCM_RX_DIAG_FUNCTIONAL    (3U)
#define DOCAN_CANTP_TX_DIAG_PHYSICAL    (0U)
#define DOCAN_CANTP_TX_DIAG_FUNCTIONAL    (1U)
#define DOCAN_CANTP_RX_DIAG_PHYSICAL    (0U)
#define DOCAN_CANTP_RX_DIAG_FUNCTIONAL    (1U)

/*==================================================================================================
*                                    Timing Configuration
*================================================================================================*/
#define DOCAN_MAIN_FUNCTION_PERIOD_MS    (10U)

/*==================================================================================================
*                                    Other Configuration
*================================================================================================*/
#define DOCAN_MAX_CHANNELS    (4U)
#define DOCAN_MAX_PDU_MAPPINGS    (8U)
#define DOCAN_CHANNEL_0    (0U)
#define DOCAN_CHANNEL_1    (1U)
#define DOCAN_CHANNEL_2    (2U)
#define DOCAN_CHANNEL_3    (3U)

#endif /* DOCAN_CFG_H */

/*==================[end of file]===========================================*/
