#!/usr/bin/env python3
"""
YuleTech BSW Code Generator

基于配置生成AutoSAR BSW代码
"""

import json
import os
from pathlib import Path
from typing import Dict, Any
from jinja2 import Template


# 代码生成模板
MCU_CFG_TEMPLATE = '''/*==================================================================================================
* Generated by YuleTech Code Generator
* Module: Mcu
* Version: {{ version }}
==================================================================================================*/

#ifndef MCU_CFG_H
#define MCU_CFG_H

/* Clock Configuration */
#define MCU_CLOCK_FREQUENCY     {{ clock_frequency }}U
#define MCU_CORE_COUNT          {{ core_count }}U

/* Version Info */
#define MCU_CFG_MAJOR_VERSION   1
#define MCU_CFG_MINOR_VERSION   0
#define MCU_CFG_PATCH_VERSION   0

#endif /* MCU_CFG_H */
'''

CAN_CFG_TEMPLATE = '''/*==================================================================================================
* Generated by YuleTech Code Generator
* Module: Can
* Version: {{ version }}
==================================================================================================*/

#ifndef CAN_CFG_H
#define CAN_CFG_H

/* CAN Configuration */
#define CAN_BAUDRATE            {{ baudrate }}U
#define CAN_CONTROLLER_COUNT    {{ controller_count }}U

/* Version Info */
#define CAN_CFG_MAJOR_VERSION   1
#define CAN_CFG_MINOR_VERSION   0
#define CAN_CFG_CFG_PATCH_VERSION   0

#endif /* CAN_CFG_H */
'''


class CodeGenerator:
    """代码生成器"""
    
    def __init__(self, config_path: str, output_path: str):
        self.config_path = Path(config_path)
        self.output_path = Path(output_path)
        self.config_data: Dict[str, Any] = {}
        
    def load_config(self) -> bool:
        """加载配置"""
        try:
            with open(self.config_path, 'r', encoding='utf-8') as f:
                self.config_data = json.load(f)
            return True
        except Exception as e:
            print(f"Error loading config: {e}")
            return False
    
    def generate_mcu_config(self) -> bool:
        """生成MCU配置"""
        try:
            module = self.config_data.get('modules', {}).get('Mcu', {})
            if not module.get('enabled', True):
                print("Mcu module is disabled, skipping...")
                return True
                
            template = Template(MCU_CFG_TEMPLATE)
            content = template.render(
                version=module.get('version', '1.0.0'),
                clock_frequency=module.get('clock_frequency', 800000000),
                core_count=module.get('core_count', 4)
            )
            
            output_file = self.output_path / "Mcu_Cfg.h"
            output_file.parent.mkdir(parents=True, exist_ok=True)
            
            with open(output_file, 'w', encoding='utf-8') as f:
                f.write(content)
                
            print(f"[OK] Generated: {output_file}")
            return True
        except Exception as e:
            print(f"[FAIL] Error generating Mcu config: {e}")
            return False
    
    def generate_can_config(self) -> bool:
        """生成CAN配置"""
        try:
            module = self.config_data.get('modules', {}).get('Can', {})
            if not module.get('enabled', True):
                print("Can module is disabled, skipping...")
                return True
                
            template = Template(CAN_CFG_TEMPLATE)
            content = template.render(
                version=module.get('version', '1.0.0'),
                baudrate=module.get('baudrate', 500000),
                controller_count=module.get('controller_count', 2)
            )
            
            output_file = self.output_path / "Can_Cfg.h"
            output_file.parent.mkdir(parents=True, exist_ok=True)
            
            with open(output_file, 'w', encoding='utf-8') as f:
                f.write(content)
                
            print(f"[OK] Generated: {output_file}")
            return True
        except Exception as e:
            print(f"[FAIL] Error generating Can config: {e}")
            return False
    
    def generate_all(self) -> bool:
        """生成所有配置"""
        print("YuleTech BSW Code Generator v1.0.0")
        print("=" * 50)
        
        if not self.load_config():
            return False
            
        success = True
        
        if not self.generate_mcu_config():
            success = False
            
        if not self.generate_can_config():
            success = False
            
        if success:
            print("\n[OK] Code generation completed successfully!")
        else:
            print("\n[FAIL] Code generation completed with errors")
            
        return success


def main():
    """主函数"""
    import sys
    
    if len(sys.argv) < 2:
        print("Usage: code_generator.py <config_file> [output_dir]")
        return 1
        
    config_file = sys.argv[1]
    output_dir = sys.argv[2] if len(sys.argv) > 2 else "./generated"
    
    generator = CodeGenerator(config_file, output_dir)
    
    if generator.generate_all():
        return 0
    else:
        return 1


if __name__ == "__main__":
    exit(main())
