/**
 * @file FrTp_Cfg.h
 * @brief FrTp Configuration configuration header
 * @version 1.0.0
 * @date 2026-08-10
 * @note AUTO-GENERATED by yuleASR Configurator
 */

#ifndef FRTP_CFG_H
#define FRTP_CFG_H

/*==================================================================================================
*                                    PRE-COMPILE CONFIGURATION
*================================================================================================*/

/*==================================================================================================
*                                    General Configuration
*================================================================================================*/
#ifndef FRTP_DEV_ERROR_DETECT
#define FRTP_DEV_ERROR_DETECT    STD_ON
#endif
#ifndef FRTP_VERSION_INFO_API
#define FRTP_VERSION_INFO_API    STD_ON
#endif

/*==================================================================================================
*                                    Module Configuration Counts
*================================================================================================*/
#ifndef FRTP_MAX_RETRY_COUNT
#define FRTP_MAX_RETRY_COUNT    (3U)
#endif

/*==================================================================================================
*                                    Hardware Object Handles
*================================================================================================*/
#define FRTP_FLAG_TX_ACTIVE    (1U)
#define FRTP_FLAG_RX_ACTIVE    (2U)
#define FRTP_TX_CONFIRMATION_ENABLED    STD_ON
#define FRTP_RX_INDICATION_ENABLED    STD_ON

/*==================================================================================================
*                                    Timing Configuration
*================================================================================================*/
#ifndef FRTP_DEFAULT_NAS_TIMEOUT
#define FRTP_DEFAULT_NAS_TIMEOUT    (100U)
#endif
#ifndef FRTP_DEFAULT_NBS_TIMEOUT
#define FRTP_DEFAULT_NBS_TIMEOUT    (100U)
#endif
#ifndef FRTP_DEFAULT_NCS_TIMEOUT
#define FRTP_DEFAULT_NCS_TIMEOUT    (100U)
#endif
#ifndef FRTP_DEFAULT_NAR_TIMEOUT
#define FRTP_DEFAULT_NAR_TIMEOUT    (100U)
#endif
#ifndef FRTP_DEFAULT_NBR_TIMEOUT
#define FRTP_DEFAULT_NBR_TIMEOUT    (100U)
#endif
#ifndef FRTP_DEFAULT_NCR_TIMEOUT
#define FRTP_DEFAULT_NCR_TIMEOUT    (100U)
#endif
#ifndef FRTP_MAIN_FUNCTION_PERIOD
#define FRTP_MAIN_FUNCTION_PERIOD    (5U)
#endif

/*==================================================================================================
*                                    Other Configuration
*================================================================================================*/
#define FRTP_CFG_VENDOR_ID    (1U)
#define FRTP_CFG_MODULE_ID    (45U)
#define FRTP_CFG_AR_RELEASE_MAJOR_VERSION    (4U)
#define FRTP_CFG_AR_RELEASE_MINOR_VERSION    (4U)
#define FRTP_CFG_SW_MAJOR_VERSION    (1U)
#define FRTP_CFG_SW_MINOR_VERSION    (0U)
#define FRTP_CFG_SW_PATCH_VERSION    (0U)
#ifndef FRTP_MAX_CONNECTIONS
#define FRTP_MAX_CONNECTIONS    (4U)
#endif
#ifndef FRTP_MAX_PAYLOAD_PER_FRAME
#define FRTP_MAX_PAYLOAD_PER_FRAME    (254U)
#endif
#ifndef FRTP_MAX_SF_PAYLOAD
#define FRTP_MAX_SF_PAYLOAD    (254U)
#endif
#ifndef FRTP_MAX_FF_PAYLOAD
#define FRTP_MAX_FF_PAYLOAD    (254U)
#endif
#ifndef FRTP_MAX_CF_PAYLOAD
#define FRTP_MAX_CF_PAYLOAD    (254U)
#endif
#ifndef FRTP_DEFAULT_BLOCK_SIZE
#define FRTP_DEFAULT_BLOCK_SIZE    (8U)
#endif
#ifndef FRTP_DEFAULT_STMIN
#define FRTP_DEFAULT_STMIN    (10U)
#endif
#ifndef FRTP_FLOW_CONTROL_ENABLED
#define FRTP_FLOW_CONTROL_ENABLED    STD_ON
#endif
#define FRTP_PCI_TYPE_MASK    (192U)
#define FRTP_PCI_TYPE_SF    (0U)
#define FRTP_PCI_TYPE_FF    (64U)
#define FRTP_PCI_TYPE_CF    (128U)
#define FRTP_PCI_TYPE_FC    (192U)
#define FRTP_PCI_SF_LENGTH_MASK    (63U)
#define FRTP_PCI_CF_SEQ_MASK    (15U)
#define FRTP_PCI_FC_STATUS_MASK    (15U)
#define FRTP_FC_STATUS_CTS    (0U)
#define FRTP_FC_STATUS_WAIT    (1U)
#define FRTP_FC_STATUS_OVFLW    (2U)
#define FRTP_FLAG_NONE    (0U)
#define FRTP_FLAG_FC_SENT    (4U)
#define FRTP_FLAG_WAIT_CONFIRM    (8U)
#define FRTP_FLAG_LAST_CF    (16U)

#endif /* FRTP_CFG_H */

/*==================[end of file]===========================================*/
