/**
 * @file Det_Cfg.h
 * @brief Det Configuration configuration header
 * @version 1.0.0
 * @date 2026-08-10
 * @note AUTO-GENERATED by yuleASR Configurator
 */

#ifndef DET_CFG_H
#define DET_CFG_H

/*==================================================================================================
*                                    PRE-COMPILE CONFIGURATION
*================================================================================================*/

/*==================================================================================================
*                                    General Configuration
*================================================================================================*/
#define DET_VERSION_INFO_API    STD_ON
#define DET_FORWARD_TO_DLT    STD_OFF
#define DET_FORWARD_TO_DEM    STD_ON
#define DET_ERROR_HOOKS_ENABLED    STD_ON
#define DET_RUNTIME_ERROR_CALLOUTS    STD_ON
#define DET_TRANSIENT_FAULT_CALLOUTS    STD_ON
#define DET_MAX_ERROR_HOOKS    (4U)
#define DET_MAX_RUNTIME_CALLOUTS    (2U)
#define DET_MAX_TRANSIENT_CALLOUTS    (2U)
#define DET_ENABLED    STD_ON
#define DET_FREEZE_ON_ERROR    STD_ON
#define DET_ERROR_LOGGING_ENABLED    STD_ON
#define DET_MAX_ERROR_ENTRIES    (10U)
#define DET_RUNTIME_ERROR_REPORTING    STD_ON
#define DET_TRANSIENT_FAULT_REPORTING    STD_OFF
#define DET_ERROR_HOOK_FORWARD    STD_ON
#define DET_RUNTIME_ERROR_HOOK_FORWARD    STD_ON
#define DET_TRANSIENT_FAULT_HOOK_FORWARD    STD_ON
#define DET_NUMBER_OF_ERROR_HOOKS    (1U)
#define DET_NUMBER_OF_RUNTIME_ERROR_HOOKS    (1U)
#define DET_NUMBER_OF_TRANSIENT_FAULT_HOOKS    (1U)
/*==================================================================================================
*                                    FUNCTION-LIKE MACROS (VERBATIM)
*================================================================================================*/
#define DET_DEM_EVENT_ID                (DemConf_DemEventParameter_DetError)


#endif /* DET_CFG_H */

/*==================[end of file]===========================================*/
