/**
 * @file RamSafety_Cfg.h
 * @brief RamSafety Configuration configuration header
 * @version 1.0.0
 * @date 2026-08-10
 * @note AUTO-GENERATED by yuleASR Configurator
 */

#ifndef RAMSAFETY_CFG_H
#define RAMSAFETY_CFG_H

#include "RamSafety.h"

#include "RamSafety.h"

/*==================================================================================================
*                                    PRE-COMPILE CONFIGURATION
*================================================================================================*/

/*==================================================================================================
*                                    General Configuration
*================================================================================================*/
#define RAMSAFETY_CFG_DEV_ERROR_DETECT    STD_ON
#define RAMSAFETY_CFG_VERSION_INFO_API    STD_ON

/*==================================================================================================
*                                    Module Configuration Counts
*================================================================================================*/
#define RAMSAFETY_CFG_NUM_REGIONS    (4U)

/*==================================================================================================
*                                    Timing Configuration
*================================================================================================*/
#define RAMSAFETY_CFG_STARTUP_TIMEOUT_MS    (5000U)
#define RAMSAFETY_CFG_RUNTIME_PERIOD_MS    (100U)

/*==================================================================================================
*                                    Other Configuration
*================================================================================================*/
#define RAMSAFETY_CFG_VENDOR_ID    (43U)
#define RAMSAFETY_CFG_AR_RELEASE_MAJOR_VERSION    (4U)
#define RAMSAFETY_CFG_AR_RELEASE_MINOR_VERSION    (7U)
#define RAMSAFETY_CFG_AR_RELEASE_REVISION_VERSION    (0U)
#define RAMSAFETY_CFG_SW_MAJOR_VERSION    (1U)
#define RAMSAFETY_CFG_SW_MINOR_VERSION    (0U)
#define RAMSAFETY_CFG_SW_PATCH_VERSION    (0U)
#define RAMSAFETY_CFG_HARDWARE_ECC    STD_ON
#define RAMSAFETY_CFG_CRC_VERIFICATION    STD_ON
#define RAMSAFETY_CFG_CRC_POLYNOMIAL    (79764919U)
#define RAMSAFETY_CFG_CRC_INITIAL    (4294967295U)
#define RAMSAFETY_CFG_MAX_REGIONS_PER_CYCLE    (1U)
#define RAMSAFETY_CFG_FAILURE_THRESHOLD    (3U)
#define RAMSAFETY_ADDR_DTCM_BASE    (536870912U)
#define RAMSAFETY_ADDR_DTCM_SIZE    (131072U)
#define RAMSAFETY_ADDR_SRAM_BASE    (541065216U)
#define RAMSAFETY_ADDR_SRAM_SIZE    (262144U)
#define RAMSAFETY_ADDR_FLEXRAM_BASE    (335544320U)
#define RAMSAFETY_ADDR_FLEXRAM_SIZE    (524288U)
#define RAMSAFETY_ADDR_STACK_BASE    (537001984U)
#define RAMSAFETY_ADDR_STACK_SIZE    (32768U)
#define RAMSAFETY_REGION_DTCM    (0U)
#define RAMSAFETY_REGION_SRAM    (1U)
#define RAMSAFETY_REGION_FLEXRAM    (2U)
#define RAMSAFETY_REGION_STACK    (3U)


/*==================================================================================================
*  NON-MACRO SEGMENT (preserved from handwritten header, merged by codegen splice)
*  typedef(0) + struct(0) + extern config tables(1) — 依赖宏段计数宏, 故置于宏段之后
*================================================================================================*/
extern const RamSafety_RegionType RamSafety_RegionConfig[RAMSAFETY_CFG_NUM_REGIONS];

#define RAMSAFETY_STOP_SEC_CONFIG_DATA_UNSPECIFIED
#include "RamSafety_MemMap.h"
#endif /* RAMSAFETY_CFG_H */

/*==================[end of file]===========================================*/
