/**
 * @file TcpIp_Cfg.h
 * @brief TcpIp Configuration configuration header
 * @version 1.0.0
 * @date 2026-08-10
 * @note AUTO-GENERATED by yuleASR Configurator
 */

#ifndef TCPIP_CFG_H
#define TCPIP_CFG_H

/*==================================================================================================
*                                    PRE-COMPILE CONFIGURATION
*================================================================================================*/

/*==================================================================================================
*                                    General Configuration
*================================================================================================*/
#define TCPIP_DEV_ERROR_DETECT    STD_ON
#define TCPIP_VERSION_INFO_API    STD_ON

/*==================================================================================================
*                                    Module Configuration Counts
*================================================================================================*/
#define TCPIP_MEMP_NUM_TCP_PCB    (8U)
#define TCPIP_MEMP_NUM_TCP_SEG    (32U)
#define TCPIP_MEMP_NUM_UDP_PCB    (8U)

/*==================================================================================================
*                                    Hardware Object Handles
*================================================================================================*/
#define TCPIP_MAX_RX_BUFFERS    (2U)

/*==================================================================================================
*                                    Timing Configuration
*================================================================================================*/
#define TCPIP_MAIN_FUNCTION_PERIOD_MS    (10U)
#define TCPIP_ARP_TIMEOUT_MS    (300000U)

/*==================================================================================================
*                                    Other Configuration
*================================================================================================*/
#define TCPIP_MAX_SOCKETS    (8U)
#define TCPIP_MAX_TCP_PBUFS    (16U)
#define TCPIP_MAX_UDP_PBUFS    (16U)
#define TCPIP_TCP_RCV_BUF_SIZE    (4096U)
#define TCPIP_TCP_SND_BUF_SIZE    (4096U)
#define TCPIP_UDP_RCV_BUF_SIZE    (2048U)
#define TCPIP_DEFAULT_IPV4_ADDR    (3232235522U)
#define TCPIP_DEFAULT_IPV4_MASK    (4294967040U)
#define TCPIP_DEFAULT_IPV4_GW    (3232235521U)
#define TCPIP_IPV6_LINKLOCAL    ""
#define TCPIP_ETH_LINK_CHECK_INTERVAL_MS    (100U)
#define TCPIP_MAX_PENDING_CONNECTIONS    (4U)
#define TCPIP_MAX_TCP_OPTIONS    (4U)
#define TCPIP_ENABLE_IPV4    STD_ON
#define TCPIP_ENABLE_IPV6    STD_OFF
#define TCPIP_ENABLE_TCP    STD_ON
#define TCPIP_ENABLE_UDP    STD_ON
#define TCPIP_ENABLE_ARP    STD_ON
#define TCPIP_ENABLE_DHCP    STD_OFF
#define TCPIP_ENABLE_DNS    STD_OFF
#define TCPIP_PBUF_POOL_SIZE    (32U)
#define TCPIP_PBUF_POOL_BUF_SIZE    (1518U)
#define TCPIP_VLAN_SUPPORT    STD_ON
#define TCPIP_DEFAULT_VLAN_ID    (0U)
#define TCPIP_DEFAULT_VLAN_PRIORITY    (0U)
#define TCPIP_ENABLE_STATISTICS    STD_ON

#endif /* TCPIP_CFG_H */

/*==================[end of file]===========================================*/
