/**
 * @file SomeIpSd_Cfg.h
 * @brief SomeIpSd Configuration configuration header
 * @version 1.0.0
 * @date 2026-08-10
 * @note AUTO-GENERATED by yuleASR Configurator
 */

#ifndef SOMEIPSD_CFG_H
#define SOMEIPSD_CFG_H


/*==================================================================================================
*                                    PRE-COMPILE CONFIGURATION
*================================================================================================*/

/*==================================================================================================
*                                    General Configuration
*================================================================================================*/
#define SOMEIPSD_DEV_ERROR_DETECT    STD_ON
#define SOMEIPSD_VERSION_INFO_API    STD_ON

/*==================================================================================================
*                                    Module Configuration Counts
*================================================================================================*/
#define SOMEIPSD_REPETITION_MAX_COUNT    (3U)
#define SOMEIPSD_NUM_OFFERED_SERVICES    (4U)
#define SOMEIPSD_NUM_REQUIRED_SERVICES    (4U)
#define SOMEIPSD_NUM_CONFIGURED_EVENTGROUPS    (8U)
#define SOMEIPSD_NUM_CONFIGURED_SUBSCRIPTIONS    (8U)

/*==================================================================================================
*                                    Timing Configuration
*================================================================================================*/
#define SOMEIPSD_MAIN_FUNCTION_PERIOD_MS    (10U)
#define SOMEIPSD_TTL_CHECK_PERIOD_MS    (100U)
#define SOMEIPSD_OFFER_CYCLE_PERIOD_MS    (1000U)

/*==================================================================================================
*                                    Other Configuration
*================================================================================================*/
#define SOMEIPSD_CFG_AR_RELEASE_MAJOR_VERSION    (4U)
#define SOMEIPSD_CFG_AR_RELEASE_MINOR_VERSION    (0U)
#define SOMEIPSD_CFG_AR_RELEASE_REVISION_VERSION    (3U)
#define SOMEIPSD_CFG_SW_MAJOR_VERSION    (1U)
#define SOMEIPSD_CFG_SW_MINOR_VERSION    (0U)
#define SOMEIPSD_CFG_SW_PATCH_VERSION    (0U)
#define SOMEIPSD_SERVER_SERVICE_DISCOVERY_ENABLED    STD_ON
#define SOMEIPSD_CLIENT_SERVICE_DISCOVERY_ENABLED    STD_ON
#define SOMEIPSD_EVENTGROUP_SUBSCRIPTION_ENABLED    STD_ON
#define SOMEIPSD_MULTICAST_RECEPTION_ENABLED    STD_ON
#define SOMEIPSD_REQUEST_RESPONSE_DELAY_ENABLED    STD_ON
#define SOMEIPSD_MAX_MESSAGE_SIZE    (1400U)
#define SOMEIPSD_MAX_ENTRIES_PER_MESSAGE    (16U)
#define SOMEIPSD_MAX_OPTIONS_PER_MESSAGE    (32U)
#define SOMEIPSD_ENTRY_HEADER_SIZE    (16U)
#define SOMEIPSD_IPV4_ENDPOINT_OPTION_SIZE    (9U)
#define SOMEIPSD_IPV6_ENDPOINT_OPTION_SIZE    (21U)
#define SOMEIPSD_CONFIGURATION_OPTION_MAX_SIZE    (256U)
#define SOMEIPSD_MAX_OFFERED_SERVICES    (8U)
#define SOMEIPSD_MAX_FOUND_SERVICES    (16U)
#define SOMEIPSD_MAX_SUBSCRIBED_EVENTGROUPS    (16U)
#define SOMEIPSD_MAX_EVENTGROUPS_PER_SERVICE    (4U)
#define SOMEIPSD_INITIAL_DELAY_MIN_MS    (50U)
#define SOMEIPSD_INITIAL_DELAY_MAX_MS    (150U)
#define SOMEIPSD_REPETITION_BASE_DELAY_MS    (100U)
#define SOMEIPSD_CYCLIC_OFFER_DELAY_MS    (3000U)
#define SOMEIPSD_CYCLIC_FIND_DELAY_MS    (3000U)
#define SOMEIPSD_OFFER_TTL_MS    (3000U)
#define SOMEIPSD_SUBSCRIPTION_TTL_MS    (3000U)
#define SOMEIPSD_TTL_FACTOR_OFFER    (3U)
#define SOMEIPSD_TTL_FACTOR_SUBSCRIBE    (3U)
#define SOMEIPSD_REQUEST_RESPONSE_DELAY_MIN_MS    (10U)
#define SOMEIPSD_REQUEST_RESPONSE_DELAY_MAX_MS    (100U)
#define SOMEIPSD_MULTICAST_IP_ADDRESS    (3774144757U)
#define SOMEIPSD_MULTICAST_PORT    (30490U)
#define SOMEIPSD_UNICAST_PORT    (30500U)
#define SOMEIPSD_LOCAL_IP_ADDRESS    (3232235786U)
#define SOMEIPSD_SUBNET_MASK    (4294967040U)
#define SOMEIPSD_DEFAULT_PROTOCOL    (17U)
#define SOMEIPSD_PROTOCOL    (17U)
#define SOMEIPSD_PROTO_TCP    (6U)
#define SOMEIPSD_PROTO_UDP    (17U)
#define SOMEIPSD_ENTRY_TYPE_FIND_SERVICE    (0U)
#define SOMEIPSD_ENTRY_TYPE_OFFER_SERVICE    (1U)
#define SOMEIPSD_ENTRY_TYPE_SUBSCRIBE    (6U)
#define SOMEIPSD_ENTRY_TYPE_SUBSCRIBE_ACK    (7U)
#define SOMEIPSD_ENTRY_TYPE_STOP_OFFER    (1U)
#define SOMEIPSD_ENTRY_TYPE_STOP_SUBSCRIBE    (6U)
#define SOMEIPSD_OPTION_TYPE_CONFIGURATION    (1U)
#define SOMEIPSD_OPTION_TYPE_LOAD_BALANCING    (2U)
#define SOMEIPSD_OPTION_TYPE_IPV4_ENDPOINT    (4U)
#define SOMEIPSD_OPTION_TYPE_IPV4_MULTICAST    (20U)
#define SOMEIPSD_OPTION_TYPE_IPV6_ENDPOINT    (6U)
#define SOMEIPSD_OPTION_TYPE_IPV6_MULTICAST    (22U)
#define SOMEIPSD_OPTION_CONFIG_LENGTH    (2U)
#define SOMEIPSD_FLAG_REBOOT    (128U)
#define SOMEIPSD_FLAG_UNICAST    (64U)
#define SOMEIPSD_FLAG_EXPLICIT_INIT_DATA    (32U)
#define SOMEIPSD_FLAGS_DEFAULT    (128U)
#define SOMEIPSD_FLAGS_RUNNING    (0U)
#define SOMEIPSD_DEFAULT_MAJOR_VERSION    (1U)
#define SOMEIPSD_DEFAULT_MINOR_VERSION    (0U)
#define SOMEIPSD_INSTANCE_ID_WILDCARD    (65535U)
#define SOMEIPSD_MAJOR_VERSION_WILDCARD    (255U)
#define SOMEIPSD_MINOR_VERSION_WILDCARD    (4294967295U)
#define SOMEIPSD_INSTANCE_ID_VEHICLE_01    (1U)
#define SOMEIPSD_INSTANCE_ID_VEHICLE_02    (2U)
#define SOMEIPSD_INSTANCE_ID_ENGINE_01    (1U)
#define SOMEIPSD_INSTANCE_ID_ENGINE_02    (2U)
#define SOMEIPSD_INSTANCE_ID_CHASSIS_01    (1U)
#define SOMEIPSD_INSTANCE_ID_BODY_01    (1U)
#define SOMEIPSD_MAX_EVENTGROUPS    (4U)
#define SOMEIPSD_EVENTGROUP_NOT_AVAILABLE    (0U)
#define SOMEIPSD_EVENTGROUP_VEHICLE_STATUS    (1U)
#define SOMEIPSD_EVENTGROUP_VEHICLE_POSITION    (2U)
#define SOMEIPSD_EVENTGROUP_VEHICLE_DIAGNOSTIC    (3U)
#define SOMEIPSD_EVENTGROUP_ENGINE_STATUS    (1U)
#define SOMEIPSD_EVENTGROUP_ENGINE_DIAGNOSTIC    (2U)
#define SOMEIPSD_EVENTGROUP_CHASSIS_STATUS    (1U)
#define SOMEIPSD_EVENTGROUP_BODY_STATUS    (1U)
#define SOMEIPSD_EVENTGROUP_BODY_COMFORT    (2U)
#define SOMEIPSD_MAX_FIND_SERVICE_RETRIES    (3U)
#define SOMEIPSD_MAX_SUBSCRIBE_RETRIES    (3U)
#define SOMEIPSD_FIND_SERVICE_RETRY_DELAY_MS    (1000U)
#define SOMEIPSD_SUBSCRIBE_RETRY_DELAY_MS    (1000U)
#define SOMEIPSD_SERVICE_AVAILABILITY_CALLBACKS    STD_ON
#define SOMEIPSD_SUBSCRIPTION_STATE_CALLBACKS    STD_ON


/*==================================================================================================
*  NON-MACRO SEGMENT (preserved from handwritten header, merged by codegen splice)
*  typedef(0) + struct(5) + extern config tables(5) — 依赖宏段计数宏, 故置于宏段之后
*================================================================================================*/
typedef struct SomeIpSd_OfferedServiceConfigType_tag SomeIpSd_OfferedServiceConfigType;
typedef struct SomeIpSd_RequiredServiceConfigType_tag SomeIpSd_RequiredServiceConfigType;
typedef struct SomeIpSd_EventGroupConfigType_tag SomeIpSd_EventGroupConfigType;
typedef struct SomeIpSd_SubscriptionConfigType_tag SomeIpSd_SubscriptionConfigType;
typedef struct SomeIpSd_ConfigType_tag SomeIpSd_ConfigType;

/*==================================================================================================
*                                    EXTERNAL CONFIGURATION
==================================================================================================*/

/**
 * @brief External declaration of the SOME/IP-SD configuration
 */
extern const SomeIpSd_ConfigType SomeIpSd_Config;

/**
 * @brief External declaration of offered service configurations
 */
extern const SomeIpSd_OfferedServiceConfigType SomeIpSd_OfferedServices[SOMEIPSD_NUM_OFFERED_SERVICES];

/**
 * @brief External declaration of required service configurations
 */
extern const SomeIpSd_RequiredServiceConfigType SomeIpSd_RequiredServices[SOMEIPSD_NUM_REQUIRED_SERVICES];

/**
 * @brief External declaration of event group configurations
 */
extern const SomeIpSd_EventGroupConfigType SomeIpSd_EventGroups[SOMEIPSD_NUM_CONFIGURED_EVENTGROUPS];

/**
 * @brief External declaration of subscription configurations
 */
extern const SomeIpSd_SubscriptionConfigType SomeIpSd_Subscriptions[SOMEIPSD_NUM_CONFIGURED_SUBSCRIPTIONS];
#endif /* SOMEIPSD_CFG_H */

/*==================[end of file]===========================================*/
