"""
DDS Configuration C Code Generator

Generates C header and source files from DDS configuration.
Supports AUTOSAR integration and E2E protection configuration.
"""

from pathlib import Path
from typing import Dict, Any, List, Optional, Union
from datetime import datetime


class CGenerator:
    """Generator for DDS C code configuration files."""
    
    def __init__(self):
        self.output_dir: Optional[Path] = None
        self.config: Dict[str, Any] = {}
        self.indent = "    "
    
    def generate(self, config: Dict[str, Any], output_dir: Union[str, Path]) -> List[Path]:
        """
        Generate C code from configuration.
        
        Args:
            config: Configuration dictionary
            output_dir: Output directory path
            
        Returns:
            List of generated file paths
        """
        self.config = config
        self.output_dir = Path(output_dir)
        self.output_dir.mkdir(parents=True, exist_ok=True)
        
        generated_files = []
        
        # Generate main configuration header
        dds_cfg_path = self._generate_dds_cfg_h()
        generated_files.append(dds_cfg_path)
        
        # Generate topic configuration header
        topic_cfg_path = self._generate_dds_topic_cfg_h()
        generated_files.append(topic_cfg_path)
        
        # Generate QoS configuration header
        qos_cfg_path = self._generate_dds_qos_cfg_h()
        generated_files.append(qos_cfg_path)
        
        # Generate transport configuration
        transport_cfg_path = self._generate_dds_transport_cfg_h()
        generated_files.append(transport_cfg_path)
        
        # Generate source file
        source_path = self._generate_dds_cfg_c()
        generated_files.append(source_path)
        
        # Generate AUTOSAR integration if needed
        if config.get('autosar'):
            autosar_path = self._generate_bswm_dds_rules_h()
            generated_files.append(autosar_path)
        
        return generated_files
    
    def _generate_header_guard(self, name: str) -> str:
        """Generate header guard macro."""
        return f"DDS_{name.upper()}_H"
    
    def _generate_file_header(self, filename: str, description: str) -> str:
        """Generate file header comment."""
        timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        return f"""/**
 * @file {filename}
 * @brief {description}
 * 
 * @warning This file is auto-generated by DDS Configuration Tool.
 *          Do not edit manually.
 * 
 * Generated: {timestamp}
 * Version: 1.0
 */

#ifndef {self._generate_header_guard(filename.replace('.', '_'))}
#define {self._generate_header_guard(filename.replace('.', '_'))}

/*==================================================================================================
*                                        INCLUDE FILES
==================================================================================================*/

"""
    
    def _generate_file_footer(self, filename: str) -> str:
        """Generate file footer."""
        return f"""
#endif /* {self._generate_header_guard(filename.replace('.', '_'))} */
/* End of file */
"""
    
    def _generate_dds_cfg_h(self) -> Path:
        """Generate Dds_Cfg.h main configuration header."""
        filename = "Dds_Cfg.h"
        filepath = self.output_dir / "include" / "dds" / filename
        filepath.parent.mkdir(parents=True, exist_ok=True)
        
        content = []
        content.append(self._generate_file_header(filename, "DDS Main Configuration"))
        
        # Includes
        content.append("#include \"Std_Types.h\"")
        content.append("#include \"Dds_Types.h\"")
        content.append("")
        
        # Version info
        content.append("/*==================================================================================================")
        content.append("*                                       VERSION INFO")
        content.append("==================================================================================================*/")
        content.append("")
        content.append("#define DDS_CFG_MAJOR_VERSION    1u")
        content.append("#define DDS_CFG_MINOR_VERSION    0u")
        content.append("#define DDS_CFG_PATCH_VERSION    0u")
        content.append("")
        
        # Domain configuration
        domain = self.config.get('domain', {})
        content.append("/*==================================================================================================")
        content.append("*                                       DOMAIN CONFIGURATION")
        content.append("==================================================================================================*/")
        content.append("")
        content.append(f"#define DDS_CFG_DOMAIN_ID        ({domain.get('domain_id', 0)}U)")
        content.append(f"#define DDS_CFG_DOMAIN_NAME      \"{domain.get('name', 'default')}\"")
        content.append("")
        
        # Discovery configuration
        discovery = domain.get('discovery', {})
        content.append("/* Discovery Settings */")
        content.append(f"#define DDS_CFG_DISCOVERY_PROTOCOL    DDS_DISC_{discovery.get('protocol', 'SIMPLE')}")
        content.append(f"#define DDS_CFG_LEASE_DURATION_SEC    ({discovery.get('lease_duration', 10)}U)")
        content.append(f"#define DDS_CFG_ANNOUNCE_PERIOD_SEC   ({discovery.get('announce_period', 5)}U)")
        content.append("")
        
        # Multicast configuration
        multicast = discovery.get('multicast', {})
        content.append("/* Multicast Settings */")
        content.append(f"#define DDS_CFG_MULTICAST_ENABLED     STD_{'ENABLED' if multicast.get('enabled', True) else 'DISABLED'}")
        content.append(f"#define DDS_CFG_MULTICAST_ADDR        \"{multicast.get('address', '239.255.0.1')}\"")
        content.append(f"#define DDS_CFG_MULTICAST_PORT        ({multicast.get('port', 7400)}U)")
        content.append("")
        
        # Transport configuration
        transport = domain.get('transport', {})
        content.append("/*==================================================================================================")
        content.append("*                                      TRANSPORT CONFIGURATION")
        content.append("==================================================================================================*/")
        content.append("")
        content.append(f"#define DDS_CFG_DEFAULT_TRANSPORT     DDS_TRANSPORT_{transport.get('default', 'UDPv4')}")
        content.append(f"#define DDS_CFG_SHM_ENABLED           STD_{'ENABLED' if transport.get('shm_enabled', True) else 'DISABLED'}")
        content.append(f"#define DDS_CFG_INTRA_PROCESS         STD_{'ENABLED' if transport.get('intra_process', True) else 'DISABLED'}")
        content.append("")
        
        # Resource limits
        resources = domain.get('resources', {})
        content.append("/*==================================================================================================")
        content.append("*                                      RESOURCE LIMITS")
        content.append("==================================================================================================*/")
        content.append("")
        content.append(f"#define DDS_CFG_MAX_PARTICIPANTS      ({resources.get('max_participants', 10)}U)")
        content.append(f"#define DDS_CFG_MAX_DOMAINS           ({resources.get('max_domains', 1)}U)")
        content.append(f"#define DDS_CFG_SHM_SIZE_KB           ({resources.get('shm_size_kb', 65536)}U)")
        content.append(f"#define DDS_CFG_SHM_SEGMENTS          ({resources.get('shm_segments', 10)}U)")
        content.append("")
        
        # Timing configuration
        timing = domain.get('timing', {})
        content.append("/*==================================================================================================")
        content.append("*                                       TIMING CONFIGURATION")
        content.append("==================================================================================================*/")
        content.append("")
        content.append(f"#define DDS_CFG_SPIN_FREQUENCY        ({timing.get('spin_frequency', 100)}U)")
        content.append(f"#define DDS_CFG_MAX_BLOCKING_MS       ({timing.get('max_blocking_time', 1000)}U)")
        content.append("")
        
        # Topic count
        topics = self.config.get('topics', [])
        content.append("/*==================================================================================================")
        content.append("*                                       TOPIC CONFIGURATION")
        content.append("==================================================================================================*/")
        content.append("")
        content.append(f"#define DDS_CFG_NUM_TOPICS            ({len(topics)}U)")
        content.append("")
        
        # Extern declarations
        content.append("/*==================================================================================================")
        content.append("*                                  EXTERNAL FUNCTION DECLARATIONS")
        content.append("==================================================================================================*/")
        content.append("")
        content.append("extern void Dds_Init(const Dds_ConfigType* configPtr);")
        content.append("extern void Dds_Deinit(void);")
        content.append("extern Std_ReturnType Dds_Start(void);")
        content.append("extern void Dds_Stop(void);")
        content.append("")
        
        content.append(self._generate_file_footer(filename))
        
        filepath.write_text('\n'.join(content))
        return filepath
    
    def _generate_dds_topic_cfg_h(self) -> Path:
        """Generate Dds_TopicCfg.h topic configuration header."""
        filename = "Dds_TopicCfg.h"
        filepath = self.output_dir / "include" / "dds" / filename
        filepath.parent.mkdir(parents=True, exist_ok=True)
        
        content = []
        content.append(self._generate_file_header(filename, "DDS Topic Configuration"))
        
        content.append("#include \"Dds_Cfg.h\"")
        content.append("#include \"Dds_Types.h\"")
        content.append("")
        
        # Topic IDs enum
        content.append("/*==================================================================================================")
        content.append("*                                       TOPIC IDENTIFIERS")
        content.append("==================================================================================================*/")
        content.append("")
        content.append("typedef enum")
        content.append("{")
        
        topics = self.config.get('topics', [])
        for i, topic in enumerate(topics):
            topic_name = topic.get('name', f'TOPIC_{i}').upper()
            content.append(f"    DDS_TOPIC_ID_{topic_name} = {i}U,")
        
        if not topics:
            content.append("    DDS_TOPIC_ID_NONE = 0U,")
        
        content.append("    DDS_TOPIC_ID_MAX")
        content.append("} Dds_TopicIdType;")
        content.append("")
        
        # Topic kinds enum
        content.append("/*==================================================================================================")
        content.append("*                                       TOPIC KINDS")
        content.append("==================================================================================================*/")
        content.append("")
        content.append("typedef enum")
        content.append("{")
        content.append("    DDS_TOPIC_KIND_STANDARD = 0U,")
        content.append("    DDS_TOPIC_KIND_SIGNAL,")
        content.append("    DDS_TOPIC_KIND_SERVICE,")
        content.append("    DDS_TOPIC_KIND_EVENT,")
        content.append("    DDS_TOPIC_KIND_FIELD")
        content.append("} Dds_TopicKindType;")
        content.append("")
        
        # Topic configuration structure
        content.append("/*==================================================================================================")
        content.append("*                                  TOPIC CONFIGURATION STRUCTURES")
        content.append("==================================================================================================*/")
        content.append("")
        content.append("typedef struct")
        content.append("{")
        content.append(f"{self.indent}Dds_TopicIdType       topicId;")
        content.append(f"{self.indent}Dds_TopicKindType     kind;")
        content.append(f"{self.indent}const char*           name;")
        content.append(f"{self.indent}const char*           dataType;")
        content.append(f"{self.indent}uint16                maxInstances;")
        content.append(f"{self.indent}boolean               e2eEnabled;")
        content.append(f"{self.indent}uint8                 e2eProfile;")
        content.append(f"{self.indent}uint16                e2eDataId;")
        content.append("} Dds_TopicConfigType;")
        content.append("")
        
        # Topic configuration declarations
        content.append("/*==================================================================================================")
        content.append("*                                  TOPIC CONFIGURATION DATA")
        content.append("==================================================================================================*/")
        content.append("")
        content.append(f"#define DDS_CFG_NUM_TOPIC_CONFIGS     ({len(topics)}U)")
        content.append("")
        content.append("extern const Dds_TopicConfigType Dds_TopicConfigs[DDS_CFG_NUM_TOPIC_CONFIGS];")
        content.append("")
        
        # E2E profile definitions
        content.append("/*==================================================================================================")
        content.append("*                                       E2E PROFILES")
        content.append("==================================================================================================*/")
        content.append("")
        content.append("#define DDS_E2E_PROFILE_NONE          0x00U")
        content.append("#define DDS_E2E_PROFILE_P01           0x01U")
        content.append("#define DDS_E2E_PROFILE_P02           0x02U")
        content.append("#define DDS_E2E_PROFILE_P04           0x04U")
        content.append("#define DDS_E2E_PROFILE_P05           0x05U")
        content.append("#define DDS_E2E_PROFILE_P06           0x06U")
        content.append("#define DDS_E2E_PROFILE_P07           0x07U")
        content.append("#define DDS_E2E_PROFILE_P11           0x0BU")
        content.append("#define DDS_E2E_PROFILE_P22           0x16U")
        content.append("")
        
        content.append(self._generate_file_footer(filename))
        
        filepath.write_text('\n'.join(content))
        return filepath
    
    def _generate_dds_qos_cfg_h(self) -> Path:
        """Generate Dds_QosCfg.h QoS configuration header."""
        filename = "Dds_QosCfg.h"
        filepath = self.output_dir / "include" / "dds" / filename
        filepath.parent.mkdir(parents=True, exist_ok=True)
        
        content = []
        content.append(self._generate_file_header(filename, "DDS QoS Configuration"))
        
        content.append("#include \"Dds_Cfg.h\"")
        content.append("#include \"Dds_Types.h\"")
        content.append("")
        
        # QoS policy kinds
        content.append("/*==================================================================================================")
        content.append("*                                       QOS POLICY KINDS")
        content.append("==================================================================================================*/")
        content.append("")
        
        # Reliability
        content.append("typedef enum")
        content.append("{")
        content.append("    DDS_RELIABILITY_BEST_EFFORT = 0U,")
        content.append("    DDS_RELIABILITY_RELIABLE")
        content.append("} Dds_ReliabilityKindType;")
        content.append("")
        
        # Durability
        content.append("typedef enum")
        content.append("{")
        content.append("    DDS_DURABILITY_VOLATILE = 0U,")
        content.append("    DDS_DURABILITY_TRANSIENT_LOCAL,")
        content.append("    DDS_DURABILITY_TRANSIENT,")
        content.append("    DDS_DURABILITY_PERSISTENT")
        content.append("} Dds_DurabilityKindType;")
        content.append("")
        
        # History
        content.append("typedef enum")
        content.append("{")
        content.append("    DDS_HISTORY_KEEP_LAST = 0U,")
        content.append("    DDS_HISTORY_KEEP_ALL")
        content.append("} Dds_HistoryKindType;")
        content.append("")
        
        # Liveliness
        content.append("typedef enum")
        content.append("{")
        content.append("    DDS_LIVELINESS_AUTOMATIC = 0U,")
        content.append("    DDS_LIVELINESS_MANUAL_BY_PARTICIPANT,")
        content.append("    DDS_LIVELINESS_MANUAL_BY_TOPIC")
        content.append("} Dds_LivelinessKindType;")
        content.append("")
        
        # QoS configuration structure
        content.append("/*==================================================================================================")
        content.append("*                                  QOS CONFIGURATION STRUCTURES")
        content.append("==================================================================================================*/")
        content.append("")
        content.append("typedef struct")
        content.append("{")
        content.append(f"{self.indent}Dds_ReliabilityKindType   kind;")
        content.append(f"{self.indent}uint32                    maxBlockingTimeMs;")
        content.append("} Dds_ReliabilityQosType;")
        content.append("")
        
        content.append("typedef struct")
        content.append("{")
        content.append(f"{self.indent}Dds_DurabilityKindType    kind;")
        content.append("} Dds_DurabilityQosType;")
        content.append("")
        
        content.append("typedef struct")
        content.append("{")
        content.append(f"{self.indent}Dds_HistoryKindType       kind;")
        content.append(f"{self.indent}uint32                    depth;")
        content.append("} Dds_HistoryQosType;")
        content.append("")
        
        content.append("typedef struct")
        content.append("{")
        content.append(f"{self.indent}Dds_LivelinessKindType    kind;")
        content.append(f"{self.indent}uint32                    leaseDurationSec;")
        content.append("} Dds_LivelinessQosType;")
        content.append("")
        
        content.append("typedef struct")
        content.append("{")
        content.append(f"{self.indent}Dds_ReliabilityQosType    reliability;")
        content.append(f"{self.indent}Dds_DurabilityQosType     durability;")
        content.append(f"{self.indent}Dds_HistoryQosType        history;")
        content.append(f"{self.indent}Dds_LivelinessQosType     liveliness;")
        content.append(f"{self.indent}uint32                    deadlineMs;")
        content.append(f"{self.indent}uint32                    latencyBudgetMs;")
        content.append(f"{self.indent}uint8                     transportPriority;")
        content.append("} Dds_QosProfileType;")
        content.append("")
        
        # QoS profile declarations
        content.append("/*==================================================================================================")
        content.append("*                                  QOS PROFILE CONFIGURATIONS")
        content.append("==================================================================================================*/")
        content.append("")
        
        profiles = self.config.get('qos_profiles', [])
        for profile in profiles:
            profile_name = profile.get('name', 'default').upper()
            content.append(f"extern const Dds_QosProfileType Dds_QosProfile_{profile_name};")
        
        content.append("")
        
        content.append(self._generate_file_footer(filename))
        
        filepath.write_text('\n'.join(content))
        return filepath
    
    def _generate_dds_transport_cfg_h(self) -> Path:
        """Generate Dds_TransportCfg.h transport configuration header."""
        filename = "Dds_TransportCfg.h"
        filepath = self.output_dir / "include" / "dds" / filename
        filepath.parent.mkdir(parents=True, exist_ok=True)
        
        content = []
        content.append(self._generate_file_header(filename, "DDS Transport Configuration"))
        
        content.append("#include \"Dds_Cfg.h\"")
        content.append("#include \"Dds_Types.h\"")
        content.append("")
        
        # Transport kinds
        content.append("/*==================================================================================================")
        content.append("*                                       TRANSPORT KINDS")
        content.append("==================================================================================================*/")
        content.append("")
        content.append("typedef enum")
        content.append("{")
        content.append("    DDS_TRANSPORT_UDPV4 = 0U,")
        content.append("    DDS_TRANSPORT_UDPV6,")
        content.append("    DDS_TRANSPORT_SHM,")
        content.append("    DDS_TRANSPORT_TCPV4,")
        content.append("    DDS_TRANSPORT_TCPV6,")
        content.append("    DDS_TRANSPORT_INTRA")
        content.append("} Dds_TransportKindType;")
        content.append("")
        
        # Transport configuration structure
        content.append("/*==================================================================================================")
        content.append("*                                  TRANSPORT CONFIGURATION STRUCTURES")
        content.append("==================================================================================================*/")
        content.append("")
        content.append("typedef struct")
        content.append("{")
        content.append(f"{self.indent}uint16    port;")
        content.append(f"{self.indent}uint8     ttl;")
        content.append(f"{self.indent}uint32    recvBufferSize;")
        content.append(f"{self.indent}uint32    sendBufferSize;")
        content.append("} Dds_UdpConfigType;")
        content.append("")
        
        content.append("typedef struct")
        content.append("{")
        content.append(f"{self.indent}uint32    segmentSize;")
        content.append(f"{self.indent}uint16    maxSegments;")
        content.append(f"{self.indent}boolean   zeroCopy;")
        content.append("} Dds_ShmConfigType;")
        content.append("")
        
        content.append("typedef struct")
        content.append("{")
        content.append(f"{self.indent}Dds_TransportKindType  kind;")
        content.append(f"{self.indent}boolean                enabled;")
        content.append(f"{self.indent}uint8                  priority;")
        content.append(f"{self.indent}Dds_UdpConfigType      udp;")
        content.append(f"{self.indent}Dds_ShmConfigType      shm;")
        content.append("} Dds_TransportConfigType;")
        content.append("")
        
        # Transport configurations
        transports = self.config.get('transports', [])
        content.append("/*==================================================================================================")
        content.append("*                                  TRANSPORT CONFIGURATION DATA")
        content.append("==================================================================================================*/")
        content.append("")
        content.append(f"#define DDS_CFG_NUM_TRANSPORTS        ({len(transports)}U)")
        content.append("")
        content.append("extern const Dds_TransportConfigType Dds_TransportConfigs[DDS_CFG_NUM_TRANSPORTS];")
        content.append("")
        
        content.append(self._generate_file_footer(filename))
        
        filepath.write_text('\n'.join(content))
        return filepath
    
    def _generate_dds_cfg_c(self) -> Path:
        """Generate Dds_Cfg.c source file."""
        filename = "Dds_Cfg.c"
        filepath = self.output_dir / "src" / "dds" / filename
        filepath.parent.mkdir(parents=True, exist_ok=True)
        
        content = []
        content.append(self._generate_file_header(filename, "DDS Configuration Source"))
        
        content.append("#include \"Dds_Cfg.h\"")
        content.append("#include \"Dds_TopicCfg.h\"")
        content.append("#include \"Dds_QosCfg.h\"")
        content.append("#include \"Dds_TransportCfg.h\"")
        content.append("")
        
        # Topic configurations
        topics = self.config.get('topics', [])
        content.append("/*==================================================================================================")
        content.append("*                                  TOPIC CONFIGURATION DATA")
        content.append("==================================================================================================*/")
        content.append("")
        content.append("const Dds_TopicConfigType Dds_TopicConfigs[DDS_CFG_NUM_TOPIC_CONFIGS] =")
        content.append("{")
        
        for i, topic in enumerate(topics):
            topic_name = topic.get('name', f'topic_{i}')
            kind = topic.get('kind', 'STANDARD')
            data_type = topic.get('data_type', 'void')
            max_instances = topic.get('max_instances', 1)
            security = topic.get('security', {})
            e2e_enabled = 'TRUE' if security.get('e2e_enabled', False) else 'FALSE'
            e2e_profile = security.get('e2e_profile', 'P01')
            e2e_data_id = security.get('e2e_data_id', 0)
            
            content.append(f"    {{ /* {topic_name} */")
            content.append(f"        .topicId = DDS_TOPIC_ID_{topic_name.upper()},")
            content.append(f"        .kind = DDS_TOPIC_KIND_{kind},")
            content.append(f"        .name = \"{topic_name}\",")
            content.append(f"        .dataType = \"{data_type}\",")
            content.append(f"        .maxInstances = {max_instances}U,")
            content.append(f"        .e2eEnabled = {e2e_enabled},")
            content.append(f"        .e2eProfile = DDS_E2E_PROFILE_{e2e_profile},")
            content.append(f"        .e2eDataId = {e2e_data_id}U")
            content.append("    },")
        
        content.append("};")
        content.append("")
        
        # QoS profiles
        profiles = self.config.get('qos_profiles', [])
        if profiles:
            content.append("/*==================================================================================================")
            content.append("*                                  QOS PROFILE DATA")
            content.append("==================================================================================================*/")
            content.append("")
            
            for profile in profiles:
                profile_name = profile.get('name', 'default')
                reliability = profile.get('reliability', {})
                durability = profile.get('durability', {})
                history = profile.get('history', {})
                liveliness = profile.get('liveliness', {})
                
                rel_kind = reliability.get('kind', 'RELIABLE')
                max_blocking = reliability.get('max_blocking_time', 100)
                dur_kind = durability.get('kind', 'VOLATILE')
                hist_kind = history.get('kind', 'KEEP_LAST')
                hist_depth = history.get('depth', 1)
                live_kind = liveliness.get('kind', 'AUTOMATIC')
                lease_dur = liveliness.get('lease_duration', 10)
                deadline = profile.get('deadline', {}).get('period', 0) * 1000
                latency = profile.get('latency_budget', 0) * 1000
                priority = profile.get('transport_priority', 0)
                
                content.append(f"const Dds_QosProfileType Dds_QosProfile_{profile_name.upper()} =")
                content.append("{")
                content.append(f"    .reliability = {{")
                content.append(f"        .kind = DDS_RELIABILITY_{rel_kind},")
                content.append(f"        .maxBlockingTimeMs = {int(max_blocking * 1000)}U")
                content.append("    },")
                content.append(f"    .durability = {{")
                content.append(f"        .kind = DDS_DURABILITY_{dur_kind}")
                content.append("    },")
                content.append(f"    .history = {{")
                content.append(f"        .kind = DDS_HISTORY_{hist_kind},")
                content.append(f"        .depth = {hist_depth}U")
                content.append("    },")
                content.append(f"    .liveliness = {{")
                content.append(f"        .kind = DDS_LIVELINESS_{live_kind},")
                content.append(f"        .leaseDurationSec = {int(lease_dur)}U")
                content.append("    },")
                content.append(f"    .deadlineMs = {int(deadline)}U,")
                content.append(f"    .latencyBudgetMs = {int(latency)}U,")
                content.append(f"    .transportPriority = {priority}U")
                content.append("};")
                content.append("")
        
        # Transport configurations
        transports = self.config.get('transports', [])
        content.append("/*==================================================================================================")
        content.append("*                                  TRANSPORT CONFIGURATION DATA")
        content.append("==================================================================================================*/")
        content.append("")
        content.append("const Dds_TransportConfigType Dds_TransportConfigs[DDS_CFG_NUM_TRANSPORTS] =")
        content.append("{")
        
        for transport in transports:
            ttype = transport.get('type', 'UDPv4')
            enabled = 'TRUE' if transport.get('enabled', True) else 'FALSE'
            priority = transport.get('priority', 0)
            udp = transport.get('udp', {})
            shm = transport.get('shm', {})
            
            content.append("    {")
            content.append(f"        .kind = DDS_TRANSPORT_{ttype.upper().replace('V', 'V')},")
            content.append(f"        .enabled = {enabled},")
            content.append(f"        .priority = {priority}U,")
            content.append("        .udp = {")
            content.append(f"            .port = {udp.get('port', 7400)}U,")
            content.append(f"            .ttl = {udp.get('ttl', 1)}U,")
            content.append(f"            .recvBufferSize = {udp.get('recv_buffer', 2097152)}U,")
            content.append(f"            .sendBufferSize = {udp.get('send_buffer', 65536)}U")
            content.append("        },")
            content.append("        .shm = {")
            content.append(f"            .segmentSize = {shm.get('segment_size', 65536)}U,")
            content.append(f"            .maxSegments = {shm.get('max_segments', 10)}U,")
            content.append(f"            .zeroCopy = {'TRUE' if shm.get('zero_copy', True) else 'FALSE'}")
            content.append("        }")
            content.append("    },")
        
        content.append("};")
        content.append("")
        
        # Main configuration structure
        content.append("/*==================================================================================================")
        content.append("*                                  MAIN CONFIGURATION")
        content.append("==================================================================================================*/")
        content.append("")
        content.append("const Dds_ConfigType Dds_Config =")
        content.append("{")
        content.append(f"    .domainId = {self.config.get('domain', {}).get('domain_id', 0)}U,")
        content.append(f"    .numTopics = DDS_CFG_NUM_TOPIC_CONFIGS,")
        content.append(f"    .numTransports = DDS_CFG_NUM_TRANSPORTS,")
        content.append("    .topics = Dds_TopicConfigs,")
        content.append("    .transports = Dds_TransportConfigs")
        content.append("};")
        content.append("")
        
        content.append(self._generate_file_footer(filename))
        
        filepath.write_text('\n'.join(content))
        return filepath
    
    def _generate_bswm_dds_rules_h(self) -> Path:
        """Generate BswM_DdsRules.h AUTOSAR BswM rules header."""
        filename = "BswM_DdsRules.h"
        filepath = self.output_dir / "include" / "autosar" / "service" / "BswM" / filename
        filepath.parent.mkdir(parents=True, exist_ok=True)
        
        content = []
        content.append(self._generate_file_header(filename, "BswM DDS Rules Configuration"))
        
        content.append("#include \"BswM.h\"")
        content.append("#include \"Dds_Cfg.h\"")
        content.append("")
        
        content.append("/*==================================================================================================")
        content.append("*                                       DDS MODE REQUEST PORTS")
        content.append("==================================================================================================*/")
        content.append("")
        content.append("typedef enum")
        content.append("{")
        content.append("    BSWM_DDS_MODE_REQ_INIT = 0U,")
        content.append("    BSWM_DDS_MODE_REQ_RUN,")
        content.append("    BSWM_DDS_MODE_REQ_STOP")
        content.append("} BswM_DdsModeRequestType;")
        content.append("")
        
        content.append("/*==================================================================================================")
        content.append("*                                       DDS RULES")
        content.append("==================================================================================================*/")
        content.append("")
        content.append("#define BSWM_NUM_DDS_RULES        3U")
        content.append("")
        content.append("extern const BswM_RuleType BswM_DdsRules[BSWM_NUM_DDS_RULES];")
        content.append("")
        
        content.append("/*==================================================================================================")
        content.append("*                                  EXTERNAL FUNCTION DECLARATIONS")
        content.append("==================================================================================================*/")
        content.append("")
        content.append("extern void BswM_Dds_Init(void);")
        content.append("extern void BswM_Dds_Deinit(void);")
        content.append("extern void BswM_Dds_SetModeRequest(BswM_DdsModeRequestType mode);")
        content.append("")
        
        content.append(self._generate_file_footer(filename))
        
        filepath.write_text('\n'.join(content))
        return filepath


class CGeneratorError(Exception):
    """Exception for C generator errors."""
    pass
