"""
DDS Configuration Code Templates

Provides Jinja2 templates for code generation.
Templates for C headers, source files, and AUTOSAR integration.
"""

# Template for Dds_Cfg.h header
DDS_CFG_H_TEMPLATE = """/**
 * @file Dds_Cfg.h
 * @brief DDS Main Configuration Header
 * 
 * @warning This file is auto-generated by DDS Configuration Tool.
 *          Do not edit manually.
 */

#ifndef DDS_CFG_H
#define DDS_CFG_H

/*==================================================================================================
*                                        INCLUDE FILES
==================================================================================================*/

#include "Std_Types.h"
#include "Dds_Types.h"

/*==================================================================================================
*                                       VERSION INFO
==================================================================================================*/

#define DDS_CFG_MAJOR_VERSION    {{ major_version }}u
#define DDS_CFG_MINOR_VERSION    {{ minor_version }}u
#define DDS_CFG_PATCH_VERSION    {{ patch_version }}u

/*==================================================================================================
*                                       DOMAIN CONFIGURATION
==================================================================================================*/

#define DDS_CFG_DOMAIN_ID        ({{ domain_id }}U)
#define DDS_CFG_DOMAIN_NAME      "{{ domain_name }}"

/* Discovery Settings */
#define DDS_CFG_DISCOVERY_PROTOCOL    DDS_DISC_{{ discovery_protocol }}
#define DDS_CFG_LEASE_DURATION_SEC    ({{ lease_duration }}U)
#define DDS_CFG_ANNOUNCE_PERIOD_SEC   ({{ announce_period }}U)

/* Multicast Settings */
#define DDS_CFG_MULTICAST_ENABLED     STD_{{ 'ENABLED' if multicast_enabled else 'DISABLED' }}
#define DDS_CFG_MULTICAST_ADDR        "{{ multicast_address }}"
#define DDS_CFG_MULTICAST_PORT        ({{ multicast_port }}U)

/*==================================================================================================
*                                      TRANSPORT CONFIGURATION
==================================================================================================*/

#define DDS_CFG_DEFAULT_TRANSPORT     DDS_TRANSPORT_{{ default_transport }}
#define DDS_CFG_SHM_ENABLED           STD_{{ 'ENABLED' if shm_enabled else 'DISABLED' }}
#define DDS_CFG_INTRA_PROCESS         STD_{{ 'ENABLED' if intra_process else 'DISABLED' }}

/*==================================================================================================
*                                      RESOURCE LIMITS
==================================================================================================*/

#define DDS_CFG_MAX_PARTICIPANTS      ({{ max_participants }}U)
#define DDS_CFG_MAX_DOMAINS           ({{ max_domains }}U)
#define DDS_CFG_SHM_SIZE_KB           ({{ shm_size_kb }}U)
#define DDS_CFG_SHM_SEGMENTS          ({{ shm_segments }}U)

/*==================================================================================================
*                                       TIMING CONFIGURATION
==================================================================================================*/

#define DDS_CFG_SPIN_FREQUENCY        ({{ spin_frequency }}U)
#define DDS_CFG_MAX_BLOCKING_MS       ({{ max_blocking_ms }}U)

/*==================================================================================================
*                                       TOPIC CONFIGURATION
==================================================================================================*/

#define DDS_CFG_NUM_TOPICS            ({{ num_topics }}U)

/*==================================================================================================
*                                  EXTERNAL FUNCTION DECLARATIONS
==================================================================================================*/

extern void Dds_Init(const Dds_ConfigType* configPtr);
extern void Dds_Deinit(void);
extern Std_ReturnType Dds_Start(void);
extern void Dds_Stop(void);

#endif /* DDS_CFG_H */
/* End of file */
"""

# Template for Dds_TopicCfg.h header
DDS_TOPIC_CFG_H_TEMPLATE = """/**
 * @file Dds_TopicCfg.h
 * @brief DDS Topic Configuration Header
 * 
 * @warning This file is auto-generated by DDS Configuration Tool.
 *          Do not edit manually.
 */

#ifndef DDS_TOPIC_CFG_H
#define DDS_TOPIC_CFG_H

#include "Dds_Cfg.h"
#include "Dds_Types.h"

/*==================================================================================================
*                                       TOPIC IDENTIFIERS
==================================================================================================*/

typedef enum
{
{% for topic in topics %}
    DDS_TOPIC_ID_{{ topic.name | upper }} = {{ loop.index0 }}U,
{% endfor %}
    DDS_TOPIC_ID_MAX
} Dds_TopicIdType;

/*==================================================================================================
*                                       TOPIC KINDS
==================================================================================================*/

typedef enum
{
    DDS_TOPIC_KIND_STANDARD = 0U,
    DDS_TOPIC_KIND_SIGNAL,
    DDS_TOPIC_KIND_SERVICE,
    DDS_TOPIC_KIND_EVENT,
    DDS_TOPIC_KIND_FIELD
} Dds_TopicKindType;

/*==================================================================================================
*                                  TOPIC CONFIGURATION STRUCTURES
==================================================================================================*/

typedef struct
{
    Dds_TopicIdType       topicId;
    Dds_TopicKindType     kind;
    const char*           name;
    const char*           dataType;
    uint16                maxInstances;
    boolean               e2eEnabled;
    uint8                 e2eProfile;
    uint16                e2eDataId;
} Dds_TopicConfigType;

/*==================================================================================================
*                                  TOPIC CONFIGURATION DATA
==================================================================================================*/

#define DDS_CFG_NUM_TOPIC_CONFIGS     ({{ topics | length }}U)

extern const Dds_TopicConfigType Dds_TopicConfigs[DDS_CFG_NUM_TOPIC_CONFIGS];

/*==================================================================================================
*                                       E2E PROFILES
==================================================================================================*/

#define DDS_E2E_PROFILE_NONE          0x00U
#define DDS_E2E_PROFILE_P01           0x01U
#define DDS_E2E_PROFILE_P02           0x02U
#define DDS_E2E_PROFILE_P04           0x04U
#define DDS_E2E_PROFILE_P05           0x05U
#define DDS_E2E_PROFILE_P06           0x06U
#define DDS_E2E_PROFILE_P07           0x07U
#define DDS_E2E_PROFILE_P11           0x0BU
#define DDS_E2E_PROFILE_P22           0x16U

#endif /* DDS_TOPIC_CFG_H */
/* End of file */
"""

# Template for Dds_QosCfg.h header
DDS_QOS_CFG_H_TEMPLATE = """/**
 * @file Dds_QosCfg.h
 * @brief DDS QoS Configuration Header
 * 
 * @warning This file is auto-generated by DDS Configuration Tool.
 *          Do not edit manually.
 */

#ifndef DDS_QOS_CFG_H
#define DDS_QOS_CFG_H

#include "Dds_Cfg.h"
#include "Dds_Types.h"

/*==================================================================================================
*                                       QOS POLICY KINDS
==================================================================================================*/

typedef enum
{
    DDS_RELIABILITY_BEST_EFFORT = 0U,
    DDS_RELIABILITY_RELIABLE
} Dds_ReliabilityKindType;

typedef enum
{
    DDS_DURABILITY_VOLATILE = 0U,
    DDS_DURABILITY_TRANSIENT_LOCAL,
    DDS_DURABILITY_TRANSIENT,
    DDS_DURABILITY_PERSISTENT
} Dds_DurabilityKindType;

typedef enum
{
    DDS_HISTORY_KEEP_LAST = 0U,
    DDS_HISTORY_KEEP_ALL
} Dds_HistoryKindType;

typedef enum
{
    DDS_LIVELINESS_AUTOMATIC = 0U,
    DDS_LIVELINESS_MANUAL_BY_PARTICIPANT,
    DDS_LIVELINESS_MANUAL_BY_TOPIC
} Dds_LivelinessKindType;

/*==================================================================================================
*                                  QOS CONFIGURATION STRUCTURES
==================================================================================================*/

typedef struct
{
    Dds_ReliabilityKindType   kind;
    uint32                    maxBlockingTimeMs;
} Dds_ReliabilityQosType;

typedef struct
{
    Dds_DurabilityKindType    kind;
} Dds_DurabilityQosType;

typedef struct
{
    Dds_HistoryKindType       kind;
    uint32                    depth;
} Dds_HistoryQosType;

typedef struct
{
    Dds_LivelinessKindType    kind;
    uint32                    leaseDurationSec;
} Dds_LivelinessQosType;

typedef struct
{
    Dds_ReliabilityQosType    reliability;
    Dds_DurabilityQosType     durability;
    Dds_HistoryQosType        history;
    Dds_LivelinessQosType     liveliness;
    uint32                    deadlineMs;
    uint32                    latencyBudgetMs;
    uint8                     transportPriority;
} Dds_QosProfileType;

/*==================================================================================================
*                                  QOS PROFILE CONFIGURATIONS
==================================================================================================*/

{% for profile in qos_profiles %}
extern const Dds_QosProfileType Dds_QosProfile_{{ profile.name | upper }};
{% endfor %}

#endif /* DDS_QOS_CFG_H */
/* End of file */
"""

# Template for Dds_Cfg.c source file
DDS_CFG_C_TEMPLATE = """/**
 * @file Dds_Cfg.c
 * @brief DDS Configuration Source
 * 
 * @warning This file is auto-generated by DDS Configuration Tool.
 *          Do not edit manually.
 */

#include "Dds_Cfg.h"
#include "Dds_TopicCfg.h"
#include "Dds_QosCfg.h"

/*==================================================================================================
*                                  TOPIC CONFIGURATION DATA
==================================================================================================*/

const Dds_TopicConfigType Dds_TopicConfigs[DDS_CFG_NUM_TOPIC_CONFIGS] =
{
{% for topic in topics %}
    { /* {{ topic.name }} */
        .topicId = DDS_TOPIC_ID_{{ topic.name | upper }},
        .kind = DDS_TOPIC_KIND_{{ topic.kind | default('STANDARD') }},
        .name = "{{ topic.name }}",
        .dataType = "{{ topic.data_type | default('void') }}",
        .maxInstances = {{ topic.max_instances | default(1) }}U,
        .e2eEnabled = {{ 'TRUE' if topic.security.e2e_enabled else 'FALSE' }},
        .e2eProfile = DDS_E2E_PROFILE_{{ topic.security.e2e_profile | default('P01') }},
        .e2eDataId = {{ topic.security.e2e_data_id | default(0) }}U
    },
{% endfor %}
};

/*==================================================================================================
*                                  QOS PROFILE DATA
==================================================================================================*/

{% for profile in qos_profiles %}
const Dds_QosProfileType Dds_QosProfile_{{ profile.name | upper }} =
{
    .reliability = {
        .kind = DDS_RELIABILITY_{{ profile.reliability.kind | default('RELIABLE') }},
        .maxBlockingTimeMs = {{ (profile.reliability.max_blocking_time | default(0.1) * 1000) | int }}U
    },
    .durability = {
        .kind = DDS_DURABILITY_{{ profile.durability.kind | default('VOLATILE') }}
    },
    .history = {
        .kind = DDS_HISTORY_{{ profile.history.kind | default('KEEP_LAST') }},
        .depth = {{ profile.history.depth | default(1) }}U
    },
    .liveliness = {
        .kind = DDS_LIVELINESS_{{ profile.liveliness.kind | default('AUTOMATIC') }},
        .leaseDurationSec = {{ profile.liveliness.lease_duration | default(10) | int }}U
    },
    .deadlineMs = {{ (profile.deadline.period | default(0) * 1000) | int }}U,
    .latencyBudgetMs = {{ (profile.latency_budget | default(0) * 1000) | int }}U,
    .transportPriority = {{ profile.transport_priority | default(0) }}U
};
{% endfor %}

/*==================================================================================================
*                                  MAIN CONFIGURATION
==================================================================================================*/

const Dds_ConfigType Dds_Config =
{
    .domainId = {{ domain_id | default(0) }}U,
    .numTopics = DDS_CFG_NUM_TOPIC_CONFIGS,
    .numTransports = DDS_CFG_NUM_TRANSPORTS,
    .topics = Dds_TopicConfigs,
    .transports = NULL
};

/* End of file */
"""

# Template for BswM_DdsRules.h
BSWM_DDS_RULES_H_TEMPLATE = """/**
 * @file BswM_DdsRules.h
 * @brief BswM DDS Rules Configuration
 * 
 * @warning This file is auto-generated by DDS Configuration Tool.
 *          Do not edit manually.
 */

#ifndef BSWM_DDS_RULES_H
#define BSWM_DDS_RULES_H

#include "BswM.h"
#include "Dds_Cfg.h"

/*==================================================================================================
*                                       DDS MODE REQUEST PORTS
==================================================================================================*/

typedef enum
{
    BSWM_DDS_MODE_REQ_INIT = 0U,
    BSWM_DDS_MODE_REQ_RUN,
    BSWM_DDS_MODE_REQ_STOP
} BswM_DdsModeRequestType;

/*==================================================================================================
*                                       DDS RULES
==================================================================================================*/

#define BSWM_NUM_DDS_RULES        {{ bswm_rules | length | default(3) }}U

extern const BswM_RuleType BswM_DdsRules[BSWM_NUM_DDS_RULES];

/*==================================================================================================
*                                  EXTERNAL FUNCTION DECLARATIONS
==================================================================================================*/

extern void BswM_Dds_Init(void);
extern void BswM_Dds_Deinit(void);
extern void BswM_Dds_SetModeRequest(BswM_DdsModeRequestType mode);

#endif /* BSWM_DDS_RULES_H */
/* End of file */
"""

# Template for E2E configuration
E2E_CONFIG_TEMPLATE = """/**
 * @file E2E_DdsCfg.h
 * @brief E2E Protection Configuration for DDS
 * 
 * @warning This file is auto-generated by DDS Configuration Tool.
 *          Do not edit manually.
 */

#ifndef E2E_DDS_CFG_H
#define E2E_DDS_CFG_H

#include "Std_Types.h"
#include "Crc.h"

/*==================================================================================================
*                                       E2E PROFILE CONFIGURATION
==================================================================================================*/

typedef struct
{
    uint16    dataId;
    uint8     profile;
    uint8     crcOffset;
    uint8     counterOffset;
    uint8     dataIdMode;
} E2E_DdsProfileConfigType;

/*==================================================================================================
*                                  E2E CONFIGURATION DATA
==================================================================================================*/

{% for topic in topics %}
{% if topic.security.e2e_enabled %}
#define E2E_DDS_{{ topic.name | upper }}_DATA_ID    {{ topic.security.e2e_data_id }}U
#define E2E_DDS_{{ topic.name | upper }}_PROFILE   E2E_P{{ topic.security.e2e_profile }}
{% endif %}
{% endfor %}

/*==================================================================================================
*                                  EXTERNAL DECLARATIONS
==================================================================================================*/

extern Std_ReturnType E2E_Dds_Protect(const E2E_DdsProfileConfigType* config, uint8* data, uint16 length);
extern Std_ReturnType E2E_Dds_Check(const E2E_DdsProfileConfigType* config, const uint8* data, uint16 length);

#endif /* E2E_DDS_CFG_H */
/* End of file */
"""


class CodeTemplates:
    """Provides code generation templates."""
    
    TEMPLATES = {
        'dds_cfg_h': DDS_CFG_H_TEMPLATE,
        'dds_topic_cfg_h': DDS_TOPIC_CFG_H_TEMPLATE,
        'dds_qos_cfg_h': DDS_QOS_CFG_H_TEMPLATE,
        'dds_cfg_c': DDS_CFG_C_TEMPLATE,
        'bswm_dds_rules_h': BSWM_DDS_RULES_H_TEMPLATE,
        'e2e_cfg_h': E2E_CONFIG_TEMPLATE
    }
    
    @classmethod
    def get_template(cls, name: str) -> str:
        """Get template by name."""
        return cls.TEMPLATES.get(name, '')
    
    @classmethod
    def render(cls, name: str, context: dict) -> str:
        """Render template with context."""
        try:
            from jinja2 import Template
            template = Template(cls.get_template(name))
            return template.render(**context)
        except ImportError:
            # Simple string replacement fallback
            result = cls.get_template(name)
            for key, value in context.items():
                placeholder = '{{ ' + key + ' }}'
                result = result.replace(placeholder, str(value))
            return result
