/**
 * @file LinSM_Cfg.h
 * @brief LinSM Configuration configuration header
 * @version 1.0.0
 * @date 2026-08-10
 * @note AUTO-GENERATED by yuleASR Configurator
 */

#ifndef LINSM_CFG_H
#define LINSM_CFG_H

/*==================================================================================================
*                                    PRE-COMPILE CONFIGURATION
*================================================================================================*/

/*==================================================================================================
*                                    General Configuration
*================================================================================================*/
#define LINSM_DEV_ERROR_DETECT    STD_ON
#define LINSM_VERSION_INFO_API    STD_ON

/*==================================================================================================
*                                    Module Configuration Counts
*================================================================================================*/
#define LINSM_REQUEST_TIMEOUT_COUNT    (LINSM_REQUEST_TIMEOUT_MS / LINSM_MAIN_FUNCTION_PERIOD_MS)
#define LINSM_CONFIRMATION_TIMEOUT_COUNT    (LINSM_CONFIRMATION_TIMEOUT_MS / LINSM_MAIN_FUNCTION_PERIOD_MS)

/*==================================================================================================
*                                    Timing Configuration
*================================================================================================*/
#define LINSM_REQUEST_TIMEOUT_MS    (100U)
#define LINSM_CONFIRMATION_TIMEOUT_MS    (50U)
#define LINSM_MAIN_FUNCTION_PERIOD_MS    (5U)
#define LINSM_WAKEUP_TIMEOUT_MS    (50U)
#define LINSM_GOTOSLEEP_TIMEOUT_MS    (100U)

/*==================================================================================================
*                                    Other Configuration
*================================================================================================*/
#define LINSM_WAKEUP_SUPPORT    STD_ON
#define LINSM_COMMUNICATION_CONTROL_SUPPORT    STD_ON
#define LINSM_SLAVE_SUPPORT    STD_ON
#define LINSM_MASTER_NODE_SUPPORT    STD_ON
#define LINSM_NUMBER_OF_CHANNELS    (1U)
#define LINSM_NUMBER_OF_SCHEDULES    (4U)
#define LINSM_CHANNEL_0    (0U)
#define LINSM_SCHEDULE_NULL    (0U)
#define LINSM_SCHEDULE_MASTER    (1U)
#define LINSM_SCHEDULE_DIAGNOSTIC    (2U)
#define LINSM_SCHEDULE_TABLE_0    (3U)
#define LINSM_INITIAL_SCHEDULE    (1U)
#define LINSM_MAX_SCHEDULE_SWITCHES    (10U)
#define LINSM_MODE_FULL_COM    (1U)
#define LINSM_MODE_NO_COM    (0U)
#define LINSM_MODE_SILENT_COM    (2U)

#endif /* LINSM_CFG_H */

/*==================[end of file]===========================================*/
