/**
 * @file CanNm_Cfg.h
 * @brief CanNm Configuration configuration header
 * @version 1.0.0
 * @date 2026-08-10
 * @note AUTO-GENERATED by yuleASR Configurator
 */

#ifndef CANNM_CFG_H
#define CANNM_CFG_H

#include "Std_Types.h"

/*==================================================================================================
*                                    PRE-COMPILE CONFIGURATION
*================================================================================================*/

/*==================================================================================================
*                                    General Configuration
*================================================================================================*/
#define CANNM_DEV_ERROR_DETECT    STD_ON
#define CANNM_VERSION_INFO_API    STD_ON
#define CANNM_NODE_DETECTION_ENABLED    STD_ON

/*==================================================================================================
*                                    Hardware Object Handles
*================================================================================================*/
#define CANNM_TX_PDU_ID    (0U)
#define CANNM_RX_PDU_ID    (1U)
#define CANNM_PDU_RX_INDICATION_ENABLED    STD_ON
#define CANNM_TX_RETRY_LIMIT    (3U)

/*==================================================================================================
*                                    Timing Configuration
*================================================================================================*/
#define CANNM_MSG_TIMEOUT_TIME    (600U)
#define CANNM_TIMEOUT_TIME    (600U)
#define CANNM_MAIN_FUNCTION_PERIOD    (10U)

/*==================================================================================================
*                                    Other Configuration
*================================================================================================*/
#define CANNM_BUS_LOAD_REDUCTION_ENABLED    STD_OFF
#define CANNM_COM_CONTROL_ENABLED    STD_ON
#define CANNM_NODE_ID_ENABLED    STD_ON
#define CANNM_USER_DATA_ENABLED    STD_ON
#define CANNM_BUS_SYNCHRONIZATION_ENABLED    STD_ON
#define CANNM_REMOTE_SLEEP_IND_ENABLED    STD_ON
#define CANNM_PASSIVE_MODE_ENABLED    STD_OFF
#define CANNM_REPEAT_MSG_IND_ENABLED    STD_ON
#define CANNM_IMMEDIATE_TRANSMISSION_ENABLED    STD_ON
#define CANNM_NUMBER_OF_CHANNELS    (1U)
#define CANNM_CHANNEL_0    (0U)
#define CANNM_PDU_LENGTH    (8U)
#define CANNM_PDU_SRC_ADDR_POS    (0U)
#define CANNM_PDU_CBV_POS    (1U)
#define CANNM_PDU_USER_DATA_POS    (2U)
#define CANNM_PDU_USER_DATA_LENGTH    (6U)
#define CANNM_MSG_CYCLE_TIME    (100U)
#define CANNM_REPEAT_MESSAGE_TIME    (1500U)
#define CANNM_WAIT_BUS_SLEEP_TIME    (2000U)
#define CANNM_IMMEDIATE_NM_CYCLE_TIME    (20U)
#define CANNM_IMMEDIATE_NM_TRANSMISSIONS    (5U)
#define CANNM_REMOTE_SLEEP_IND_TIME    (1000U)
#define CANNM_NODE_ID    (1U)
#define CANNM_CLUSTER_ID    (1U)
#define CANNM_CAN_ID_BASE    (1024U)
#define CANNM_STATE_CHANGE_NOTIFICATION_ENABLED    STD_ON
#define CANNM_REMOTE_SLEEP_CALLBACK_ENABLED    STD_ON
#define CANNM_BUS_SLEEP_MODE_ENTRY_ENABLED    STD_ON
#define CANNM_PREPARE_BUS_SLEEP_MODE_ENTRY_ENABLED    STD_ON
#define CANNM_NETWORK_MODE_ENTRY_ENABLED    STD_ON
#define CANNM_MAX_NODES    (8U)

#endif /* CANNM_CFG_H */

/*==================[end of file]===========================================*/
