/**
 * @file EcuM_Cfg.h
 * @brief EcuM Configuration configuration header
 * @version 1.0.0
 * @date 2026-08-10
 * @note AUTO-GENERATED by yuleASR Configurator
 */

#ifndef ECUM_CFG_H
#define ECUM_CFG_H

#include "Std_Types.h"   /* 非宏段依赖 Std_Types 基础类型 (uint32/uint8/uint16/boolean 等)，生成宏段不含此 include */

/*==================================================================================================
*                                    PRE-COMPILE CONFIGURATION
*================================================================================================*/

/*==================================================================================================
*                                    General Configuration
*================================================================================================*/
#define ECUM_DEV_ERROR_DETECT    STD_ON
#define ECUM_VERSION_INFO_API    STD_ON

/*==================================================================================================
*                                    Processing Modes
*================================================================================================*/
#define ECUM_POLL_MODE_SUPPORTED    STD_ON
#ifndef ECUM_POLL_SID
#define ECUM_POLL_SID    (19U)
#endif

/*==================================================================================================
*                                    Timing Configuration
*================================================================================================*/
#define ECUM_MAIN_FUNCTION_PERIOD    (10U)
#define ECUM_WAKEUP_VALIDATION_TIMEOUT    (100U)
#define ECUM_CHECK_WAKEUP_TIMEOUT    (50U)
#define ECUM_NVM_READALL_TIMEOUT    (10000U)
#define ECUM_NVM_WRITEALL_TIMEOUT    (10000U)
#define ECUM_STARTUP_TIMEOUT    (5000U)
#define ECUM_SLEEP_TRANSITION_TIMEOUT    (1000U)
#define ECUM_WAKEUP_RESTART_TIMEOUT    (5000U)
#define ECUM_SHUTDOWN_TRANSITION_TIMEOUT    (1000U)

/*==================================================================================================
*                                    Other Configuration
*================================================================================================*/
#define ECUM_MAX_USERS    (32U)
#define ECUM_MAX_WAKEUP_SOURCES    (32U)
#define ECUM_MULTI_CORE_SUPPORT    STD_OFF
#define ECUM_FAST_STARTUP_MODE    STD_OFF
#ifndef ECUM_WKSOURCE_POWER
#define ECUM_WKSOURCE_POWER    (1U)
#endif
#ifndef ECUM_WKSOURCE_RESET
#define ECUM_WKSOURCE_RESET    (2U)
#endif
#ifndef ECUM_WKSOURCE_INTERNAL_RESET
#define ECUM_WKSOURCE_INTERNAL_RESET    (4U)
#endif
#ifndef ECUM_WKSOURCE_INTERNAL_WDG
#define ECUM_WKSOURCE_INTERNAL_WDG    (8U)
#endif
#ifndef ECUM_WKSOURCE_EXTERNAL_WDG
#define ECUM_WKSOURCE_EXTERNAL_WDG    (16U)
#endif
#ifndef ECUM_WKSOURCE_TIMER
#define ECUM_WKSOURCE_TIMER    (32U)
#endif
#ifndef ECUM_WKSOURCE_CAN
#define ECUM_WKSOURCE_CAN    (64U)
#endif
#ifndef ECUM_WKSOURCE_CAN0
#define ECUM_WKSOURCE_CAN0    (64U)
#endif
#ifndef ECUM_WKSOURCE_CAN1
#define ECUM_WKSOURCE_CAN1    (128U)
#endif
#ifndef ECUM_WKSOURCE_CAN2
#define ECUM_WKSOURCE_CAN2    (256U)
#endif
#ifndef ECUM_WKSOURCE_CAN3
#define ECUM_WKSOURCE_CAN3    (512U)
#endif
#ifndef ECUM_WKSOURCE_LIN
#define ECUM_WKSOURCE_LIN    (1024U)
#endif
#ifndef ECUM_WKSOURCE_ETH
#define ECUM_WKSOURCE_ETH    (2048U)
#endif
#ifndef ECUM_WKSOURCE_FLEXRAY
#define ECUM_WKSOURCE_FLEXRAY    (4096U)
#endif
#ifndef ECUM_WKSOURCE_GPIO
#define ECUM_WKSOURCE_GPIO    (8192U)
#endif
#ifndef ECUM_WKSOURCE_SPI
#define ECUM_WKSOURCE_SPI    (16384U)
#endif
#ifndef ECUM_WKSOURCE_I2C
#define ECUM_WKSOURCE_I2C    (32768U)
#endif
#ifndef ECUM_WKSOURCE_ADC
#define ECUM_WKSOURCE_ADC    (65536U)
#endif
#define ECUM_CONFIGURED_WAKEUP_SOURCES    \
(ECUM_WKSOURCE_POWER | ECUM_WKSOURCE_RESET | ECUM_WKSOURCE_TIMER | \
ECUM_WKSOURCE_CAN | ECUM_WKSOURCE_CAN0 | ECUM_WKSOURCE_GPIO)
#define ECUM_CHECK_WAKEUP_ENABLED    STD_ON
#define ECUM_DEFAULT_SLEEP_MODE    (0U)
#define ECUM_HALT_MODE_SUPPORTED    STD_ON
#define ECUM_NVM_ENABLED    STD_ON
#define ECUM_WDGM_ENABLED    STD_ON
#define ECUM_COMM_ENABLED    STD_ON
#define ECUM_BSWM_ENABLED    STD_ON
#define ECUM_SCHM_ENABLED    STD_ON
#define ECUM_RTE_ENABLED    STD_ON
#define ECUM_STARTUP_ONE_ENABLED    STD_ON
#define ECUM_STARTUP_TWO_ENABLED    STD_ON
#define ECUM_STARTUP_THREE_ENABLED    STD_ON
#define ECUM_RESET_MCU    (0U)
#define ECUM_RESET_WDG    (1U)
#define ECUM_RESET_IO    (2U)
#define ECUM_RESET_SW    (3U)
#ifndef ECUM_DEFAULT_RESET_TYPE
#define ECUM_DEFAULT_RESET_TYPE    (0U)
#endif
#define ECUM_ALARM_CLOCK_ENABLED    STD_OFF
#define ECUM_ALARM_CLOCK_TIME_BASE    (1000U)
#define ECUM_FIXED_BLOCKS_ENABLED    STD_OFF
#define ECUM_PREOS_CALLBACK_ENABLED    STD_ON
#define ECUM_POSTOS_CALLBACK_ENABLED    STD_ON
#ifndef ECUM_STARTUPONE_SID
#define ECUM_STARTUPONE_SID    (15U)
#endif
#ifndef ECUM_STARTUPTWO_SID
#define ECUM_STARTUPTWO_SID    (16U)
#endif
#ifndef ECUM_SLEEP_SID
#define ECUM_SLEEP_SID    (17U)
#endif
#ifndef ECUM_HALT_SID
#define ECUM_HALT_SID    (18U)
#endif
#ifndef ECUM_WAKEUPRESTART_SID
#define ECUM_WAKEUPRESTART_SID    (20U)
#endif
#ifndef ECUM_CLEARWAKEUPEVENT_SID
#define ECUM_CLEARWAKEUPEVENT_SID    (21U)
#endif
#ifndef ECUM_CHECKWAKEUP_SID
#define ECUM_CHECKWAKEUP_SID    (22U)
#endif
#ifndef ECUM_ENABLEWAKEUPSOURCES_SID
#define ECUM_ENABLEWAKEUPSOURCES_SID    (23U)
#endif
#ifndef ECUM_DISABLEWAKEUPSOURCES_SID
#define ECUM_DISABLEWAKEUPSOURCES_SID    (24U)
#endif
#ifndef ECUM_GETSTATUSOFWAKEUPSOURCE_SID
#define ECUM_GETSTATUSOFWAKEUPSOURCE_SID    (25U)
#endif


/*==================================================================================================
*  NON-MACRO SEGMENT (preserved from handwritten header, merged by codegen splice)
*  typedef(1) + struct(0) + extern config tables(0) — 依赖宏段计数宏, 故置于宏段之后
*================================================================================================*/
typedef uint8 EcuM_ResetType;
#endif /* ECUM_CFG_H */

/*==================[end of file]===========================================*/
