/**
 * @file LinTp_Cfg.h
 * @brief LinTp_Ecual Configuration configuration header
 * @version 1.0.0
 * @date 2026-08-10
 * @note AUTO-GENERATED by yuleASR Configurator
 */

#ifndef LINTP_CFG_H
#define LINTP_CFG_H

/*==================================================================================================
*                                    PRE-COMPILE CONFIGURATION
*================================================================================================*/

/*==================================================================================================
*                                    General Configuration
*================================================================================================*/
#define LINTP_DEV_ERROR_DETECT    STD_ON
#define LINTP_VERSION_INFO_API    STD_ON
#define LINTP_SID_GET_VERSION_INFO    (7U)

/*==================================================================================================
*                                    Module Configuration Counts
*================================================================================================*/
#define LINTP_MAX_CHANNEL_COUNT    (2U)
#define LINTP_NSDU_COUNT    (4U)
#define LINTP_RX_NSDU_COUNT    (2U)
#define LINTP_TX_NSDU_COUNT    (2U)

/*==================================================================================================
*                                    Hardware Object Handles
*================================================================================================*/
#define LINTP_E_INVALID_TX_ID    (5U)
#define LINTP_E_INVALID_RX_ID    (6U)
#define LINTP_SID_RX_INDICATION    (66U)
#define LINTP_SID_TX_CONFIRMATION    (67U)

/*==================================================================================================
*                                    Timing Configuration
*================================================================================================*/
#define LINTP_SF_TIMEOUT_CYCLES    (100U)
#define LINTP_FF_TIMEOUT_CYCLES    (100U)
#define LINTP_CF_TIMEOUT_CYCLES    (100U)
#define LINTP_FC_TIMEOUT_CYCLES    (100U)
#define LINTP_E_TIMEOUT    (112U)

/*==================================================================================================
*                                    Other Configuration
*================================================================================================*/
#define LINTP_CFG_VENDOR_ID    (153U)
#define LINTP_CFG_MODULE_ID    (98U)
#define LINTP_CFG_SW_MAJOR_VERSION    (1U)
#define LINTP_CFG_SW_MINOR_VERSION    (0U)
#define LINTP_CFG_SW_PATCH_VERSION    (0U)
#define LINTP_CFG_AR_RELEASE_MAJOR_VERSION    (4U)
#define LINTP_CFG_AR_RELEASE_MINOR_VERSION    (4U)
#define LINTP_CFG_AR_RELEASE_REVISION_VERSION    (0U)
#define LINTP_CANCEL_TRANSMIT_API    STD_ON
#define LINTP_CANCEL_RECEIVE_API    STD_ON
#define LINTP_CHANGE_PARAMETER_API    STD_ON
#define LINTP_SUPPORT_WAIT_FRAMES    STD_ON
#define LINTP_EXTENDED_ADDRESSING_SUPPORT    STD_OFF
#define LINTP_NAS_DEFAULT    (1000U)
#define LINTP_NCS_DEFAULT    (1000U)
#define LINTP_NCR_DEFAULT    (1000U)
#define LINTP_STMIN_DEFAULT    (20U)
#define LINTP_BS_DEFAULT    (8U)
#define LINTP_MAX_WFT    (10U)
#define LINTP_BUFFER_SIZE    (4095U)
#define LINTP_SF_MAX_DATA_LENGTH    (6U)
#define LINTP_FF_MAX_DATA_LENGTH    (5U)
#define LINTP_CF_MAX_DATA_LENGTH    (6U)
#define LINTP_E_UNINIT    (0U)
#define LINTP_E_INVALID_PDU_SDU_ID    (1U)
#define LINTP_E_PARAM_POINTER    (2U)
#define LINTP_E_INVALID_PARAMETER    (3U)
#define LINTP_E_INIT_FAILED    (4U)
#define LINTP_E_INVALD_NSDU_ID    (32U)
#define LINTP_E_INVALD_NSA    (48U)
#define LINTP_E_INVALID_FRAME    (113U)
#define LINTP_E_BUFFER_OVERFLOW    (114U)
#define LINTP_E_SEQUENCE_ERROR    (115U)
#define LINTP_E_INVALID_FC    (116U)
#define LINTP_SID_INIT    (1U)
#define LINTP_SID_DEINIT    (2U)
#define LINTP_SID_TRANSMIT    (3U)
#define LINTP_SID_CANCEL_TRANSMIT    (4U)
#define LINTP_SID_CANCEL_RECEIVE    (5U)
#define LINTP_SID_CHANGE_PARAMETER    (6U)
#define LINTP_SID_MAIN_FUNCTION    (8U)
#define LINTP_SID_TRIGGER_TRANSMIT    (68U)

#endif /* LINTP_CFG_H */

/*==================[end of file]===========================================*/
