/**
 * @file Uart_Cfg.h
 * @brief Uart Configuration configuration header
 * @version 1.0.0
 * @date 2026-08-10
 * @note AUTO-GENERATED by yuleASR Configurator
 */

#ifndef UART_CFG_H
#define UART_CFG_H

#include "Std_Types.h"

/*==================================================================================================
*                                    PRE-COMPILE CONFIGURATION
*================================================================================================*/

/*==================================================================================================
*                                    General Configuration
*================================================================================================*/
#define UART_DEV_ERROR_DETECT    STD_ON
#define UART_VERSION_INFO_API    STD_ON
#define UART_SERVICE_ID_GETVERSIONINFO    (5U)

/*==================================================================================================
*                                    Module Configuration Counts
*================================================================================================*/
#define UART_CHANNEL_COUNT    (4U)

/*==================================================================================================
*                                    Baudrate Configurations
*================================================================================================*/
#define UART_SERVICE_ID_SETBAUDRATE    (14U)

/*==================================================================================================
*                                    Processing Modes
*================================================================================================*/
#define UART_MULTI_PROCESSOR_MODE    STD_OFF
#define UART_SERVICE_ID_ENABLEINTERRUPT    (9U)
#define UART_SERVICE_ID_DISABLEINTERRUPT    (10U)

/*==================================================================================================
*                                    Hardware Object Handles
*================================================================================================*/
#define UART0_DMA_TX_CHANNEL    (0U)
#define UART0_DMA_RX_CHANNEL    (1U)
#define UART1_DMA_TX_CHANNEL    (2U)
#define UART1_DMA_RX_CHANNEL    (3U)
#define UART2_DMA_TX_CHANNEL    (4U)
#define UART2_DMA_RX_CHANNEL    (5U)
#define UART3_DMA_TX_CHANNEL    (6U)
#define UART3_DMA_RX_CHANNEL    (7U)
#define UART_TX_IRQ_TYPE    (0U)
#define UART_RX_IRQ_TYPE    (1U)
#define UART_TX_FIFO_THRESHOLD    (8U)
#define UART_RX_FIFO_THRESHOLD    (8U)
#define UART_TX_TIMEOUT_MS    (1000U)
#define UART_RX_TIMEOUT_MS    (1000U)

/*==================================================================================================
*                                    Other Configuration
*================================================================================================*/
#define UART_VENDOR_ID_CFG    (1U)
#define UART_MODULE_ID_CFG    (17U)
#define UART_SW_MAJOR_VERSION_CFG    (1U)
#define UART_SW_MINOR_VERSION_CFG    (0U)
#define UART_SW_PATCH_VERSION_CFG    (0U)
#define UART_DMA_SUPPORT    STD_ON
#define UART_FIFO_SUPPORT    STD_ON
#define UART_HW_HANDSHAKE_SUPPORT    STD_ON
#define UART_CHANNEL_0    (0U)
#define UART_CHANNEL_1    (1U)
#define UART_CHANNEL_2    (2U)
#define UART_CHANNEL_3    (3U)
#define UART_REF_CLOCK_HZ    (80000000U)
#define UART_DMA_FIFO_THRESHOLD    (4U)
#define UART_IRQ_PRIORITY_LEVEL    (5U)
#define UART_ERROR_IRQ_TYPE    (2U)
#define UART_FIFO_DEPTH    (32U)
#define UART_SERVICE_ID_INIT    (0U)
#define UART_SERVICE_ID_DEINIT    (1U)
#define UART_SERVICE_ID_SEND    (2U)
#define UART_SERVICE_ID_RECEIVE    (3U)
#define UART_SERVICE_ID_GETSTATUS    (4U)
#define UART_SERVICE_ID_SENDDMA    (6U)
#define UART_SERVICE_ID_RECEIVEDMA    (7U)
#define UART_SERVICE_ID_ABORT    (8U)
#define UART_SERVICE_ID_ENABLEDMA    (11U)
#define UART_SERVICE_ID_DISABLEDMA    (12U)
#define UART_SERVICE_ID_CLEARFIFO    (13U)

#endif /* UART_CFG_H */

/*==================[end of file]===========================================*/
