/**
 * @file CanTp_Cfg.h
 * @brief CanTp Configuration configuration header
 * @version 1.0.0
 * @date 2026-08-10
 * @note AUTO-GENERATED by yuleASR Configurator
 */

#ifndef CANTP_CFG_H
#define CANTP_CFG_H

/*==================================================================================================
*                                    PRE-COMPILE CONFIGURATION
*================================================================================================*/

/*==================================================================================================
*                                    General Configuration
*================================================================================================*/
#define CANTP_DEV_ERROR_DETECT    STD_ON
#define CANTP_VERSION_INFO_API    STD_ON

/*==================================================================================================
*                                    Module Configuration Counts
*================================================================================================*/
#define CANTP_NUM_CHANNELS    (2U)
#define CANTP_NUM_TX_NSDU    (4U)
#define CANTP_NUM_RX_NSDU    (4U)

/*==================================================================================================
*                                    Hardware Object Handles
*================================================================================================*/
#define CANTP_TX_DIAG_PHYSICAL    (0U)
#define CANTP_TX_DIAG_FUNCTIONAL    (1U)
#define CANTP_TX_UDS_PHYSICAL    (2U)
#define CANTP_TX_UDS_FUNCTIONAL    (3U)
#define CANTP_RX_DIAG_PHYSICAL    (0U)
#define CANTP_RX_DIAG_FUNCTIONAL    (1U)
#define CANTP_RX_UDS_PHYSICAL    (2U)
#define CANTP_RX_UDS_FUNCTIONAL    (3U)
#define CANTP_TX_ADDRESS    (0U)
#define CANTP_RX_ADDRESS    (0U)
#define CANTP_CANIF_TX_PDU_ID    (0U)
#define CANTP_CANIF_RX_PDU_ID    (0U)
#define CANTP_CANIF_FC_TX_PDU_ID    (1U)
#define CANTP_CANIF_FC_RX_PDU_ID    (1U)

/*==================================================================================================
*                                    Timing Configuration
*================================================================================================*/
#define CANTP_MAIN_FUNCTION_PERIOD_MS    (5U)

/*==================================================================================================
*                                    Other Configuration
*================================================================================================*/
#define CANTP_DYNAMIC_CHANNEL_ALLOCATION    STD_OFF
#define CANTP_PADDING_BYTE    STD_ON
#define CANTP_PADDING_BYTE_VALUE    (204U)
#define CANTP_CHANGE_PARAMETER_API    STD_ON
#define CANTP_READ_PARAMETER_API    STD_ON
#define CANTP_MAX_CHANNEL_CNT    (4U)
#define CANTP_NAS_DEFAULT    (25U)
#define CANTP_NBS_DEFAULT    (75U)
#define CANTP_NCS_DEFAULT    (25U)
#define CANTP_NAR_DEFAULT    (25U)
#define CANTP_NBR_DEFAULT    (75U)
#define CANTP_NCR_DEFAULT    (150U)
#define CANTP_BS_DEFAULT    (8U)
#define CANTP_STMIN_DEFAULT    (20U)
#define CANTP_WFT_MAX_DEFAULT    (8U)
#define CANTP_ADDRESSING_FORMAT    CANTP_STANDARD
#define CANTP_MAX_MESSAGE_LENGTH    (4095U)
#define CANTP_CANFD_MAX_MESSAGE_LENGTH    (4095U)
#define CANTP_CHANNEL_BUFFER_SIZE    (64U)
#define CANTP_CAN_FRAME_LENGTH    (8U)
#define CANTP_INVALID_CHANNEL_ID    (255U)

#endif /* CANTP_CFG_H */

/*==================[end of file]===========================================*/
