/**
 * @file Ecuc.h
 * @brief AUTOSAR ECU Configuration base definitions (Native Stub)
 *
 * Minimal stub for native (x86_64/Darwin) compilation.
 * Provides ECUC base type definitions needed by Ecuc_*_Cfg.h headers
 * generated by the yuleASR Configurator.
 */
#ifndef ECUC_H
#define ECUC_H

#include "Std_Types.h"

/* ECUC Configuration variant types */
#define ECUC_VARIANT_PRE_COMPILE        ((uint8)0x01U)
#define ECUC_VARIANT_LINK_TIME          ((uint8)0x02U)
#define ECUC_VARIANT_POST_BUILD         ((uint8)0x03U)

/* Error codes for ECUC configuration validation */
#define ECUC_E_PARAM_POINTER            ((uint8)0x01U)
#define ECUC_E_PARAM_VALUE              ((uint8)0x02U)
#define ECUC_E_PARAM_CONFIG             ((uint8)0x03U)
#define ECUC_E_PARAM_INTEGER            ((uint8)0x04U)
#define ECUC_E_INIT_FAILED              ((uint8)0x05U)

/* Common parameters for all BSW modules */
#ifndef NULL_PTR
#define NULL_PTR                        ((void*)0)
#endif

#endif /* ECUC_H */
