/**
 * @file Ecuc.h
 * @brief AUTOSAR ECU Configuration base definitions (Native Stub)
 *
 * Minimal stub for native (x86_64/Darwin) compilation.
 * Provides ECUC base type definitions needed by Ecuc_*_Cfg.h headers
 * generated by the yuleASR Configurator.
 */
/*
 * This file is located at include/autosar/EcuC.h and is included BEFORE
 * src/bsw/services/ecuC/include/EcuC.h in the search path. To avoid
 * shadowing the real header, we include it directly via relative path.
 */
#ifndef AUTOSAR_ECUC_STUB_H
#define AUTOSAR_ECUC_STUB_H

#include "Std_Types.h"

/* Forward to the real module header */
#include "../../src/bsw/services/ecuC/include/EcuC.h"

/* ECUC Configuration variant types (fallback for when real header is absent) */
#ifndef ECUC_VARIANT_PRE_COMPILE
#define ECUC_VARIANT_PRE_COMPILE        ((uint8)0x01U)
#define ECUC_VARIANT_LINK_TIME          ((uint8)0x02U)
#define ECUC_VARIANT_POST_BUILD         ((uint8)0x03U)
#endif
#ifndef ECUC_E_PARAM_POINTER
#define ECUC_E_PARAM_POINTER            ((uint8)0x01U)
#define ECUC_E_PARAM_VALUE              ((uint8)0x02U)
#define ECUC_E_PARAM_CONFIG             ((uint8)0x03U)
#define ECUC_E_PARAM_INTEGER            ((uint8)0x04U)
#define ECUC_E_INIT_FAILED              ((uint8)0x05U)
#endif

#endif /* AUTOSAR_ECUC_STUB_H */
