/**
 * @file Dio_Cfg.h
 * @brief Dio Configuration configuration header
 * @version 1.0.0
 * @date 2026-08-10
 * @note AUTO-GENERATED by yuleASR Configurator
 */

#ifndef DIO_CFG_H
#define DIO_CFG_H

#include "Std_Types.h"   /* 非宏段依赖 Std_Types 基础类型 (uint32/uint8/uint16/boolean 等)，生成宏段不含此 include */

/*==================================================================================================
*                                    PRE-COMPILE CONFIGURATION
*================================================================================================*/

/*==================================================================================================
*                                    General Configuration
*================================================================================================*/
#define DIO_DEV_ERROR_DETECT    STD_ON
#define DIO_VERSION_INFO_API    STD_ON

/*==================================================================================================
*                                    Module Configuration Counts
*================================================================================================*/
#define DIO_NUM_PORTS    (8U)
#define DIO_NUM_CHANNELS_PER_PORT    (32U)
#define DIO_NUM_CHANNEL_GROUPS    (4U)

/*==================================================================================================
*                                    Other Configuration
*================================================================================================*/
#define DIO_FLIP_CHANNEL_API    STD_ON
#define DIO_MASKED_WRITE_PORT_API    STD_ON
#define DIO_PORT_A    (0U)
#define DIO_PORT_B    (1U)
#define DIO_PORT_C    (2U)
#define DIO_PORT_D    (3U)
#define DIO_PORT_E    (4U)
#define DIO_PORT_F    (5U)
#define DIO_PORT_G    (6U)
#define DIO_PORT_H    (7U)
#define DIO_CHANNEL_A0    (0U)
#define DIO_CHANNEL_A1    (1U)
#define DIO_CHANNEL_A2    (2U)
#define DIO_CHANNEL_A3    (3U)
#define DIO_CHANNEL_A4    (4U)
#define DIO_CHANNEL_A5    (5U)
#define DIO_CHANNEL_A6    (6U)
#define DIO_CHANNEL_A7    (7U)
#define DIO_CHANNEL_B0    (256U)
#define DIO_CHANNEL_B1    (257U)
#define DIO_CHANNEL_B2    (258U)
#define DIO_CHANNEL_B3    (259U)
#define DIO_CHANNEL_B4    (260U)
#define DIO_CHANNEL_B5    (261U)
#define DIO_CHANNEL_B6    (262U)
#define DIO_CHANNEL_B7    (263U)
#define DIO_CHANNEL_C0    (512U)
#define DIO_CHANNEL_C1    (513U)
#define DIO_CHANNEL_C2    (514U)
#define DIO_CHANNEL_C3    (515U)
#define DIO_CHANNEL_C4    (516U)
#define DIO_CHANNEL_C5    (517U)
#define DIO_CHANNEL_C6    (518U)
#define DIO_CHANNEL_C7    (519U)
#define DIO_CHANNEL_D0    (768U)
#define DIO_CHANNEL_D1    (769U)
#define DIO_CHANNEL_D2    (770U)
#define DIO_CHANNEL_D3    (771U)
#define DIO_CHANNEL_D4    (772U)
#define DIO_CHANNEL_D5    (773U)
#define DIO_CHANNEL_D6    (774U)
#define DIO_CHANNEL_D7    (775U)
#define DIO_CHANNEL_E0    (1024U)
#define DIO_CHANNEL_E1    (1025U)
#define DIO_CHANNEL_E2    (1026U)
#define DIO_CHANNEL_E3    (1027U)
#define DIO_CHANNEL_E4    (1028U)
#define DIO_CHANNEL_E5    (1029U)
#define DIO_CHANNEL_E6    (1030U)
#define DIO_CHANNEL_E7    (1031U)
#define DIO_CHANNEL_10    (1280U)
#define DIO_CHANNEL_11    (1281U)
#define DIO_CHANNEL_12    (1282U)
#define DIO_CHANNEL_13    (1283U)
#define DIO_CHANNEL_20    (1284U)
#define DIO_CHANNEL_21    (1285U)
#define DIO_CHANNEL_22    (1286U)
#define DIO_CHANNEL_23    (1287U)
#define DIO_CHANNEL_30    (1288U)
#define DIO_CHANNEL_32    (1289U)
#define DIO_CHANNEL_CAN0_STB    (1280U)
#define DIO_CHANNEL_CAN0_EN    (1281U)
#define DIO_CHANNEL_CAN0_ERR    (1282U)
#define DIO_CHANNEL_CAN0_WAK    (1283U)
#define DIO_CHANNEL_CAN1_STB    (1284U)
#define DIO_CHANNEL_CAN1_EN    (1285U)
#define DIO_CHANNEL_CAN1_ERR    (1286U)
#define DIO_CHANNEL_CAN1_WAK    (1287U)
#define DIO_CHANNEL_CAN2_STB    (1288U)
#define DIO_CHANNEL_CAN2_ERR    (1289U)
#define DIO_INVALID_CHANNEL    (65535U)


/*==================================================================================================
*  NON-MACRO SEGMENT (preserved from handwritten header, merged by codegen splice)
*  typedef(0) + struct(1) + extern config tables(1) — 依赖宏段计数宏, 故置于宏段之后
*================================================================================================*/
typedef struct {
    uint8 dummy;
} Dio_ConfigType;

extern const Dio_ConfigType Dio_Config;
#endif /* DIO_CFG_H */

/*==================[end of file]===========================================*/
