/**
 * @file Srp_Cfg.h
 * @brief Srp Configuration configuration header
 * @version 1.0.0
 * @date 2026-08-10
 * @note AUTO-GENERATED by yuleASR Configurator
 */

#ifndef SRP_CFG_H
#define SRP_CFG_H

/*==================================================================================================
*                                    PRE-COMPILE CONFIGURATION
*================================================================================================*/

/*==================================================================================================
*                                    General Configuration
*================================================================================================*/
#define SRP_DEV_ERROR_DETECT    STD_ON
#define SRP_VERSION_INFO_API    STD_ON

/*==================================================================================================
*                                    Other Configuration
*================================================================================================*/
#define SRP_MAX_STREAMS    (256U)
#define SRP_MAX_DOMAINS    (4U)
#define SRP_ETHERTYPE    (8938U)
#define SRP_DEFAULT_PRIORITY    (3U)
#define SRP_ATTRIBUTE_TYPE_TALKER_ADVERTISE    (1U)
#define SRP_ATTRIBUTE_TYPE_TALKER_FAILED    (2U)
#define SRP_ATTRIBUTE_TYPE_LISTENER_READY    (3U)
#define SRP_ATTRIBUTE_TYPE_LISTENER_READY_FAILED    (4U)
#define SRP_ATTRIBUTE_TYPE_LISTENER_ASKING_FAILED    (5U)

#endif /* SRP_CFG_H */

/*==================[end of file]===========================================*/
