/**
 * @file SomeIpXf_Cfg.h
 * @brief SomeIpXf Configuration configuration header
 * @version 1.0.0
 * @date 2026-08-10
 * @note AUTO-GENERATED by yuleASR Configurator
 */

#ifndef SOMEIPXF_CFG_H
#define SOMEIPXF_CFG_H

/*==================================================================================================
*                                    PRE-COMPILE CONFIGURATION
*================================================================================================*/

/*==================================================================================================
*                                    General Configuration
*================================================================================================*/
#define SOMEIPXF_DEV_ERROR_DETECT    STD_ON
#define SOMEIPXF_VERSION_INFO_API    STD_ON

/*==================================================================================================
*                                    Other Configuration
*================================================================================================*/
#define SOMEIPXF_NUMBER_OF_TRANSFORMERS    (8U)
#define SOMEIPXF_NUMBER_OF_DATA_ELEMENTS    (32U)
#define SOMEIPXF_MAX_BUFFER_SIZE    (1400U)
#define SOMEIPXF_MAX_STRING_LENGTH    (256U)
#define SOMEIPXF_MAX_ARRAY_ELEMENTS    (64U)
#define SOMEIPXF_ENABLE_BOOLEAN    STD_ON
#define SOMEIPXF_ENABLE_UINT8    STD_ON
#define SOMEIPXF_ENABLE_UINT16    STD_ON
#define SOMEIPXF_ENABLE_UINT32    STD_ON
#define SOMEIPXF_ENABLE_UINT64    STD_ON
#define SOMEIPXF_ENABLE_SINT8    STD_ON
#define SOMEIPXF_ENABLE_SINT16    STD_ON
#define SOMEIPXF_ENABLE_SINT32    STD_ON
#define SOMEIPXF_ENABLE_SINT64    STD_ON
#define SOMEIPXF_ENABLE_FLOAT32    STD_ON
#define SOMEIPXF_ENABLE_FLOAT64    STD_ON
#define SOMEIPXF_ENABLE_STRING    STD_ON
#define SOMEIPXF_ENABLE_ARRAY    STD_ON
#define SOMEIPXF_ENABLE_STRUCT    STD_ON
#define SOMEIPXF_ENABLE_UNION    STD_OFF
#define SOMEIPXF_E2E_ENABLED    STD_OFF
#define SOMEIPXF_E2E_PROFILE    (0U)
#define SOMEIPXF_TRANSFORMER_ID_0    (0U)
#define SOMEIPXF_TRANSFORMER_ID_1    (1U)
#define SOMEIPXF_TRANSFORMER_ID_2    (2U)
#define SOMEIPXF_TRANSFORMER_ID_3    (3U)
#define SOMEIPXF_TRANSFORMER_ID_4    (4U)
#define SOMEIPXF_TRANSFORMER_ID_5    (5U)
#define SOMEIPXF_TRANSFORMER_ID_6    (6U)
#define SOMEIPXF_TRANSFORMER_ID_7    (7U)
#define SOMEIPXF_SERVICE_ID_ECU_MONITOR    (1U)
#define SOMEIPXF_SERVICE_ID_DIAGNOSTICS    (2U)
#define SOMEIPXF_SERVICE_ID_VEHICLE_DATA    (3U)
#define SOMEIPXF_SERVICE_ID_ENGINE_CTRL    (4U)
#define SOMEIPXF_METHOD_ID_GET_STATUS    (1U)
#define SOMEIPXF_METHOD_ID_SET_MODE    (2U)
#define SOMEIPXF_METHOD_ID_NOTIFY_EVENT    (32769U)
#define SOMEIPXF_PROTOCOL_VERSION    (1U)
#define SOMEIPXF_INTERFACE_VERSION    (1U)
#define SOMEIPXF_BIG_ENDIAN    STD_ON
#define SOMEIPXF_LITTLE_ENDIAN    STD_OFF

#endif /* SOMEIPXF_CFG_H */

/*==================[end of file]===========================================*/
