/**
 * @file LinIf_Cfg.h
 * @brief LinIf Configuration configuration header
 * @version 1.0.0
 * @date 2026-08-10
 * @note AUTO-GENERATED by yuleASR Configurator
 */

#ifndef LINIF_CFG_H
#define LINIF_CFG_H

/*==================================================================================================
*                                    PRE-COMPILE CONFIGURATION
*================================================================================================*/

/*==================================================================================================
*                                    General Configuration
*================================================================================================*/
#define LINIF_DEV_ERROR_DETECT    STD_ON
#define LINIF_VERSION_INFO_API    STD_ON

/*==================================================================================================
*                                    Other Configuration
*================================================================================================*/
#define LINIF_MAX_CHANNELS    (2U)
#define LINIF_MAX_FRAMES    (16U)
#define LINIF_MAX_SCHEDULES    (8U)
#define LINIF_MAX_SCHEDULE_ENTRIES    (32U)
#define LINIF_FRAME_UNCONDITIONAL    (0U)
#define LINIF_FRAME_EVENT_TRIGGERED    (1U)
#define LINIF_FRAME_SPORADIC    (2U)
#define LINIF_SCHEDULE_NULL    (0U)
#define LINIF_SCHEDULE_NORMAL    (1U)
#define LINIF_SCHEDULE_DIAG_REQUEST    (2U)
#define LINIF_SCHEDULE_DIAG_RESPONSE    (3U)

#endif /* LINIF_CFG_H */

/*==================[end of file]===========================================*/
