/**
 * @file J1939Tp_Cfg.h
 * @brief J1939Tp_Ecual Configuration configuration header
 * @version 1.0.0
 * @date 2026-08-10
 * @note AUTO-GENERATED by yuleASR Configurator
 */

#ifndef J1939TP_CFG_H
#define J1939TP_CFG_H

#include "Std_Types.h"
#include "J1939.h"
#include "MemMap.h"
#include "MemMap.h"

/*==================================================================================================
*                                    PRE-COMPILE CONFIGURATION
*================================================================================================*/

/*==================================================================================================
*                                    General Configuration
*================================================================================================*/
#define J1939TP_DEV_ERROR_DETECT    STD_ON
#define J1939TP_VERSION_INFO_API    STD_ON

/*==================================================================================================
*                                    Module Configuration Counts
*================================================================================================*/
#define J1939TP_MAX_NUM_PACKETS    (255U)

/*==================================================================================================
*                                    Hardware Object Handles
*================================================================================================*/
#define J1939TP_MAX_TX_SDU_PER_CHANNEL    (4U)
#define J1939TP_MAX_RX_SDU_PER_CHANNEL    (4U)
#define J1939TP_TX_CM_PDU_ID    (0U)
#define J1939TP_TX_DT_PDU_ID    (1U)
#define J1939TP_TX_CONF_CM_ID    (2U)
#define J1939TP_TX_CONF_DT_ID    (3U)
#define J1939TP_RX_CM_PDU_ID    (4U)
#define J1939TP_RX_DT_PDU_ID    (5U)

/*==================================================================================================
*                                    Timing Configuration
*================================================================================================*/
#define J1939TP_DEFAULT_TIMEOUT    (1250U)
#define J1939TP_T1_TIMEOUT    (750U)
#define J1939TP_T2_TIMEOUT    (1250U)
#define J1939TP_T3_TIMEOUT    (1250U)
#define J1939TP_T4_TIMEOUT    (1050U)
#define J1939TP_TH_TIMEOUT    (500U)
#define J1939TP_MAIN_FUNCTION_PERIOD_MS    (10U)

/*==================================================================================================
*                                    Other Configuration
*================================================================================================*/
#define J1939TP_DYNAMIC_CHANNEL_ALLOCATION    STD_OFF
#define J1939TP_BAM_SUPPORT    STD_ON
#define J1939TP_RTS_CTS_SUPPORT    STD_ON
#define J1939TP_CHANGE_PARAMETER_API    STD_ON
#define J1939TP_MAX_CHANNEL_CNT    (2U)
#define J1939TP_MAX_MESSAGE_LENGTH    (1785U)
#define J1939TP_MAX_DT_DATA_LEN    (7U)
#define J1939TP_MAX_PACKETS_PER_CTS    (16U)
#define J1939TP_CM_PGN    (60416U)
#define J1939TP_CM_DA_GLOBAL    (255U)
#define J1939TP_DT_PGN    (60160U)
#define J1939TP_DT_DA_GLOBAL    (255U)
#define J1939TP_CM_PRIORITY    (7U)
#define J1939TP_DT_PRIORITY    (7U)
#define J1939TP_BAM_PRIORITY    (7U)
#define J1939TP_MAX_RETRIES    (3U)
#define J1939TP_RETRY_INTERVAL    (100U)
#define J1939TP_DEFAULT_SA    (128U)
#define J1939TP_DEFAULT_DA    (0U)
#define J1939TP_GLOBAL_ADDRESS    (255U)
#define J1939TP_NULL_ADDRESS    (254U)

#endif /* J1939TP_CFG_H */

/*==================[end of file]===========================================*/
