/**
 * @file Dcm_Cfg.h
 * @brief Dcm Configuration configuration header
 * @version 1.0.0
 * @date 2026-08-10
 * @note AUTO-GENERATED by yuleASR Configurator
 */

#ifndef DCM_CFG_H
#define DCM_CFG_H

/*==================================================================================================
*                                    PRE-COMPILE CONFIGURATION
*================================================================================================*/

/*==================================================================================================
*                                    General Configuration
*================================================================================================*/
#define DCM_DEV_ERROR_DETECT    STD_ON
#define DCM_VERSION_INFO_API    STD_ON

/*==================================================================================================
*                                    Module Configuration Counts
*================================================================================================*/
#define DCM_NUM_PROTOCOLS    (2U)
#define DCM_NUM_CONNECTIONS    (4U)
#define DCM_NUM_RX_PDU_IDS    (4U)
#define DCM_NUM_TX_PDU_IDS    (4U)
#define DCM_NUM_SESSIONS    (4U)
#define DCM_NUM_SECURITY_LEVELS    (3U)
#define DCM_NUM_SERVICES    (16U)
#define DCM_OBD_NUM_PIDS    (32U)
#define DCM_NUM_ROUTINES    (8U)
#define DCM_NUM_DIDS    (32U)
#define DCM_NUM_RIDS    (8U)

/*==================================================================================================
*                                    Hardware Object Handles
*================================================================================================*/
#define DCM_RX_BUFFER_SIZE    (256U)
#define DCM_TX_BUFFER_SIZE    (256U)

/*==================================================================================================
*                                    Timing Configuration
*================================================================================================*/
#define DCM_SESSION_DEFAULT_TIMEOUT    (5000U)
#define DCM_SESSION_PROGRAMMING_TIMEOUT    (5000U)
#define DCM_SESSION_EXTENDED_TIMEOUT    (5000U)
#define DCM_SESSION_SAFETY_TIMEOUT    (5000U)
#define DCM_MAIN_FUNCTION_PERIOD_MS    (10U)

/*==================================================================================================
*                                    Other Configuration
*================================================================================================*/
#define DCM_RESPOND_ALL_REQUEST    STD_ON
#define DCM_TASK_TIME    STD_ON
#define DCM_PROTOCOL_OBD_ON_CAN    (0U)
#define DCM_PROTOCOL_UDS_ON_CAN    (1U)
#define DCM_PROTOCOL_UDS_ON_FLEXRAY    (2U)
#define DCM_PROTOCOL_UDS_ON_IP    (3U)
#define DCM_SESSION_DEFAULT    DCM_DEFAULT_SESSION
#define DCM_SESSION_PROGRAMMING    DCM_PROGRAMMING_SESSION
#define DCM_SESSION_EXTENDED    DCM_EXTENDED_DIAGNOSTIC_SESSION
#define DCM_SESSION_SAFETY    DCM_SAFETY_SYSTEM_DIAGNOSTIC_SESSION
#define DCM_SEC_LEVEL_LOCKED    (0U)
#define DCM_SEC_LEVEL_1    (1U)
#define DCM_SEC_LEVEL_2    (2U)
#define DCM_SECURITY_MAX_ATTEMPTS    (3U)
#define DCM_SECURITY_DELAY_TIME_MS    (10000U)
#define DCM_BUFFER_SIZE    (4095U)
#define DCM_MAX_REQUEST_SIZE    (4095U)
#define DCM_MAX_RESPONSE_SIZE    (4095U)
#define DCM_P2SERVER_MAX    (50U)
#define DCM_P2STAR_SERVER_MAX    (5000U)
#define DCM_S3SERVER    (5000U)
#define DCM_OBD_SUPPORT    STD_ON
#define DCM_ROUTINE_CONTROL_SUPPORT    STD_ON
#define DCM_DATA_TRANSFER_SUPPORT    STD_ON
#define DCM_TRANSFER_BLOCK_SIZE    (1024U)
#define DCM_TRANSFER_MAX_BLOCK_SIZE    (4096U)
#define DCM_SEED_SIZE    (4U)
#define DCM_KEY_SIZE    (4U)
#define DCM_MAX_SECURITY_ATTEMPTS    (3U)
#define DCM_SECURITY_DELAY_TIME    (10000U)
#define DCM_SEC_LEV_LOCKED    (0U)

#endif /* DCM_CFG_H */

/*==================[end of file]===========================================*/
