/**
 * @file EthSM_Cfg.h
 * @brief EthSM_Ecual Configuration configuration header
 * @version 1.0.0
 * @date 2026-08-10
 * @note AUTO-GENERATED by yuleASR Configurator
 */

#ifndef ETHSM_CFG_H
#define ETHSM_CFG_H

#include "Std_Types.h"

/*==================================================================================================
*                                    PRE-COMPILE CONFIGURATION
*================================================================================================*/

/*==================================================================================================
*                                    General Configuration
*================================================================================================*/
#define ETHSM_VERSION_INFO_API    STD_ON
#define ETHSM_DEV_ERROR_DETECT    STD_ON

/*==================================================================================================
*                                    Controller Definitions
*================================================================================================*/
#define ETHSM_CTRL_IDX_NETWORK_0    (0U)
#define ETHSM_CTRL_IDX_NETWORK_1    (1U)
#define ETHSM_TRCV_IDX_NETWORK_0    (0U)
#define ETHSM_TRCV_IDX_NETWORK_1    (1U)
#define ETHSM_TCPIP_CTRL_IDX_NETWORK_0    (0U)
#define ETHSM_TCPIP_CTRL_IDX_NETWORK_1    (1U)

/*==================================================================================================
*                                    Timing Configuration
*================================================================================================*/
#define ETHSM_TIMEOUT_WAIT_TRCVLINK    (100U)
#define ETHSM_TIMEOUT_WAIT_ONLINE    (5000U)
#define ETHSM_TIMEOUT_TRCV_WAKEUP    (50U)

/*==================================================================================================
*                                    Other Configuration
*================================================================================================*/
#define ETHSM_CFG_VENDOR_ID    (1U)
#define ETHSM_CFG_MODULE_ID    (67U)
#define ETHSM_CFG_AR_RELEASE_MAJOR_VERSION    (4U)
#define ETHSM_CFG_AR_RELEASE_MINOR_VERSION    (4U)
#define ETHSM_CFG_AR_RELEASE_REVISION_VERSION    (0U)
#define ETHSM_CFG_SW_MAJOR_VERSION    (1U)
#define ETHSM_CFG_SW_MINOR_VERSION    (0U)
#define ETHSM_CFG_SW_PATCH_VERSION    (0U)
#define ETHSM_WAKEUP_SUPPORT    STD_ON
#define ETHSM_TRCVLINK_CHANGE_NOTIFICATION    STD_ON
#define ETHSM_STATE_CHANGE_CALLBACK    STD_ON
#define ETHSM_MAX_NETWORKS    (2U)
#define ETHSM_NETWORK_0    (0U)
#define ETHSM_NETWORK_1    (1U)
#define ETHSM_LINK_DEBOUNCE_TIME    (20U)
#define ETHSM_MAIN_FUNCTION_CYCLE_MS    (10U)
#define ETHSM_WAKEUP_SOURCE_NETWORK_0    (1U)
#define ETHSM_WAKEUP_SOURCE_NETWORK_1    (2U)
#define ETHSM_WAKEUP_BY_BUS_NETWORK_0    STD_ON
#define ETHSM_WAKEUP_BY_BUS_NETWORK_1    STD_ON
#define ETHSM_MAX_RETRIES    (3U)
#define ETHSM_RETRY_DELAY_MS    (100U)
#define ETHSM_CONFIG_VARIANT    (0U)
#define ETHSM_CONFIG_VARIANT_PRECOMPILE    (0U)
#define ETHSM_CONFIG_VARIANT_SELECTABLE    (1U)
#define ETHSM_CONFIG_VARIANT_POSTBUILD    (2U)

#endif /* ETHSM_CFG_H */

/*==================[end of file]===========================================*/
