/**
 * @file StbM_Cfg.h
 * @brief StbM Configuration configuration header
 * @version 1.0.0
 * @date 2026-08-10
 * @note AUTO-GENERATED by yuleASR Configurator
 */

#ifndef STBM_CFG_H
#define STBM_CFG_H

/*==================================================================================================
*                                    PRE-COMPILE CONFIGURATION
*================================================================================================*/

/*==================================================================================================
*                                    General Configuration
*================================================================================================*/
#define STBM_DEV_ERROR_DETECT    STD_ON
#define STBM_VERSION_INFO_API    STD_ON
#define STBM_ALLOWED_RATE_DEVIATION_PPM    (100000U)

/*==================================================================================================
*                                    Controller Definitions
*================================================================================================*/
#define STBM_ETH_CONTROLLER_0    (0U)
#define STBM_ETH_CONTROLLER_1    (1U)

/*==================================================================================================
*                                    Timing Configuration
*================================================================================================*/
#define STBM_SYNC_TIMEOUT_MS    (1000U)
#define STBM_MAIN_FUNCTION_PERIOD_MS    (10U)

/*==================================================================================================
*                                    Other Configuration
*================================================================================================*/
#define STBM_NUMBER_OF_TIMEBASES    (4U)
#define STBM_ENABLE_GPTP    STD_ON
#define STBM_ENABLE_PTP    STD_OFF
#define STBM_ENABLE_CAN_SYNC    STD_OFF
#define STBM_ENABLE_FR_SYNC    STD_OFF
#define STBM_TIMEBASE_ID_0    (0U)
#define STBM_TIMEBASE_ID_1    (1U)
#define STBM_TIMEBASE_ID_2    (2U)
#define STBM_TIMEBASE_ID_3    (3U)
#define STBM_UPDATE_FREQ_MS    (10U)
#define STBM_MAX_RATE_CORRECTION_PPM    (500000U)

#endif /* STBM_CFG_H */

/*==================[end of file]===========================================*/
