/**
 * @file LinSM_Cfg.h
 * @brief LinSM_Ecual Configuration configuration header
 * @version 1.0.0
 * @date 2026-08-10
 * @note AUTO-GENERATED by yuleASR Configurator
 */

#ifndef LINSM_CFG_H
#define LINSM_CFG_H

/*==================================================================================================
*                                    PRE-COMPILE CONFIGURATION
*================================================================================================*/

/*==================================================================================================
*                                    General Configuration
*================================================================================================*/
#define LINSM_VERSION_INFO_API    STD_ON
#define LINSM_DEV_ERROR_DETECT    STD_ON

/*==================================================================================================
*                                    Module Configuration Counts
*================================================================================================*/
#define LINSM_CHANNEL_COUNT    (2U)
#define LINSM_SCHEDULE_COUNT_PER_CHANNEL    (4U)
#define LINSM_TOTAL_SCHEDULE_COUNT    (LINSM_CHANNEL_COUNT * LINSM_SCHEDULE_COUNT_PER_CHANNEL)
#define LINSM_WAKEUP_SOURCE_COUNT    (2U)
#define LINSM_MAX_RETRY_COUNT    (3U)

/*==================================================================================================
*                                    Timing Configuration
*================================================================================================*/
#define LINSM_SCHEDULE_CONFIRMATION_TIMEOUT    (1000U)
#define LINSM_WAKEUP_CONFIRMATION_TIMEOUT    (5000U)
#define LINSM_SLEEP_CONFIRMATION_TIMEOUT    (1000U)
#define LINSM_MAIN_FUNCTION_PERIOD_MS    (10U)

/*==================================================================================================
*                                    Other Configuration
*================================================================================================*/
#define LINSM_WAKEUP_SUPPORT    STD_ON
#define LINSM_SLEEP_SUPPORT    STD_ON
#define LINSM_SCHEDULE_TABLE_SWITCHING    STD_ON
#define LINSM_MODE_REQUEST_REPETITION_TIME    (50U)
#define LINSM_CHANNEL_0    (0U)
#define LINSM_CHANNEL_1    (1U)
#define LINSM_INVALID_CHANNEL    (255U)
#define LINSM_SCHEDULE_NULL    (0U)
#define LINSM_SCHEDULE_DIAG_REQUEST    (1U)
#define LINSM_SCHEDULE_DIAG_RESPONSE    (2U)
#define LINSM_SCHEDULE_NORMAL    (3U)
#define LINSM_SCHEDULE_MASTER    (4U)
#define LINSM_SCHEDULE_INVALID    (255U)
#define ECUM_WKSOURCE_LIN_CH0    (32U)
#define ECUM_WKSOURCE_LIN_CH1    (33U)
#ifndef COMM_CHANNEL_LIN1
#define COMM_CHANNEL_LIN1    (1U)
#endif
#define LINSM_WAKEUP_SOURCE_CH0    (32U)
#define LINSM_WAKEUP_SOURCE_CH1    (33U)
#define LINSM_COMM_CHANNEL_0    COMM_CHANNEL_LIN0
#define LINSM_COMM_CHANNEL_1    (1U)
#define LINSM_MAX_TRANSITIONS_PER_CYCLE    (3U)
#define LINSM_POSTBUILD_VARIANT_SUPPORT    STD_OFF
#define LINSM_CONFIG_VARIANT    (1U)
#define LINSM_VARIANT_PRECOMPILE    (1U)
#define LINSM_VARIANT_LINKTIME    (2U)
#define LINSM_VARIANT_POSTBUILD    (3U)

#endif /* LINSM_CFG_H */

/*==================[end of file]===========================================*/
