/**
 * @file BswM_Cfg.h
 * @brief BswM Configuration configuration header
 * @version 1.0.0
 * @date 2026-08-10
 * @note AUTO-GENERATED by yuleASR Configurator
 */

#ifndef BSWM_CFG_H
#define BSWM_CFG_H

/*==================================================================================================
*                                    PRE-COMPILE CONFIGURATION
*================================================================================================*/

/*==================================================================================================
*                                    General Configuration
*================================================================================================*/
#define BSWM_DEV_ERROR_DETECT    STD_ON
#define BSWM_VERSION_INFO_API    STD_ON

/*==================================================================================================
*                                    Other Configuration
*================================================================================================*/
#define BSWM_MAX_MODE_REQUEST_PORTS    (32U)
#define BSWM_MAX_RULES    (64U)
#define BSWM_MAX_ACTIONS    (128U)
#define BSWM_MAX_ACTION_LISTS    (32U)
#define BSWM_MODE_STARTUP    (0U)
#define BSWM_MODE_RUN    (1U)
#define BSWM_MODE_SHUTDOWN    (2U)
#define BSWM_MODE_SLEEP    (3U)
#define BSWM_MODE_WAKEUP    (4U)
#define BSWM_ECUM_STATE_STARTUP    (16U)
#define BSWM_ECUM_STATE_RUN    (32U)
#define BSWM_ECUM_STATE_SHUTDOWN    (48U)
#define BSWM_ECUM_STATE_SLEEP    (64U)

#endif /* BSWM_CFG_H */

/*==================[end of file]===========================================*/
