/**
 * @file RamTst_Cfg.h
 * @brief RamTst Configuration configuration header
 * @version 1.0.0
 * @date 2026-08-10
 * @note AUTO-GENERATED by yuleASR Configurator
 */

#ifndef RAMTST_CFG_H
#define RAMTST_CFG_H

#include "Std_Types.h"

/*==================================================================================================
*                                    PRE-COMPILE CONFIGURATION
*================================================================================================*/

/*==================================================================================================
*                                    General Configuration
*================================================================================================*/
#define RAMTST_DEV_ERROR_DETECT    STD_ON
#define RAMTST_VERSION_INFO_API    STD_ON

/*==================================================================================================
*                                    Timing Configuration
*================================================================================================*/
#define RAMTST_TIMEOUT_MS    (5000U)

/*==================================================================================================
*                                    Other Configuration
*================================================================================================*/
#define RAMTST_SET_MODE_API    STD_OFF
#define RAMTST_GET_MODE_API    STD_OFF
#define RAMTST_INSTANCE_ID    (0U)
#define RAMTST_START_ADDRESS    (536870912U)
#define RAMTST_SIZE    (131072U)
#define RAMTST_ALGORITHM    RAMTST_ALGORITHM_MARCH_C
#define RAMTST_CALL_CYCLE    (10U)
#define RAMTST_STOP_ON_ERROR    STD_OFF
#define RAMTST_PATTERN_SEED    (2779096485U)

#endif /* RAMTST_CFG_H */

/*==================[end of file]===========================================*/
