// @ts-check

const sidebars = {
  tutorialSidebar: [
    {
      type: 'category',
      label: '快速开始',
      collapsed: false,
      items: [
        'quick-start/intro',
        'quick-start/installation',
        'quick-start/first-project',
        'quick-start/configuration',
      ],
    },
    {
      type: 'category',
      label: '概念指南',
      collapsed: true,
      items: [
        'concepts/what-is-autosar',
        'concepts/bsw-architecture',
        'concepts/layered-structure',
        'concepts/rte',
        'concepts/mcal',
        'concepts/ecual',
        'concepts/services',
      ],
    },
    {
      type: 'category',
      label: 'MCAL 驱动 (21)',
      collapsed: true,
      items: [
        'drivers/mcal/ADC',
        'drivers/mcal/CAN',
        'drivers/mcal/Crypto',
        'drivers/mcal/dio',
        'drivers/mcal/eep',
        'drivers/mcal/ETH',
        'drivers/mcal/fee',
        'drivers/mcal/flash',
        'drivers/mcal/fls',
        'drivers/mcal/gpt',
        'drivers/mcal/i2c',
        'drivers/mcal/icu',
        'drivers/mcal/LIN',
        'drivers/mcal/mcu',
        'drivers/mcal/ocu',
        'drivers/mcal/port',
        'drivers/mcal/pwm',
        'drivers/mcal/ramtst',
        'drivers/mcal/spi',
        'drivers/mcal/uart',
        'drivers/mcal/wdg',
      ],
    },
    {
      type: 'category',
      label: 'ECUAL 驱动 (29)',
      collapsed: true,
      items: [
        'drivers/ecual/CanIf',
        'drivers/ecual/CanTp',
        'drivers/ecual/canNm',
        'drivers/ecual/cansm',
        'drivers/ecual/CANTSYN',
        'drivers/ecual/cantrcv',
        'drivers/ecual/DLT',
        'drivers/ecual/doip',
        'drivers/ecual/ea',
        'drivers/ecual/EthIf',
        'drivers/ecual/ethsm',
        'drivers/ecual/ethtrcv',
        'drivers/ecual/fim',
        'drivers/ecual/frif',
        'drivers/ecual/frtp',
        'drivers/ecual/iohwab',
        'drivers/ecual/ipdum',
        'drivers/ecual/J1939Tp',
        'drivers/ecual/LinIf',
        'drivers/ecual/linnm',
        'drivers/ecual/linsm',
        'drivers/ecual/lintp',
        'drivers/ecual/lintrcv',
        'drivers/ecual/memif',
        'drivers/ecual/someipif',
        'drivers/ecual/someipsd',
        'drivers/ecual/srp',
        'drivers/ecual/wdgif',
        'drivers/ecual/xcp',
      ],
    },
    {
      type: 'category',
      label: '服务层模块 (34)',
      collapsed: true,
      items: [
        'drivers/services/BSWM',
        'drivers/services/CANM',
        'drivers/services/COM',
        'drivers/services/COMM',
        'drivers/services/crc',
        'drivers/services/CRYIF',
        'drivers/services/CSM',
        'drivers/services/Dcm',
        'drivers/services/DEM',
        'drivers/services/det',
        'drivers/services/docan',
        'drivers/services/e2e',
        'drivers/services/ecuc',
        'drivers/services/ECUM',
        'drivers/services/j1939nm',
        'drivers/services/keym',
        'drivers/services/linm',
        'drivers/services/lntm',
        'drivers/services/mem',
        'drivers/services/mqtt',
        'drivers/services/Nm',
        'drivers/services/NVM',
        'drivers/services/PDUR',
        'drivers/services/ramsafety',
        'drivers/services/schm',
        'drivers/services/secoc',
        'drivers/services/SOAD',
        'drivers/services/SOMEIP',
        'drivers/services/SOMEIPTP',
        'drivers/services/SOMEIPXF',
        'drivers/services/stbm',
        'drivers/services/swc',
        'drivers/services/udpnm',
        'drivers/services/WDGM',
      ],
    },
    {
      type: 'category',
      label: '高级主题',
      collapsed: true,
      items: [
        'advanced/toolchain',
        'advanced/code-generation',
        'advanced/testing',
        'advanced/performance-optimization',
        'advanced/debugging',
      ],
    },
    'contributing',
    'faq',
    'troubleshooting',
  ],
};

module.exports = sidebars;
