/**
 * @file Nm_Cfg.h
 * @brief Nm Configuration configuration header
 * @version 1.0.0
 * @date 2026-08-10
 * @note AUTO-GENERATED by yuleASR Configurator
 */

#ifndef NM_CFG_H
#define NM_CFG_H

#include "Nm.h"

/*==================================================================================================
*                                    PRE-COMPILE CONFIGURATION
*================================================================================================*/

/*==================================================================================================
*                                    General Configuration
*================================================================================================*/
#define NM_DEV_ERROR_DETECT    STD_ON
#define NM_VERSION_INFO_API    STD_ON

/*==================================================================================================
*                                    Module Configuration Counts
*================================================================================================*/
#define NM_NODE_COUNT    (4U)
#define NM_CLUSTER_COUNT    (2U)

/*==================================================================================================
*                                    Hardware Object Handles
*================================================================================================*/
#define NM_CAR_WAKEUP_RX_ENABLED    STD_OFF
#define NM_CAR_WAKEUP_TX_ENABLED    STD_OFF

/*==================================================================================================
*                                    Timing Configuration
*================================================================================================*/
#define NM_TIMEOUT_TIME    (1000U)
#define NM_MAIN_FUNCTION_PERIOD    (10U)

/*==================================================================================================
*                                    Other Configuration
*================================================================================================*/
#define NM_MAX_CHANNELS    (8U)
#define NM_NODE_ID    (1U)
#define NM_REPEAT_MESSAGE_TIME    (100U)
#define NM_WAIT_BUS_SLEEP_TIME    (500U)
#define NM_REMOTE_SLEEP_IND_TIME    (2000U)
#define NM_COORDINATOR_SUPPORT_ENABLED    STD_ON
#define NM_COORDINATOR_SYNC_SUPPORT    STD_ON
#define NM_PASSIVE_MODE_ENABLED    STD_OFF
#define NM_PARTIAL_NETWORKING_ENABLED    STD_OFF
#define NM_PN_EIRA_CALCULATION_ENABLED    STD_OFF
#define NM_PN_ERA_CALCULATION_ENABLED    STD_OFF
#define NM_STATE_CHANGE_IND_ENABLED    STD_ON
#define NM_REMOTE_SLEEP_IND_ENABLED    STD_ON
#define NM_BUS_SYNCHRONIZATION_ENABLED    STD_OFF
#define NM_CHANNEL_CAN0    (0U)
#define NM_CHANNEL_CAN1    (1U)
#define NM_CHANNEL_LIN0    (2U)
#define NM_CHANNEL_ETH0    (3U)
#define NM_COMM_ENABLED    STD_ON
/*==================================================================================================
*                                    FUNCTION-LIKE MACROS (VERBATIM)
*================================================================================================*/
#define NM_STATE_CHANGE_NOTIFICATION(ch, prev, curr) \
Appl_Nm_StateChangeNotification(ch, prev, curr)
#define NM_REMOTE_SLEEP_INDICATION(ch) \
Appl_Nm_RemoteSleepIndication(ch)
#define NM_REMOTE_SLEEP_CANCELLATION(ch) \
Appl_Nm_RemoteSleepCancellation(ch)


#endif /* NM_CFG_H */

/*==================[end of file]===========================================*/
