/**
 * @file Can_Cfg.h
 * @brief CAN Driver Configuration Template - AutoSAR MCAL
 * @version 1.0.0
 * @date 2026-04-22
 * @author ConfigGenerator
 *
 * @note This file is generated by the ConfigGenerator tool.
 *       Manual changes may be overwritten.
 */

#ifndef CAN_CFG_H
#define CAN_CFG_H

#include "Std_Types.h"

/*==================================================================================================
*                                    PRE-COMPILE CONFIGURATION
==================================================================================================*/
#define CAN_DEV_ERROR_DETECT            (STD_ON)
#define CAN_VERSION_INFO_API            (STD_ON)
#define CAN_MULTIPLEXED_TRANSMISSION    (STD_OFF)
#define CAN_HW_TRANSMIT_CANCELLATION    (STD_OFF)
#define CAN_FIFO_ENABLE                 (STD_ON)
#define CAN_WAKEUP_SUPPORT              (STD_ON)

/*==================================================================================================
*                                    CONTROLLER CONFIGURATION
==================================================================================================*/
#define CAN_NUM_CONTROLLERS             (2U)
#define CAN_NUM_HOH                     (8U)
#define CAN_NUM_HW_OBJECTS              (16U)

/*==================================================================================================
*                                    BAUDRATE CONFIGURATION
==================================================================================================*/
#define CAN_NUM_BAUDRATES               (3U)

#define CAN_BAUDRATE_125K               (125000U)
#define CAN_BAUDRATE_250K               (250000U)
#define CAN_BAUDRATE_500K               (500000U)
#define CAN_BAUDRATE_1000K              (1000000U)

/*==================================================================================================
*                                    CAN ID TYPE
==================================================================================================*/
#define CAN_ID_TYPE_STANDARD            (0U)
#define CAN_ID_TYPE_EXTENDED            (1U)

/*==================================================================================================
*                                    CONTROLLER IDs
==================================================================================================*/
#define CAN_CONTROLLER_0                (0U)
#define CAN_CONTROLLER_1                (1U)

#endif /* CAN_CFG_H */
