/* AUTOGENERATED FILE - DO NOT EDIT */
#include "Os_Cfg.h"
#include "Os_Internal.h"

/*=============================================================================
 * 任务控制块定义
 *===========================================================================*/
static Os_TaskControlBlockType Os_TaskCB[OS_TASK_COUNT];

const Os_TaskConfigType Os_TaskConfig[OS_TASK_COUNT] = {

    {
        .name = "Init",
        .priority = 10,
        .activation = 1,
        .autostart = TRUE,
        .schedule = FULL,
        .entry = Task_Init_Entry,
        .pcb = &Os_TaskCB[0]
    },

    {
        .name = "Cyclic10ms",
        .priority = 5,
        .activation = 1,
        .autostart = FALSE,
        .schedule = FULL,
        .entry = Task_Cyclic10ms_Entry,
        .pcb = &Os_TaskCB[1]
    },

    {
        .name = "Cyclic100ms",
        .priority = 3,
        .activation = 1,
        .autostart = FALSE,
        .schedule = FULL,
        .entry = Task_Cyclic100ms_Entry,
        .pcb = &Os_TaskCB[2]
    },

    {
        .name = "Background",
        .priority = 1,
        .activation = 1,
        .autostart = FALSE,
        .schedule = NON,
        .entry = Task_Background_Entry,
        .pcb = &Os_TaskCB[3]
    }

};

/*=============================================================================
 * 报警配置定义
 *===========================================================================*/
static Os_AlarmControlBlockType Os_AlarmCB[OS_ALARM_COUNT];

const Os_AlarmConfigType Os_AlarmConfig[OS_ALARM_COUNT] = {

    {
        .name = "Alarm10ms",
        .counter = SystemCounter,
        .action = ACTIVATETASK,
        .task = TASK_CYCLIC10MS,
        
        
        .autostart = TRUE,
        .period = 10,
        .pcb = &Os_AlarmCB[0]
    },

    {
        .name = "Alarm100ms",
        .counter = SystemCounter,
        .action = ACTIVATETASK,
        .task = TASK_CYCLIC100MS,
        
        
        .autostart = TRUE,
        .period = 100,
        .pcb = &Os_AlarmCB[1]
    },

    {
        .name = "AlarmEvent",
        .counter = SystemCounter,
        .action = SETEVENT,
        .task = TASK_CYCLIC10MS,
        .event = EVENT_EVENT10MS,
        
        .autostart = FALSE,
        .period = 0,
        .pcb = &Os_AlarmCB[2]
    }

};

/*=============================================================================
 * 资源配置定义
 *===========================================================================*/
static Os_ResourceControlBlockType Os_ResourceCB[OS_RESOURCE_COUNT];

const Os_ResourceConfigType Os_ResourceConfig[OS_RESOURCE_COUNT] = {

    {
        .name = "Resource1",
        .priority_ceiling = 8,
        .pcb = &Os_ResourceCB[0]
    },

    {
        .name = "Resource2",
        .priority_ceiling = 6,
        .pcb = &Os_ResourceCB[1]
    }

};

/*=============================================================================
 * 调度表配置定义
 *===========================================================================*/

static const Os_ScheduleTableExpiryPointType Os_ST_Main_ExpiryPoints[3] = {

    {
        .offset = 0,
        .task_count = 1,
        .tasks = { TASK_CYCLIC10MS }
    },

    {
        .offset = 10,
        .task_count = 1,
        .tasks = { TASK_CYCLIC100MS }
    },

    {
        .offset = 20,
        .task_count = 0,
        .tasks = {  }
    }

};


const Os_ScheduleTableConfigType Os_ScheduleTableConfig[OS_SCHEDULETABLE_COUNT] = {

    {
        .name = "ST_Main",
        .periodic = TRUE,
        .expiry_point_count = 3,
        .expiry_points = Os_ST_Main_ExpiryPoints
    }

};

/*=============================================================================
 * 任务入口函数声明 (用户实现)
 *===========================================================================*/

extern void Task_Init_Entry(void);

extern void Task_Cyclic10ms_Entry(void);

extern void Task_Cyclic100ms_Entry(void);

extern void Task_Background_Entry(void);


/*=============================================================================
 * 报警回调函数声明 (用户实现)
 *===========================================================================*/






