/* AUTOGENERATED FILE - DO NOT EDIT */
#ifndef OS_CFG_H
#define OS_CFG_H

#include "Os_Types.h"

/*=============================================================================
 * 任务定义
 *===========================================================================*/
#define OS_TASK_COUNT 4

#define TASK_INIT 0

#define TASK_CYCLIC10MS 1

#define TASK_CYCLIC100MS 2

#define TASK_BACKGROUND 3

/*=============================================================================
 * 报警定义
 *===========================================================================*/
#define OS_ALARM_COUNT 3

#define ALARM_ALARM10MS 0

#define ALARM_ALARM100MS 1

#define ALARM_ALARMEVENT 2

/*=============================================================================
 * 资源定义
 *===========================================================================*/
#define OS_RESOURCE_COUNT 2

#define RES_RESOURCE1 0
#define RES_RESOURCE1_PRIORITY 8

#define RES_RESOURCE2 1
#define RES_RESOURCE2_PRIORITY 6

/*=============================================================================
 * 事件定义
 *===========================================================================*/
#define OS_EVENT_COUNT 3

#define EVENT_EVENT10MS ((EventMaskType)0x00000001)

#define EVENT_EVENT100MS ((EventMaskType)0x00000002)

#define EVENT_EVENTSHUTDOWN ((EventMaskType)0x80000000)

/*=============================================================================
 * 调度表定义
 *===========================================================================*/
#define OS_SCHEDULETABLE_COUNT 1

#define SCHEDULETABLE_ST_MAIN 0

/*=============================================================================
 * 任务属性
 *===========================================================================*/

#define TASK_INIT_PRIORITY 10
#define TASK_INIT_ACTIVATION 1
#define TASK_INIT_AUTOSTART TRUE
#define TASK_INIT_SCHEDULE FULL

#define TASK_CYCLIC10MS_PRIORITY 5
#define TASK_CYCLIC10MS_ACTIVATION 1
#define TASK_CYCLIC10MS_AUTOSTART FALSE
#define TASK_CYCLIC10MS_SCHEDULE FULL

#define TASK_CYCLIC100MS_PRIORITY 3
#define TASK_CYCLIC100MS_ACTIVATION 1
#define TASK_CYCLIC100MS_AUTOSTART FALSE
#define TASK_CYCLIC100MS_SCHEDULE FULL

#define TASK_BACKGROUND_PRIORITY 1
#define TASK_BACKGROUND_ACTIVATION 1
#define TASK_BACKGROUND_AUTOSTART FALSE
#define TASK_BACKGROUND_SCHEDULE NON

/*=============================================================================
 * 报警属性
 *===========================================================================*/

#define ALARM_ALARM10MS_COUNTER SystemCounter
#define ALARM_ALARM10MS_ACTION ACTIVATETASK
#define ALARM_ALARM10MS_TASK Cyclic10ms


#define ALARM_ALARM100MS_COUNTER SystemCounter
#define ALARM_ALARM100MS_ACTION ACTIVATETASK
#define ALARM_ALARM100MS_TASK Cyclic100ms


#define ALARM_ALARMEVENT_COUNTER SystemCounter
#define ALARM_ALARMEVENT_ACTION SETEVENT
#define ALARM_ALARMEVENT_TASK Cyclic10ms
#define ALARM_ALARMEVENT_EVENT Event10ms


#endif /* OS_CFG_H */