/**
 * @file J1939Tp_Cfg.h
 * @brief J1939Tp Configuration configuration header
 * @version 1.0.0
 * @date 2026-08-10
 * @note AUTO-GENERATED by yuleASR Configurator
 */

#ifndef J1939TP_CFG_H
#define J1939TP_CFG_H

#include "Std_Types.h"

/*==================================================================================================
*                                    PRE-COMPILE CONFIGURATION
*================================================================================================*/

/*==================================================================================================
*                                    General Configuration
*================================================================================================*/
#define J1939TP_VERSION_INFO_API    STD_ON
#define J1939TP_DEV_ERROR_DETECT    STD_ON

/*==================================================================================================
*                                    Hardware Object Handles
*================================================================================================*/
#define J1939TP_J1939TP_FPP_TX_ENABLED    STD_ON
#define J1939TP_J1939TP_FPP_RX_ENABLED    STD_ON
#define J1939TP_BAM_TX_ENABLED    STD_ON
#define J1939TP_BAM_RX_ENABLED    STD_ON
#define J1939TP_CMDT_TX_ENABLED    STD_ON
#define J1939TP_CMDT_RX_ENABLED    STD_ON
#define J1939TP_MAX_TX_CHANNELS    (4U)
#define J1939TP_MAX_RX_CHANNELS    (4U)

/*==================================================================================================
*                                    Timing Configuration
*================================================================================================*/
#define J1939TP_MAIN_FUNCTION_PERIOD    (10U)
#define J1939TP_T1_TIMEOUT_DEFAULT    (750U)
#define J1939TP_T2_TIMEOUT_DEFAULT    (1250U)
#define J1939TP_T3_TIMEOUT_DEFAULT    (1250U)
#define J1939TP_T4_TIMEOUT_DEFAULT    (1050U)

/*==================================================================================================
*                                    Other Configuration
*================================================================================================*/
#define J1939TP_N_BROADCAST_TIME    (50U)
#define J1939TP_MAX_PG    (32U)
#define J1939TP_MAX_CONNECTIONS    (8U)
#define J1939TP_N_BS_DEFAULT    (500U)
#define J1939TP_N_CS_DEFAULT    (500U)
#define J1939TP_N_BR_DEFAULT    (0U)
#define J1939TP_N_AR_DEFAULT    (500U)
#define J1939TP_CM_RTS    (16U)
#define J1939TP_CM_CTS    (17U)
#define J1939TP_CM_ACK    (19U)
#define J1939TP_CM_BAM    (32U)
#define J1939TP_CM_ABORT    (255U)
#define J1939TP_DT_PACKET_SIZE    (7U)
#define J1939TP_MAX_TP_PACKETS    (255U)
#define J1939TP_MAX_TP_SIZE    (1785U)
#define J1939TP_CM_PACKET_SIZE    (8U)
#define J1939TP_PGN_TP_CM    (60416U)
#define J1939TP_PGN_TP_DT    (60160U)
/*==================================================================================================
*                                    FUNCTION-LIKE MACROS (VERBATIM)
*================================================================================================*/
#define J1939TP_CAN_ID(prio, pgn, sa)   ((((uint32)(prio) & 0x07U) << 26) | \
(((uint32)(pgn) & 0x03FFFFU) << 8) | \
((uint32)(sa) & 0xFFU))
#define J1939TP_GET_SA(canid)           ((uint8)((canid) & 0xFFU))
#define J1939TP_GET_PGN(canid)          (((canid) >> 8) & 0x03FFFFU)
#define J1939TP_GET_PRIO(canid)         (((canid) >> 26) & 0x07U)
#define J1939TP_IS_PDU1(pgn)            (((pgn) & 0x00F000U) < 0x00F000U)
#define J1939TP_IS_PDU2(pgn)            (((pgn) & 0x00F000U) >= 0x00F000U)


#endif /* J1939TP_CFG_H */

/*==================[end of file]===========================================*/
