/**
 * @file Dem_Cfg.h
 * @brief Dem_Legacy Configuration configuration header
 * @version 1.0.0
 * @date 2026-08-10
 * @note AUTO-GENERATED by yuleASR Configurator
 */

#ifndef DEM_CFG_H
#define DEM_CFG_H

/*==================================================================================================
*                                    PRE-COMPILE CONFIGURATION
*================================================================================================*/

/*==================================================================================================
*                                    General Configuration
*================================================================================================*/
#define DEM_DEV_ERROR_DETECT    STD_ON
#define DEM_VERSION_INFO_API    STD_ON

/*==================================================================================================
*                                    Module Configuration Counts
*================================================================================================*/
#define DEM_CFG_AGING_COUNTER_THRESHOLD    (40U)
#define DEM_CFG_DEBOUNCE_COUNTER_SUPPORT    STD_ON
#define DEM_CFG_DEBOUNCE_COUNTER_MAX    (127U)
#define DEM_CFG_DEBOUNCE_COUNTER_MIN    (-128U)
#define DEM_CFG_DEBOUNCE_COUNTER_FAILED    (127U)
#define DEM_CFG_DEBOUNCE_COUNTER_PASSED    (-128U)

/*==================================================================================================
*                                    Timing Configuration
*================================================================================================*/
#define DEM_CFG_MAIN_FUNCTION_PERIOD_MS    (10U)
#define DEM_CFG_DEBOUNCE_TASK_PERIOD_MS    (10U)
#define DEM_CFG_NVM_WRITE_TIMEOUT_MS    (100U)
#define DEM_CFG_NVM_READ_TIMEOUT_MS    (50U)
#define DEM_CFG_CLEAR_DTC_TIMEOUT_MS    (10000U)
#define DEM_CFG_DISABLE_DTC_RECORD_TIMEOUT_MS    (5000U)
#define DEM_CFG_GET_DTC_STATUS_TIMEOUT_MS    (1000U)

/*==================================================================================================
*                                    Other Configuration
*================================================================================================*/
#define DEM_CFG_VENDOR_ID    (100U)
#define DEM_CFG_MODULE_ID    (54U)
#define DEM_CFG_MAJOR_VERSION    (1U)
#define DEM_CFG_MINOR_VERSION    (0U)
#define DEM_CFG_PATCH_VERSION    (0U)
#define DEM_DEBUG_SUPPORT    STD_OFF
#define DEM_CFG_FreezeFrameSupport    STD_ON
#define DEM_CFG_ExtendedDataSupport    STD_ON
#define DEM_CFG_AgingSupport    STD_ON
#define DEM_CFG_OperationCycleSupport    STD_ON
#define DEM_CFG_IndicatorSupport    STD_ON
#define DEM_CFG_EventDebounceSupport    STD_ON
#define DEM_CFG_OBDSupport    STD_OFF
#define DEM_CFG_J1939Support    STD_OFF
#define DEM_CFG_BswMSupport    STD_ON
#define DEM_CFG_FimSupport    STD_ON
#define DEM_CFG_DcmSupport    STD_ON
#define DEM_CFG_MAX_NUMBER_EVENTS    (100U)
#define DEM_CFG_MAX_NUMBER_DTCS    (80U)
#define DEM_CFG_MAX_FREEZEFRAME_RECORDS    (3U)
#define DEM_CFG_MAX_EXTENDED_DATA_RECORDS    (2U)
#define DEM_CFG_MAX_FREEZEFRAME_SIZE    (50U)
#define DEM_CFG_MAX_EXTENDED_DATA_SIZE    (20U)
#define DEM_CFG_MAX_INDICATORS    (8U)
#define DEM_CFG_MAX_INDICATOR_ATTRIBUTES    (2U)
#define DEM_CFG_MAX_OPERATION_CYCLES    (4U)
#define DEM_CFG_MAX_DEBOUNCE_ALGORITHMS    (50U)
#define DEM_CFG_EVENT_QUEUE_SIZE    (20U)
#define DEM_CFG_DTC_FORMAT    DEM_DTC_FORMAT_UDS
#define DEM_CFG_PRIMARY_MEMORY_MAX_ENTRIES    (50U)
#define DEM_CFG_MIRROR_MEMORY_MAX_ENTRIES    (10U)
#define DEM_CFG_PERMANENT_MEMORY_MAX_ENTRIES    (5U)
#define DEM_CFG_USER_DEFINED_MEMORY    (0U)
#define DEM_CFG_AGING_CYCLE_THRESHOLD    (40U)
#define DEM_CFG_DEBOUNCE_TIME_SUPPORT    STD_ON
#define DEM_CFG_DEBOUNCE_MONITOR_SUPPORT    STD_ON
#define DEM_CFG_CALLBACK_ON_EVC_STATUS_CHANGED    STD_ON
#define DEM_CFG_CALLBACK_ON_EVC_DATA_CHANGED    STD_OFF
#define DEM_CFG_CALLBACK_ON_DTC_STATUS_CHANGED    STD_ON
#define DEM_CFG_CALLBACK_ON_MONITOR_STATUS_CHANGED    STD_OFF
#define DEM_CFG_CALLBACK_ON_CYCLE_STATUS_CHANGED    STD_ON
#define DEM_CFG_NVM_WRITE_RETRY    (3U)
#define DEM_CFG_NVM_READ_RETRY    (3U)
#define DEM_CFG_COMBINED_DTCS_SUPPORT    STD_OFF
#define DEM_CFG_MULTIPLE_EVENT_MEMORIES    STD_OFF
#define DEM_CFG_TIME_BASED_DEBOUNCE    STD_ON
#define DEM_CFG_FREQUENCY_BASED_DEBOUNCE    STD_OFF
#define DEM_CFG_STORAGE_CONDITIONS_SUPPORT    STD_OFF
#define DEM_CFG_ENABLE_CONDITIONS_SUPPORT    STD_OFF
#define DEM_CFG_COMPONENT_AVAILABLE_SUPPORT    STD_OFF
#define DEM_CFG_PID41_SUPPORT    STD_OFF
#define DEM_CFG_PID1C_SUPPORT    STD_OFF
#define DEM_CFG_WWH_OBD_SUPPORT    STD_OFF
#define DEM_CFG_WORLD_WIDE_HARMONIZED_OBD    STD_OFF
#define DEM_CFG_EMISSION_RELATED_DTCS_ONLY    STD_OFF
#define DEM_CFG_CLEAR_DTCLIMIT_SUPPORT    STD_OFF
#define DEM_CFG_WARNING_INDICATOR_SUPPORTED    STD_ON
#define DEM_CFG_MIL_INDICATOR_SUPPORTED    STD_ON
#define DEM_CFG_SERVICE_ONLY_TRACKING    STD_OFF

#endif /* DEM_CFG_H */

/*==================[end of file]===========================================*/
