/**
 * @file CanTrcv_Cfg.h
 * @brief CanTrcv Configuration configuration header
 * @version 1.0.0
 * @date 2026-08-10
 * @note AUTO-GENERATED by yuleASR Configurator
 */

#ifndef CANTRCV_CFG_H
#define CANTRCV_CFG_H

#include "Std_Types.h"   /* 非宏段依赖 Std_Types 基础类型 (uint32/uint8/uint16/boolean 等)，生成宏段不含此 include */
#include "Dio.h"
#include "Spi.h"
#include "EcuM.h"

#include "Std_Types.h"

/*==================================================================================================
*                                    PRE-COMPILE CONFIGURATION
*================================================================================================*/

/*==================================================================================================
*                                    General Configuration
*================================================================================================*/
#define CANTRCV_VERSION_INFO_API    STD_ON
#define CANTRCV_DEV_ERROR_DETECT    STD_ON
#define CANTRCV_REPORT_TO_DET    STD_ON

/*==================================================================================================
*                                    Module Configuration Counts
*================================================================================================*/
#define CANTRCV_NUM_CHANNELS    (2U)

/*==================================================================================================
*                                    Timing Configuration
*================================================================================================*/
#define CANTRCV_MODE_TRANSITION_TIMEOUT_MS    (100U)
#define CANTRCV_MAIN_FUNCTION_PERIOD_MS    (10U)

/*==================================================================================================
*                                    Other Configuration
*================================================================================================*/
#define CANTRCV_WAKEUP_BY_BUS_USED    STD_ON
#define CANTRCV_WAKEUP_BY_PIN_USED    STD_ON
#define CANTRCV_SPI_USED    STD_OFF
#define CANTRCV_DIO_USED    STD_ON
#define CANTRCV_CHECK_WAKEUP_API    STD_ON
#define CANTRCV_CHECK_WAKEUP_BY_TRCV_API    STD_ON
#define CANTRCV_DEINIT_API    STD_ON
#define CANTRCV_TIMING_OPTIMIZATION    STD_OFF
#define CANTRCV_MULTIPLE_TRCV_SUPPORT    STD_ON
#define CANTRCV_MAX_TRANSCEIVERS    (2U)
#define CANTRCV_HARDWARE_TYPE    CANTRCV_TJA1043
#define CANTRCV_DEFAULT_HARDWARE_TYPE    CANTRCV_TJA1043
#define CANTRCV_TJA1043_STB_EN_DELAY_US    (10U)
#define CANTRCV_SLEEP_MODE_DELAY_MS    (5U)
#define CANTRCV_STANDBY_MODE_DELAY_MS    (2U)
#define CANTRCV_NORMAL_MODE_DELAY_MS    (2U)
#define CANTRCV_MAX_CHANNELS    (2U)
#define CANTRCV_CH0_STB_PIN    DIO_CHANNEL_10
#define CANTRCV_CH0_EN_PIN    DIO_CHANNEL_11
#define CANTRCV_CH0_NERR_PIN    DIO_CHANNEL_12
#define CANTRCV_CH0_WAK_PIN    DIO_CHANNEL_13
#define CANTRCV_CH1_STB_PIN    DIO_CHANNEL_20
#define CANTRCV_CH1_EN_PIN    DIO_CHANNEL_21
#define CANTRCV_CH1_NERR_PIN    DIO_CHANNEL_22
#define CANTRCV_CH1_WAK_PIN    DIO_CHANNEL_23
#define CANTRCV_CH0_SPI_SEQUENCE    SPI_SEQUENCE_0
#define CANTRCV_CH0_SPI_CHANNEL    SPI_CHANNEL_0
#define CANTRCV_CH1_SPI_SEQUENCE    SPI_SEQUENCE_1
#define CANTRCV_CH1_SPI_CHANNEL    SPI_CHANNEL_1
#define CANTRCV_CH0_WAKEUP_SOURCE    ECUM_WKSOURCE_CAN
#define CANTRCV_CH1_WAKEUP_SOURCE    ECUM_WKSOURCE_CAN1
#define CANTRCV_DEFAULT_WAKEUP_MODE    CANTRCV_WUMODE_ENABLE
#define CANTRCV_WAKEUP_FILTERING_ENABLED    STD_ON
#define CANTRCV_RUNTIME_ERROR_REPORTING    STD_OFF
#define CANTRCV_PROD_ERROR_REPORTING    STD_OFF
#define CANTRCV_WAKEUP_NOTIFICATION_ENABLED    STD_ON
#define CANTRCV_ERROR_NOTIFICATION_ENABLED    STD_ON
#ifndef CANTRCV_INSTANCE_ID
#define CANTRCV_INSTANCE_ID    (0U)
#endif
#define CANTRCV_E_INVALID_CHANNEL    (1U)
#define CANTRCV_E_PARAM_TRCV_OPMODE    (2U)
#define CANTRCV_E_PARAM_POINTER    (3U)
#define CANTRCV_E_UNINIT    (4U)
#define CANTRCV_E_PARAM_TRCV_WAKEUP_MODE    (5U)
/*==================================================================================================
*                                    CONDITIONAL INCLUDES
*================================================================================================*/
#if (CANTRCV_DIO_USED == STD_ON)
#include "Dio.h"
#endif
#if (CANTRCV_SPI_USED == STD_ON)
#include "Spi.h"
#endif
#if (CANTRCV_WAKEUP_BY_BUS_USED == STD_ON)
#include "EcuM.h"
#endif



/*==================================================================================================
*  NON-MACRO SEGMENT (preserved from handwritten header, merged by codegen splice)
*  typedef(0) + struct(0) + extern config tables(2) — 依赖宏段计数宏, 故置于宏段之后
*================================================================================================*/
#if (CANTRCV_WAKEUP_NOTIFICATION_ENABLED == STD_ON)
/**
 * @brief Callback function for wake-up notification.
 *
 * This function is called by the CanTrcv module when a wake-up event
 * is detected on any configured transceiver.
 *
 * @param[in] Transceiver Transceiver on which wake-up was detected
 */
extern void CanTrcv_WakeupNotification(uint8 Transceiver);
#endif

#if (CANTRCV_ERROR_NOTIFICATION_ENABLED == STD_ON)
/**
 * @brief Callback function for error notification.
 *
 * This function is called by the CanTrcv module when a transceiver
 * error is detected.
 *
 * @param[in] Transceiver Transceiver on which error was detected
 * @param[in] ErrorCode Error code indicating the type of error
 */
extern void CanTrcv_ErrorNotification(uint8 Transceiver, uint8 ErrorCode);
#endif
#endif /* CANTRCV_CFG_H */

/*==================[end of file]===========================================*/
