/**
 * @file Dlt_Cfg.h
 * @brief Dlt Configuration configuration header
 * @version 1.0.0
 * @date 2026-08-10
 * @note AUTO-GENERATED by yuleASR Configurator
 */

#ifndef DLT_CFG_H
#define DLT_CFG_H

#include "Std_Types.h"   /* 非宏段依赖 Std_Types 基础类型 (uint32/uint8/uint16/boolean 等)，生成宏段不含此 include */

/*==================================================================================================
*                                    PRE-COMPILE CONFIGURATION
*================================================================================================*/

/*==================================================================================================
*                                    General Configuration
*================================================================================================*/
#define DLT_DEV_ERROR_DETECT    STD_ON

/*==================================================================================================
*                                    Other Configuration
*================================================================================================*/
#define DLT_RUNTIME_ERROR_REPORT    STD_ON
#define DLT_MESSAGE_LOSS_REPORT    STD_ON
#define DLT_TRANSPORT_PROTOCOL    DLT_TRANSPORT_UDP
#define DLT_SERVER_PORT    (3490U)
#define DLT_BUFFER_SIZE    (4096U)
#define DLT_MAX_MSG_SIZE    (1400U)
#define DLT_QUEUE_SIZE    (256U)
#define DLT_MAX_APPS    (32U)
#define DLT_PRIORITY_QUEUE_ENABLED    STD_ON
#define DLT_HIGH_PRIORITY_QUEUE_SIZE    (64U)
#define DLT_DEFAULT_LOG_LEVEL    DLT_LOG_INFO
#define DLT_DEFAULT_ENABLED    STD_ON
#define DLT_TIMESTAMP_ENABLED    STD_ON
#define DLT_TIMESTAMP_PRECISION_US    (100U)
#define DLT_SESSION_ID_ENABLED    STD_ON
#define DLT_DEFAULT_SESSION_ID    (1U)
#define DLT_MAIN_FUNCTION_CYCLE    (10U)
#define DLT_MESSAGE_LOSS_THRESHOLD    (100U)

/*==================================================================================================
*                                    Context Configuration (ecual 合并)
* 2026-08-15: 由 ecual/dlt 链接期配置体系迁移而来，供 Dlt_Lcfg.c 的 context 配置表使用。
*================================================================================================*/
#define DLT_MAX_CONTEXT_COUNT    (32U)          /* 最大 context 数量 (Dlt_ContextConfig 表大小) */
#define DLT_BUFFER_COUNT    (4U)                /* 缓冲区数量 (优先级 0~3) */
#define DLT_BUFFERING_TIMEOUT    (1000U)        /* 缓冲超时 (ms) */
#define DLT_MAIN_FUNCTION_PERIOD    (10U)       /* 主函数周期 (ms, ecual 兼容名) */
#define DLT_USE_COM    STD_ON                   /* 是否启用 Com 集成 (Tx 确认/Rx 指示) */
#define DLT_ECU_ID    "ECU1"                    /* ECU ID (4 字节, 用于 DLT 标准头) */
#define DLT_ECU_ID_LENGTH    (4U)               /* ECU ID 长度 */
#define DLT_PROTOCOL_VERSION_MAJOR    (1U)      /* DLT 协议版本-主 */
#define DLT_PROTOCOL_VERSION_MINOR    (0U)      /* DLT 协议版本-次 */
#define DLT_MAX_CONTEXT_DESCRIPTION    (32U)    /* context 描述最大长度 (Dlt_ContextType.description 定长) */


/*==================================================================================================
*  NON-MACRO SEGMENT (preserved from handwritten header, merged by codegen splice)
*  typedef(0) + struct(0) + extern config tables(4) — 依赖宏段计数宏, 故置于宏段之后
*================================================================================================*/
extern const Dlt_TransportConfigType Dlt_TransportConfig;

/**
 * @brief 过滤器配置数组
 */
extern const Dlt_FilterConfigType* Dlt_FilterConfigTable;

/**
 * @brief 过滤器数量
 */
extern const uint16 Dlt_FilterConfigCount;

/**
 * @brief 模块配置
 */
extern const Dlt_ConfigType Dlt_Config;
#endif /* DLT_CFG_H */

/*==================[end of file]===========================================*/
