/**
 * @file Dlt_Cfg.h
 * @brief Dlt Configuration configuration header
 * @version 1.0.0
 * @date 2026-08-10
 * @note AUTO-GENERATED by yuleASR Configurator
 */

#ifndef DLT_CFG_H
#define DLT_CFG_H

#include "Std_Types.h"   /* 非宏段依赖 Std_Types 基础类型 (uint32/uint8/uint16/boolean 等)，生成宏段不含此 include */

/*==================================================================================================
*                                    PRE-COMPILE CONFIGURATION
*================================================================================================*/

/*==================================================================================================
*                                    General Configuration
*================================================================================================*/
#define DLT_DEV_ERROR_DETECT    STD_ON

/*==================================================================================================
*                                    Other Configuration
*================================================================================================*/
#define DLT_RUNTIME_ERROR_REPORT    STD_ON
#define DLT_MESSAGE_LOSS_REPORT    STD_ON
#define DLT_TRANSPORT_PROTOCOL    DLT_TRANSPORT_UDP
#define DLT_SERVER_PORT    (3490U)
#define DLT_BUFFER_SIZE    (4096U)
#define DLT_MAX_MSG_SIZE    (1400U)
#define DLT_QUEUE_SIZE    (256U)
#define DLT_MAX_APPS    (32U)
#define DLT_PRIORITY_QUEUE_ENABLED    STD_ON
#define DLT_HIGH_PRIORITY_QUEUE_SIZE    (64U)
#define DLT_DEFAULT_LOG_LEVEL    DLT_LOG_INFO
#define DLT_DEFAULT_ENABLED    STD_ON
#define DLT_TIMESTAMP_ENABLED    STD_ON
#define DLT_TIMESTAMP_PRECISION_US    (100U)
#define DLT_SESSION_ID_ENABLED    STD_ON
#define DLT_DEFAULT_SESSION_ID    (1U)
#define DLT_MAIN_FUNCTION_CYCLE    (10U)
#define DLT_MESSAGE_LOSS_THRESHOLD    (100U)


/*==================================================================================================
*  NON-MACRO SEGMENT (preserved from handwritten header, merged by codegen splice)
*  typedef(0) + struct(0) + extern config tables(4) — 依赖宏段计数宏, 故置于宏段之后
*================================================================================================*/
extern const Dlt_TransportConfigType Dlt_TransportConfig;

/**
 * @brief 过滤器配置数组
 */
extern const Dlt_FilterConfigType* Dlt_FilterConfigTable;

/**
 * @brief 过滤器数量
 */
extern const uint16 Dlt_FilterConfigCount;

/**
 * @brief 模块配置
 */
extern const Dlt_ConfigType Dlt_Config;
#endif /* DLT_CFG_H */

/*==================[end of file]===========================================*/
