/**
 * @file CanNm_Cfg.h
 * @brief CanNm_Ecual Configuration configuration header
 * @version 1.0.0
 * @date 2026-08-10
 * @note AUTO-GENERATED by yuleASR Configurator
 */

#ifndef CANNM_CFG_H
#define CANNM_CFG_H

/*==================================================================================================
*                                    PRE-COMPILE CONFIGURATION
*================================================================================================*/

/*==================================================================================================
*                                    General Configuration
*================================================================================================*/
#define CANNM_VERSION_INFO_API    STD_ON
#define CANNM_NODE_DETECTION_ENABLED    STD_ON
#define CANNM_DEV_ERROR_DETECT    STD_ON

/*==================================================================================================
*                                    Hardware Object Handles
*================================================================================================*/
#define CANNM_CAR_WAKEUP_RX_ENABLED    STD_OFF
#define CANNM_PDU_RX_INDICATION_ENABLED    STD_ON
#define CANNM_CHANNEL_0_TX_PDUID    (0U)
#define CANNM_CHANNEL_1_TX_PDUID    (1U)
#define CANNM_CHANNEL_0_RX_PDUID    (0U)
#define CANNM_CHANNEL_1_RX_PDUID    (1U)

/*==================================================================================================
*                                    Timing Configuration
*================================================================================================*/
#define CANNM_NM_TIMEOUT_TIME_DEFAULT    (1000U)
#define CANNM_MAIN_FUNCTION_PERIOD    0.01f
#define CANNM_MAIN_FUNCTION_PERIOD_MS    (10U)

/*==================================================================================================
*                                    Other Configuration
*================================================================================================*/
#define CANNM_VENDOR_ID_CFG    (1U)
#define CANNM_MODULE_ID_CFG    (31U)
#define CANNM_CFG_SW_MAJOR_VERSION    (4U)
#define CANNM_CFG_SW_MINOR_VERSION    (4U)
#define CANNM_CFG_SW_PATCH_VERSION    (0U)
#define CANNM_CFG_AR_MAJOR_VERSION    (4U)
#define CANNM_CFG_AR_MINOR_VERSION    (4U)
#define CANNM_CFG_AR_PATCH_VERSION    (0U)
#define CANNM_COM_CONTROL_ENABLED    STD_ON
#define CANNM_COORDINATOR_SUPPORT_ENABLED    STD_ON
#define CANNM_PASSIVE_MODE_ENABLED    STD_OFF
#define CANNM_NODE_ID_ENABLED    STD_ON
#define CANNM_REMOTE_SLEEP_IND_ENABLED    STD_ON
#define CANNM_USER_DATA_ENABLED    STD_ON
#define CANNM_PN_ENABLED    STD_ON
#define CANNM_STATE_CHANGE_IND_ENABLED    STD_ON
#define CANNM_BUS_SYNCHRONIZATION_ENABLED    STD_OFF
#define CANNM_REMOTE_SLEEP_IND_CALLBACK    STD_ON
#define CANNM_IMMEDIATE_TRANSMIT_ENABLED    STD_ON
#define CANNM_ACTIVE_WAKEUP_BIT_ENABLED    STD_ON
#define CANNM_NUMBER_OF_CHANNELS    (2U)
#define CANNM_MAX_NUMBER_OF_CHANNELS    (2U)
#define CANNM_CHANNEL_0    (0U)
#define CANNM_CHANNEL_1    (1U)
#define CANNM_CHANNEL_0_NAME    "CanNm_Channel_0"
#define CANNM_CHANNEL_1_NAME    "CanNm_Channel_1"
#define CANNM_REPEAT_MESSAGE_TIME_DEFAULT    (400U)
#define CANNM_WAIT_BUS_SLEEP_TIME_DEFAULT    (1000U)
#define CANNM_MESSAGE_CYCLE_TIME_DEFAULT    (100U)
#define CANNM_MESSAGE_CYCLE_OFFSET_DEFAULT    (10U)
#define CANNM_IMMEDIATE_NM_CYCLE_TIME    (20U)
#define CANNM_IMMEDIATE_NM_TRANSMSSIONS    (3U)
#define CANNM_REMOTE_SLEEP_IND_TIME    (2000U)
#define CANNM_PDU_LENGTH    (8U)
#define CANNM_PDU_NID_POSITION    (0U)
#define CANNM_PDU_CBV_POSITION    (1U)
#define CANNM_USER_DATA_POSITION    (0U)
#define CANNM_USER_DATA_LENGTH    (8U)
#define CANNM_CHANNEL_0_NODE_ID    (1U)
#define CANNM_CHANNEL_1_NODE_ID    (2U)
#define CANNM_STATE_CHANGE_IND_FCT    "Nm_StateChangeNotification"
#define CANNM_REMOTE_SLEEP_IND_FCT    "Nm_RemoteSleepIndication"
#define CANNM_REMOTE_SLEEP_CANCEL_FCT    "Nm_RemoteSleepCancellation"

#endif /* CANNM_CFG_H */

/*==================[end of file]===========================================*/
